-- CRPE Francais - Module V1
-- Generated from content/french-crpe-module.ts
-- Do not edit manually: rerun `npm run generate:french-module-seed`.

insert into public.exercises (
  id, subject, subdomain, topic_key, topic_label, level,
  exercise_type, instruction, support_text, choices, expected_answer,
  detailed_explanation, validation_status, source, access_tier, is_published
)
values
(
  '51000000-0000-0000-0000-000000000001',
  'Francais',
  'orthographe',
  'accord_sujet_verbe',
  'Accord sujet-verbe',
  'Facile',
  'correction_orthographique',
  'Corrigez si necessaire : "Les eleves de cette classe travaille serieusement."',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["Les eleves de cette classe travaillent serieusement."]}'::jsonb,
  'Le noyau du sujet est "eleves", au pluriel. Le verbe doit donc prendre la marque du pluriel. Le groupe "de cette classe" n''est qu''un complement du nom.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '51000000-0000-0000-0000-000000000002',
  'Francais',
  'orthographe',
  'accord_sujet_verbe',
  'Accord sujet-verbe',
  'Facile',
  'qcm',
  'Choisissez la forme correcte : "Le bruit des chaises ... la concentration."',
  null,
  '[{"id":"a","label":"perturbent"},{"id":"b","label":"perturbe"},{"id":"c","label":"perturbes"},{"id":"d","label":"perturbera-t-il"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le sujet est "Le bruit", singulier. "Des chaises" complete le nom "bruit" mais ne commande pas l''accord du verbe.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '51000000-0000-0000-0000-000000000003',
  'Francais',
  'orthographe',
  'accord_sujet_verbe',
  'Accord sujet-verbe',
  'Facile',
  'vrai_faux',
  'Vrai ou faux : dans "Ni Paul ni ses camarades ne renoncent", le pluriel du verbe est correct.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Le sujet est compose de deux termes coordonnes. Ici, l''idee de pluralite justifie le verbe au pluriel.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '51000000-0000-0000-0000-000000000004',
  'Francais',
  'orthographe',
  'accord_sujet_verbe',
  'Accord sujet-verbe',
  'Facile',
  'correction_orthographique',
  'Corrigez si necessaire : "La plupart des candidats reussit cette etape."',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["La plupart des candidats reussissent cette etape."]}'::jsonb,
  'Dans cette phrase, l''expression "la plupart des candidats" renvoie a une pluralite reelle. Le verbe s''accorde donc au pluriel.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '51000000-0000-0000-0000-000000000005',
  'Francais',
  'orthographe',
  'accord_sujet_verbe',
  'Accord sujet-verbe',
  'Facile',
  'reponse_courte',
  'Dans "Un grand nombre d''exercices sont proposes", expliquez en un mot pourquoi le verbe est au pluriel.',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["pluralite","sens","pluriel logique"]}'::jsonb,
  'L''accord suit ici l''idee de pluralite portee par l''expression. Le sens de l''ensemble doit etre pris en compte.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '51000000-0000-0000-0000-000000000006',
  'Francais',
  'orthographe',
  'accord_sujet_verbe',
  'Accord sujet-verbe',
  'Facile',
  'correction_orthographique',
  'Corrigez si necessaire : "Toi qui relis ce chapitre, tu comprennent mieux la regle."',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["Toi qui relis ce chapitre, tu comprends mieux la regle."]}'::jsonb,
  'Le verbe principal s''accorde avec le pronom sujet "tu". Il ne faut pas se laisser influencer par une autre forme verbale deja presente dans la phrase.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '51000000-0000-0000-0000-000000000007',
  'Francais',
  'orthographe',
  'accord_sujet_verbe',
  'Accord sujet-verbe',
  'Facile',
  'qcm',
  'Choisissez la bonne forme : "Une serie de revisions bien pensee ... les candidats les plus fragiles."',
  null,
  '[{"id":"a","label":"aident"},{"id":"b","label":"aideront"},{"id":"c","label":"aide"},{"id":"d","label":"aider"}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  'Le sujet est "Une serie", singulier. Le groupe "de revisions bien pensee" ne modifie pas l''accord verbal. Le present de l''indicatif est attendu ici.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '51000000-0000-0000-0000-000000000008',
  'Francais',
  'orthographe',
  'accord_sujet_verbe',
  'Accord sujet-verbe',
  'Facile',
  'reponse_courte',
  'Dans "Ce ne sont pas les erreurs mais la fatigue qui explique ce blocage", quel est le verbe correct ?',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["explique"]}'::jsonb,
  'Le relatif "qui" reprend ici "la fatigue". C''est donc ce groupe, singulier, qui commande l''accord du verbe.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '51000000-0000-0000-0000-000000000009',
  'Francais',
  'orthographe',
  'accord_sujet_verbe',
  'Accord sujet-verbe',
  'Facile',
  'vrai_faux',
  'Vrai ou faux : "Plus d''un candidat ont hesite" est une phrase correctement accordee.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Dans l''usage scolaire de reference, "plus d''un" commande en principe le singulier: "plus d''un candidat a hesite".',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '51000000-0000-0000-0000-000000000010',
  'Francais',
  'orthographe',
  'accord_sujet_verbe',
  'Accord sujet-verbe',
  'Facile',
  'correction_orthographique',
  'Corrigez si necessaire : "Ni la fatigue ni le stress n''empechent cette candidate de poursuivre."',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["Ni la fatigue ni le stress n''empeche cette candidate de poursuivre."]}'::jsonb,
  'Les deux sujets coordonnes renvoient ici a deux noms singuliers envisages l''un apres l''autre. Dans ce type de phrase, le singulier est attendu dans l''usage scolaire de reference.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '52000000-0000-0000-0000-000000000001',
  'Francais',
  'grammaire',
  'nature_fonction_phrase_simple',
  'Nature et fonction dans la phrase simple',
  'Facile',
  'identification_grammaticale',
  'Dans "Les formateurs expliquent la consigne aux candidats", quelle est la fonction de "Les formateurs" ?',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["sujet"]}'::jsonb,
  'Le groupe "Les formateurs" accomplit l''action exprimee par le verbe "expliquent". Il commande aussi l''accord du verbe: c''est le sujet.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '52000000-0000-0000-0000-000000000002',
  'Francais',
  'grammaire',
  'nature_fonction_phrase_simple',
  'Nature et fonction dans la phrase simple',
  'Facile',
  'identification_grammaticale',
  'Dans la meme phrase, quelle est la fonction de "la consigne" ?',
  'Phrase support : "Les formateurs expliquent la consigne aux candidats."',
  null,
  '{"mode":"text","acceptableAnswers":["cod","complement d''objet direct"]}'::jsonb,
  'Le groupe complete directement le verbe "expliquent" sans preposition. Il s''agit donc d''un COD.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '52000000-0000-0000-0000-000000000003',
  'Francais',
  'grammaire',
  'nature_fonction_phrase_simple',
  'Nature et fonction dans la phrase simple',
  'Facile',
  'identification_grammaticale',
  'Dans la meme phrase, quelle est la fonction de "aux candidats" ?',
  'Phrase support : "Les formateurs expliquent la consigne aux candidats."',
  null,
  '{"mode":"text","acceptableAnswers":["coi","complement d''objet indirect"]}'::jsonb,
  'Le groupe est introduit par la preposition "a". Il complete le verbe de facon indirecte: c''est un COI.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '52000000-0000-0000-0000-000000000004',
  'Francais',
  'grammaire',
  'nature_fonction_phrase_simple',
  'Nature et fonction dans la phrase simple',
  'Facile',
  'qcm',
  'Dans "Les eleves semblent fatigues", "fatigues" est :',
  null,
  '[{"id":"a","label":"un COD"},{"id":"b","label":"un attribut du sujet"},{"id":"c","label":"un complement du nom"},{"id":"d","label":"un complement circonstanciel"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le verbe "semblent" est un verbe d''etat. Le groupe attribue une propriete au sujet "Les eleves" : c''est un attribut du sujet.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '52000000-0000-0000-0000-000000000005',
  'Francais',
  'grammaire',
  'nature_fonction_phrase_simple',
  'Nature et fonction dans la phrase simple',
  'Facile',
  'reponse_courte',
  'Dans "Le professeur parle a sa classe", pourquoi "a sa classe" n''est-il pas COD ?',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["parce qu''il y a une preposition","parce qu''il est introduit par une preposition","parce qu''il y a a"]}'::jsonb,
  'Un COD complete le verbe directement. Ici, le groupe est introduit par la preposition "a" : ce n''est donc pas un COD.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '52000000-0000-0000-0000-000000000006',
  'Francais',
  'grammaire',
  'nature_fonction_phrase_simple',
  'Nature et fonction dans la phrase simple',
  'Facile',
  'vrai_faux',
  'Vrai ou faux : dans "Les candidats relisent leur copie", "leur copie" est sujet.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Le sujet est "Les candidats". Le groupe "leur copie" complete le verbe "relisent" : il s''agit d''un COD.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '52000000-0000-0000-0000-000000000007',
  'Francais',
  'grammaire',
  'nature_fonction_phrase_simple',
  'Nature et fonction dans la phrase simple',
  'Facile',
  'identification_grammaticale',
  'Dans "Ce manuel utile reste sur la table", quelle est la nature de "Ce" ?',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["determinant","determinant demonstratif"]}'::jsonb,
  'Le mot "Ce" introduit le nom "manuel". Sa nature grammaticale est celle d''un determinant demonstratif.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '52000000-0000-0000-0000-000000000008',
  'Francais',
  'grammaire',
  'nature_fonction_phrase_simple',
  'Nature et fonction dans la phrase simple',
  'Facile',
  'qcm',
  'Dans "Les formateurs travaillent dans la salle", "dans la salle" est :',
  null,
  '[{"id":"a","label":"un attribut du sujet"},{"id":"b","label":"un COD"},{"id":"c","label":"un complement du nom"},{"id":"d","label":"un complement circonstanciel de lieu"}]'::jsonb,
  '{"mode":"single_choice","value":"d"}'::jsonb,
  'Le groupe indique le lieu ou se deroule l''action. Il ne complete pas le verbe comme objet: c''est un complement circonstanciel de lieu.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '52000000-0000-0000-0000-000000000009',
  'Francais',
  'grammaire',
  'nature_fonction_phrase_simple',
  'Nature et fonction dans la phrase simple',
  'Facile',
  'identification_grammaticale',
  'Dans "La phrase que tu analyses est courte", quelle est la nature de "que" ?',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["pronom relatif"]}'::jsonb,
  'Le mot "que" introduit une relative et reprend l''antecedent "phrase". Sa nature est donc celle d''un pronom relatif.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '52000000-0000-0000-0000-000000000010',
  'Francais',
  'grammaire',
  'nature_fonction_phrase_simple',
  'Nature et fonction dans la phrase simple',
  'Facile',
  'reponse_courte',
  'Expliquez en une courte phrase la difference entre nature et fonction.',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["la nature dit ce qu''est le mot, la fonction dit son role dans la phrase","la nature dit ce qu''est un mot, la fonction dit le role qu''il joue"]}'::jsonb,
  'La nature renvoie a la classe grammaticale du mot ou du groupe. La fonction renvoie a son role dans la phrase. Une analyse juste commence par cette distinction.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '53000000-0000-0000-0000-000000000001',
  'Francais',
  'conjugaison',
  'futur_conditionnel_subjonctif',
  'Futur, conditionnel, subjonctif',
  'Intermediaire',
  'qcm',
  'Completez : "Demain, nous ... la correction complete."',
  null,
  '[{"id":"a","label":"verrions"},{"id":"b","label":"verrons"},{"id":"c","label":"voyons"},{"id":"d","label":"ayons vu"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'L''adverbe "Demain" inscrit l''action dans l''avenir presente comme certaine. Le futur simple "verrons" est donc attendu.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '53000000-0000-0000-0000-000000000002',
  'Francais',
  'conjugaison',
  'futur_conditionnel_subjonctif',
  'Futur, conditionnel, subjonctif',
  'Intermediaire',
  'qcm',
  'Completez : "Avec plus de temps, nous ... davantage d''exercices."',
  null,
  '[{"id":"a","label":"ferons"},{"id":"b","label":"faisons"},{"id":"c","label":"ferions"},{"id":"d","label":"fissions"}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  'La phrase exprime une hypothese. Le conditionnel present "ferions" correspond a cette valeur.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '53000000-0000-0000-0000-000000000003',
  'Francais',
  'conjugaison',
  'futur_conditionnel_subjonctif',
  'Futur, conditionnel, subjonctif',
  'Intermediaire',
  'reponse_courte',
  'Conjuguez : "Il faut que vous (prendre) le temps de relire."',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["preniez"]}'::jsonb,
  'Apres "Il faut que", le verbe se met au subjonctif. La forme correcte est "preniez".',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '53000000-0000-0000-0000-000000000004',
  'Francais',
  'conjugaison',
  'futur_conditionnel_subjonctif',
  'Futur, conditionnel, subjonctif',
  'Intermediaire',
  'vrai_faux',
  'Vrai ou faux : dans "Je voudrais que tu viennes", "viennes" est au subjonctif.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'La subordonnee introduite par "que" depend ici d''un verbe de souhait. Le subjonctif present "viennes" est correct.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '53000000-0000-0000-0000-000000000005',
  'Francais',
  'conjugaison',
  'futur_conditionnel_subjonctif',
  'Futur, conditionnel, subjonctif',
  'Intermediaire',
  'qcm',
  'Dans "Si tu travaillais davantage, tu reussirais", "reussirais" est au :',
  null,
  '[{"id":"a","label":"futur"},{"id":"b","label":"subjonctif"},{"id":"c","label":"imparfait"},{"id":"d","label":"conditionnel"}]'::jsonb,
  '{"mode":"single_choice","value":"d"}'::jsonb,
  'La structure "si + imparfait" appelle ici le conditionnel dans la proposition principale. La valeur est hypothetique.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '53000000-0000-0000-0000-000000000006',
  'Francais',
  'conjugaison',
  'futur_conditionnel_subjonctif',
  'Futur, conditionnel, subjonctif',
  'Intermediaire',
  'reponse_courte',
  'Donnez l''infinitif du verbe dans "nous tiendrons".',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["tenir"]}'::jsonb,
  'Le futur de "tenir" se construit sur le radical "tiendr-". Il faut reconnaitre l''infinitif derriere cette variation du radical.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '53000000-0000-0000-0000-000000000007',
  'Francais',
  'conjugaison',
  'futur_conditionnel_subjonctif',
  'Futur, conditionnel, subjonctif',
  'Intermediaire',
  'qcm',
  'Completez : "Bien qu''il ... fatigue, il continue."',
  null,
  '[{"id":"a","label":"est"},{"id":"b","label":"sera"},{"id":"c","label":"soit"},{"id":"d","label":"etait"}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  'La locution "bien que" introduit une subordonnee qui demande le subjonctif. "Soit" est donc la forme correcte.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '53000000-0000-0000-0000-000000000008',
  'Francais',
  'conjugaison',
  'futur_conditionnel_subjonctif',
  'Futur, conditionnel, subjonctif',
  'Intermediaire',
  'vrai_faux',
  'Vrai ou faux : dans "Quand tu arriveras, nous commencerons", les deux verbes sont au futur.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Dans cette phrase, l''action est envisagee dans l''avenir pour les deux verbes. Il faut lire la phrase elle-meme plutot qu''appliquer une regle approximative.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '53000000-0000-0000-0000-000000000009',
  'Francais',
  'conjugaison',
  'futur_conditionnel_subjonctif',
  'Futur, conditionnel, subjonctif',
  'Intermediaire',
  'qcm',
  'Dans quelle phrase le conditionnel exprime-t-il une attenuation ?',
  null,
  '[{"id":"a","label":"Je dirais que cette reponse est juste."},{"id":"b","label":"Demain, je dirai la verite."},{"id":"c","label":"Je dis toujours la verite."},{"id":"d","label":"Je dirai ce que je pense, quoi qu''il arrive."}]'::jsonb,
  '{"mode":"single_choice","value":"a"}'::jsonb,
  'Dans "Je dirais", le locuteur prend de la distance et attenue son affirmation. Il ne s''agit pas d''un futur mais d''une valeur modale.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '53000000-0000-0000-0000-000000000010',
  'Francais',
  'conjugaison',
  'futur_conditionnel_subjonctif',
  'Futur, conditionnel, subjonctif',
  'Intermediaire',
  'reponse_courte',
  'Dans "Je dirais que cette reponse est juste", quel mot montre que l''attenuation est portee par le conditionnel ?',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["dirais","je dirais"]}'::jsonb,
  'Le conditionnel est porte par le verbe ''dirais''. C''est lui qui introduit la prise de distance.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '54000000-0000-0000-0000-000000000001',
  'Francais',
  'comprehension_texte',
  'inferences_et_connecteurs',
  'Inferences et connecteurs',
  'Intermediaire',
  'qcm',
  'Ou Lina pose-t-elle son cartable ?',
  'Texte support : "Lina posa son cartable sur le banc avant d''entrer en classe."',
  '[{"id":"a","label":"Sur le banc"},{"id":"b","label":"Dans l''armoire"},{"id":"c","label":"Sous la table"},{"id":"d","label":"Devant la porte"}]'::jsonb,
  '{"mode":"single_choice","value":"a"}'::jsonb,
  'Le texte dit explicitement: "Lina posa son cartable sur le banc". Il faut d''abord verifier si la reponse est ecrite avant de chercher une inference.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '54000000-0000-0000-0000-000000000002',
  'Francais',
  'comprehension_texte',
  'inferences_et_connecteurs',
  'Inferences et connecteurs',
  'Intermediaire',
  'qcm',
  'Que peut-on inferer de la situation ?',
  'Texte support : "Paul serra son manteau et pressa le pas."',
  '[{"id":"a","label":"Il est midi."},{"id":"b","label":"Il fait probablement froid."},{"id":"c","label":"Le personnage est en vacances."},{"id":"d","label":"Paul cherche un taxi."}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le texte ne dit pas explicitement qu''il fait froid, mais les gestes "serra son manteau" et "pressa le pas" constituent des indices convergents.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '54000000-0000-0000-0000-000000000003',
  'Francais',
  'comprehension_texte',
  'inferences_et_connecteurs',
  'Inferences et connecteurs',
  'Intermediaire',
  'qcm',
  'Dans "Il avait revise, pourtant il a echoue", le mot "pourtant" marque :',
  null,
  '[{"id":"a","label":"Une addition"},{"id":"b","label":"Une cause"},{"id":"c","label":"Une consequence"},{"id":"d","label":"Une opposition"}]'::jsonb,
  '{"mode":"single_choice","value":"d"}'::jsonb,
  'Le connecteur "pourtant" oppose le resultat a ce qu''on attendait. Il est donc un marqueur d''opposition.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '54000000-0000-0000-0000-000000000004',
  'Francais',
  'comprehension_texte',
  'inferences_et_connecteurs',
  'Inferences et connecteurs',
  'Intermediaire',
  'analyse_texte',
  'Dans "Lina prend son parapluie. Elle sort aussitot.", a qui renvoie le pronom "Elle" ?',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["Lina"]}'::jsonb,
  'Le pronom reprend le personnage feminin deja mentionne. Le referent le plus coherent ici est "Lina".',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '54000000-0000-0000-0000-000000000005',
  'Francais',
  'comprehension_texte',
  'inferences_et_connecteurs',
  'Inferences et connecteurs',
  'Intermediaire',
  'qcm',
  'Quel titre convient le mieux a ce passage ?',
  'Texte support : "Lina prend son parapluie, traverse la cour humide et entre rapidement dans le batiment."',
  '[{"id":"a","label":"La salle informatique"},{"id":"b","label":"Une recette de cuisine"},{"id":"c","label":"Un trajet en bus"},{"id":"d","label":"Une entree sous l''orage"}]'::jsonb,
  '{"mode":"single_choice","value":"d"}'::jsonb,
  'Le passage evoque la pluie, le parapluie et l''entree en classe. Le dernier titre synthetise au mieux l''atmosphere et l''action.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '54000000-0000-0000-0000-000000000006',
  'Francais',
  'comprehension_texte',
  'inferences_et_connecteurs',
  'Inferences et connecteurs',
  'Intermediaire',
  'qcm',
  'Quel etat du personnage peut-on inferer ?',
  'Texte support : "Maya serrait les poings et evitait les regards."',
  '[{"id":"a","label":"Il est amuse."},{"id":"b","label":"Il est tendu ou en colere."},{"id":"c","label":"Il s''endort."},{"id":"d","label":"Il cherche ses lunettes."}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Les gestes "serrait les poings" et "evitait les regards" sont compatibles avec une tension emotionnelle. L''inference doit reposer sur les indices corporels.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '54000000-0000-0000-0000-000000000007',
  'Francais',
  'comprehension_texte',
  'inferences_et_connecteurs',
  'Inferences et connecteurs',
  'Intermediaire',
  'qcm',
  'Dans "Elle parla tout bas pour ne pas reveiller son frere", l''expression "pour ne pas reveiller son frere" indique :',
  null,
  '[{"id":"a","label":"La cause"},{"id":"b","label":"Le but"},{"id":"c","label":"La consequence"},{"id":"d","label":"L''opposition"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'La tournure introduite par "pour" exprime ici l''intention du personnage. Elle indique le but de l''action.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '54000000-0000-0000-0000-000000000008',
  'Francais',
  'comprehension_texte',
  'inferences_et_connecteurs',
  'Inferences et connecteurs',
  'Intermediaire',
  'vrai_faux',
  'Vrai ou faux : dans "Je traversai la cour en silence", le narrateur parle a la premiere personne.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Le pronom "Je" et la terminaison verbale indiquent un point de vue a la premiere personne.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '54000000-0000-0000-0000-000000000009',
  'Francais',
  'comprehension_texte',
  'inferences_et_connecteurs',
  'Inferences et connecteurs',
  'Intermediaire',
  'qcm',
  'Dans "Le givre recouvrait la pelouse, c''est-a-dire une fine couche de glace", l''expression "c''est-a-dire" annonce :',
  null,
  '[{"id":"a","label":"Une reformulation"},{"id":"b","label":"Une opposition"},{"id":"c","label":"Une conclusion"},{"id":"d","label":"Une enumeration"}]'::jsonb,
  '{"mode":"single_choice","value":"a"}'::jsonb,
  'La seconde partie explicite la premiere. On est bien dans une reformulation destinee a aider la comprehension.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '54000000-0000-0000-0000-000000000010',
  'Francais',
  'comprehension_texte',
  'inferences_et_connecteurs',
  'Inferences et connecteurs',
  'Intermediaire',
  'analyse_texte',
  'Pourquoi la reponse ''Il est midi'' n''est-elle pas recevable a la question 2 ?',
  'Rappel du texte support de la question 2 : "Paul serra son manteau et pressa le pas."',
  null,
  '{"mode":"text","acceptableAnswers":["parce que le texte ne donne aucun indice sur l''heure","aucun indice sur l''heure n''est donne","le texte ne permet pas de savoir l''heure"]}'::jsonb,
  'Une bonne inference s''appuie sur des indices textuels. Or rien, dans le passage, ne permet de deduire l''heure de la scene. Il faut distinguer l''inference justifiee de l''invention.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '56000000-0000-0000-0000-000000000001',
  'Francais',
  'grammaire',
  'formes_de_phrase_et_voix_passive',
  'Formes de phrase et voix passive',
  'Intermediaire',
  'qcm',
  'Dans quelle phrase le verbe est-il a la voix passive ?',
  null,
  '[{"id":"a","label":"Le jury corrige les copies avec attention."},{"id":"b","label":"Les copies sont corrigees avec attention par le jury."},{"id":"c","label":"Le jury a corrige les copies."},{"id":"d","label":"Corriger les copies demande du temps."}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Dans la phrase correcte, le sujet "copies" subit l''action et la construction "etre + participe passe" signale la voix passive.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '56000000-0000-0000-0000-000000000002',
  'Francais',
  'grammaire',
  'formes_de_phrase_et_voix_passive',
  'Formes de phrase et voix passive',
  'Intermediaire',
  'reponse_courte',
  'Transformez a la voix passive.',
  'Phrase support : "Le jury souligne les progres des candidats."',
  null,
  '{"mode":"text","acceptableAnswers":["les progres des candidats sont soulignes par le jury","les progres des candidats sont soulignes par le jury."]}'::jsonb,
  'Le COD de la phrase active devient le sujet du passif. Le verbe "souligne" devient "sont soulignes" pour s''accorder avec "progres", masculin pluriel.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '56000000-0000-0000-0000-000000000003',
  'Francais',
  'grammaire',
  'formes_de_phrase_et_voix_passive',
  'Formes de phrase et voix passive',
  'Intermediaire',
  'vrai_faux',
  'Vrai ou faux : on peut transformer en phrase passive "Les eleves telephonent a leur formateur".',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Le verbe "telephoner a" construit ici un COI et non un COD. Sans complement d''objet direct, la passivation canonique n''est pas attendue.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '56000000-0000-0000-0000-000000000004',
  'Francais',
  'grammaire',
  'formes_de_phrase_et_voix_passive',
  'Formes de phrase et voix passive',
  'Intermediaire',
  'qcm',
  'Quelle est la transformation passive correcte de "Le correcteur relevera les erreurs" ?',
  null,
  '[{"id":"a","label":"Les erreurs releveront le correcteur."},{"id":"b","label":"Les erreurs sont relevees par le correcteur."},{"id":"c","label":"Les erreurs seront relevees par le correcteur."},{"id":"d","label":"Le correcteur aura releve les erreurs."}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  'Le futur simple actif devient ici un futur passif: "seront relevees". Le participe passe s''accorde avec "erreurs", feminin pluriel.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '56000000-0000-0000-0000-000000000005',
  'Francais',
  'grammaire',
  'formes_de_phrase_et_voix_passive',
  'Formes de phrase et voix passive',
  'Intermediaire',
  'identification_grammaticale',
  'Dans "La consigne a ete comprise par les candidats", quelle etait la fonction de "la consigne" dans la phrase active ?',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["cod","complement d''objet direct"]}'::jsonb,
  'Dans le passage a la voix passive, l''ancien COD devient le sujet de la nouvelle phrase.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '56000000-0000-0000-0000-000000000006',
  'Francais',
  'grammaire',
  'formes_de_phrase_et_voix_passive',
  'Formes de phrase et voix passive',
  'Intermediaire',
  'reponse_courte',
  'Transformez a la voix active.',
  'Phrase support : "La consigne a ete comprise par les candidats."',
  null,
  '{"mode":"text","acceptableAnswers":["les candidats ont compris la consigne","les candidats ont compris la consigne."]}'::jsonb,
  'Le complement d''agent "par les candidats" redevient sujet de la phrase active, et "la consigne" reprend sa fonction de COD.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '56000000-0000-0000-0000-000000000007',
  'Francais',
  'grammaire',
  'formes_de_phrase_et_voix_passive',
  'Formes de phrase et voix passive',
  'Intermediaire',
  'qcm',
  'Dans la phrase passive "Les copies seront relues par les formateurs", quel groupe est complement d''agent ?',
  null,
  '[{"id":"a","label":"Les copies"},{"id":"b","label":"seront relues"},{"id":"c","label":"les formateurs"},{"id":"d","label":"par les formateurs"}]'::jsonb,
  '{"mode":"single_choice","value":"d"}'::jsonb,
  'Le complement d''agent designe celui qui accomplit reellement l''action dans une phrase passive. Il est ici introduit par "par".',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '56000000-0000-0000-0000-000000000008',
  'Francais',
  'grammaire',
  'formes_de_phrase_et_voix_passive',
  'Formes de phrase et voix passive',
  'Intermediaire',
  'vrai_faux',
  'Vrai ou faux : dans "Les affiches ont ete collees par les eleves", le participe passe "collees" s''accorde avec "affiches".',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Dans une construction passive, le participe passe s''accorde avec le sujet grammatical, ici "affiches", feminin pluriel.',
  'valide',
  'Module Francais CRPE V1',
  'free',
  true
),

(
  '57000000-0000-0000-0000-000000000001',
  'Francais',
  'analyse_langue',
  'transformations_de_phrase_crpe',
  'Transformations de phrase type CRPE',
  'Intermediaire',
  'qcm',
  'Quelle est la mise en relief correcte du COD dans "Le professeur explique la regle" ?',
  null,
  '[{"id":"a","label":"C''est la regle que le professeur explique."},{"id":"b","label":"C''est le professeur que la regle explique."},{"id":"c","label":"C''est la regle qui le professeur explique."},{"id":"d","label":"La regle, le professeur l''a explique."}]'::jsonb,
  '{"mode":"single_choice","value":"a"}'::jsonb,
  'Pour mettre en relief le COD, on utilise ici la tournure "c''est ... que". Le groupe focalise reste "la regle".',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '57000000-0000-0000-0000-000000000002',
  'Francais',
  'analyse_langue',
  'transformations_de_phrase_crpe',
  'Transformations de phrase type CRPE',
  'Intermediaire',
  'reponse_courte',
  'Mettez la phrase a la forme negative.',
  'Phrase support : "Les candidats comprennent encore la consigne."',
  null,
  '{"mode":"text","acceptableAnswers":["les candidats ne comprennent pas encore la consigne","les candidats ne comprennent pas encore la consigne."]}'::jsonb,
  'La negation canonique se construit ici avec "ne ... pas" autour du verbe. Le reste de la phrase est conserve.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '57000000-0000-0000-0000-000000000003',
  'Francais',
  'analyse_langue',
  'transformations_de_phrase_crpe',
  'Transformations de phrase type CRPE',
  'Intermediaire',
  'qcm',
  'Quelle est la transformation interrogative correcte de "Vous comprenez cette consigne" ?',
  null,
  '[{"id":"a","label":"Vous comprenez-vous cette consigne ?"},{"id":"b","label":"Cette consigne comprenez-vous ?"},{"id":"c","label":"Comprenez-vous cette consigne ?"},{"id":"d","label":"Est-ce que vous comprenez, cette consigne ?"}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  'L''interrogation directe avec inversion du sujet se forme ici par "Comprenez-vous ... ?".',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '57000000-0000-0000-0000-000000000004',
  'Francais',
  'analyse_langue',
  'transformations_de_phrase_crpe',
  'Transformations de phrase type CRPE',
  'Intermediaire',
  'vrai_faux',
  'Vrai ou faux : la pronominalisation de "les erreurs de syntaxe" dans "Le jury repere les erreurs de syntaxe" donne "Le jury les repere".',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Le groupe COD "les erreurs de syntaxe" peut etre remplace par le pronom personnel COD "les". Cette manipulation confirme sa fonction.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '57000000-0000-0000-0000-000000000005',
  'Francais',
  'analyse_langue',
  'transformations_de_phrase_crpe',
  'Transformations de phrase type CRPE',
  'Intermediaire',
  'reponse_courte',
  'Transformez en mettant le sujet en relief.',
  'Phrase support : "Marie a trouve la reponse."',
  null,
  '{"mode":"text","acceptableAnswers":["c''est marie qui a trouve la reponse","c''est marie qui a trouve la reponse."]}'::jsonb,
  'Pour mettre le sujet en relief, la tournure canonique est "c''est ... qui". Le sujet focalise est ici "Marie".',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '57000000-0000-0000-0000-000000000006',
  'Francais',
  'analyse_langue',
  'transformations_de_phrase_crpe',
  'Transformations de phrase type CRPE',
  'Intermediaire',
  'reponse_courte',
  'Pronominalisez le COD.',
  'Phrase support : "Le candidat consulte le bareme."',
  null,
  '{"mode":"text","acceptableAnswers":["le candidat le consulte","le candidat le consulte."]}'::jsonb,
  'Le groupe "le bareme" est COD. Il est repris par le pronom COD "le", place avant le verbe conjugue.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '57000000-0000-0000-0000-000000000007',
  'Francais',
  'analyse_langue',
  'transformations_de_phrase_crpe',
  'Transformations de phrase type CRPE',
  'Intermediaire',
  'qcm',
  'Dans "Dans cette copie, le candidat justifie sa reponse", quelle manipulation montre le mieux que "Dans cette copie" est un complement circonstanciel ?',
  null,
  '[{"id":"a","label":"Le remplacement par un pronom sujet."},{"id":"b","label":"L''accord du verbe avec ce groupe."},{"id":"c","label":"Sa suppression sans rendre la phrase agrammaticale."},{"id":"d","label":"Le deplacement en fin de phrase ou en tete de phrase."}]'::jsonb,
  '{"mode":"single_choice","value":"d"}'::jsonb,
  'Le deplacement est une manipulation classique des complements circonstanciels. Il montre ici que le groupe garde sa place mobile sans commander l''accord.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '57000000-0000-0000-0000-000000000008',
  'Francais',
  'analyse_langue',
  'transformations_de_phrase_crpe',
  'Transformations de phrase type CRPE',
  'Intermediaire',
  'analyse_texte',
  'Pourquoi la tournure "Le jury les repere" confirme-t-elle que "les erreurs de syntaxe" est un COD ?',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["parce que le groupe peut etre remplace par un pronom cod","parce qu''on peut le remplacer par un pronom cod","parce qu''il est remplacable par le pronom les"]}'::jsonb,
  'La pronominalisation par "les" montre que le groupe occupe une fonction de complement d''objet direct. La manipulation sert ici de preuve syntaxique.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '55000000-0000-0000-0000-000000000001',
  'Francais',
  'didactique_francais',
  'lecture_et_comprehension',
  'Lecture, comprehension et etude de la langue',
  'Intermediaire',
  'qcm',
  'Un eleve ecrit "les enfant chante". Le premier geste utile de l''enseignant est de :',
  null,
  '[{"id":"a","label":"Dire seulement que c''est faux."},{"id":"b","label":"Chercher ce que l''eleve a compris ou non de l''accord."},{"id":"c","label":"Passer immediatement a une autre notion."},{"id":"d","label":"Faire copier la phrase correcte dix fois."}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'La reponse la plus didactiquement juste consiste a analyser l''erreur pour identifier l''obstacle. Sans cela, la correction risque de rester superficielle.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '55000000-0000-0000-0000-000000000002',
  'Francais',
  'didactique_francais',
  'lecture_et_comprehension',
  'Lecture, comprehension et etude de la langue',
  'Intermediaire',
  'vrai_faux',
  'Vrai ou faux : la dictee negociee est interessante parce qu''elle oblige les eleves a verbaliser leurs raisonnements orthographiques.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'La dictee negociee ne vaut pas par son aspect collectif en soi, mais parce qu''elle rend visibles les procedures et les justifications des eleves.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '55000000-0000-0000-0000-000000000003',
  'Francais',
  'didactique_francais',
  'lecture_et_comprehension',
  'Lecture, comprehension et etude de la langue',
  'Intermediaire',
  'qcm',
  'Quelle pratique aide le plus les eleves a progresser en comprehension ?',
  null,
  '[{"id":"a","label":"Leur demander seulement de relire en silence."},{"id":"b","label":"Corriger uniquement les mots mal lus."},{"id":"c","label":"Enseigner explicitement des strategies comme anticiper, verifier et inferer."},{"id":"d","label":"Privilegier uniquement la lecture a voix haute."}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  'La comprehension progresse quand les strategies de lecteur sont enseignees et rendues visibles. La simple repetition de lecture ne suffit pas.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '55000000-0000-0000-0000-000000000004',
  'Francais',
  'didactique_francais',
  'lecture_et_comprehension',
  'Lecture, comprehension et etude de la langue',
  'Intermediaire',
  'reponse_courte',
  'Qu''est-ce que la conscience phonologique ?',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["la capacite a identifier et manipuler les sons de la langue","identifier et manipuler les sons de la langue","manipuler les sons de la langue"]}'::jsonb,
  'La conscience phonologique concerne les sons de l''oral: syllabes, rimes, phonemes. Elle ne se confond pas avec la simple connaissance des lettres.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '55000000-0000-0000-0000-000000000005',
  'Francais',
  'didactique_francais',
  'lecture_et_comprehension',
  'Lecture, comprehension et etude de la langue',
  'Intermediaire',
  'qcm',
  'Pour installer durablement un mot nouveau, il vaut mieux :',
  null,
  '[{"id":"a","label":"Le faire copier une seule fois."},{"id":"b","label":"Le faire rencontrer et reutiliser dans plusieurs contextes."},{"id":"c","label":"Le faire memoriser hors de toute phrase."},{"id":"d","label":"Le faire chercher dans le dictionnaire une seule fois."}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le vocabulaire se stabilise grace a des rencontres multiples, des reformulations et des reutilisations. Une exposition unique reste fragile.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '55000000-0000-0000-0000-000000000006',
  'Francais',
  'didactique_francais',
  'lecture_et_comprehension',
  'Lecture, comprehension et etude de la langue',
  'Intermediaire',
  'qcm',
  'Pour aider des eleves a produire un texte, il est pertinent de :',
  null,
  '[{"id":"a","label":"Les laisser ecrire sans preparation puis corriger a la fin."},{"id":"b","label":"Prevoir un temps de planification, de mise en texte puis de revision."},{"id":"c","label":"Corriger a leur place des la premiere phrase."},{"id":"d","label":"Imposer le nombre de mots avant tout autre consigne."}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'La production d''ecrit est un processus. Planifier, ecrire et reviser constituent des etapes complementaires qui rendent l''activite plus apprenable.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '55000000-0000-0000-0000-000000000007',
  'Francais',
  'didactique_francais',
  'lecture_et_comprehension',
  'Lecture, comprehension et etude de la langue',
  'Intermediaire',
  'vrai_faux',
  'Vrai ou faux : l''oral joue un role important dans les apprentissages du francais, y compris au-dela de la maternelle.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'L''oral soutient la comprehension, la formulation de la pensee, le lexique et l''acces a l''ecrit. Il ne doit pas etre traite comme un apprentissage secondaire.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '55000000-0000-0000-0000-000000000008',
  'Francais',
  'didactique_francais',
  'lecture_et_comprehension',
  'Lecture, comprehension et etude de la langue',
  'Intermediaire',
  'qcm',
  'Pourquoi un corpus de phrases variees est-il utile pour enseigner une notion grammaticale ?',
  null,
  '[{"id":"a","label":"Parce qu''il permet de faire apparaitre des regularites et des contrastes."},{"id":"b","label":"Parce qu''il remplace toute manipulation."},{"id":"c","label":"Parce qu''il evite d''avoir a justifier les regles."},{"id":"d","label":"Parce qu''il simplifie la memorisation des exceptions."}]'::jsonb,
  '{"mode":"single_choice","value":"a"}'::jsonb,
  'Un corpus bien choisi permet de comparer, de classer et de justifier. C''est un support d''observation, pas un simple stock d''exemples.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '55000000-0000-0000-0000-000000000009',
  'Francais',
  'didactique_francais',
  'lecture_et_comprehension',
  'Lecture, comprehension et etude de la langue',
  'Intermediaire',
  'reponse_courte',
  'A quoi sert d''abord une evaluation formative ?',
  null,
  null,
  '{"mode":"text","acceptableAnswers":["a ajuster l''enseignement et aider l''eleve a progresser","ajuster l''enseignement et aider l''eleve a progresser","faire progresser en ajustant l''enseignement"]}'::jsonb,
  'L''evaluation formative n''a pas pour premier but de classer. Elle sert a recueillir des indices sur les acquis et les obstacles pour orienter la suite du travail.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
),

(
  '55000000-0000-0000-0000-000000000010',
  'Francais',
  'didactique_francais',
  'lecture_et_comprehension',
  'Lecture, comprehension et etude de la langue',
  'Intermediaire',
  'qcm',
  'La fluence en lecture designe surtout :',
  null,
  '[{"id":"a","label":"La vitesse seule."},{"id":"b","label":"Une lecture suffisamment exacte, rapide et expressive pour soutenir la comprehension."},{"id":"c","label":"La capacite a recopier vite."},{"id":"d","label":"La maitrise exclusive de la correspondance grapheme-phoneme."}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'La fluence articule exactitude, rythme et prosodie. Elle a du sens parce qu''elle soutient la comprehension du texte, pas parce qu''elle installe une simple performance de vitesse.',
  'valide',
  'Module Francais CRPE V1',
  'premium',
  true
);
