insert into public.exercises (
  id,
  subject,
  subdomain,
  topic_key,
  topic_label,
  level,
  exercise_type,
  instruction,
  support_text,
  choices,
  expected_answer,
  detailed_explanation,
  validation_status,
  source,
  access_tier,
  is_published
)
values
  (
    '11111111-1111-1111-1111-111111111111',
    'Francais',
    'grammaire',
    'classes_grammaticales',
    'Classes grammaticales',
    'Facile',
    'qcm',
    'Dans la phrase "Les eleves ecoutent attentivement la consigne", quelle est la nature du mot "attentivement" ?',
    null,
    '[{"id":"a","label":"Un adjectif qualificatif"},{"id":"b","label":"Un adverbe"},{"id":"c","label":"Un nom commun"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Attentivement" precise la maniere dont les eleves ecoutent. Il modifie le verbe "ecoutent" : c''est donc un adverbe.',
    'valide',
    'Creation CRPE Francais V1',
    'free',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111112',
    'Francais',
    'grammaire',
    'fonctions_essentielles',
    'Sujet, COD, COI et attribut',
    'Intermediaire',
    'identification_grammaticale',
    'Identifiez la fonction du groupe nominal souligne : "Les enseignants preparents <les evaluations de fin de periode>."',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["complement d''objet direct","cod"]}'::jsonb,
    'Le groupe nominal complete directement le verbe "preparent" sans preposition. Il s''agit d''un complement d''objet direct.',
    'valide',
    'Creation CRPE Francais V1',
    'premium',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111113',
    'Francais',
    'orthographe',
    'participe_passe_pronominaux',
    'Participe passe et verbes pronominaux',
    'Facile',
    'vrai_faux',
    'Vrai ou faux : dans "Ils se sont parle hier", le participe passe s''accorde.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":false}'::jsonb,
    'Avec le verbe pronominal "se parler", le complement est indirect. Le participe passe "parle" ne s''accorde donc pas.',
    'valide',
    'Creation CRPE Francais V1',
    'free',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111114',
    'Francais',
    'orthographe',
    'accords_groupe_nominal',
    'Accords dans le groupe nominal',
    'Intermediaire',
    'correction_orthographique',
    'Corrigez l''orthographe de la phrase suivante si necessaire : "Les enfant jouent dans la cour de recreation."',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["Les enfants jouent dans la cour de recreation."]}'::jsonb,
    'Le nom "enfant" doit etre accorde au pluriel : "enfants". Le reste de la phrase est correct.',
    'valide',
    'Creation CRPE Francais V1',
    'premium',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111115',
    'Francais',
    'conjugaison',
    'temps_de_base',
    'Present, imparfait et futur',
    'Facile',
    'qcm',
    'Quelle est la forme correcte au futur simple du verbe "voir" avec "nous" ?',
    null,
    '[{"id":"a","label":"nous voyons"},{"id":"b","label":"nous verrons"},{"id":"c","label":"nous verrions"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    'Le futur simple du verbe "voir" avec "nous" est "nous verrons".',
    'valide',
    'Creation CRPE Francais V1',
    'free',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111116',
    'Francais',
    'conjugaison',
    'modes_temps_proches',
    'Futur, conditionnel et subjonctif',
    'Avance',
    'reponse_courte',
    'Conjuguez correctement le verbe entre parentheses : "Il faut que vous (prendre) le temps de relire."',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["preniez"]}'::jsonb,
    'Apres "il faut que", on emploie le subjonctif present. Pour "prendre" a la 2e personne du pluriel, on ecrit "vous preniez".',
    'valide',
    'Creation CRPE Francais V1',
    'premium',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111117',
    'Francais',
    'lexique',
    'synonymes_antonymes',
    'Synonymie et antonymie',
    'Facile',
    'qcm',
    'Quel mot est un synonyme de "rigoureux" dans un contexte d''etude ?',
    null,
    '[{"id":"a","label":"methodique"},{"id":"b","label":"bruyant"},{"id":"c","label":"timide"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    'Dans un contexte d''etude, "rigoureux" renvoie a une attitude serieuse et methodique.',
    'valide',
    'Creation CRPE Francais V1',
    'free',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111118',
    'Francais',
    'lexique',
    'synonymes_antonymes',
    'Synonymie et antonymie',
    'Intermediaire',
    'reponse_courte',
    'Donnez l''antonyme du mot "explicite".',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["implicite"]}'::jsonb,
    'L''antonyme courant de "explicite" est "implicite".',
    'valide',
    'Creation CRPE Francais V1',
    'premium',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111119',
    'Francais',
    'comprehension_texte',
    'sentiment_etat_du_narrateur',
    'Sentiment et evolution du texte',
    'Intermediaire',
    'analyse_texte',
    'Quel est le sentiment principal exprime par le narrateur dans l''extrait ?',
    '"En entrant dans la classe, il sentit immediatement une forme d''apaisement. Les voix se taisaient, les regards se posaient, et le silence semblait enfin possible."',
    null,
    '{"mode":"text","acceptableAnswers":["apaisement","un apaisement"]}'::jsonb,
    'Le texte insiste sur le calme retrouve, le silence et la detente progressive. Le sentiment dominant est donc l''apaisement.',
    'valide',
    'Creation CRPE Francais V1',
    'free',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111120',
    'Francais',
    'comprehension_texte',
    'indices_evolution_texte',
    'Indices d''evolution du texte',
    'Avance',
    'reponse_courte',
    'Dans cet extrait, quel indice montre que la situation s''ameliore ?',
    '"En entrant dans la classe, il sentit immediatement une forme d''apaisement. Les voix se taisaient, les regards se posaient, et le silence semblait enfin possible."',
    null,
    '{"mode":"text","acceptableAnswers":["les voix se taisaient","le silence semblait enfin possible"]}'::jsonb,
    'L''amelioration est perceptible parce que le bruit diminue et que le calme devient possible. Les formulations "les voix se taisaient" et "le silence semblait enfin possible" l''indiquent clairement.',
    'valide',
    'Creation CRPE Francais V1',
    'premium',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111121',
    'Francais',
    'analyse_langue',
    'propositions_subordonnees',
    'Propositions subordonnees',
    'Intermediaire',
    'identification_grammaticale',
    'Dans la phrase "Quand il pleut, les eleves restent en classe", quelle est la nature de "Quand il pleut" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["proposition subordonnee circonstancielle de temps","subordonnee circonstancielle de temps"]}'::jsonb,
    'Le groupe "Quand il pleut" introduit une circonstance temporelle et contient un verbe conjugue. C''est donc une proposition subordonnee circonstancielle de temps.',
    'valide',
    'Creation CRPE Francais V1',
    'free',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111122',
    'Francais',
    'analyse_langue',
    'effets_de_texte',
    'Effets de texte et interpretation',
    'Avance',
    'analyse_texte',
    'Expliquez brievement l''effet produit par l''opposition entre "se taisaient" et "semblait enfin possible".',
    '"Les voix se taisaient, les regards se posaient, et le silence semblait enfin possible."',
    null,
    '{"mode":"text","acceptableAnswers":["elle montre une installation progressive du calme","elle souligne la progression vers le calme"]}'::jsonb,
    'L''auteur construit une progression : le bruit baisse d''abord, puis le silence devient envisageable. L''effet produit est celui d''un retour graduel au calme.',
    'valide',
    'Creation CRPE Francais V1',
    'premium',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111123',
    'Francais',
    'didactique_francais',
    'enseignement_comprehension',
    'Enseignement de la comprehension',
    'Intermediaire',
    'vrai_faux',
    'Vrai ou faux : en didactique du francais, l''enseignement explicite de la comprehension est inutile si les eleves lisent souvent.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":false}'::jsonb,
    'La pratique reguliere de lecture ne suffit pas toujours. Les strategies de comprehension doivent aussi etre enseignees explicitement.',
    'valide',
    'Creation CRPE Francais V1',
    'free',
    true
  ),
  (
    '11111111-1111-1111-1111-111111111124',
    'Francais',
    'didactique_francais',
    'justification_par_le_texte',
    'Justification par le texte',
    'Avance',
    'reponse_courte',
    'Quelle competence l''enseignant cherche-t-il a developper lorsqu''il demande aux eleves de justifier leurs reponses a partir du texte ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["la comprehension justifiee","l''interpretation appuyee sur le texte","la justification des reponses par le texte"]}'::jsonb,
    'Demander aux eleves de s''appuyer sur le texte developpe une comprehension argumentee, fondee sur des indices explicites.',
    'valide',
    'Creation CRPE Francais V1',
    'premium',
    true
  );

-- Questions supplementaires pour former de vraies series de 5 questions
-- Serie : classes_grammaticales / Facile / free (questions 2-5)
-- Serie : fonctions_essentielles / Intermediaire / premium (questions 2-5)
-- Serie : temps_de_base / Facile / free (questions 2-5)

insert into public.exercises (
  id, subject, subdomain, topic_key, topic_label, level,
  exercise_type, instruction, support_text, choices, expected_answer,
  detailed_explanation, validation_status, source, access_tier, is_published
)
values
  -- classes_grammaticales / Facile / free
  (
    '11111111-1111-1111-1111-111111111125', 'Francais', 'grammaire',
    'classes_grammaticales', 'Classes grammaticales', 'Facile',
    'qcm',
    'Quelle est la nature du mot "petit" dans la phrase "Le petit chat dort" ?',
    null,
    '[{"id":"a","label":"Un adverbe"},{"id":"b","label":"Un adjectif qualificatif"},{"id":"c","label":"Un nom commun"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Petit" qualifie le nom "chat" en indiquant une caracteristique. C''est un adjectif qualificatif epithete.',
    'valide', 'Creation CRPE Francais V1', 'free', true
  ),
  (
    '11111111-1111-1111-1111-111111111126', 'Francais', 'grammaire',
    'classes_grammaticales', 'Classes grammaticales', 'Facile',
    'qcm',
    'Quelle est la nature du mot "dans" dans la phrase "Il joue dans la cour" ?',
    null,
    '[{"id":"a","label":"Un adverbe"},{"id":"b","label":"Une conjonction de coordination"},{"id":"c","label":"Une preposition"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Dans" introduit un complement de lieu. Il etablit une relation entre "joue" et "la cour" : c''est une preposition.',
    'valide', 'Creation CRPE Francais V1', 'free', true
  ),
  (
    '11111111-1111-1111-1111-111111111127', 'Francais', 'grammaire',
    'classes_grammaticales', 'Classes grammaticales', 'Facile',
    'qcm',
    'Quelle est la nature du mot "et" dans "Les eleves et les professeurs travaillent" ?',
    null,
    '[{"id":"a","label":"Une preposition"},{"id":"b","label":"Une conjonction de coordination"},{"id":"c","label":"Un pronom"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Et" relie deux groupes nominaux de meme fonction. C''est une conjonction de coordination.',
    'valide', 'Creation CRPE Francais V1', 'free', true
  ),
  (
    '11111111-1111-1111-1111-111111111128', 'Francais', 'grammaire',
    'classes_grammaticales', 'Classes grammaticales', 'Facile',
    'qcm',
    'Quelle est la nature du mot "nous" dans "Nous partons demain" ?',
    null,
    '[{"id":"a","label":"Un nom propre"},{"id":"b","label":"Un adjectif"},{"id":"c","label":"Un pronom personnel"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Nous" designe les locuteurs et remplace un groupe nominal. C''est un pronom personnel sujet.',
    'valide', 'Creation CRPE Francais V1', 'free', true
  ),

  -- fonctions_essentielles / Intermediaire / premium
  (
    '11111111-1111-1111-1111-111111111129', 'Francais', 'grammaire',
    'fonctions_essentielles', 'Sujet, COD, COI et attribut', 'Intermediaire',
    'identification_grammaticale',
    'Identifiez la fonction du groupe souligne : "Il a offert un cadeau <a Marie>."',
    null, null,
    '{"mode":"text","acceptableAnswers":["complement d''objet indirect","coi"]}'::jsonb,
    '"A Marie" complete le verbe "offrir" par l''intermediaire de la preposition "a". Il s''agit d''un complement d''objet indirect.',
    'valide', 'Creation CRPE Francais V1', 'premium', true
  ),
  (
    '11111111-1111-1111-1111-111111111130', 'Francais', 'grammaire',
    'fonctions_essentielles', 'Sujet, COD, COI et attribut', 'Intermediaire',
    'identification_grammaticale',
    'Identifiez la fonction du mot souligne : "Il semble <intelligent>."',
    null, null,
    '{"mode":"text","acceptableAnswers":["attribut du sujet"]}'::jsonb,
    '"Intelligent" est relie au sujet "il" par le verbe d''etat "sembler". C''est un attribut du sujet.',
    'valide', 'Creation CRPE Francais V1', 'premium', true
  ),
  (
    '11111111-1111-1111-1111-111111111131', 'Francais', 'grammaire',
    'fonctions_essentielles', 'Sujet, COD, COI et attribut', 'Intermediaire',
    'identification_grammaticale',
    'Identifiez la fonction du groupe souligne : "<Les eleves> travaillent en silence."',
    null, null,
    '{"mode":"text","acceptableAnswers":["sujet"]}'::jsonb,
    '"Les eleves" commande l''accord du verbe "travaillent". C''est le sujet du verbe.',
    'valide', 'Creation CRPE Francais V1', 'premium', true
  ),
  (
    '11111111-1111-1111-1111-111111111132', 'Francais', 'grammaire',
    'fonctions_essentielles', 'Sujet, COD, COI et attribut', 'Intermediaire',
    'identification_grammaticale',
    'Identifiez la fonction du groupe souligne : "Il explique <la lecon>."',
    null, null,
    '{"mode":"text","acceptableAnswers":["complement d''objet direct","cod"]}'::jsonb,
    '"La lecon" repond a la question "expliquer quoi ?", sans preposition. C''est un complement d''objet direct.',
    'valide', 'Creation CRPE Francais V1', 'premium', true
  ),

  -- temps_de_base / Facile / free
  (
    '11111111-1111-1111-1111-111111111133', 'Francais', 'conjugaison',
    'temps_de_base', 'Present, imparfait et futur', 'Facile',
    'qcm',
    'Quelle est la forme correcte au futur simple du verbe "aller" avec "je" ?',
    null,
    '[{"id":"a","label":"je vais"},{"id":"b","label":"j''allais"},{"id":"c","label":"j''irai"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    'Le futur simple de "aller" est irregulier : j''irai, tu iras, il ira... Le radical est "ir-".',
    'valide', 'Creation CRPE Francais V1', 'free', true
  ),
  (
    '11111111-1111-1111-1111-111111111134', 'Francais', 'conjugaison',
    'temps_de_base', 'Present, imparfait et futur', 'Facile',
    'qcm',
    'Quelle est la forme correcte a l''imparfait du verbe "etre" avec "nous" ?',
    null,
    '[{"id":"a","label":"nous sommes"},{"id":"b","label":"nous etions"},{"id":"c","label":"nous serons"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    'L''imparfait de "etre" donne : j''etais, tu etais, il etait, nous etions, vous etiez, ils etaient.',
    'valide', 'Creation CRPE Francais V1', 'free', true
  ),
  (
    '11111111-1111-1111-1111-111111111135', 'Francais', 'conjugaison',
    'temps_de_base', 'Present, imparfait et futur', 'Facile',
    'qcm',
    'Quelle est la forme correcte au present du verbe "avoir" avec "ils" ?',
    null,
    '[{"id":"a","label":"ils avaient"},{"id":"b","label":"ils auront"},{"id":"c","label":"ils ont"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    'Le present de "avoir" a la 3e personne du pluriel est "ils ont". Verbe irregulier a memoriser.',
    'valide', 'Creation CRPE Francais V1', 'free', true
  ),
  (
    '11111111-1111-1111-1111-111111111136', 'Francais', 'conjugaison',
    'temps_de_base', 'Present, imparfait et futur', 'Facile',
    'qcm',
    'Quelle est la forme correcte au futur simple du verbe "faire" avec "tu" ?',
    null,
    '[{"id":"a","label":"tu feras"},{"id":"b","label":"tu faisais"},{"id":"c","label":"tu faites"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    'Le futur simple de "faire" est irregulier : je ferai, tu feras, il fera... Le radical est "fer-".',
    'valide', 'Creation CRPE Francais V1', 'free', true
  );
