-- CRPE Français — Compréhension de texte V2 (5 séries × 10 questions)
insert into public.exercises (
  id, subject, subdomain, topic_key, topic_label, level,
  exercise_type, instruction, support_text, choices, expected_answer,
  detailed_explanation, validation_status, source, access_tier, is_published
)
values

-- ============================================================
-- SÉRIE 30 — Compréhension de texte documentaire (free)
-- ============================================================

(
  '30000000-0000-0000-0000-000000000001',
  'Francais',
  'comprehension_texte',
  'cpt_texte_documentaire',
  'Compréhension de texte documentaire',
  'Intermediaire',
  'qcm',
  'Quel est l''objectif principal d''un texte documentaire ?',
  'Le texte documentaire est un écrit non fictif qui vise à transmettre des informations sur le monde réel. Il s''appuie sur des faits vérifiables, des données chiffrées ou des explications objectives. On le rencontre dans les encyclopédies, les manuels scolaires et les articles de presse scientifique.',
  '[{"id":"a","label":"Divertir le lecteur par une histoire imaginaire"},{"id":"b","label":"Informer le lecteur sur un sujet réel à partir de faits vérifiables"},{"id":"c","label":"Convaincre le lecteur d''adopter une opinion"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le texte documentaire appartient au domaine des écrits informatifs non fictifs. Son but premier est de transmettre des connaissances sur la réalité à l''aide de faits vérifiables, de données et d''explications objectives. Il se distingue du texte narratif (qui raconte) et du texte argumentatif (qui cherche à convaincre). Cette distinction fondamentale est au cœur des programmes de l''école primaire pour enseigner la compréhension de l''écrit.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '30000000-0000-0000-0000-000000000002',
  'Francais',
  'comprehension_texte',
  'cpt_texte_documentaire',
  'Compréhension de texte documentaire',
  'Intermediaire',
  'vrai_faux',
  'Un texte documentaire peut contenir des titres, des sous-titres et des légendes pour organiser l''information.',
  'Le texte documentaire est un écrit non fictif qui vise à transmettre des informations sur le monde réel. Il s''appuie sur des faits vérifiables, des données chiffrées ou des explications objectives. On le rencontre dans les encyclopédies, les manuels scolaires et les articles de presse scientifique.',
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Vrai. Les textes documentaires utilisent abondamment les éléments paratextuels : titres, sous-titres, intertitres, légendes, encadrés, schémas annotés. Ces éléments facilitent la navigation dans le texte et aident le lecteur à anticiper le contenu. Apprendre aux élèves à exploiter le paratexte est une compétence clé de la compréhension documentaire enseignée à l''école primaire.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '30000000-0000-0000-0000-000000000003',
  'Francais',
  'comprehension_texte',
  'cpt_texte_documentaire',
  'Compréhension de texte documentaire',
  'Intermediaire',
  'qcm',
  'Parmi ces caractéristiques, laquelle est propre au texte documentaire ?',
  'Le texte documentaire est un écrit non fictif qui vise à transmettre des informations sur le monde réel. Il s''appuie sur des faits vérifiables, des données chiffrées ou des explications objectives. On le rencontre dans les encyclopédies, les manuels scolaires et les articles de presse scientifique.',
  '[{"id":"a","label":"La présence d''un narrateur à la première personne"},{"id":"b","label":"L''utilisation de faits vérifiables et de données objectives"},{"id":"c","label":"La construction d''un suspense narratif"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le recours à des faits vérifiables et à des données objectives est la marque distinctive du texte documentaire. Il s''oppose ainsi au texte de fiction (narrateur, suspense) et se distingue du texte d''opinion (point de vue subjectif). La vérifiabilité des informations est un critère essentiel que les futurs enseignants doivent savoir expliquer aux élèves lors de séances de lecture documentaire.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '30000000-0000-0000-0000-000000000004',
  'Francais',
  'comprehension_texte',
  'cpt_texte_documentaire',
  'Compréhension de texte documentaire',
  'Intermediaire',
  'qcm',
  'Quelle structure est la plus fréquente dans un texte documentaire explicatif ?',
  'Le texte documentaire est un écrit non fictif qui vise à transmettre des informations sur le monde réel. Il s''appuie sur des faits vérifiables, des données chiffrées ou des explications objectives. On le rencontre dans les encyclopédies, les manuels scolaires et les articles de presse scientifique.',
  '[{"id":"a","label":"Situation initiale — péripétie — situation finale"},{"id":"b","label":"Introduction du sujet — développement thématique — conclusion"},{"id":"c","label":"Thèse — antithèse — synthèse"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le texte documentaire explicatif s''organise généralement en trois parties : une introduction qui présente le sujet, un développement qui expose les informations de façon thématique ou chronologique, et une conclusion qui synthétise. La structure « situation initiale — péripétie — situation finale » est propre au récit de fiction, et la structure « thèse — antithèse — synthèse » appartient au texte dialectique. Reconnaître ces structures aide les élèves à identifier le genre textuel.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '30000000-0000-0000-0000-000000000005',
  'Francais',
  'comprehension_texte',
  'cpt_texte_documentaire',
  'Compréhension de texte documentaire',
  'Intermediaire',
  'vrai_faux',
  'Un article d''encyclopédie est un exemple de texte documentaire.',
  'Le texte documentaire est un écrit non fictif qui vise à transmettre des informations sur le monde réel. Il s''appuie sur des faits vérifiables, des données chiffrées ou des explications objectives. On le rencontre dans les encyclopédies, les manuels scolaires et les articles de presse scientifique.',
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Vrai. L''article encyclopédique est un genre documentaire par excellence : il traite d''un sujet de façon objective, s''appuie sur des informations vérifiables, utilise un lexique spécialisé et adopte une organisation thématique. Il est souvent cité dans les programmes scolaires comme support privilégié pour travailler la compréhension du texte documentaire à l''école primaire.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '30000000-0000-0000-0000-000000000006',
  'Francais',
  'comprehension_texte',
  'cpt_texte_documentaire',
  'Compréhension de texte documentaire',
  'Intermediaire',
  'qcm',
  'Dans un texte documentaire, à quoi sert principalement le lexique spécialisé ?',
  'Le texte documentaire est un écrit non fictif qui vise à transmettre des informations sur le monde réel. Il s''appuie sur des faits vérifiables, des données chiffrées ou des explications objectives. On le rencontre dans les encyclopédies, les manuels scolaires et les articles de presse scientifique.',
  '[{"id":"a","label":"À rendre le texte plus difficile à comprendre"},{"id":"b","label":"À désigner avec précision les notions propres au domaine traité"},{"id":"c","label":"À exprimer les émotions de l''auteur"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le lexique spécialisé (ou vocabulaire technique) d''un texte documentaire sert à nommer avec précision les concepts propres au domaine abordé. Il n''a pas pour but de compliquer la lecture, mais d''assurer l''exactitude terminologique. À l''école, travailler ce lexique spécialisé lors de lectures documentaires enrichit le vocabulaire disciplinaire des élèves et développe leur capacité à lire des écrits fonctionnels variés.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '30000000-0000-0000-0000-000000000007',
  'Francais',
  'comprehension_texte',
  'cpt_texte_documentaire',
  'Compréhension de texte documentaire',
  'Intermediaire',
  'vrai_faux',
  'Un texte documentaire adopte toujours un point de vue neutre et objectif.',
  'Le texte documentaire est un écrit non fictif qui vise à transmettre des informations sur le monde réel. Il s''appuie sur des faits vérifiables, des données chiffrées ou des explications objectives. On le rencontre dans les encyclopédies, les manuels scolaires et les articles de presse scientifique.',
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Faux. Bien que le texte documentaire tende vers l''objectivité, il n''est jamais totalement neutre : le choix des informations retenues, la sélection des sources et l''angle de traitement reflètent des choix éditoriaux. Sensibiliser les élèves à cette limite est un objectif de l''éducation aux médias et à l''information (EMI), compétence transversale inscrite dans les programmes de l''école primaire.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '30000000-0000-0000-0000-000000000008',
  'Francais',
  'comprehension_texte',
  'cpt_texte_documentaire',
  'Compréhension de texte documentaire',
  'Intermediaire',
  'qcm',
  'Comment appelle-t-on l''ensemble des éléments visuels qui accompagnent un texte documentaire (images, schémas, graphiques) ?',
  'Le texte documentaire est un écrit non fictif qui vise à transmettre des informations sur le monde réel. Il s''appuie sur des faits vérifiables, des données chiffrées ou des explications objectives. On le rencontre dans les encyclopédies, les manuels scolaires et les articles de presse scientifique.',
  '[{"id":"a","label":"Les péritextes"},{"id":"b","label":"Les iconotextes ou éléments iconographiques"},{"id":"c","label":"Les métaphores visuelles"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'On désigne par iconotexte ou éléments iconographiques l''ensemble des images, schémas, graphiques et tableaux qui accompagnent un texte documentaire. Ces éléments ne sont pas décoratifs : ils apportent une information complémentaire ou redondante qui facilite la compréhension. À l''école, apprendre à articuler le texte et l''image est une compétence de compréhension à part entière, travaillée dans les séquences de lecture documentaire.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '30000000-0000-0000-0000-000000000009',
  'Francais',
  'comprehension_texte',
  'cpt_texte_documentaire',
  'Compréhension de texte documentaire',
  'Intermediaire',
  'qcm',
  'Quelle est la différence principale entre un texte documentaire et un texte de fiction ?',
  'Le texte documentaire est un écrit non fictif qui vise à transmettre des informations sur le monde réel. Il s''appuie sur des faits vérifiables, des données chiffrées ou des explications objectives. On le rencontre dans les encyclopédies, les manuels scolaires et les articles de presse scientifique.',
  '[{"id":"a","label":"Le texte documentaire parle d''animaux, la fiction parle de personnes"},{"id":"b","label":"Le texte documentaire s''appuie sur des faits réels, la fiction construit un monde imaginaire"},{"id":"c","label":"Le texte documentaire est toujours court, la fiction est toujours longue"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'La distinction fondamentale entre texte documentaire et fiction repose sur le rapport au réel : le documentaire s''ancre dans des faits vérifiables, la fiction construit un univers imaginaire. Cette opposition n''est pas liée au sujet (on peut écrire un documentaire sur des animaux) ni à la longueur. C''est l''une des premières catégorisations textuelles enseignées aux élèves dès le cycle 2, car elle conditionne la posture de lecture.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '30000000-0000-0000-0000-000000000010',
  'Francais',
  'comprehension_texte',
  'cpt_texte_documentaire',
  'Compréhension de texte documentaire',
  'Intermediaire',
  'qcm',
  'Dans un texte documentaire sur les abeilles, la phrase « La reine pond jusqu''à 2 000 œufs par jour » est une information :',
  'Le texte documentaire est un écrit non fictif qui vise à transmettre des informations sur le monde réel. Il s''appuie sur des faits vérifiables, des données chiffrées ou des explications objectives. On le rencontre dans les encyclopédies, les manuels scolaires et les articles de presse scientifique.',
  '[{"id":"a","label":"Subjective, car elle exprime l''admiration de l''auteur"},{"id":"b","label":"Objective et vérifiable, caractéristique du texte documentaire"},{"id":"c","label":"Fictive, car aucune abeille ne peut pondre autant"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Cette phrase est une information objective et vérifiable : elle énonce un fait chiffré observable dans la réalité. C''est la marque typique du texte documentaire, qui s''appuie sur des données factuelles plutôt que sur des jugements de valeur. Apprendre aux élèves à distinguer une information objective d''une opinion subjective est une compétence de lecture critique essentielle dans les programmes du cycle 3.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

-- ============================================================
-- SÉRIE 31 — Inférences et implicite du texte (free)
-- ============================================================

(
  '31000000-0000-0000-0000-000000000001',
  'Francais',
  'comprehension_texte',
  'cpt_inferences',
  'Inférences et implicite du texte',
  'Intermediaire',
  'qcm',
  'Qu''est-ce qu''une inférence en lecture ?',
  'Marie rentra chez elle trempée. Elle posa son parapluie dans l''entrée et alla chercher une serviette. Par la fenêtre, elle vit les flaques d''eau sur le trottoir.',
  '[{"id":"a","label":"Une information explicitement écrite dans le texte"},{"id":"b","label":"Une information que le lecteur déduit à partir d''indices textuels et de ses connaissances"},{"id":"c","label":"Un résumé du texte rédigé par l''auteur"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Une inférence est une opération cognitive par laquelle le lecteur déduit des informations non explicitement formulées dans le texte, en combinant des indices textuels et ses connaissances du monde. Par exemple, dans le texte support, on infère qu''il a plu sans que ce soit dit directement. Cette compétence est centrale dans les programmes de lecture de l''école primaire : de nombreux élèves en difficulté sont précisément ceux qui ne savent pas dépasser la lecture littérale.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '31000000-0000-0000-0000-000000000002',
  'Francais',
  'comprehension_texte',
  'cpt_inferences',
  'Inférences et implicite du texte',
  'Intermediaire',
  'vrai_faux',
  'D''après le texte, on peut déduire qu''il a plu lorsque Marie était dehors.',
  'Marie rentra chez elle trempée. Elle posa son parapluie dans l''entrée et alla chercher une serviette. Par la fenêtre, elle vit les flaques d''eau sur le trottoir.',
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Vrai. C''est une inférence logique : Marie est trempée, elle a utilisé un parapluie, et des flaques d''eau sont visibles sur le trottoir. Aucun de ces indices pris isolément n''affirme qu''il a plu, mais leur combinaison le rend évident. Cette inférence de type causal est l''une des plus fréquentes dans les textes narratifs et documentaires. Les enseigner explicitement aux élèves améliore significativement leur compréhension en lecture.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '31000000-0000-0000-0000-000000000003',
  'Francais',
  'comprehension_texte',
  'cpt_inferences',
  'Inférences et implicite du texte',
  'Intermediaire',
  'qcm',
  'Quelle est la différence entre une information explicite et une information implicite dans un texte ?',
  'Marie rentra chez elle trempée. Elle posa son parapluie dans l''entrée et alla chercher une serviette. Par la fenêtre, elle vit les flaques d''eau sur le trottoir.',
  '[{"id":"a","label":"L''information explicite est dans le texte, l''implicite doit être déduite"},{"id":"b","label":"L''information explicite est fausse, l''implicite est vraie"},{"id":"c","label":"L''information explicite concerne les personnages, l''implicite concerne le décor"}]'::jsonb,
  '{"mode":"single_choice","value":"a"}'::jsonb,
  'L''information explicite est directement formulée dans le texte, disponible en lecture littérale. L''information implicite, elle, n''est pas dite mais peut être reconstruite par inférence. Dans le texte support, « Marie rentra chez elle trempée » est explicite ; « il pleuvait » est implicite. Cette distinction est fondamentale dans l''enseignement de la compréhension : les questions sur l''implicite sont souvent celles qui départagent les bons lecteurs des lecteurs en difficulté.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '31000000-0000-0000-0000-000000000004',
  'Francais',
  'comprehension_texte',
  'cpt_inferences',
  'Inférences et implicite du texte',
  'Intermediaire',
  'qcm',
  'Parmi ces types d''inférences, lequel s''appuie principalement sur les connaissances du lecteur plutôt que sur des indices du texte ?',
  'Marie rentra chez elle trempée. Elle posa son parapluie dans l''entrée et alla chercher une serviette. Par la fenêtre, elle vit les flaques d''eau sur le trottoir.',
  '[{"id":"a","label":"L''inférence logique"},{"id":"b","label":"L''inférence pragmatique ou encyclopédique"},{"id":"c","label":"L''inférence anaphorique"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'L''inférence pragmatique (ou encyclopédique) mobilise les connaissances du monde du lecteur pour combler les ellipses du texte. Par exemple, savoir qu''un parapluie sert à se protéger de la pluie permet d''inférer qu''il pleuvait. L''inférence logique, elle, découle d''une déduction formelle ; l''inférence anaphorique lie un pronom à son référent. Ces distinctions permettent à l''enseignant de cibler l''obstacle de compréhension de chaque élève.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '31000000-0000-0000-0000-000000000005',
  'Francais',
  'comprehension_texte',
  'cpt_inferences',
  'Inférences et implicite du texte',
  'Intermediaire',
  'vrai_faux',
  'Une inférence anaphorique consiste à identifier à quel nom renvoie un pronom dans le texte.',
  'Marie rentra chez elle trempée. Elle posa son parapluie dans l''entrée et alla chercher une serviette. Par la fenêtre, elle vit les flaques d''eau sur le trottoir.',
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Vrai. L''inférence anaphorique consiste à résoudre une anaphore, c''est-à-dire à identifier le référent d''un pronom, d''un groupe nominal de reprise ou d''un synonyme. Dans le texte support, comprendre que « elle » désigne Marie est une inférence anaphorique. C''est l''une des inférences les plus précocement travaillées à l''école car son échec entraîne une rupture de la cohérence et une incompréhension du texte.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '31000000-0000-0000-0000-000000000006',
  'Francais',
  'comprehension_texte',
  'cpt_inferences',
  'Inférences et implicite du texte',
  'Intermediaire',
  'qcm',
  'Quel est l''état émotionnel probable de Marie dans ce texte, même s''il n''est pas explicitement nommé ?',
  'Marie rentra chez elle trempée. Elle posa son parapluie dans l''entrée et alla chercher une serviette. Par la fenêtre, elle vit les flaques d''eau sur le trottoir.',
  '[{"id":"a","label":"Joyeuse et enthousiaste"},{"id":"b","label":"Indifférente et calme"},{"id":"c","label":"Probablement inconfortable ou contrariée d''être trempée"}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  'Être trempé est généralement une expérience désagréable, et chercher une serviette indique une réaction pratique face à un inconfort. L''inférence sur l''état émotionnel d''un personnage est une inférence pragmatique qui mobilise les connaissances du monde et l''empathie du lecteur. Travailler ces inférences émotionnelles à l''école développe à la fois la compréhension et les compétences psychosociales des élèves.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '31000000-0000-0000-0000-000000000007',
  'Francais',
  'comprehension_texte',
  'cpt_inferences',
  'Inférences et implicite du texte',
  'Intermediaire',
  'vrai_faux',
  'Les élèves en difficulté de compréhension ont généralement du mal avec la lecture littérale mais réussissent bien les inférences.',
  'Marie rentra chez elle trempée. Elle posa son parapluie dans l''entrée et alla chercher une serviette. Par la fenêtre, elle vit les flaques d''eau sur le trottoir.',
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Faux. C''est l''inverse : les élèves en difficulté de compréhension réussissent souvent la lecture littérale (retrouver une information explicitement écrite) mais échouent sur les inférences, qui requièrent de dépasser la surface du texte. Cet obstacle, bien documenté par les recherches en psycholinguistique et en didactique de la lecture, justifie un enseignement explicite des stratégies inférentielles dès le cycle 2.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '31000000-0000-0000-0000-000000000008',
  'Francais',
  'comprehension_texte',
  'cpt_inferences',
  'Inférences et implicite du texte',
  'Intermediaire',
  'qcm',
  'Quelle stratégie pédagogique est recommandée pour enseigner les inférences aux élèves ?',
  'Marie rentra chez elle trempée. Elle posa son parapluie dans l''entrée et alla chercher une serviette. Par la fenêtre, elle vit les flaques d''eau sur le trottoir.',
  '[{"id":"a","label":"Demander aux élèves de mémoriser les définitions des types d''inférences"},{"id":"b","label":"Rendre visibles les raisonnements par la verbalisation et le questionnement explicite"},{"id":"c","label":"Éviter les questions sur l''implicite pour ne pas décourager les élèves"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'L''enseignement explicite des inférences passe par la verbalisation des raisonnements : l''enseignant modélise à voix haute comment il déduit une information, puis les élèves verbalisent leur propre raisonnement. Cette approche métacognitive, recommandée par les recherches en didactique de la lecture, est bien plus efficace que la mémorisation de définitions. Elle permet aux élèves de transférer les stratégies à de nouveaux textes.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '31000000-0000-0000-0000-000000000009',
  'Francais',
  'comprehension_texte',
  'cpt_inferences',
  'Inférences et implicite du texte',
  'Intermediaire',
  'qcm',
  'Dans le texte support, quel indice permet d''inférer que Marie est rentrée à pied plutôt qu''en voiture ?',
  'Marie rentra chez elle trempée. Elle posa son parapluie dans l''entrée et alla chercher une serviette. Par la fenêtre, elle vit les flaques d''eau sur le trottoir.',
  '[{"id":"a","label":"Le fait qu''elle soit trempée et ait utilisé un parapluie"},{"id":"b","label":"Le fait qu''elle regarde par la fenêtre"},{"id":"c","label":"Le fait qu''elle cherche une serviette"}]'::jsonb,
  '{"mode":"single_choice","value":"a"}'::jsonb,
  'Être trempée malgré l''utilisation d''un parapluie indique une exposition directe aux intempéries, ce qui n''aurait pas été le cas dans une voiture. C''est une inférence logique combinant la signification du parapluie (protection contre la pluie lors de déplacements à pied) et le fait d''être trempée. Cette inférence mobilise à la fois des connaissances encyclopédiques et un raisonnement logique, illustrant la complexité cognitive de la lecture.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

(
  '31000000-0000-0000-0000-000000000010',
  'Francais',
  'comprehension_texte',
  'cpt_inferences',
  'Inférences et implicite du texte',
  'Intermediaire',
  'vrai_faux',
  'L''implicite culturel dans un texte est accessible de la même façon à tous les lecteurs, quelle que soit leur origine.',
  'Marie rentra chez elle trempée. Elle posa son parapluie dans l''entrée et alla chercher une serviette. Par la fenêtre, elle vit les flaques d''eau sur le trottoir.',
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Faux. L''implicite culturel repose sur des connaissances et des références partagées au sein d''une communauté. Un lecteur dont la culture d''origine est différente peut ne pas posséder ces références et ainsi échouer à produire l''inférence attendue. Cette réalité est cruciale pour les enseignants : elle implique de ne pas supposer que tous les élèves partagent les mêmes connaissances du monde, et d''expliciter les savoirs encyclopédiques nécessaires à la compréhension.',
  'valide',
  'CRPE Français — Compréhension V2',
  'free',
  true
),

-- ============================================================
-- SÉRIE 32 — Connecteurs logiques et cohérence textuelle (premium)
-- ============================================================

(
  '32000000-0000-0000-0000-000000000001',
  'Francais',
  'comprehension_texte',
  'cpt_connecteurs_coherence',
  'Connecteurs logiques et cohérence textuelle',
  'Intermediaire',
  'qcm',
  'Quel connecteur logique exprime une relation de cause ?',
  null,
  '[{"id":"a","label":"Cependant"},{"id":"b","label":"Parce que"},{"id":"c","label":"Ensuite"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  '« Parce que » est un connecteur causal : il relie une conséquence à sa cause. « Cependant » exprime une opposition, et « ensuite » marque une succession temporelle. Les connecteurs logiques sont classés selon la relation logique qu''ils instaurent : causalité, opposition, addition, conséquence, condition, but. Maîtriser ces catégories est indispensable pour comprendre et produire des textes cohérents, compétence explicitement visée dans les programmes du cycle 3.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '32000000-0000-0000-0000-000000000002',
  'Francais',
  'comprehension_texte',
  'cpt_connecteurs_coherence',
  'Connecteurs logiques et cohérence textuelle',
  'Intermediaire',
  'vrai_faux',
  'Le connecteur « donc » exprime une relation de conséquence.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Vrai. « Donc » est un connecteur consécutif qui marque la conséquence : il relie une cause à son effet. Il appartient à la famille des connecteurs consécutifs avec « ainsi », « par conséquent », « c''est pourquoi ». La distinction entre cause (pourquoi quelque chose arrive) et conséquence (ce qui résulte de cela) est une notion logique fondamentale que les élèves doivent maîtriser pour lire et produire des textes argumentatifs et explicatifs.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '32000000-0000-0000-0000-000000000003',
  'Francais',
  'comprehension_texte',
  'cpt_connecteurs_coherence',
  'Connecteurs logiques et cohérence textuelle',
  'Intermediaire',
  'qcm',
  'Dans la phrase « Il travaille dur ; pourtant, il n''obtient pas de bons résultats », quel rapport logique est exprimé ?',
  null,
  '[{"id":"a","label":"Une relation de cause à effet"},{"id":"b","label":"Une relation d''opposition ou de concession"},{"id":"c","label":"Une relation d''addition"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  '« Pourtant » est un connecteur adversatif ou concessif : il introduit une opposition entre un fait attendu (travailler dur devrait mener au succès) et la réalité contraire. Les connecteurs d''opposition (mais, or, cependant, néanmoins, pourtant, toutefois) sont particulièrement importants dans les textes argumentatifs. Les élèves confondent souvent cause et opposition : un travail explicite sur ces connecteurs améliore leur compréhension des textes complexes.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '32000000-0000-0000-0000-000000000004',
  'Francais',
  'comprehension_texte',
  'cpt_connecteurs_coherence',
  'Connecteurs logiques et cohérence textuelle',
  'Intermediaire',
  'qcm',
  'Quelle est la fonction des connecteurs logiques dans un texte ?',
  null,
  '[{"id":"a","label":"Décorer le texte et le rendre plus élégant stylistiquement"},{"id":"b","label":"Assurer la cohérence en signalant les relations logiques entre les idées"},{"id":"c","label":"Indiquer les temps verbaux utilisés dans la phrase"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Les connecteurs logiques sont des outils de cohérence textuelle : ils articulent les idées entre elles en signalant explicitement la nature du lien (cause, opposition, addition, conséquence, condition, etc.). Sans eux, les phrases resteraient juxtaposées sans que le lecteur saisisse leur rapport. Dans les programmes scolaires, les connecteurs sont travaillés tant en lecture (comprendre les relations logiques) qu''en production écrite (structurer sa pensée).',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '32000000-0000-0000-0000-000000000005',
  'Francais',
  'comprehension_texte',
  'cpt_connecteurs_coherence',
  'Connecteurs logiques et cohérence textuelle',
  'Intermediaire',
  'vrai_faux',
  'Les connecteurs temporels comme « ensuite », « puis » et « enfin » peuvent aussi organiser un raisonnement logique en plus d''une suite d''événements.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Vrai. Les connecteurs temporels peuvent avoir une double fonction : ils organisent les événements dans le temps mais peuvent aussi structurer une argumentation ou une démonstration (« d''abord… ensuite… enfin »). Cette ambivalence est importante : un connecteur temporel dans un texte argumentatif signale une progression logique plus qu''une succession chronologique. Enseigner cette polyvalence aide les élèves à comprendre l''organisation de différents types de textes.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '32000000-0000-0000-0000-000000000006',
  'Francais',
  'comprehension_texte',
  'cpt_connecteurs_coherence',
  'Connecteurs logiques et cohérence textuelle',
  'Intermediaire',
  'qcm',
  'Quel connecteur permet d''introduire une condition ?',
  null,
  '[{"id":"a","label":"Si"},{"id":"b","label":"Donc"},{"id":"c","label":"Or"}]'::jsonb,
  '{"mode":"single_choice","value":"a"}'::jsonb,
  '« Si » est le connecteur conditionnel par excellence : il introduit une condition dont dépend la réalisation d''un événement. « Donc » est consécutif et « or » est adversatif ou permet d''introduire un élément nouveau dans un raisonnement. Les connecteurs conditionnels (si, à condition que, pourvu que, en supposant que) sont abordés progressivement à l''école primaire, car ils impliquent une maîtrise du mode conditionnel et d''un raisonnement hypothétique.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '32000000-0000-0000-0000-000000000007',
  'Francais',
  'comprehension_texte',
  'cpt_connecteurs_coherence',
  'Connecteurs logiques et cohérence textuelle',
  'Intermediaire',
  'vrai_faux',
  'Un texte cohérent est un texte dans lequel toutes les phrases parlent du même sujet sans jamais utiliser de connecteurs.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Faux. La cohérence textuelle repose sur plusieurs mécanismes : la progression thématique, la reprise anaphorique, et les connecteurs. Un texte peut être incohérent même si toutes les phrases parlent du même sujet, si les liens logiques entre elles sont absents ou incorrects. Les connecteurs sont un outil essentiel de la cohérence, mais non le seul. Enseigner la cohérence textuelle implique de travailler sur tous ces mécanismes conjointement.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '32000000-0000-0000-0000-000000000008',
  'Francais',
  'comprehension_texte',
  'cpt_connecteurs_coherence',
  'Connecteurs logiques et cohérence textuelle',
  'Intermediaire',
  'qcm',
  'Dans « Il faisait froid, c''est pourquoi elle prit son manteau », quel est le rôle de « c''est pourquoi » ?',
  null,
  '[{"id":"a","label":"Il exprime une opposition entre les deux propositions"},{"id":"b","label":"Il exprime la conséquence de la première proposition sur la seconde"},{"id":"c","label":"Il exprime une condition pour que la seconde proposition soit vraie"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  '« C''est pourquoi » est un connecteur consécutif : il signale que la seconde proposition est la conséquence logique de la première. Il appartient à la même famille que « donc », « ainsi », « par conséquent », « aussi » (en tête de phrase). Distinguer la relation cause-conséquence de la relation condition-conséquence est une difficulté récurrente chez les élèves, et un travail explicite sur les connecteurs consécutifs est recommandé dès le cycle 3.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '32000000-0000-0000-0000-000000000009',
  'Francais',
  'comprehension_texte',
  'cpt_connecteurs_coherence',
  'Connecteurs logiques et cohérence textuelle',
  'Intermediaire',
  'qcm',
  'Quel connecteur convient le mieux pour compléter : « Il aime la lecture… il préfère les romans policiers » ?',
  null,
  '[{"id":"a","label":"Mais"},{"id":"b","label":"En particulier"},{"id":"c","label":"Pourtant"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  '« En particulier » est un connecteur d''exemplification ou de précision : il introduit une information plus précise ou un exemple qui illustre la proposition précédente. « Mais » et « pourtant » introduiraient une opposition, ce qui ne convient pas ici puisque la seconde proposition est dans la continuité de la première. Ce type d''exercice de choix de connecteur, fréquent dans les évaluations CRPE, teste la compréhension fine des relations logiques entre propositions.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '32000000-0000-0000-0000-000000000010',
  'Francais',
  'comprehension_texte',
  'cpt_connecteurs_coherence',
  'Connecteurs logiques et cohérence textuelle',
  'Intermediaire',
  'vrai_faux',
  'La cohérence textuelle repose uniquement sur l''enchaînement logique des idées, indépendamment de la grammaire et du vocabulaire.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Faux. La cohérence textuelle est un phénomène global qui intègre plusieurs dimensions : la progression thématique (chaque phrase apporte une information nouvelle), la reprise référentielle (anaphores, substituts lexicaux), les connecteurs logiques, et la cohérence temporelle (concordance des temps). La grammaire et le vocabulaire y jouent un rôle direct. C''est pourquoi l''enseignement de la production écrite et de la compréhension doit articuler ces différentes dimensions.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

-- ============================================================
-- SÉRIE 33 — Texte argumentatif et injonctif (premium)
-- ============================================================

(
  '33000000-0000-0000-0000-000000000001',
  'Francais',
  'comprehension_texte',
  'cpt_texte_argumentatif',
  'Texte argumentatif et injonctif',
  'Avance',
  'qcm',
  'Quelle est la structure canonique d''un texte argumentatif ?',
  null,
  '[{"id":"a","label":"Introduction — péripéties — dénouement"},{"id":"b","label":"Thèse — arguments — conclusion"},{"id":"c","label":"Titre — développement — bibliographie"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le texte argumentatif s''organise autour d''une thèse (la position défendue), d''arguments qui la soutiennent (souvent illustrés par des exemples), et d''une conclusion qui la réaffirme. Cette structure, parfois enrichie d''une antithèse et d''une réfutation, est fondamentale dans la culture scolaire et universitaire. L''initiation à la lecture des textes argumentatifs commence au cycle 3 et s''approfondit au collège, mais les bases s''acquièrent dès l''école primaire.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '33000000-0000-0000-0000-000000000002',
  'Francais',
  'comprehension_texte',
  'cpt_texte_argumentatif',
  'Texte argumentatif et injonctif',
  'Avance',
  'vrai_faux',
  'Dans un texte argumentatif, la thèse est l''opinion ou la position que l''auteur cherche à défendre.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Vrai. La thèse est le point de vue que l''auteur défend et cherche à faire partager au lecteur. Elle est soutenue par des arguments (raisons qui la justifient) eux-mêmes étayés par des exemples ou des preuves. Distinguer la thèse des arguments est une compétence analytique travaillée en lecture dès le cycle 3 : elle prépare les élèves à la pensée critique et à la production de textes argumentés.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '33000000-0000-0000-0000-000000000003',
  'Francais',
  'comprehension_texte',
  'cpt_texte_argumentatif',
  'Texte argumentatif et injonctif',
  'Avance',
  'qcm',
  'Qu''est-ce qu''une réfutation dans un texte argumentatif ?',
  null,
  '[{"id":"a","label":"Un argument qui soutient la thèse principale"},{"id":"b","label":"La réponse de l''auteur à un argument adverse pour le contester"},{"id":"c","label":"La conclusion qui résume les arguments"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'La réfutation consiste à présenter un argument opposé à la thèse défendue, puis à le contester pour montrer sa faiblesse ou son insuffisance. Elle renforce la démonstration en montrant que l''auteur a examiné les objections possibles. Dans un texte dialectique (thèse — antithèse — synthèse), l''antithèse peut être réfutée dans la synthèse. Identifier les réfutations est une compétence avancée de lecture critique, visée en fin de cycle 3.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '33000000-0000-0000-0000-000000000004',
  'Francais',
  'comprehension_texte',
  'cpt_texte_argumentatif',
  'Texte argumentatif et injonctif',
  'Avance',
  'qcm',
  'Quelle est la caractéristique principale d''un texte injonctif ?',
  null,
  '[{"id":"a","label":"Il raconte une histoire avec des personnages"},{"id":"b","label":"Il donne des instructions ou des consignes pour accomplir une action"},{"id":"c","label":"Il décrit un lieu ou un personnage avec précision"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le texte injonctif a pour fonction de donner des instructions, des directives ou des consignes pour réaliser une action. On le reconnaît à l''emploi de l''impératif, des verbes à l''infinitif à valeur d''ordre, et d''une organisation souvent numérotée ou chronologique. Les recettes de cuisine, les modes d''emploi et les consignes scolaires sont des textes injonctifs. Apprendre aux élèves à lire et à produire ce type de texte est un objectif des programmes de l''école primaire.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '33000000-0000-0000-0000-000000000005',
  'Francais',
  'comprehension_texte',
  'cpt_texte_argumentatif',
  'Texte argumentatif et injonctif',
  'Avance',
  'vrai_faux',
  'Un texte argumentatif cherche à modifier les opinions ou les comportements du lecteur.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Vrai. L''argumentation a pour finalité de convaincre ou de persuader : convaincre fait appel à la raison (arguments logiques, preuves), persuader fait appel aux émotions et aux valeurs. Ces deux modes visent à modifier la position ou le comportement du lecteur. Développer chez les élèves une posture de lecteur critique face aux textes argumentatifs est un objectif central de l''enseignement du français et de l''éducation civique.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '33000000-0000-0000-0000-000000000006',
  'Francais',
  'comprehension_texte',
  'cpt_texte_argumentatif',
  'Texte argumentatif et injonctif',
  'Avance',
  'qcm',
  'Quelle marque linguistique est caractéristique du texte injonctif ?',
  null,
  '[{"id":"a","label":"L''emploi fréquent de l''imparfait de narration"},{"id":"b","label":"L''emploi de l''impératif ou de l''infinitif à valeur d''ordre"},{"id":"c","label":"L''emploi du subjonctif présent pour exprimer le doute"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le texte injonctif se reconnaît à l''emploi de l''impératif (« Ajoutez le sel », « Tournez à gauche ») ou de l''infinitif à valeur d''ordre (« Mélanger les ingrédients »). Ces formes verbales expriment la directive ou la consigne. L''imparfait est caractéristique des récits, et le subjonctif du doute ou de la nécessité. Reconnaître les marques linguistiques des types de textes est une compétence grammaticale au service de la compréhension.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '33000000-0000-0000-0000-000000000007',
  'Francais',
  'comprehension_texte',
  'cpt_texte_argumentatif',
  'Texte argumentatif et injonctif',
  'Avance',
  'vrai_faux',
  'Dans un texte argumentatif, un exemple sert à illustrer et renforcer un argument.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Vrai. L''exemple est un outil rhétorique qui illustre concrètement un argument abstrait, rendant ainsi la démonstration plus accessible et plus convaincante. Il ne constitue pas lui-même un argument, mais lui donne corps. La distinction argument / exemple est une compétence analytique travaillée en lecture critique : elle aide les élèves à évaluer la solidité d''un raisonnement et à ne pas confondre une preuve anecdotique avec une démonstration rigoureuse.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '33000000-0000-0000-0000-000000000008',
  'Francais',
  'comprehension_texte',
  'cpt_texte_argumentatif',
  'Texte argumentatif et injonctif',
  'Avance',
  'qcm',
  'Quelle est la différence entre convaincre et persuader ?',
  null,
  '[{"id":"a","label":"Convaincre fait appel à la raison, persuader fait appel aux émotions"},{"id":"b","label":"Convaincre s''adresse à un groupe, persuader s''adresse à un individu"},{"id":"c","label":"Convaincre utilise des images, persuader utilise des mots"}]'::jsonb,
  '{"mode":"single_choice","value":"a"}'::jsonb,
  'Convaincre désigne l''action d''emporter l''adhésion par des arguments rationnels, des preuves et des démonstrations logiques. Persuader, en revanche, mobilise les émotions, les valeurs et la sensibilité du destinataire. Un discours efficace combine souvent les deux registres. Cette distinction rhétorique, héritée d''Aristote (logos, ethos, pathos), est pertinente pour analyser les textes argumentatifs et pour développer l''esprit critique des élèves face aux messages médiatiques.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '33000000-0000-0000-0000-000000000009',
  'Francais',
  'comprehension_texte',
  'cpt_texte_argumentatif',
  'Texte argumentatif et injonctif',
  'Avance',
  'qcm',
  'Dans une recette de cuisine, pourquoi les étapes sont-elles numérotées ?',
  null,
  '[{"id":"a","label":"Pour permettre au lecteur de choisir les étapes qu''il préfère réaliser"},{"id":"b","label":"Pour indiquer l''ordre obligatoire dans lequel les actions doivent être effectuées"},{"id":"c","label":"Pour donner une valeur décorative à la mise en page"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Dans un texte injonctif comme une recette, la numérotation des étapes indique un ordre procédural obligatoire : chaque action dépend de la précédente. Cette organisation est un trait caractéristique des textes procéduraux (recettes, modes d''emploi, consignes). Apprendre aux élèves à respecter l''ordre des consignes est une compétence de lecture fonctionnelle essentielle, travaillée dans les situations de vie réelle et dans les séances de compréhension de l''écrit.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '33000000-0000-0000-0000-000000000010',
  'Francais',
  'comprehension_texte',
  'cpt_texte_argumentatif',
  'Texte argumentatif et injonctif',
  'Avance',
  'vrai_faux',
  'Un texte argumentatif et un texte injonctif ont la même finalité communicative.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Faux. Ces deux types de textes cherchent bien à agir sur le lecteur, mais de façon différente. Le texte argumentatif vise à modifier les opinions ou les croyances en apportant des arguments. Le texte injonctif vise à faire agir en donnant des instructions à suivre. Leur finalité communicative diffère donc : persuader vs. faire faire. Cette distinction est fondamentale pour la didactique des types de textes à l''école primaire.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

-- ============================================================
-- SÉRIE 34 — Résumé et reformulation (premium)
-- ============================================================

(
  '34000000-0000-0000-0000-000000000001',
  'Francais',
  'comprehension_texte',
  'cpt_resume_reformulation',
  'Résumé et reformulation',
  'Avance',
  'qcm',
  'Quelle est la différence principale entre un résumé et une paraphrase ?',
  null,
  '[{"id":"a","label":"Le résumé est plus long que le texte original, la paraphrase est plus courte"},{"id":"b","label":"Le résumé condense les idées essentielles avec ses propres mots, la paraphrase reproduit le texte en changeant seulement certains mots"},{"id":"c","label":"Le résumé est réservé aux textes narratifs, la paraphrase aux textes argumentatifs"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Le résumé est une réécriture condensée et fidèle des idées essentielles d''un texte, rédigée avec ses propres mots et structures. La paraphrase, elle, redit le texte en changeant seulement quelques mots ou en réordonnant les phrases : elle n''implique pas de véritable compréhension et n''est pas acceptable comme preuve de compréhension. Apprendre aux élèves à résumer plutôt qu''à paraphraser est un objectif pédagogique central au cycle 3, car le résumé exige une compréhension profonde.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '34000000-0000-0000-0000-000000000002',
  'Francais',
  'comprehension_texte',
  'cpt_resume_reformulation',
  'Résumé et reformulation',
  'Avance',
  'vrai_faux',
  'Résumer un texte consiste à recopier les phrases les plus importantes du texte original.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Faux. Recopier les phrases d''un texte, même les plus importantes, est de la copie ou de la citation, non un résumé. Résumer implique de reformuler avec ses propres mots, de condenser l''information en hiérarchisant l''essentiel et l''accessoire, et d''adopter une perspective surplombante sur le texte. Cette distinction est cruciale dans l''enseignement : de nombreux élèves confondent souligner des phrases et résumer, ce qui masque leurs difficultés de compréhension réelle.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '34000000-0000-0000-0000-000000000003',
  'Francais',
  'comprehension_texte',
  'cpt_resume_reformulation',
  'Résumé et reformulation',
  'Avance',
  'qcm',
  'Quelle compétence cognitive est principalement mise en jeu lors de la rédaction d''un résumé ?',
  null,
  '[{"id":"a","label":"La mémorisation exacte des formulations de l''auteur"},{"id":"b","label":"La hiérarchisation de l''information et la reformulation"},{"id":"c","label":"La copie rapide et sans erreurs orthographiques"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Résumer un texte mobilise deux opérations cognitives essentielles : la hiérarchisation (distinguer l''information principale des détails secondaires) et la reformulation (exprimer les idées retenues avec ses propres mots). Ces deux compétences sont de haut niveau et révèlent une compréhension profonde du texte. Le résumé est donc un outil d''évaluation de la compréhension et un exercice de structuration de la pensée, particulièrement valorisé dans les épreuves de français du CRPE.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '34000000-0000-0000-0000-000000000004',
  'Francais',
  'comprehension_texte',
  'cpt_resume_reformulation',
  'Résumé et reformulation',
  'Avance',
  'qcm',
  'Lors de la rédaction d''un résumé, que doit-on faire des exemples et des détails illustratifs du texte original ?',
  null,
  '[{"id":"a","label":"Les copier tels quels car ils sont indispensables à la compréhension"},{"id":"b","label":"Les supprimer ou les synthétiser, sauf s''ils constituent l''idée principale"},{"id":"c","label":"Les placer au début du résumé pour capter l''attention"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Dans un résumé, les exemples et les détails illustratifs sont généralement supprimés ou synthétisés, car ils servent à illustrer une idée et non à l''exprimer. On conserve l''idée générale qu''ils illustrent. Cette opération de condensation est l''une des plus difficiles pour les élèves, qui ont tendance à conserver tous les détails concrets. Enseigner à distinguer l''idée principale de ses illustrations est une compétence de compréhension fine travaillée au cycle 3.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '34000000-0000-0000-0000-000000000005',
  'Francais',
  'comprehension_texte',
  'cpt_resume_reformulation',
  'Résumé et reformulation',
  'Avance',
  'vrai_faux',
  'Un bon résumé peut contenir des informations qui ne se trouvent pas dans le texte original si elles semblent pertinentes.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Faux. Un résumé doit être strictement fidèle au contenu du texte original : il ne doit ni ajouter d''informations extérieures, ni introduire les opinions du résumeur. Ajouter des informations non présentes dans le texte constituerait un commentaire ou une synthèse personnelle, non un résumé. Cette règle de fidélité est fondamentale dans l''enseignement du résumé : elle développe chez les élèves la rigueur intellectuelle et la distinction entre ce qui est dit et ce qu''on pense.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '34000000-0000-0000-0000-000000000006',
  'Francais',
  'comprehension_texte',
  'cpt_resume_reformulation',
  'Résumé et reformulation',
  'Avance',
  'qcm',
  'Quelle est la longueur idéale d''un résumé par rapport au texte original ?',
  null,
  '[{"id":"a","label":"Il doit faire la même longueur que le texte original"},{"id":"b","label":"Il doit être plus long que le texte original pour être complet"},{"id":"c","label":"Il doit être significativement plus court, souvent entre un quart et un tiers du texte original"}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  'Un résumé doit être sensiblement plus court que le texte d''origine : la règle pratique est souvent le quart ou le tiers de la longueur originale, selon le niveau scolaire et la consigne. Cette contrainte de concision oblige à hiérarchiser et à condenser. À l''école primaire, on peut proposer des résumés plus libres en termes de longueur, mais la contrainte de brièveté est toujours présente pour distinguer le résumé de la reformulation extensive.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '34000000-0000-0000-0000-000000000007',
  'Francais',
  'comprehension_texte',
  'cpt_resume_reformulation',
  'Résumé et reformulation',
  'Avance',
  'vrai_faux',
  'La reformulation d''une phrase implique nécessairement une réduction de son contenu informationnel.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Faux. Reformuler une phrase consiste à l''exprimer différemment en conservant le même sens, sans nécessairement réduire son contenu. Une reformulation peut être plus longue que l''original si elle explicite ce qui était implicite. La différence avec le résumé est que la reformulation ne condense pas obligatoirement. En classe, travailler la reformulation développe la maîtrise lexicale et syntaxique des élèves, qui apprennent à exprimer la même idée de plusieurs façons.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '34000000-0000-0000-0000-000000000008',
  'Francais',
  'comprehension_texte',
  'cpt_resume_reformulation',
  'Résumé et reformulation',
  'Avance',
  'qcm',
  'Quel est l''intérêt pédagogique de demander aux élèves de reformuler oralement ce qu''ils ont compris d''un texte ?',
  null,
  '[{"id":"a","label":"Cela permet de gagner du temps en évitant de relire le texte"},{"id":"b","label":"Cela révèle les représentations des élèves et évalue leur compréhension réelle"},{"id":"c","label":"Cela développe uniquement les compétences orthographiques"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'La reformulation orale est un outil d''évaluation formative puissant : elle révèle ce que l''élève a réellement compris, met en évidence ses erreurs de compréhension ou ses lacunes, et distingue les élèves qui ont compris de ceux qui ont mémorisé des formulations sans en saisir le sens. C''est pourquoi les pratiques de « lecture à voix haute puis reformulation » sont recommandées dans l''enseignement de la compréhension. La reformulation développe également la fluidité langagière et l''expression orale.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '34000000-0000-0000-0000-000000000009',
  'Francais',
  'comprehension_texte',
  'cpt_resume_reformulation',
  'Résumé et reformulation',
  'Avance',
  'qcm',
  'Parmi ces formulations, laquelle constitue une reformulation acceptable de « Le soleil se couche à l''horizon » ?',
  null,
  '[{"id":"a","label":"L''astre du jour disparaît progressivement derrière la ligne où le ciel rejoint la terre"},{"id":"b","label":"Il fait beau ce soir et le ciel est rouge"},{"id":"c","label":"Le soleil se couche à l''horizon, c''est-à-dire que le soleil se couche à l''horizon"}]'::jsonb,
  '{"mode":"single_choice","value":"a"}'::jsonb,
  'La reformulation (a) exprime la même idée avec un lexique différent (« astre du jour » pour « soleil », « disparaît progressivement » pour « se couche ») tout en conservant le sens. La formulation (b) ajoute des informations non présentes et change le sens. La formulation (c) est une pseudo-reformulation qui répète le texte sans le transformer. Travailler sur des exemples concrets de reformulation acceptable et inacceptable est une démarche efficace pour développer la conscience linguistique des élèves.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
),

(
  '34000000-0000-0000-0000-000000000010',
  'Francais',
  'comprehension_texte',
  'cpt_resume_reformulation',
  'Résumé et reformulation',
  'Avance',
  'vrai_faux',
  'Savoir résumer un texte est une compétence utile uniquement dans le cadre scolaire.',
  null,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  'Faux. Le résumé est une compétence transversale aux usages sociaux de l''écrit : résumer un article de presse, un rapport professionnel, un contrat ou une discussion relève des mêmes opérations cognitives. Cette compétence est fondamentale dans la vie professionnelle et citoyenne. En l''enseignant à l''école, on ne prépare pas seulement les élèves aux examens : on les dote d''un outil intellectuel de traitement de l''information utile tout au long de la vie.',
  'valide',
  'CRPE Français — Compréhension V2',
  'premium',
  true
);
