import { ExerciseRecord, RevisionSession } from "@/types/domain";
import {
  frenchModuleSeriesIntegration,
  part4PremierLotSeriesCompletes,
} from "@/content/french-crpe-module";

const createdAt = "2026-03-12T08:00:00.000Z";

type QuestionInput = Omit<
  ExerciseRecord,
  "subject" | "validation_status" | "source" | "is_published" | "created_at" | "updated_at"
>;

type SessionInput = Omit<RevisionSession, "questionCount">;

function question(data: QuestionInput): ExerciseRecord {
  return {
    subject: "Francais",
    validation_status: "valide",
    source: "Serie CRPE Francais V1",
    is_published: true,
    created_at: createdAt,
    updated_at: createdAt,
    common_mistake: null,
    ...data,
  };
}

function buildSession(data: SessionInput): RevisionSession {
  return {
    ...data,
    questionCount: data.questions.length,
  };
}

function textAnswer(...acceptableAnswers: string[]) {
  return {
    mode: "text" as const,
    acceptableAnswers,
  };
}

function qcm(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  choices: Array<{ id: string; label: string }>,
  value: string,
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
) {
  return question({
    id,
    subdomain,
    level,
    exercise_type: "qcm",
    instruction,
    support_text: null,
    choices,
    expected_answer: { mode: "single_choice", value },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
  });
}

function vraiFaux(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  value: boolean,
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
) {
  return question({
    id,
    subdomain,
    level,
    exercise_type: "vrai_faux",
    instruction,
    support_text: null,
    choices: [
      { id: "true", label: "Vrai" },
      { id: "false", label: "Faux" },
    ],
    expected_answer: { mode: "boolean", value },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
  });
}

function reponseCourte(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  acceptableAnswers: string[],
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
  exercise_type: ExerciseRecord["exercise_type"] = "reponse_courte",
  support_text: string | null = null,
) {
  return question({
    id,
    subdomain,
    level,
    exercise_type,
    instruction,
    support_text,
    choices: null,
    expected_answer: textAnswer(...acceptableAnswers),
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
  });
}

function correction(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  acceptableAnswers: string[],
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
) {
  return reponseCourte(
    id,
    subdomain,
    level,
    instruction,
    acceptableAnswers,
    explanation,
    commonMistake,
    access_tier,
    "correction_orthographique",
  );
}

const legacyFrenchCrpeSeriesSeed: RevisionSession[] = [
  buildSession({
    id: "serie-accords-sujet-verbe",
    title: "Accords sujet-verbe dans des phrases simples et piegeuses",
    summary: "Une serie fondamentale pour fiabiliser l'accord du verbe, y compris quand le sujet est eloigne.",
    objective: "Identifier le vrai sujet avant de choisir la terminaison verbale.",
    introduction:
      "Cette serie travaille un automatisme central du CRPE : ne pas accorder avec le mot le plus proche, mais avec le noyau du sujet.",
    subdomain: "orthographe",
    topicKey: "accord_sujet_verbe",
    topicLabel: "Accord sujet-verbe",
    level: "Facile",
    exerciseTypeLabel: "Correction orthographique, QCM, vrai/faux",
    estimatedMinutes: 12,
    access_tier: "free",
    recommendedOrder: 1,
    completionSummary: {
      skill: "Identifier le sujet reel avant d'accorder le verbe",
      keyPoints: [
        "Le verbe s'accorde avec le noyau du sujet.",
        "Un complement du nom ne commande pas l'accord.",
        "Les groupes collectifs demandent une verification du sens.",
      ],
      retryAdvice: "Soulignez le sujet, puis son noyau, avant de corriger la forme verbale.",
    },
    questions: [
      correction(
        "asv-1",
        "orthographe",
        "Facile",
        'Corrigez si necessaire : "Les eleves de cette classe travaille serieusement."',
        ["Les eleves de cette classe travaillent serieusement."],
        'Le noyau du sujet est "eleves", au pluriel. Le verbe doit donc s\'accorder au pluriel.',
        "Accorder avec le mot le plus proche au lieu du noyau du sujet.",
        "free",
      ),
      qcm(
        "asv-2",
        "orthographe",
        "Facile",
        'Choisissez la forme correcte : "Le bruit des chaises ... la concentration."',
        [
          { id: "a", label: "perturbent" },
          { id: "b", label: "perturbes" },
          { id: "c", label: "perturbait" },
          { id: "d", label: "perturbe" },
        ],
        "d",
        'Le sujet est "Le bruit", singulier. "Des chaises" est un complement du nom.',
        'Accorder avec "chaises" parce que ce nom est plus proche du verbe.',
        "free",
      ),
      vraiFaux(
        "asv-3",
        "orthographe",
        "Facile",
        'Vrai ou faux : dans "Ni Paul ni ses camarades ne renoncent", le verbe au pluriel est correct.',
        true,
        'Deux sujets sont coordonnes par "ni ... ni" : le pluriel est ici attendu.',
        "N'accorder qu'avec le premier sujet.",
        "free",
      ),
      correction(
        "asv-4",
        "orthographe",
        "Facile",
        'Corrigez si necessaire : "La plupart des candidats reussit cette etape."',
        ["La plupart des candidats reussissent cette etape."],
        'Avec "la plupart des candidats", l\'accord suit ici l\'idee de pluralite.',
        'Accorder au singulier parce que "plupart" semble etre le noyau decisif.',
        "free",
      ),
      reponseCourte(
        "asv-5",
        "orthographe",
        "Facile",
        'Dans "Un grand nombre d\'exercices sont proposes", expliquez en un mot pourquoi le verbe est au pluriel.',
        ["sens", "pluralite", "pluriel logique"],
        "L'accord suit ici le sens pluriel de l'expression.",
        "Croire que le singulier est obligatoire des qu'un groupe commence par un nom singulier.",
        "free",
      ),
      correction(
        "asv-6",
        "orthographe",
        "Facile",
        'Corrigez si necessaire : "Toi qui relis ce chapitre, tu comprennent mieux la regle."',
        ["Toi qui relis ce chapitre, tu comprends mieux la regle."],
        'Le verbe principal s\'accorde avec "tu".',
        "Se laisser contaminer par une autre personne deja presente dans la phrase.",
        "free",
      ),
    ],
  }),
  buildSession({
    id: "serie-fonctions-essentielles",
    title: "Fonctions essentielles : sujet, verbe, COD, COI",
    summary: "Une serie de base pour distinguer les fonctions centrales de la phrase sans confondre nature et fonction.",
    objective: "Identifier sujet, COD, COI et attribut du sujet dans des phrases courtes.",
    introduction:
      "L'enjeu est simple : analyser ce que fait chaque groupe dans la phrase, et non seulement reconnaitre sa nature grammaticale.",
    subdomain: "grammaire",
    topicKey: "fonctions_essentielles",
    topicLabel: "Sujet, COD, COI et attribut",
    level: "Facile",
    exerciseTypeLabel: "Identification grammaticale, QCM, vrai/faux",
    estimatedMinutes: 11,
    access_tier: "free",
    recommendedOrder: 2,
    completionSummary: {
      skill: "Analyser la structure minimale de la phrase",
      keyPoints: [
        "La nature d'un groupe n'est pas sa fonction.",
        "Le COD complete le verbe sans preposition.",
        "Le COI est souvent introduit par une preposition.",
      ],
      retryAdvice: "Quand vous hésitez, verifiez si le groupe est prepositionnel ou non.",
    },
    questions: [
      reponseCourte(
        "fct-1",
        "grammaire",
        "Facile",
        'Dans "Les formateurs expliquent la consigne aux candidats", quelle est la fonction de "Les formateurs" ?',
        ["sujet"],
        'Le groupe accomplit l\'action exprimee par le verbe : c\'est le sujet.',
        'Repondre "groupe nominal" au lieu de donner la fonction.',
        "free",
        "identification_grammaticale",
      ),
      reponseCourte(
        "fct-2",
        "grammaire",
        "Facile",
        'Dans la meme phrase, quelle est la fonction de "la consigne" ?',
        ["cod", "complement d'objet direct"],
        'Le groupe complete directement le verbe, sans preposition : c\'est un COD.',
        "Confondre COD et COI.",
        "free",
        "identification_grammaticale",
        'Phrase support : "Les formateurs expliquent la consigne aux candidats."',
      ),
      reponseCourte(
        "fct-3",
        "grammaire",
        "Facile",
        'Dans la meme phrase, quelle est la fonction de "aux candidats" ?',
        ["coi", "complement d'objet indirect"],
        'Le groupe est introduit par "a" : il s\'agit d\'un COI.',
        "Oublier que la preposition change la fonction.",
        "free",
        "identification_grammaticale",
        'Phrase support : "Les formateurs expliquent la consigne aux candidats."',
      ),
      qcm(
        "fct-4",
        "grammaire",
        "Facile",
        'Dans "Les eleves semblent fatigues", "fatigues" est :',
        [
          { id: "a", label: "COD" },
          { id: "b", label: "attribut du sujet" },
          { id: "c", label: "epithete" },
          { id: "d", label: "complement circonstanciel" },
        ],
        "b",
        'Le verbe "semblent" est un verbe d\'etat. "Fatigues" est attribut du sujet.',
        'Repondre "epithete" ou "adjectif" sans lire la consigne.',
        "free",
      ),
      reponseCourte(
        "fct-5",
        "grammaire",
        "Facile",
        'Dans "Le professeur parle a sa classe", pourquoi "a sa classe" n\'est-il pas COD ?',
        [
          "parce qu'il y a une preposition",
          "parce qu'il est introduit par une preposition",
          "parce qu'il y a a",
        ],
        'Le groupe est introduit par "a" : il ne complete pas directement le verbe.',
        "Chercher seulement a quelle question le groupe repond.",
        "free",
      ),
      vraiFaux(
        "fct-6",
        "grammaire",
        "Facile",
        'Vrai ou faux : dans "Les candidats relisent leur copie", "leur copie" est sujet.',
        false,
        'Le sujet est "Les candidats". "Leur copie" est COD.',
        "Prendre le groupe le plus proche du verbe pour le sujet.",
        "free",
      ),
    ],
  }),
  buildSession({
    id: "serie-classes-grammaticales",
    title: "Classes grammaticales usuelles",
    summary: "Une serie de consolidation pour reconnaitre les classes grammaticales les plus frequentes.",
    objective: "Distinguer nom, verbe, adjectif, adverbe, determinant et pronom.",
    introduction:
      "La confusion entre classes grammaticales fragilise ensuite toute l'analyse. Cette serie travaille les reperages de base.",
    subdomain: "grammaire",
    topicKey: "classes_grammaticales",
    topicLabel: "Classes grammaticales",
    level: "Facile",
    exerciseTypeLabel: "QCM, identification grammaticale",
    estimatedMinutes: 10,
    access_tier: "free",
    recommendedOrder: 3,
    completionSummary: {
      skill: "Identifier les classes grammaticales les plus frequentes",
      keyPoints: [
        "La classe depend de la nature du mot.",
        "L'adverbe modifie souvent un verbe, un adjectif ou un autre adverbe.",
        "Le determinant introduit le nom.",
      ],
      retryAdvice: "Demandez-vous a quel mot l'element se rattache et quelle nature il possede.",
    },
    questions: [
      qcm(
        "cgr-1",
        "grammaire",
        "Facile",
        'Dans "Elle relit vite sa copie", "vite" est :',
        [
          { id: "a", label: "un adjectif" },
          { id: "b", label: "un nom" },
          { id: "c", label: "un pronom" },
          { id: "d", label: "un adverbe" },
        ],
        "d",
        '"Vite" modifie le verbe "relit" : c\'est un adverbe.',
        "Le confondre avec un adjectif parce qu'il exprime une qualite.",
        "free",
      ),
      reponseCourte(
        "cgr-2",
        "grammaire",
        "Facile",
        'Dans "Ce manuel utile reste sur la table", quelle est la classe grammaticale de "Ce" ?',
        ["determinant", "determinant demonstratif"],
        'Le mot introduit le nom "manuel" : c\'est un determinant demonstratif.',
        'Repondre "pronom" sans voir qu\'un nom suit immediatement.',
        "free",
        "identification_grammaticale",
      ),
      qcm(
        "cgr-3",
        "grammaire",
        "Facile",
        'Dans "Leur attention augmente", "attention" est :',
        [
          { id: "a", label: "un nom" },
          { id: "b", label: "un verbe" },
          { id: "c", label: "un adjectif" },
          { id: "d", label: "un adverbe" },
        ],
        "a",
        '"Attention" designe ici une realite : c\'est un nom.',
        "Le prendre pour un verbe a cause de la terminaison.",
        "free",
      ),
      reponseCourte(
        "cgr-4",
        "grammaire",
        "Facile",
        'Dans "Ces consignes sont utiles", quelle est la classe grammaticale de "utiles" ?',
        ["adjectif", "adjectif qualificatif"],
        '"Utiles" qualifie le sujet "consignes" : c\'est un adjectif qualificatif.',
        'Repondre "attribut" alors que la consigne demande la nature grammaticale.',
        "free",
        "identification_grammaticale",
      ),
      qcm(
        "cgr-5",
        "grammaire",
        "Facile",
        'Dans "Ils progressent parce qu\'ils s\'entrainent", "ils" est :',
        [
          { id: "a", label: "un determinant" },
          { id: "b", label: "un adverbe" },
          { id: "c", label: "un nom" },
          { id: "d", label: "un pronom" },
        ],
        "d",
        '"Ils" remplace un groupe nominal : c\'est un pronom personnel.',
        "Le classer comme determinant parce qu'il renvoie a des personnes.",
        "free",
      ),
    ],
  }),
  buildSession({
    id: "serie-homophones-grammaticaux",
    title: "Homophones grammaticaux frequents",
    summary: "Une serie de discrimination grammaticale pour choisir la bonne graphie a partir d'un raisonnement.",
    objective: "Reconnaitre les principaux homophones grammaticaux a l'aide de tests simples.",
    introduction:
      "Les homophones sont tres rentables au CRPE. L'enjeu est de justifier chaque choix par une regle grammaticale claire.",
    subdomain: "orthographe",
    topicKey: "homophones_grammaticaux",
    topicLabel: "Homophones grammaticaux",
    level: "Intermediaire",
    exerciseTypeLabel: "QCM",
    estimatedMinutes: 10,
    access_tier: "free",
    recommendedOrder: 4,
    completionSummary: {
      skill: "Choisir une graphie en s'appuyant sur la grammaire",
      keyPoints: [
        'Remplacer "a" par "avait" permet souvent de trancher.',
        "Il faut distinguer coordination, verbe et preposition.",
        "La nature du determinant aide a choisir entre ses, ces, son.",
      ],
      retryAdvice: "Avant de repondre, formulez le test grammatical qui valide votre choix.",
    },
    questions: [
      qcm(
        "hg-1",
        "orthographe",
        "Intermediaire",
        'Completez : "Il ... relu sa fiche avant de partir."',
        [
          { id: "a", label: "a" },
          { id: "b", label: "à" },
        ],
        "a",
        'On peut remplacer par "avait relu" : il s\'agit du verbe avoir.',
        "Choisir selon la sonorite sans verifier la nature grammaticale.",
        "free",
      ),
      qcm(
        "hg-2",
        "orthographe",
        "Intermediaire",
        'Completez : "Il pense ... ses resultats."',
        [
          { id: "a", label: "a" },
          { id: "b", label: "à" },
        ],
        "b",
        'Ici, le mot introduit un complement : c\'est une preposition.',
        "Ecrire le verbe avoir devant un groupe nominal.",
        "free",
      ),
      qcm(
        "hg-3",
        "orthographe",
        "Intermediaire",
        'Completez : "Les consignes sont claires ... precises."',
        [
          { id: "a", label: "et" },
          { id: "b", label: "est" },
        ],
        "a",
        'Le mot relie ici deux adjectifs : c\'est une conjonction de coordination.',
        "Confondre conjonction et verbe etre.",
        "free",
      ),
      qcm(
        "hg-4",
        "orthographe",
        "Intermediaire",
        'Completez : "Cette regle ... difficile au premier abord."',
        [
          { id: "a", label: "et" },
          { id: "b", label: "est" },
        ],
        "b",
        'Le mot est ici le verbe etre au present.',
        "Choisir la coordination sans identifier le verbe principal.",
        "free",
      ),
      qcm(
        "hg-5",
        "orthographe",
        "Intermediaire",
        'Completez : "... cahier est range, mais ... stylos sont restes sur la table."',
        [
          { id: "a", label: "Son / ses" },
          { id: "b", label: "Sont / ces" },
          { id: "c", label: "Son / ces" },
          { id: "d", label: "Ses / ces" },
        ],
        "c",
        '"Son" est possessif singulier ; "ces" est demonstratif pluriel.',
        'Ecrire "ses" uniquement parce que le nom qui suit est au pluriel.',
        "free",
      ),
      qcm(
        "hg-6",
        "orthographe",
        "Intermediaire",
        'Completez : "... sont les eleves qui se preparent, pas ... voisins."',
        [
          { id: "a", label: "Ce / ses" },
          { id: "b", label: "Se / ces" },
          { id: "c", label: "Ses / ces" },
          { id: "d", label: "Ce / ces" },
        ],
        "d",
        'On ecrit "Ce sont" dans la tournure presentative. "Ces" designe ensuite les voisins.',
        'Confondre "ce" et "se" dans une tournure non pronominale.',
        "free",
      ),
    ],
  }),
  buildSession({
    id: "serie-accords-groupe-nominal",
    title: "Accords dans le groupe nominal",
    summary: "Une serie pour stabiliser les accords determinant, nom et adjectif.",
    objective: "Accorder correctement les elements du groupe nominal dans des cas courants.",
    introduction:
      "Le groupe nominal semble simple, mais les erreurs reviennent vite quand plusieurs expansions se cumulent.",
    subdomain: "orthographe",
    topicKey: "accords_groupe_nominal",
    topicLabel: "Accords dans le groupe nominal",
    level: "Facile",
    exerciseTypeLabel: "Correction orthographique, QCM",
    estimatedMinutes: 10,
    access_tier: "free",
    recommendedOrder: 5,
    completionSummary: {
      skill: "Accorder correctement les constituants du groupe nominal",
      keyPoints: [
        "Le determinant, le nom et l'adjectif s'accordent entre eux.",
        "Le genre et le nombre se verifient sur le nom noyau.",
        "Un adjectif place apres plusieurs noms demande une lecture attentive.",
      ],
      retryAdvice: "Reperez d'abord le nom noyau, puis verifiez les accords autour de lui.",
    },
    questions: [
      correction(
        "agn-1",
        "orthographe",
        "Facile",
        'Corrigez si necessaire : "Ces exercice difficiles demandent une lecture attentive."',
        ["Ces exercices difficiles demandent une lecture attentive."],
        '"Ces" est pluriel ; le nom doit donc s\'ecrire "exercices".',
        "N'accorder qu'un seul element du groupe nominal.",
        "free",
      ),
      qcm(
        "agn-2",
        "orthographe",
        "Facile",
        'Choisissez la bonne forme : "Une consigne et une demarche ...".',
        [
          { id: "a", label: "precise" },
          { id: "b", label: "precis" },
          { id: "c", label: "precises" },
          { id: "d", label: "precisee" },
        ],
        "c",
        'L\'adjectif se rapporte a deux noms feminins coordonnes : "precises".',
        "Accorder avec le nom le plus proche seulement.",
        "free",
      ),
      correction(
        "agn-3",
        "orthographe",
        "Facile",
        'Corrigez si necessaire : "Chaque candidate motivees relit ses notes."',
        ["Chaque candidate motivee relit ses notes."],
        'Le determinant "chaque" impose ici le singulier.',
        "Laisser l'adjectif au pluriel en se fiant a l'idee de groupe.",
        "free",
      ),
      qcm(
        "agn-4",
        "orthographe",
        "Facile",
        'Choisissez la forme correcte : "Des outils pedagogiques tres ..."',
        [
          { id: "a", label: "utile" },
          { id: "b", label: "utilisee" },
          { id: "c", label: "utilises" },
          { id: "d", label: "utiles" },
        ],
        "d",
        'Le nom "outils" est masculin pluriel ; l\'adjectif doit s\'accorder avec lui.',
        'Se laisser perturber par l\'adverbe "tres".',
        "free",
      ),
      reponseCourte(
        "agn-5",
        "orthographe",
        "Facile",
        'Dans "Les principales difficultes syntaxiques", quel mot commande l\'accord de "principales" ?',
        ["difficultes", "le nom difficultes"],
        'L\'adjectif "principales" s\'accorde avec le nom noyau "difficultes".',
        "Chercher un accord avec le mot le plus proche sans repérer le noyau nominal.",
        "free",
      ),
    ],
  }),
  buildSession({
    id: "serie-temps-de-base",
    title: "Present, imparfait et futur",
    summary: "Une serie de consolidation sur les temps de base et leurs formes les plus frequentes.",
    objective: "Reconnaître et produire les formes correctes au present, a l'imparfait et au futur simple.",
    introduction:
      "Avant les cas plus fins, il faut d'abord fiabiliser les temps de base. Cette serie melange reperage de forme et choix du temps.",
    subdomain: "conjugaison",
    topicKey: "temps_de_base",
    topicLabel: "Present, imparfait et futur",
    level: "Facile",
    exerciseTypeLabel: "QCM, reponse courte",
    estimatedMinutes: 10,
    access_tier: "free",
    recommendedOrder: 6,
    completionSummary: {
      skill: "Choisir et former correctement les temps de base",
      keyPoints: [
        "Le present peut exprimer une habitude ou un constat.",
        "L'imparfait sert souvent au cadre ou a l'habitude dans le passe.",
        "Le futur simple exprime un fait a venir pose comme certain.",
      ],
      retryAdvice: "Reperez d'abord les indices temporels, puis verifiez la terminaison du verbe choisi.",
    },
    questions: [
      qcm(
        "tdb-1",
        "conjugaison",
        "Facile",
        'Completez : "Chaque semaine, ils ... leurs erreurs."',
        [
          { id: "a", label: "analysent" },
          { id: "b", label: "analyseront" },
          { id: "c", label: "analysaient" },
          { id: "d", label: "analyseraient" },
        ],
        "a",
        'L\'expression "Chaque semaine" renvoie ici a une habitude actuelle : le present convient.',
        "Choisir le futur a cause de l'idee de repetition.",
        "free",
      ),
      qcm(
        "tdb-2",
        "conjugaison",
        "Facile",
        'Completez : "Quand elle etait etudiante, elle ... beaucoup."',
        [
          { id: "a", label: "lisait" },
          { id: "b", label: "lira" },
          { id: "c", label: "lit" },
          { id: "d", label: "lirait" },
        ],
        "a",
        "Le cadre passe et habituel appelle l'imparfait.",
        "Garder le present par automatisme de lecture.",
        "free",
      ),
      reponseCourte(
        "tdb-3",
        "conjugaison",
        "Facile",
        'Conjuguez au futur simple : "Nous (relire) la correction demain."',
        ["relirons"],
        'Le futur simple de "relire" a la 1re personne du pluriel est "relirons".',
        "Confondre le radical du futur avec celui du conditionnel.",
        "free",
      ),
      qcm(
        "tdb-4",
        "conjugaison",
        "Facile",
        'Choisissez la bonne forme : "Pendant le cours, les eleves ... en silence."',
        [
          { id: "a", label: "ecoutaient" },
          { id: "b", label: "ecoutent" },
          { id: "c", label: "ecouteront" },
          { id: "d", label: "ecouteraient" },
        ],
        "a",
        "Le groupe introducteur inscrit la scene dans un cadre descriptif passe : l'imparfait est attendu.",
        "Se fier a la vraisemblance de la phrase sans repérer le cadre temporel.",
        "free",
      ),
      reponseCourte(
        "tdb-5",
        "conjugaison",
        "Facile",
        'Donnez la forme au present : "Vous (finir) ce travail en groupe."',
        ["finissez"],
        '"Finir" au present, 2e personne du pluriel, se conjugue "vous finissez".',
        'Oublier le double "s" de la terminaison du 2e groupe.',
        "free",
      ),
    ],
  }),
  buildSession({
    id: "serie-synonymes-antonymes",
    title: "Synonymes, antonymes et precision lexicale",
    summary: "Une serie pour travailler la justesse du mot choisi, pas seulement une proximite vague de sens.",
    objective: "Identifier un synonyme pertinent, un antonyme exact et quelques nuances lexicales.",
    introduction:
      "Le lexique utile au CRPE demande de la precision. Cette serie vous entraine a choisir le mot juste selon le contexte.",
    subdomain: "lexique",
    topicKey: "synonymes_antonymes",
    topicLabel: "Synonymie et antonymie",
    level: "Facile",
    exerciseTypeLabel: "QCM, reponse courte",
    estimatedMinutes: 9,
    access_tier: "free",
    recommendedOrder: 7,
    completionSummary: {
      skill: "Choisir un mot proche ou oppose avec precision",
      keyPoints: [
        "Un synonyme n'est pas interchangeable dans tous les contextes.",
        "L'antonyme doit respecter le sens exact du mot de depart.",
        "Le contexte aide a valider une proposition.",
      ],
      retryAdvice: "Remplacez le mot cible dans la phrase : si le sens bouge trop, la reponse n'est pas bonne.",
    },
    questions: [
      qcm(
        "lex-1",
        "lexique",
        "Facile",
        'Quel mot est le plus proche de "rigoureux" dans "un raisonnement rigoureux" ?',
        [
          { id: "a", label: "precis" },
          { id: "b", label: "bruyant" },
          { id: "c", label: "rapide" },
          { id: "d", label: "simple" },
        ],
        "a",
        '"Precis" est le mot le plus proche dans ce contexte.',
        "Choisir un mot positif mais non semantiquement proche.",
        "free",
      ),
      qcm(
        "lex-2",
        "lexique",
        "Facile",
        'Quel est l\'antonyme le plus exact de "implicite" ?',
        [
          { id: "a", label: "explicite" },
          { id: "b", label: "complexe" },
          { id: "c", label: "faible" },
          { id: "d", label: "vague" },
        ],
        "a",
        '"Explicite" est l\'oppose exact de "implicite".',
        "Confondre antonymie et simple changement de registre.",
        "free",
      ),
      reponseCourte(
        "lex-3",
        "lexique",
        "Facile",
        'Donnez un synonyme acceptable de "observer" dans "observer une erreur".',
        ["reperer", "constater"],
        'Dans ce contexte, "reperer" ou "constater" sont pertinents.',
        'Proposer un mot trop vague comme "voir".',
        "free",
      ),
      qcm(
        "lex-4",
        "lexique",
        "Facile",
        'Dans "une remarque nuancee", quel mot est le plus proche de "nuancee" ?',
        [
          { id: "a", label: "violente" },
          { id: "b", label: "banale" },
          { id: "c", label: "mesuree" },
          { id: "d", label: "breve" },
        ],
        "c",
        '"Mesuree" conserve l\'idee d\'une expression non brutale et precise.',
        "Choisir un mot seulement courant, sans proximite semantique claire.",
        "free",
      ),
      reponseCourte(
        "lex-5",
        "lexique",
        "Facile",
        'Donnez un antonyme acceptable de "frequent" dans "une erreur frequente".',
        ["rare", "occasionnel"],
        '"Rare" est l\'antonyme le plus direct ; "occasionnel" reste acceptable selon le contexte.',
        "Donner un mot negatif sans relation d'opposition nette.",
        "free",
      ),
    ],
  }),
  buildSession({
    id: "serie-nature-ou-fonction",
    title: "Nature ou fonction : ne plus melanger",
    summary: "Une serie pour distinguer la nature d'un mot ou groupe et sa fonction dans la phrase.",
    objective: "Repondre a une question d'analyse sans confondre classe grammaticale et role syntaxique.",
    introduction:
      "Beaucoup d'erreurs viennent d'une reponse juste... mais a une autre question. Cette serie cible la confusion classique entre nature et fonction.",
    subdomain: "analyse_langue",
    topicKey: "nature_ou_fonction",
    topicLabel: "Nature ou fonction",
    level: "Facile",
    exerciseTypeLabel: "Identification grammaticale, vrai/faux",
    estimatedMinutes: 10,
    access_tier: "free",
    recommendedOrder: 8,
    completionSummary: {
      skill: "Distinguer ce qu'est un mot et le role qu'il joue",
      keyPoints: [
        "La nature renvoie a la classe grammaticale.",
        "La fonction renvoie au role dans la phrase.",
        "Un meme groupe peut garder sa nature et changer de fonction selon le contexte.",
      ],
      retryAdvice: "Relisez toujours la consigne : demande-t-on la nature ou la fonction ?",
    },
    questions: [
      vraiFaux(
        "nof-1",
        "analyse_langue",
        "Facile",
        'Vrai ou faux : dans "Ces eleves progressent vite", dire que "vite" est adverbe repond a une question de nature.',
        true,
        'Dire que "vite" est un adverbe, c\'est indiquer sa nature grammaticale.',
        'Employer "fonction" pour toute analyse grammaticale.',
        "free",
      ),
      reponseCourte(
        "nof-2",
        "analyse_langue",
        "Facile",
        'Dans "Les candidats relisent leur copie", quelle est la fonction de "leur copie" ?',
        ["cod", "complement d'objet direct"],
        'Le groupe recoit directement l\'action du verbe : c\'est un COD.',
        'Repondre "groupe nominal", ce qui indique seulement la nature.',
        "free",
        "identification_grammaticale",
      ),
      reponseCourte(
        "nof-3",
        "analyse_langue",
        "Facile",
        'Dans "Un texte complexe", quelle est la nature de "complexe" ?',
        ["adjectif", "adjectif qualificatif"],
        '"Complexe" qualifie le nom "texte" : sa nature est adjectif qualificatif.',
        'Repondre "epithete" alors que la consigne demande la nature.',
        "free",
        "identification_grammaticale",
      ),
      vraiFaux(
        "nof-4",
        "analyse_langue",
        "Facile",
        'Vrai ou faux : dans "Le travail reste exigeant", "exigeant" est attribut du sujet.',
        true,
        'Le verbe "reste" est un verbe d\'etat. "Exigeant" est donc attribut du sujet.',
        'Se contenter de dire "adjectif" sans donner la fonction demandee.',
        "free",
      ),
      reponseCourte(
        "nof-5",
        "analyse_langue",
        "Facile",
        'Dans "Les outils numeriques", donnez la nature du groupe entier "Les outils numeriques".',
        ["groupe nominal", "gn"],
        'L\'ensemble forme un groupe nominal construit autour du nom noyau "outils".',
        "Donner une fonction alors que la consigne demande la nature du groupe.",
        "free",
      ),
    ],
  }),
  buildSession({
    id: "serie-futur-conditionnel-subjonctif",
    title: "Futur, conditionnel et subjonctif : ne plus confondre",
    summary: "Une serie pour distinguer des formes proches et les employer selon le sens et la construction.",
    objective: "Differencier futur, conditionnel et subjonctif en liant les terminaisons aux valeurs d'emploi.",
    introduction:
      "Les erreurs de conjugaison viennent souvent d'une lecture trop rapide. Ici, vous travaillez a la fois la forme verbale et la valeur qu'elle exprime.",
    subdomain: "conjugaison",
    topicKey: "modes_temps_proches",
    topicLabel: "Futur, conditionnel et subjonctif",
    level: "Intermediaire",
    exerciseTypeLabel: "QCM, reponse courte, vrai/faux",
    estimatedMinutes: 13,
    access_tier: "premium",
    recommendedOrder: 9,
    completionSummary: {
      skill: "Relier le mode et le temps au contexte de la phrase",
      keyPoints: [
        "Le futur renvoie a un fait a venir presente comme certain.",
        "Le conditionnel sert souvent l'hypothese ou l'attenuation.",
        'Le subjonctif depend de certaines constructions comme "il faut que" ou "bien que".',
      ],
      retryAdvice: "Reperez d'abord le declencheur : adverbe temporel, hypothese ou locution subordonnante.",
    },
    questions: [
      qcm(
        "fcs-1",
        "conjugaison",
        "Intermediaire",
        'Completez : "Demain, nous ... la correction complete."',
        [
          { id: "a", label: "verrions" },
          { id: "b", label: "verrons" },
          { id: "c", label: "voyons" },
          { id: "d", label: "verrez" },
        ],
        "b",
        'L\'adverbe "Demain" introduit ici un futur pose comme certain.',
        "Choisir le conditionnel parce que la terminaison semble plus soutenue.",
        "premium",
      ),
      qcm(
        "fcs-2",
        "conjugaison",
        "Intermediaire",
        'Completez : "Avec plus de temps, nous ... davantage d\'exercices."',
        [
          { id: "a", label: "ferons" },
          { id: "b", label: "ferions" },
          { id: "c", label: "faisons" },
          { id: "d", label: "fassions" },
        ],
        "b",
        "La phrase exprime une hypothese : le conditionnel est attendu.",
        "Ne regarder que la terminaison sans tenir compte de la valeur hypothetique.",
        "premium",
      ),
      reponseCourte(
        "fcs-3",
        "conjugaison",
        "Intermediaire",
        'Conjuguez : "Il faut que vous (prendre) le temps de relire."',
        ["preniez"],
        'Apres "il faut que", le verbe se met au subjonctif present.',
        "Donner l'infinitif ou employer l'indicatif.",
        "premium",
      ),
      vraiFaux(
        "fcs-4",
        "conjugaison",
        "Intermediaire",
        'Vrai ou faux : dans "Je voudrais que tu viennes", "viennes" est au subjonctif.',
        true,
        'Le verbe est bien au subjonctif present dans cette subordonnee introduite par "que".',
        'Repondre simplement "present" sans preciser le mode verbal.',
        "premium",
      ),
      qcm(
        "fcs-5",
        "conjugaison",
        "Intermediaire",
        'Dans "Si tu travaillais davantage, tu reussirais", "reussirais" est au :',
        [
          { id: "a", label: "futur" },
          { id: "b", label: "conditionnel" },
          { id: "c", label: "subjonctif" },
          { id: "d", label: "imparfait" },
        ],
        "b",
        'La structure "si + imparfait" appelle ici un conditionnel dans la proposition principale.',
        "Confondre futur et conditionnel a cause de la proximite des terminaisons.",
        "premium",
      ),
      reponseCourte(
        "fcs-6",
        "conjugaison",
        "Intermediaire",
        'Donnez l\'infinitif du verbe dans "nous tiendrons".',
        ["tenir"],
        'Malgre le radical irregulier "tiendr-", l\'infinitif reste "tenir".',
        "Reconstruire un infinitif fictif a partir du radical du futur.",
        "premium",
      ),
      qcm(
        "fcs-7",
        "conjugaison",
        "Intermediaire",
        'Completez : "Bien qu\'il ... fatigue, il continue."',
        [
          { id: "a", label: "est" },
          { id: "b", label: "sera" },
          { id: "c", label: "serait" },
          { id: "d", label: "soit" },
        ],
        "d",
        'La locution "bien que" demande le subjonctif.',
        'Garder l\'indicatif par automatisme apres "bien que".',
        "premium",
      ),
    ],
  }),
  buildSession({
    id: "serie-analyse-groupe-nominal-relative",
    title: "Analyse de la langue : groupe nominal et subordination",
    summary: "Une serie exigeante pour relier groupe nominal, proposition relative et chaine d'accords.",
    objective: "Observer la structure d'une phrase complexe et justifier une analyse precise.",
    introduction:
      "Cette serie demande une lecture ordonnee de la phrase : reperer le noyau, identifier la relative, puis suivre les accords a distance.",
    subdomain: "analyse_langue",
    topicKey: "relative_et_chaine_accords",
    topicLabel: "Relative et chaine d'accords",
    level: "Difficile",
    exerciseTypeLabel: "Identification grammaticale, analyse, vrai/faux",
    estimatedMinutes: 14,
    access_tier: "premium",
    recommendedOrder: 10,
    completionSummary: {
      skill: "Articuler syntaxe, groupe nominal et accords dans une phrase complexe",
      keyPoints: [
        "Le noyau d'un groupe nominal n'est pas tout le groupe.",
        "Une relative a une nature et une fonction distinctes.",
        "Le participe passe avec avoir peut s'accorder avec un COD antepose.",
      ],
      retryAdvice: "Reperez d'abord les noyaux nominaux, puis les verbes, puis les marqueurs de subordination.",
    },
    questions: [
      reponseCourte(
        "agl-1",
        "analyse_langue",
        "Difficile",
        "Quel est le noyau du groupe nominal sujet dans la phrase support ?",
        ["eleves"],
        'Le groupe sujet complet commence par "Les eleves qui relisent...", mais son noyau est "eleves".',
        "Recopier tout le groupe nominal au lieu d'identifier la tete du groupe.",
        "premium",
        "identification_grammaticale",
        'Phrase support : "Les eleves qui relisent attentivement leur brouillon reperent souvent des erreurs qu\'ils n\'avaient pas vues au debut."',
      ),
      reponseCourte(
        "agl-2",
        "analyse_langue",
        "Difficile",
        'Quelle est la nature de "qui relisent attentivement leur brouillon" ?',
        ["proposition subordonnee relative", "subordonnee relative"],
        'Le groupe est introduit par le pronom relatif "qui" : c\'est une proposition subordonnee relative.',
        'Repondre seulement "proposition" ou confondre avec une conjonction.',
        "premium",
        "identification_grammaticale",
        'Phrase support : "Les eleves qui relisent attentivement leur brouillon reperent souvent des erreurs qu\'ils n\'avaient pas vues au debut."',
      ),
      reponseCourte(
        "agl-3",
        "analyse_langue",
        "Difficile",
        "Quelle est la fonction de cette proposition relative ?",
        ["complement de l'antecedent", "expansion du nom", "complement de l'antecedent eleves"],
        "La relative precise quels eleves sont concernes : elle est complement de l'antecedent.",
        "Redonner la nature de la relative alors que la consigne demande sa fonction.",
        "premium",
        "reponse_courte",
        'Phrase support : "Les eleves qui relisent attentivement leur brouillon reperent souvent des erreurs qu\'ils n\'avaient pas vues au debut."',
      ),
      reponseCourte(
        "agl-4",
        "analyse_langue",
        "Difficile",
        'Dans "des erreurs qu\'ils n\'avaient pas vues", quelle est la nature de "qu\'" ?',
        ["pronom relatif"],
        '"Qu\'" introduit une relative et reprend le nom "erreurs" : c\'est un pronom relatif.',
        "Parler de conjonction de subordination.",
        "premium",
        "identification_grammaticale",
        'Phrase support : "Les eleves qui relisent attentivement leur brouillon reperent souvent des erreurs qu\'ils n\'avaient pas vues au debut."',
      ),
      reponseCourte(
        "agl-5",
        "analyse_langue",
        "Difficile",
        'Quel est l\'antecedent de "qu\'" ?',
        ["erreurs"],
        'Le pronom relatif "qu\'" reprend le nom "erreurs".',
        "Choisir un nom plus proche sans verifier le lien syntaxique.",
        "premium",
        "reponse_courte",
        'Phrase support : "Les eleves qui relisent attentivement leur brouillon reperent souvent des erreurs qu\'ils n\'avaient pas vues au debut."',
      ),
      reponseCourte(
        "agl-6",
        "analyse_langue",
        "Difficile",
        'Pourquoi le verbe "avaient vues" s\'accorde-t-il avec "qu\'" ?',
        [
          "parce que qu' reprend erreurs, cod place avant le verbe",
          "parce que le cod est place avant le verbe",
          "parce que qu' reprend erreurs, cod antepose",
        ],
        'Avec l\'auxiliaire avoir, le participe passe s\'accorde avec le COD lorsqu\'il est place avant le verbe.',
        'Accorder le participe passe avec le sujet "ils".',
        "premium",
        "analyse_texte",
        'Phrase support : "Les eleves qui relisent attentivement leur brouillon reperent souvent des erreurs qu\'ils n\'avaient pas vues au debut."',
      ),
      vraiFaux(
        "agl-7",
        "analyse_langue",
        "Difficile",
        'Vrai ou faux : dans la phrase support, "attentivement" est une expansion du nom "brouillon".',
        false,
        '"Attentivement" modifie le verbe "relisent" : c\'est un adverbe de maniere.',
        "Rattacher automatiquement tout element voisin au nom le plus proche.",
        "premium",
      ),
    ],
  }),
  buildSession({
    id: "serie-gn-expansions",
    title: "Groupe nominal et expansions",
    summary: "Une serie d'approfondissement pour analyser le groupe nominal, son noyau et ses expansions.",
    objective: "Identifier le nom noyau et distinguer adjectif epithete, complement du nom et proposition relative.",
    introduction:
      "Cette serie travaille une competence tres rentable : savoir decrire precisement la composition d'un groupe nominal.",
    subdomain: "grammaire",
    topicKey: "groupe_nominal_expansions",
    topicLabel: "Groupe nominal et expansions",
    level: "Intermediaire",
    exerciseTypeLabel: "Identification grammaticale, analyse",
    estimatedMinutes: 12,
    access_tier: "premium",
    recommendedOrder: 11,
    completionSummary: {
      skill: "Analyser un groupe nominal dans le detail",
      keyPoints: [
        "Le noyau est le nom principal du groupe.",
        "Une expansion peut etre un adjectif, un complement du nom ou une relative.",
        "Il faut distinguer nature de l'expansion et role dans le groupe.",
      ],
      retryAdvice: "Commencez toujours par isoler le noyau, puis nommez les expansions une a une.",
    },
    questions: [
      reponseCourte(
        "gne-1",
        "grammaire",
        "Intermediaire",
        'Dans "un manuel de grammaire tres utile", quel est le noyau du groupe nominal ?',
        ["manuel"],
        'Le nom principal du groupe est "manuel". Le reste vient le preciser.',
        "Prendre toute la suite du groupe comme noyau.",
        "premium",
        "identification_grammaticale",
      ),
      reponseCourte(
        "gne-2",
        "grammaire",
        "Intermediaire",
        'Dans le meme groupe, quelle est la nature de "de grammaire" ?',
        ["complement du nom"],
        '"De grammaire" complete le nom "manuel" : c\'est un complement du nom.',
        'Repondre "groupe prepositionnel" alors qu\'on attend le role de l\'expansion.',
        "premium",
        "identification_grammaticale",
        'Support : "un manuel de grammaire tres utile"',
      ),
      reponseCourte(
        "gne-3",
        "grammaire",
        "Intermediaire",
        'Dans le meme groupe, quelle est la nature de "utile" ?',
        ["adjectif", "adjectif qualificatif"],
        '"Utile" est un adjectif qualificatif rattache au nom "manuel".',
        'Repondre "epithete" alors que la consigne demande la nature grammaticale.',
        "premium",
        "identification_grammaticale",
        'Support : "un manuel de grammaire tres utile"',
      ),
      qcm(
        "gne-4",
        "grammaire",
        "Intermediaire",
        'Dans "les eleves qui relisent leur brouillon", l\'expansion du nom est :',
        [
          { id: "a", label: "un adjectif epithete" },
          { id: "b", label: "une proposition relative" },
          { id: "c", label: "un adverbe" },
          { id: "d", label: "un complement du nom" },
        ],
        "b",
        'Le groupe introduit par "qui" est une proposition subordonnee relative.',
        "Ne pas reconnaitre le pronom relatif comme indice principal.",
        "premium",
      ),
      reponseCourte(
        "gne-5",
        "grammaire",
        "Intermediaire",
        "Expliquez brievement la difference entre un adjectif epithete et un complement du nom.",
        [
          "l'adjectif qualifie directement le nom, le complement du nom est souvent introduit par une preposition",
          "l'adjectif est un adjectif qui qualifie le nom, le complement du nom est souvent prepositionnel",
        ],
        "L'adjectif epithete est un adjectif ; le complement du nom est souvent un groupe prepositionnel.",
        "Se contenter de donner un exemple sans expliquer la difference de nature.",
        "premium",
        "analyse_texte",
      ),
    ],
  }),
  buildSession({
    id: "serie-participe-passe-etre",
    title: "Participe passe avec etre",
    summary: "Une serie pour consolider la regle d'accord la plus stable avant les cas plus delicats avec avoir.",
    objective: "Accorder correctement le participe passe employe avec l'auxiliaire etre.",
    introduction:
      "L'accord du participe passe avec etre est plus regulier qu'avec avoir, mais les erreurs restent frequentes quand le sujet est eloigne.",
    subdomain: "orthographe",
    topicKey: "participe_passe_etre",
    topicLabel: "Participe passe avec etre",
    level: "Intermediaire",
    exerciseTypeLabel: "QCM, vrai/faux, correction orthographique",
    estimatedMinutes: 10,
    access_tier: "premium",
    recommendedOrder: 12,
    completionSummary: {
      skill: "Accorder correctement le participe passe avec etre",
      keyPoints: [
        "Avec etre, le participe passe s'accorde avec le sujet.",
        "Il faut identifier le vrai sujet avant de choisir la marque finale.",
        "La distance entre sujet et verbe ne change pas la regle.",
      ],
      retryAdvice: "Soulignez le sujet, puis verifiez son genre et son nombre avant de corriger la forme.",
    },
    questions: [
      qcm(
        "ppe-1",
        "orthographe",
        "Intermediaire",
        'Choisissez la bonne forme : "Les copies sont ..."',
        [
          { id: "a", label: "corrige" },
          { id: "b", label: "corriges" },
          { id: "c", label: "corrigees" },
          { id: "d", label: "corrigeant" },
        ],
        "c",
        'Le sujet "copies" est feminin pluriel. Le participe passe avec etre s\'accorde donc en genre et en nombre.',
        "Laisser la forme invariable par automatisme.",
        "premium",
      ),
      correction(
        "ppe-2",
        "orthographe",
        "Intermediaire",
        'Corrigez si necessaire : "Les consignes sont reste clair."',
        ["Les consignes sont restees claires."],
        'Avec l\'auxiliaire etre, "restees" s\'accorde avec "consignes". L\'adjectif "claires" s\'accorde egalement.',
        "Corriger le participe passe mais oublier l'accord de l'adjectif qui suit.",
        "premium",
      ),
      vraiFaux(
        "ppe-3",
        "orthographe",
        "Intermediaire",
        'Vrai ou faux : dans "Les eleves sont arrives en avance", "arrives" est correctement accorde.',
        true,
        'Le sujet "eleves" est masculin pluriel. La forme "arrives" est correcte.',
        "Croire que le participe passe reste invariable quand il est employe avec etre.",
        "premium",
      ),
      qcm(
        "ppe-4",
        "orthographe",
        "Intermediaire",
        'Choisissez la forme correcte : "La candidate est ..."',
        [
          { id: "a", label: "preparee" },
          { id: "b", label: "prepare" },
          { id: "c", label: "prepares" },
          { id: "d", label: "preparees" },
        ],
        "a",
        'Le sujet est feminin singulier : on ecrit "preparee".',
        "Oublier la marque du feminin au singulier.",
        "premium",
      ),
      reponseCourte(
        "ppe-5",
        "orthographe",
        "Intermediaire",
        'Dans "Les erreurs sont reperees", avec quel element le participe passe s\'accorde-t-il ?',
        ["le sujet", "erreurs", "les erreurs"],
        'Avec etre, le participe passe s\'accorde avec le sujet : ici, "les erreurs".',
        "Chercher un COD alors que la regle demande de repérer le sujet.",
        "premium",
      ),
    ],
  }),
];

const MODULE_EXERCISE_TYPE_LABELS: Record<ExerciseRecord["exercise_type"], string> = {
  qcm: "QCM",
  vrai_faux: "Vrai/faux",
  reponse_courte: "Reponse courte",
  identification_grammaticale: "Identification grammaticale",
  correction_orthographique: "Correction orthographique",
  analyse_texte: "Analyse de texte",
};

function buildModuleSession(series: (typeof part4PremierLotSeriesCompletes)[number]): RevisionSession {
  const integration = frenchModuleSeriesIntegration[series.id];
  const questions = series.questions.map((item) =>
    question({
      id: item.id,
      subdomain: series.domain,
      topic_key: series.subdomain,
      topic_label: series.subdomainLabel,
      level: series.level,
      exercise_type: item.type,
      instruction: item.instruction,
      support_text: item.supportText,
      choices: item.choices,
      expected_answer: item.expectedAnswer,
      detailed_explanation: item.explanation,
      common_mistake: item.commonMistake,
      access_tier: integration.accessTier,
    })
  );

  return buildSession({
    id: series.id,
    title: series.title,
    summary: series.objective,
    objective: series.objective,
    introduction: series.introduction,
    subdomain: series.domain,
    topicKey: series.subdomain,
    topicLabel: series.subdomainLabel,
    level: series.level,
    exerciseTypeLabel: Array.from(
      new Set(series.questions.map((item) => MODULE_EXERCISE_TYPE_LABELS[item.type])),
    ).join(", "),
    estimatedMinutes: series.estimatedMinutes,
    access_tier: integration.accessTier,
    recommendedOrder: integration.recommendedOrder,
    completionSummary: {
      skill: series.bilan.competenceTravaillee,
      keyPoints: series.bilan.pointsARetenir,
      retryAdvice: series.bilan.conseilDeReprise,
    },
    questions,
  });
}

const moduleFrenchCrpeSeriesSeed = part4PremierLotSeriesCompletes.map(buildModuleSession);

export const frenchCrpeSeriesSeed: RevisionSession[] = [
  ...legacyFrenchCrpeSeriesSeed,
  ...moduleFrenchCrpeSeriesSeed,
];
