import { ExerciseRecord, RevisionSession } from "@/types/domain";

const createdAt = "2026-03-19T08:00:00.000Z";

type QuestionInput = Omit<
  ExerciseRecord,
  "subject" | "validation_status" | "source" | "is_published" | "created_at" | "updated_at"
>;

type SessionInput = Omit<RevisionSession, "questionCount">;

function question(data: QuestionInput): ExerciseRecord {
  return {
    subject: "Francais",
    validation_status: "valide",
    source: "Serie CRPE Francais V3",
    is_published: true,
    created_at: createdAt,
    updated_at: createdAt,
    common_mistake: null,
    ...data,
  };
}

function buildSession(data: SessionInput): RevisionSession {
  return { ...data, questionCount: data.questions.length };
}

function qcm(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  choices: Array<{ id: string; label: string }>,
  value: string,
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
) {
  return question({
    id, subdomain, level, exercise_type: "qcm",
    instruction, support_text: null, choices,
    expected_answer: { mode: "single_choice", value },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
    topic_key: null, topic_label: null,
  });
}

function vraiFaux(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  value: boolean,
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
) {
  return question({
    id, subdomain, level, exercise_type: "vrai_faux",
    instruction, support_text: null,
    choices: [{ id: "true", label: "Vrai" }, { id: "false", label: "Faux" }],
    expected_answer: { mode: "boolean", value },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
    topic_key: null, topic_label: null,
  });
}

function reponseCourte(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  acceptableAnswers: string[],
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
  exercise_type: ExerciseRecord["exercise_type"] = "reponse_courte",
  support_text: string | null = null,
) {
  return question({
    id, subdomain, level, exercise_type,
    instruction, support_text, choices: null,
    expected_answer: { mode: "text", acceptableAnswers },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
    topic_key: null, topic_label: null,
  });
}

function correction(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  acceptableAnswers: string[],
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
) {
  return reponseCourte(id, subdomain, level, instruction, acceptableAnswers, explanation, commonMistake, access_tier, "correction_orthographique");
}

export const seriesV3BatchD: RevisionSession[] = [
  // ─── Série 51 : Participe passé avec être ──────────────────────────────────
  buildSession({
    id: "fr-v3d-serie-ppe",
    title: "Participe passé avec être : correction d'erreurs",
    summary: "Repérer et corriger les erreurs d'accord du participe passé conjugué avec l'auxiliaire être.",
    objective: "Accorder correctement le participe passé avec être en tenant compte du genre et du nombre du sujet.",
    introduction: "Avec l'auxiliaire être, le participe passé s'accorde en genre et en nombre avec le sujet. C'est une règle fondamentale que les élèves maîtrisent progressivement à l'école primaire.",
    subdomain: "orthographe",
    topicKey: "participe_passe_etre",
    topicLabel: "Participe passé avec être",
    level: "Intermediaire",
    exerciseTypeLabel: "Correction d'erreurs, QCM, vrai/faux",
    estimatedMinutes: 13,
    access_tier: "free",
    recommendedOrder: 51,
    completionSummary: {
      skill: "Accorder le participe passé avec être selon le genre et le nombre du sujet",
      keyPoints: [
        "Avec être, le PP s'accorde avec le sujet : Marie est tombée (fém. sing.).",
        "Les verbes pronominaux utilisent aussi être comme auxiliaire.",
        "Ne pas confondre avec avoir, où le PP reste invariable (sauf règle du COD).",
      ],
      retryAdvice: "Identifiez d'abord le sujet, déterminez son genre et son nombre, puis accordez le participe passé en conséquence.",
    },
    questions: [
      correction(
        "v3d-ppe-1",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Marie est tombé dans l'escalier. »",
        ["Marie est tombée dans l'escalier."],
        "Le sujet Marie est féminin singulier. Avec l'auxiliaire être, le participe passé tombe s'accorde → tombée.",
        "Oublier le -e final car le participe passé ressemble à un adjectif et l'accord visuel est parfois négligé à l'oral.",
        "free",
      ),
      correction(
        "v3d-ppe-2",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Ils sont partie à l'aube. »",
        ["Ils sont partis à l'aube."],
        "Le sujet Ils est masculin pluriel. Le participe passé de partir avec être s'accorde → partis (masc. plur.).",
        "Écrire 'partie' (féminin) au lieu de 'partis' (masculin pluriel).",
        "free",
      ),
      correction(
        "v3d-ppe-3",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Nous sommes arrivé à temps. »",
        ["Nous sommes arrivés à temps."],
        "Le sujet Nous (groupe mixte ou masculin pluriel) exige l'accord au masculin pluriel → arrivés.",
        "Oublier le -s du pluriel lorsque le participe passé se termine déjà par une consonne apparente à l'oral.",
        "free",
      ),
      correction(
        "v3d-ppe-4",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Elle s'est levé trop tard. »",
        ["Elle s'est levée trop tard."],
        "Le verbe pronominal se lever utilise être comme auxiliaire. Le sujet Elle est féminin singulier → levée.",
        "Traiter les verbes pronominaux comme s'ils utilisaient avoir, et donc ne pas accorder.",
        "free",
      ),
      correction(
        "v3d-ppe-5",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Les enfants sont resté à la maison. »",
        ["Les enfants sont restés à la maison."],
        "Le sujet Les enfants est masculin pluriel. Le participe passé de rester avec être → restés.",
        "Omettre le -s final au pluriel, surtout quand la phrase est longue.",
        "free",
      ),
      correction(
        "v3d-ppe-6",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Lucie et Emma sont venu ensemble. »",
        ["Lucie et Emma sont venues ensemble."],
        "Lucie et Emma : deux sujets féminins singuliers → sujet féminin pluriel → venues.",
        "Accorder au masculin pluriel par défaut lorsque plusieurs sujets sont énumérés, sans vérifier leur genre.",
        "free",
      ),
      correction(
        "v3d-ppe-7",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Les deux professeures sont arrivé en retard. »",
        ["Les deux professeures sont arrivées en retard."],
        "Le sujet Les deux professeures est féminin pluriel → arrivées (fém. plur.).",
        "Ne pas accorder car le mot 'professeures' est perçu comme un terme neutre dans le langage courant.",
        "free",
      ),
      correction(
        "v3d-ppe-8",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Il est née en 1990. »",
        ["Il est né en 1990."],
        "Le sujet Il est masculin singulier. Le participe passé de naître → né (masc. sing., sans -e).",
        "Écrire née par analogie avec le féminin, en oubliant de vérifier le genre du sujet.",
        "free",
      ),
      correction(
        "v3d-ppe-9",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Elles sont sortis par la porte de derrière. »",
        ["Elles sont sorties par la porte de derrière."],
        "Le sujet Elles est féminin pluriel. Le participe passé de sortir avec être → sorties.",
        "Accorder au masculin pluriel par défaut lorsque plusieurs personnes sont impliquées.",
        "free",
      ),
      correction(
        "v3d-ppe-10",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Les filles sont allé au marché. »",
        ["Les filles sont allées au marché."],
        "Le sujet Les filles est féminin pluriel → allées. Le verbe aller utilise toujours être comme auxiliaire.",
        "Confondre aller avec un verbe du 1er groupe qui se conjuguerait avec avoir.",
        "free",
      ),
    ],
  }),

  // ─── Série 52 : Homophones courants ────────────────────────────────────────
  buildSession({
    id: "fr-v3d-serie-hom1",
    title: "Homophones courants : correction d'erreurs",
    summary: "Identifier et corriger les confusions entre homophones grammaticaux fréquents : a/à, est/et, ou/où, on/ont, son/sont, ce/se.",
    objective: "Distinguer les homophones grammaticaux et choisir la graphie correcte selon la fonction dans la phrase.",
    introduction: "Les homophones grammaticaux sont une source d'erreur très fréquente chez les élèves. Savoir les distinguer est une compétence clé que l'enseignant du primaire doit maîtriser et savoir enseigner.",
    subdomain: "orthographe",
    topicKey: "homophones_courants",
    topicLabel: "Homophones courants",
    level: "Facile",
    exerciseTypeLabel: "Correction d'erreurs, QCM",
    estimatedMinutes: 12,
    access_tier: "free",
    recommendedOrder: 52,
    completionSummary: {
      skill: "Identifier et corriger les homophones grammaticaux courants",
      keyPoints: [
        "a (verbe avoir) vs à (préposition) : remplacer par 'avait' pour tester.",
        "est (verbe être) vs et (conjonction) : remplacer est par 'était', et par 'ainsi que'.",
        "on (pronom) vs ont (verbe avoir) : remplacer par 'il' pour tester.",
        "son (déterminant) vs sont (verbe être) : remplacer par 'mon' pour tester son, par 'étaient' pour sont.",
      ],
      retryAdvice: "Pour chaque homophone, appliquez le test de remplacement par une forme dont l'accord est audible.",
    },
    questions: [
      correction(
        "v3d-hom1-1",
        "orthographe",
        "Facile",
        "Corrige l'erreur dans cette phrase : « Il à mangé une pomme. »",
        ["Il a mangé une pomme."],
        "Ici, 'a' est le verbe avoir conjugué (on peut le remplacer par 'avait'). La préposition à s'utilise pour indiquer un lieu, un temps ou un but.",
        "Écrire à (préposition) au lieu de a (verbe avoir) car les deux se prononcent pareil.",
        "free",
      ),
      correction(
        "v3d-hom1-2",
        "orthographe",
        "Facile",
        "Corrige l'erreur dans cette phrase : « Elle est grande est sportive. »",
        ["Elle est grande et sportive."],
        "La conjonction de coordination et relie deux adjectifs. On peut la remplacer par 'ainsi que'. Le verbe être conjugué est ('était') ne peut pas avoir ce rôle.",
        "Confondre le verbe est avec la conjonction et car ils sont homophones.",
        "free",
      ),
      correction(
        "v3d-hom1-3",
        "orthographe",
        "Facile",
        "Corrige l'erreur dans cette phrase : « Ou habitez-vous ? »",
        ["Où habitez-vous ?"],
        "Où (avec accent grave) est un adverbe de lieu interrogatif. Ou (sans accent) est une conjonction de coordination exprimant un choix.",
        "Omettre l'accent grave sur où interrogatif ou relatif de lieu.",
        "free",
      ),
      correction(
        "v3d-hom1-4",
        "orthographe",
        "Facile",
        "Corrige l'erreur dans cette phrase : « Le chien et sont maître se promènent. »",
        ["Le chien et son maître se promènent."],
        "Son est un déterminant possessif (remplaçable par 'mon'). Sont est le verbe être conjugué (remplaçable par 'étaient').",
        "Confondre son (déterminant) et sont (verbe être conjugué au présent de l'indicatif).",
        "free",
      ),
      correction(
        "v3d-hom1-5",
        "orthographe",
        "Facile",
        "Corrige l'erreur dans cette phrase : « Ces chaussures sont a moi. »",
        ["Ces chaussures sont à moi."],
        "Ici, à est une préposition d'appartenance. Le verbe avoir conjugué (a) ne peut pas introduire un pronom tonique.",
        "Écrire a (verbe avoir) au lieu de à (préposition) devant un pronom tonique.",
        "free",
      ),
      correction(
        "v3d-hom1-6",
        "orthographe",
        "Facile",
        "Corrige l'erreur dans cette phrase : « On as fini les devoirs. »",
        ["On a fini les devoirs."],
        "On est un pronom de la 3e personne du singulier : il se conjugue comme il/elle → on a (pas on as). La 2e personne du singulier (tu as) ne s'applique pas ici.",
        "Confondre la conjugaison de on (3e pers. sing.) avec celle de tu (2e pers. sing.).",
        "free",
      ),
      correction(
        "v3d-hom1-7",
        "orthographe",
        "Facile",
        "Corrige l'erreur dans cette phrase : « C'est ces affaires, pas les miennes. »",
        ["C'est ses affaires, pas les miennes."],
        "Ses est un déterminant possessif de la 3e personne (remplaçable par 'mes'). Ces est un déterminant démonstratif (remplaçable par 'ces livres-là').",
        "Confondre ses (possessif) et ces (démonstratif) car ils sont homophones.",
        "free",
      ),
      correction(
        "v3d-hom1-8",
        "orthographe",
        "Facile",
        "Corrige l'erreur dans cette phrase : « Je la pose la sur la table. »",
        ["Je la pose là sur la table."],
        "Là (avec accent grave) est un adverbe de lieu. La (sans accent) est un article défini féminin ou un pronom personnel COD.",
        "Omettre l'accent grave sur là adverbe de lieu.",
        "free",
      ),
      qcm(
        "v3d-hom1-9",
        "orthographe",
        "Facile",
        "Choisissez la forme correcte : « Il ___ appris sa leçon. »",
        [
          { id: "a", label: "a" },
          { id: "b", label: "à" },
        ],
        "a",
        "Il a appris : verbe avoir conjugué à la 3e personne du singulier (on peut le remplacer par 'avait'). À est une préposition qui ne peut pas introduire un participe passé.",
        "Écrire à (préposition) au lieu de a (verbe avoir) par méconnaissance du test de remplacement.",
        "free",
      ),
      correction(
        "v3d-hom1-10",
        "orthographe",
        "Facile",
        "Corrige l'erreur dans cette phrase : « Se matin, il pleut. »",
        ["Ce matin, il pleut."],
        "Ce est un déterminant démonstratif masculin singulier devant un nom. Se est un pronom réfléchi utilisé dans les verbes pronominaux.",
        "Confondre ce (déterminant démonstratif) et se (pronom réfléchi) car ils sont homophones.",
        "free",
      ),
    ],
  }),

  // ─── Série 53 : Infinitif vs participe passé en -é ─────────────────────────
  buildSession({
    id: "fr-v3d-serie-inf",
    title: "Infinitif ou participe passé en -é ? Correction d'erreurs",
    summary: "Distinguer l'infinitif (-er) du participe passé (-é) dans des contextes variés et corriger les confusions.",
    objective: "Choisir entre infinitif et participe passé en -é grâce au test de substitution par un verbe du 3e groupe.",
    introduction: "La confusion entre infinitif et participe passé en -é est l'une des erreurs orthographiques les plus fréquentes au primaire. La règle du test de remplacement (vendre/vendu) est un outil pédagogique clé.",
    subdomain: "orthographe",
    topicKey: "infinitif_participe_passe_er_e",
    topicLabel: "Infinitif vs participe passé en -é",
    level: "Intermediaire",
    exerciseTypeLabel: "Correction d'erreurs, QCM, vrai/faux",
    estimatedMinutes: 13,
    access_tier: "free",
    recommendedOrder: 53,
    completionSummary: {
      skill: "Appliquer le test de substitution pour choisir entre -er et -é",
      keyPoints: [
        "Après un verbe modal (vouloir, pouvoir, devoir, faire, aller…) → infinitif en -er.",
        "Après un auxiliaire (avoir/être) → participe passé en -é.",
        "Test : remplacer par 'vendre' (inf.) ou 'vendu' (PP) pour entendre la différence.",
      ],
      retryAdvice: "Systématisez le test de substitution : si 'vendu' sonne juste, écrivez -é ; si 'vendre' sonne juste, écrivez -er.",
    },
    questions: [
      correction(
        "v3d-inf-1",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Il faut mangé des légumes. »",
        ["Il faut manger des légumes."],
        "Après il faut, on utilise l'infinitif. Test : 'il faut vendre' (sens) vs 'il faut vendu' (impossible) → infinitif → manger.",
        "Écrire -é après il faut car on associe cette construction à un participe passé.",
        "free",
      ),
      correction(
        "v3d-inf-2",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Elle a terminée son travail. »",
        ["Elle a terminé son travail."],
        "Avec l'auxiliaire avoir, le participe passé ne s'accorde pas avec le sujet : elle a terminé (COD 'son travail' est après le verbe). Le -e final est donc incorrect.",
        "Accorder le participe passé avec avoir avec le sujet, par analogie avec la règle de l'auxiliaire être.",
        "free",
      ),
      correction(
        "v3d-inf-3",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Je veux chanté une chanson. »",
        ["Je veux chanter une chanson."],
        "Après vouloir, on utilise l'infinitif. Test : 'je veux vendre' (correct) vs 'je veux vendu' (impossible) → infinitif → chanter.",
        "Écrire -é après un verbe modal en confondant avec la structure auxiliaire + participe passé.",
        "free",
      ),
      correction(
        "v3d-inf-4",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Il a décidé de restée chez lui. »",
        ["Il a décidé de rester chez lui."],
        "Après la préposition de introduisant un complément verbal, on utilise l'infinitif → rester. Test : 'décider de vendre' (correct) → infinitif.",
        "Écrire -ée après une préposition en confondant avec un accord de participe passé.",
        "free",
      ),
      correction(
        "v3d-inf-5",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Elle a essayé de chanté. »",
        ["Elle a essayé de chanter."],
        "La préposition de introduit un infinitif complément du verbe essayer. Test : 'essayer de vendre' → infinitif → chanter.",
        "Confondre la terminaison -é (participe passé de essayé) avec celle du verbe qui suit.",
        "free",
      ),
      correction(
        "v3d-inf-6",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Le gâteau est mangée. »",
        ["Le gâteau est mangé."],
        "Le sujet gâteau est masculin singulier. Avec l'auxiliaire être au passif, le participe passé s'accorde avec le sujet → mangé (masc. sing.), sans -e.",
        "Accorder le participe passé au féminin par association avec 'mangée' sans vérifier le genre du sujet.",
        "free",
      ),
      correction(
        "v3d-inf-7",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Elle a voulu s'arrêtée. »",
        ["Elle a voulu s'arrêter."],
        "Après voulu, on attend un infinitif. S'arrêter est le verbe pronominal à l'infinitif. Test : 'elle a voulu vendre' → infinitif → s'arrêter.",
        "Écrire -ée en accordant avec le sujet Elle, en confondant verbe modal + infinitif avec auxiliaire + participe passé.",
        "free",
      ),
      correction(
        "v3d-inf-8",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Nous avons regardé joué les enfants. »",
        ["Nous avons regardé jouer les enfants."],
        "Après regarder (verbe de perception), l'infinitif exprime l'action observée. Les enfants jouent = on regarde les enfants jouer → infinitif jouer.",
        "Écrire -é après regardé par analogie avec la construction auxiliaire + PP.",
        "free",
      ),
      vraiFaux(
        "v3d-inf-9",
        "orthographe",
        "Intermediaire",
        "Après un verbe modal comme vouloir, pouvoir ou devoir, on utilise toujours l'infinitif.",
        true,
        "Les verbes modaux (vouloir, pouvoir, devoir, savoir, faire, laisser, voir, entendre…) sont suivis d'un infinitif. Ex : je dois partir, il peut venir, nous voulons réussir.",
        "Penser que l'infinitif ne s'emploie qu'en début de phrase ou après une préposition.",
        "free",
      ),
      qcm(
        "v3d-inf-10",
        "orthographe",
        "Intermediaire",
        "Complétez : « Il faut ___ ses efforts. »",
        [
          { id: "a", label: "doublé" },
          { id: "b", label: "doubler" },
          { id: "c", label: "doublée" },
        ],
        "b",
        "Après il faut, on utilise l'infinitif. Test : 'il faut vendre ses efforts' (sens) → infinitif → doubler.",
        "Écrire doublé (participe passé) après il faut, en confondant avec une construction auxiliaire + PP.",
        "free",
      ),
    ],
  }),

  // ─── Série 54 : Accord de l'adjectif qualificatif ──────────────────────────
  buildSession({
    id: "fr-v3d-serie-adj",
    title: "Accord de l'adjectif qualificatif : correction d'erreurs",
    summary: "Repérer et corriger les erreurs d'accord de l'adjectif qualificatif en genre et en nombre.",
    objective: "Accorder correctement l'adjectif qualificatif avec le nom ou le pronom auquel il se rapporte.",
    introduction: "L'accord de l'adjectif est une règle enseignée dès le cycle 2. En maîtriser les nuances — y compris les cas particuliers comme 'avoir l'air' — est indispensable pour le CRPE.",
    subdomain: "orthographe",
    topicKey: "accord_adjectif_qualificatif",
    topicLabel: "Accord de l'adjectif qualificatif",
    level: "Intermediaire",
    exerciseTypeLabel: "Correction d'erreurs, QCM, vrai/faux",
    estimatedMinutes: 13,
    access_tier: "free",
    recommendedOrder: 54,
    completionSummary: {
      skill: "Accorder l'adjectif qualificatif avec son référent nominal",
      keyPoints: [
        "L'adjectif s'accorde en genre et en nombre avec le nom (ou pronom) qu'il qualifie.",
        "Pour le féminin, on ajoute généralement -e ; pour le pluriel, -s.",
        "Avec avoir l'air + adjectif, les deux accords sont tolérés : l'adjectif peut s'accorder avec le sujet ou rester invariable.",
      ],
      retryAdvice: "Identifiez le nom que l'adjectif qualifie, déterminez son genre et son nombre, puis appliquez les marques d'accord.",
    },
    questions: [
      correction(
        "v3d-adj-1",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Elle est intelligent. »",
        ["Elle est intelligente."],
        "Le sujet Elle est féminin singulier. L'adjectif attribut s'accorde avec le sujet → intelligente (fém. sing., ajout de -e).",
        "Laisser l'adjectif au masculin par défaut, sans vérifier le genre du sujet.",
        "free",
      ),
      correction(
        "v3d-adj-2",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Des résultats excellent. »",
        ["Des résultats excellents."],
        "Le nom résultats est masculin pluriel. L'adjectif épithète s'accorde → excellents (ajout de -s).",
        "Oublier le -s du pluriel sur l'adjectif épithète lorsque le nom est éloigné.",
        "free",
      ),
      correction(
        "v3d-adj-3",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Une femme courageux. »",
        ["Une femme courageuse."],
        "Le nom femme est féminin singulier. L'adjectif courageux forme son féminin en -euse → courageuse.",
        "Appliquer la marque du féminin -e directement sur courageux, donnant *courageuxe au lieu de courageuse.",
        "free",
      ),
      correction(
        "v3d-adj-4",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Les enfants semblent content. »",
        ["Les enfants semblent contents."],
        "Le sujet Les enfants est masculin pluriel. L'adjectif attribut s'accorde → contents (ajout de -s).",
        "Ne pas accorder l'adjectif attribut placé après le verbe attributif, en le traitant comme un adverbe invariable.",
        "free",
      ),
      correction(
        "v3d-adj-5",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Elles ont l'air fatiguée. »",
        ["Elles ont l'air fatiguées.", "Elles ont l'air fatigué."],
        "Deux accords sont grammaticalement admis. Si l'adjectif se rapporte au sujet Elles (fém. plur.) → fatiguées. Si l'on considère que avoir l'air est une locution figée dont l'adjectif qualifie l'air (masc. sing.) → fatigué. Les deux formes sont acceptées. En revanche, fatiguée (fém. sing.) est incorrect car il y a discordance de nombre avec le sujet pluriel.",
        "Accorder au féminin singulier 'fatiguée' en ne tenant compte que du genre du sujet, sans respecter le nombre.",
        "free",
      ),
      correction(
        "v3d-adj-6",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Elle semble surpris par la nouvelle. »",
        ["Elle semble surprise par la nouvelle."],
        "Le sujet Elle est féminin singulier. L'adjectif attribut de surpris forme son féminin → surprise.",
        "Laisser l'adjectif au masculin singulier après un verbe attributif, en oubliant l'accord avec le sujet féminin.",
        "free",
      ),
      correction(
        "v3d-adj-7",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Un livre intéressants. »",
        ["Un livre intéressant."],
        "Le nom livre est masculin singulier. L'adjectif épithète s'accorde au singulier → intéressant (sans -s).",
        "Ajouter un -s à l'adjectif sans vérifier le nombre du nom.",
        "free",
      ),
      vraiFaux(
        "v3d-adj-8",
        "orthographe",
        "Intermediaire",
        "L'adjectif épithète s'accorde en genre et en nombre avec le nom qu'il qualifie.",
        true,
        "Que l'adjectif soit placé avant (épithète antéposée : une belle maison) ou après le nom (épithète postposée : une maison belle), il s'accorde toujours en genre et en nombre avec ce nom.",
        "Croire que seul l'adjectif attribut (après un verbe attributif) s'accorde.",
        "free",
      ),
      qcm(
        "v3d-adj-9",
        "orthographe",
        "Intermediaire",
        "Complétez : « Ces fleurs sont ___. »",
        [
          { id: "a", label: "beau" },
          { id: "b", label: "beaux" },
          { id: "c", label: "belles" },
          { id: "d", label: "belle" },
        ],
        "c",
        "Le sujet Ces fleurs est féminin pluriel. L'adjectif attribut beau forme son féminin pluriel en belles.",
        "Choisir beaux (masc. plur.) en oubliant de vérifier le genre féminin du nom fleurs.",
        "free",
      ),
      correction(
        "v3d-adj-10",
        "orthographe",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Les décision finales restent incertaines. »",
        ["Les décisions finales restent incertaines."],
        "Décision est au pluriel (Les décisions) : l'adjectif épithète final s'accorde → finales, et le sujet au pluriel exige incertaines. L'erreur principale est l'oubli du -s sur décisions.",
        "Oublier d'accorder le nom au pluriel lorsque le déterminant les est présent.",
        "free",
      ),
    ],
  }),

  // ─── Série 55 : Passé composé vs imparfait ──────────────────────────────────
  buildSession({
    id: "fr-v3d-serie-pci",
    title: "Passé composé et imparfait : correction d'erreurs",
    summary: "Identifier et corriger les emplois incorrects du passé composé et de l'imparfait dans un récit.",
    objective: "Choisir le bon temps du passé selon la valeur aspectuelle : action accomplie (PC) vs état ou habitude (imparfait).",
    introduction: "L'opposition passé composé / imparfait structure le récit au passé. La confondre produit un texte narrativement incohérent. Ce point est central dans l'enseignement de la conjugaison au cycle 3.",
    subdomain: "conjugaison",
    topicKey: "passe_compose_imparfait",
    topicLabel: "Passé composé vs imparfait",
    level: "Intermediaire",
    exerciseTypeLabel: "Correction d'erreurs, QCM, vrai/faux",
    estimatedMinutes: 14,
    access_tier: "free",
    recommendedOrder: 55,
    completionSummary: {
      skill: "Distinguer et employer correctement le passé composé et l'imparfait",
      keyPoints: [
        "Passé composé : action ponctuelle, délimitée, achevée (hier soir, soudain, tout à coup).",
        "Imparfait : état, habitude, action de fond, durée non délimitée (chaque été, pendant que, toujours).",
        "Dans un récit, l'imparfait plante le décor, le PC fait avancer l'action.",
      ],
      retryAdvice: "Demandez-vous si l'action est délimitée dans le temps (→ PC) ou si elle exprime un état/une habitude (→ imparfait).",
    },
    questions: [
      correction(
        "v3d-pci-1",
        "conjugaison",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Hier, je mangeais une pomme. »",
        ["Hier, j'ai mangé une pomme."],
        "'Hier' indique un moment précis et révolu. L'action est ponctuelle et achevée → passé composé : j'ai mangé.",
        "Employer l'imparfait après 'hier' par confusion avec l'idée de durée passée.",
        "free",
      ),
      correction(
        "v3d-pci-2",
        "conjugaison",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Chaque été, j'ai nagé dans la mer. »",
        ["Chaque été, je nageais dans la mer."],
        "'Chaque été' exprime une habitude répétée → imparfait : je nageais.",
        "Employer le passé composé pour exprimer une habitude passée en confondant répétition et action ponctuelle.",
        "free",
      ),
      correction(
        "v3d-pci-3",
        "conjugaison",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Soudain, il pleuvait très fort. »",
        ["Soudain, il a plu très fort.", "Soudain, il plut très fort."],
        "'Soudain' introduit une action soudaine, ponctuelle → passé composé (il a plu) ou passé simple (il plut). L'imparfait ne convient pas pour une action déclenchée brutalement.",
        "Utiliser l'imparfait après 'soudain' en confondant durée et soudaineté.",
        "free",
      ),
      correction(
        "v3d-pci-4",
        "conjugaison",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Pendant qu'elle a lu, le téléphone sonnait. »",
        ["Pendant qu'elle lisait, le téléphone sonnait."],
        "'Pendant que' introduit deux actions simultanées de fond → les deux verbes sont à l'imparfait : elle lisait / le téléphone sonnait.",
        "Mettre le verbe de la principale ou de la subordonnée au passé composé en confondant action de fond et action ponctuelle.",
        "free",
      ),
      correction(
        "v3d-pci-5",
        "conjugaison",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Ce matin, il se promenait dans le parc. »",
        ["Ce matin, il s'est promené dans le parc."],
        "'Ce matin' situe l'action dans un cadre temporel délimité et révolu → passé composé : il s'est promené.",
        "Employer l'imparfait après 'ce matin' en l'associant à une durée sans percevoir le caractère achevé de l'action.",
        "free",
      ),
      qcm(
        "v3d-pci-6",
        "conjugaison",
        "Intermediaire",
        "Complétez : « Quand j'___ petit, j'habitais à Lyon. »",
        [
          { id: "a", label: "étais" },
          { id: "b", label: "ai été" },
          { id: "c", label: "fus" },
        ],
        "a",
        "La proposition exprime un état dans le passé (être petit) sur une durée non délimitée → imparfait : j'étais petit.",
        "Choisir le passé composé 'j'ai été' en confondant état durable et action ponctuelle.",
        "free",
      ),
      correction(
        "v3d-pci-7",
        "conjugaison",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Quand il a vu l'accident, il s'arrêtait. »",
        ["Quand il a vu l'accident, il s'est arrêté.", "Quand il vit l'accident, il s'arrêta.", "Quand il a vu l'accident, il s'arrêta."],
        "La vue de l'accident et l'arrêt sont deux actions ponctuelles et successives → passé composé (ou passé simple à l'écrit littéraire) pour les deux. L'imparfait 's'arrêtait' est incorrect ici car l'arrêt est un événement ponctuel, pas un état de fond.",
        "Employer l'imparfait pour le deuxième verbe en le percevant comme une action de fond alors qu'il s'agit d'une réaction ponctuelle.",
        "free",
      ),
      vraiFaux(
        "v3d-pci-8",
        "conjugaison",
        "Intermediaire",
        "L'imparfait exprime une action achevée à un moment précis du passé.",
        false,
        "L'imparfait exprime des états, des habitudes, des descriptions ou des actions de fond non délimitées. C'est le passé composé (ou le passé simple) qui exprime l'action achevée et ponctuelle.",
        "Confondre l'imparfait (durée, habitude) avec le passé composé (action achevée, ponctuelle).",
        "free",
      ),
      correction(
        "v3d-pci-9",
        "conjugaison",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Tous les matins, il s'est levé à six heures. »",
        ["Tous les matins, il se levait à six heures."],
        "'Tous les matins' exprime une habitude répétée → imparfait : il se levait.",
        "Employer le passé composé pour exprimer une habitude en confondant répétition et action accomplie unique.",
        "free",
      ),
      correction(
        "v3d-pci-10",
        "conjugaison",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Hier soir, nous regardions le film jusqu'à minuit. »",
        ["Hier soir, nous avons regardé le film jusqu'à minuit."],
        "'Hier soir… jusqu'à minuit' délimite clairement le début et la fin de l'action → action achevée → passé composé : nous avons regardé.",
        "Employer l'imparfait parce que regarder un film semble durer dans le temps, sans tenir compte de la délimitation temporelle explicite.",
        "free",
      ),
    ],
  }),

  // ─── Série 56 : Discours direct et indirect ─────────────────────────────────
  buildSession({
    id: "fr-v3d-serie-ddi",
    title: "Discours direct et indirect : correction d'erreurs",
    summary: "Corriger les erreurs de transposition du discours direct au discours indirect : concordance des temps, pronoms, adverbes.",
    objective: "Maîtriser les transformations syntaxiques et temporelles requises lors du passage au discours indirect.",
    introduction: "La transposition du discours direct en discours indirect mobilise plusieurs compétences : concordance des temps, changement de pronoms, transformation des adverbes de temps et de lieu. Savoir enseigner ces mécanismes est attendu au CRPE.",
    subdomain: "grammaire",
    topicKey: "discours_direct_indirect",
    topicLabel: "Discours direct et indirect",
    level: "Avance",
    exerciseTypeLabel: "Correction d'erreurs, QCM, vrai/faux",
    estimatedMinutes: 15,
    access_tier: "premium",
    recommendedOrder: 56,
    completionSummary: {
      skill: "Transposer correctement le discours direct en discours indirect",
      keyPoints: [
        "Concordance des temps : présent → imparfait, futur → conditionnel présent, passé composé → plus-que-parfait.",
        "Pronoms personnels et possessifs changent selon le locuteur.",
        "Adverbes temporels : aujourd'hui → ce jour-là, demain → le lendemain, hier → la veille.",
        "Élision obligatoire : que + il/elle → qu'il/qu'elle.",
      ],
      retryAdvice: "Repérez d'abord le verbe introducteur, puis appliquez systématiquement les changements de temps, pronoms et adverbes.",
    },
    questions: [
      correction(
        "v3d-ddi-1",
        "grammaire",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Il a dit qu'il viendra demain. »",
        ["Il a dit qu'il viendrait le lendemain."],
        "Le verbe introducteur 'a dit' est au passé → concordance des temps : futur simple → conditionnel présent (viendrait). L'adverbe 'demain' devient 'le lendemain' au discours indirect.",
        "Garder le futur simple 'viendra' et l'adverbe 'demain' sans appliquer la concordance des temps ni le changement d'adverbe.",
        "premium",
      ),
      correction(
        "v3d-ddi-2",
        "grammaire",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Elle m'a demandé si je veux venir. »",
        ["Elle m'a demandé si je voulais venir."],
        "Le verbe introducteur 'a demandé' est au passé → concordance : présent → imparfait (voulais).",
        "Garder le présent 'veux' sans appliquer la concordance des temps après un verbe introducteur au passé.",
        "premium",
      ),
      correction(
        "v3d-ddi-3",
        "grammaire",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Il déclara que il avait terminé son travail. »",
        ["Il déclara qu'il avait terminé son travail."],
        "Devant un mot commençant par une voyelle, la conjonction que s'élide en qu'. L'écriture 'que il' (sans élision) est une faute d'orthographe.",
        "Oublier l'élision de que devant une voyelle par inattention ou par calque de l'oral.",
        "premium",
      ),
      correction(
        "v3d-ddi-4",
        "grammaire",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Il m'a dit qu'il est fatigué. »",
        ["Il m'a dit qu'il était fatigué."],
        "Verbe introducteur au passé (a dit) → concordance : présent → imparfait (était fatigué).",
        "Conserver le présent 'est' au discours indirect après un verbe introducteur au passé.",
        "premium",
      ),
      correction(
        "v3d-ddi-5",
        "grammaire",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Elle lui a demandé s'il a faim. »",
        ["Elle lui a demandé s'il avait faim."],
        "Verbe introducteur au passé (a demandé) → concordance : présent → imparfait (avait faim).",
        "Ne pas appliquer la concordance des temps dans les interrogatives indirectes introduites par 'si'.",
        "premium",
      ),
      qcm(
        "v3d-ddi-6",
        "grammaire",
        "Avance",
        "Quelle est la meilleure transposition au discours indirect ? Direct : « Il a affirmé : \"Je suis content.\" »",
        [
          { id: "a", label: "Il a affirmé qu'il était content." },
          { id: "b", label: "Il a affirmé qu'il est content." },
          { id: "c", label: "Il a affirmé être content." },
        ],
        "a",
        "La forme canonique du discours indirect après un verbe au passé utilise la concordance des temps : présent → imparfait → 'il était content'. La forme c (infinitif) est possible quand sujet principal = sujet de la subordonnée, mais elle est moins explicite.",
        "Conserver le présent 'est' (réponse b) sans appliquer la concordance des temps.",
        "premium",
      ),
      correction(
        "v3d-ddi-7",
        "grammaire",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Le professeur a dit d'ouvrir vos livres. »",
        ["Le professeur leur a demandé d'ouvrir leurs livres."],
        "Au discours indirect, l'impératif se transforme en infinitif introduit par de. Le déterminant possessif vos (2e pers. plur.) doit devenir leurs (3e pers. plur.) pour s'accorder avec le changement de point de vue.",
        "Conserver 'vos' du discours direct sans adapter les déterminants possessifs au point de vue du narrateur.",
        "premium",
      ),
      correction(
        "v3d-ddi-8",
        "grammaire",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Il a dit qu'il partirait aujourd'hui. »",
        ["Il a dit qu'il partirait ce jour-là."],
        "Au discours indirect, 'aujourd'hui' (déictique temporel) se transforme en 'ce jour-là' pour maintenir la cohérence du point de vue narratif.",
        "Conserver 'aujourd'hui' sans transformer les déictiques temporels au discours indirect.",
        "premium",
      ),
      vraiFaux(
        "v3d-ddi-9",
        "grammaire",
        "Avance",
        "Au discours indirect, le verbe introducteur 'demander' introduit une question par la conjonction 'que'.",
        false,
        "Pour une question fermée (oui/non), 'demander' est suivi de 'si'. Pour une question ouverte (qui, quoi, où…), il est suivi de l'adverbe ou pronom interrogatif. Pour une injonction, 'demander' est suivi de 'de' + infinitif. La conjonction 'que' n'introduit pas de question.",
        "Utiliser 'que' après 'demander' par analogie avec les autres verbes déclaratifs.",
        "premium",
      ),
      correction(
        "v3d-ddi-10",
        "grammaire",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Elle a crié qu'elle reviendrai. »",
        ["Elle a crié qu'elle reviendrait."],
        "Verbe introducteur au passé (a crié) → concordance : futur simple → conditionnel présent (reviendrait). La terminaison -ai est celle du futur, pas du conditionnel (-ait).",
        "Écrire -ai (futur) au lieu de -ait (conditionnel présent) en oubliant la concordance des temps.",
        "premium",
      ),
    ],
  }),

  // ─── Série 57 : Tout et même ────────────────────────────────────────────────
  buildSession({
    id: "fr-v3d-serie-tout",
    title: "Tout et même : invariables ou accordés ?",
    summary: "Maîtriser les règles d'accord de 'tout' (adjectif vs adverbe) et de 'même' (adjectif vs adverbe) dans des phrases variées.",
    objective: "Distinguer les emplois de 'tout' et 'même' et appliquer les règles d'accord correspondantes.",
    introduction: "'Tout' et 'même' sont des mots polycatégoriels dont l'accord dépend de leur nature grammaticale dans la phrase. Ces cas sont régulièrement abordés en cycle 3 et constituent un point attendu au CRPE.",
    subdomain: "orthographe",
    topicKey: "tout_meme_accord",
    topicLabel: "Tout et même",
    level: "Avance",
    exerciseTypeLabel: "Correction d'erreurs, QCM, vrai/faux",
    estimatedMinutes: 14,
    access_tier: "premium",
    recommendedOrder: 57,
    completionSummary: {
      skill: "Accorder correctement 'tout' et 'même' selon leur nature grammaticale",
      keyPoints: [
        "Tout adjectif indéfini s'accorde : tous les hommes, toute la classe, toutes les filles.",
        "Tout adverbe (= entièrement) est invariable, SAUF devant un adjectif féminin commençant par une consonne ou un h aspiré : elle est toute petite, mais elle est tout émue.",
        "Même adjectif s'accorde : les mêmes résultats, elle-même → elles-mêmes.",
        "Même adverbe (= aussi, jusqu'à) est invariable : même les experts se trompent.",
      ],
      retryAdvice: "Pour 'tout' adverbe : vérifiez le genre de l'adjectif et sa première lettre. Pour 'même', demandez-vous s'il qualifie un nom (adjectif → accord) ou s'il renforce (adverbe → invariable).",
    },
    questions: [
      correction(
        "v3d-tout-c1",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Tout les filles sont venues. »",
        ["Toutes les filles sont venues."],
        "Tout est ici un adjectif indéfini déterminant (= la totalité de). Il s'accorde avec le nom féminin pluriel filles → toutes.",
        "Laisser tout invariable en le confondant avec un adverbe.",
        "premium",
      ),
      correction(
        "v3d-tout-c2",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Elles sont tout prêtes. »",
        ["Elles sont toutes prêtes."],
        "Tout qualifie ici un adjectif féminin pluriel (prêtes) qui commence par une consonne. L'adverbe tout prend la marque du féminin pluriel devant un adjectif féminin commençant par une consonne → toutes.",
        "Laisser tout invariable en croyant que l'adverbe est toujours invariable.",
        "premium",
      ),
      correction(
        "v3d-tout-c3",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Il est toute surpris. »",
        ["Il est tout surpris."],
        "Tout est un adverbe devant l'adjectif masculin singulier surpris → invariable : tout surpris.",
        "Accorder tout au féminin par attraction de la terminaison de l'adjectif.",
        "premium",
      ),
      correction(
        "v3d-tout-c4",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Elle est tout honteuse. »",
        ["Elle est toute honteuse."],
        "Tout est un adverbe devant l'adjectif féminin honteuse qui commence par une consonne → tout prend la marque du féminin → toute honteuse.",
        "Laisser tout invariable devant un adjectif féminin commençant par une consonne.",
        "premium",
      ),
      qcm(
        "v3d-tout-c5",
        "orthographe",
        "Avance",
        "Complétez : « Les enfants, ___ joyeux, chantaient. »",
        [
          { id: "a", label: "tout" },
          { id: "b", label: "toute" },
          { id: "c", label: "toutes" },
          { id: "d", label: "tous" },
        ],
        "d",
        "Tout est ici un adjectif indéfini apposé au nom masculin pluriel enfants → tous.",
        "Choisir tout (invariable) en confondant adjectif et adverbe.",
        "premium",
      ),
      correction(
        "v3d-tout-c6",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Mêmes les professeurs sont venus. »",
        ["Même les professeurs sont venus."],
        "Même est ici un adverbe de renforcement (= jusqu'à, y compris) → invariable : même les professeurs.",
        "Accorder même en -s en le confondant avec l'adjectif (les mêmes professeurs).",
        "premium",
      ),
      correction(
        "v3d-tout-c7",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Ils m'ont dit la mêmes chose. »",
        ["Ils m'ont dit la même chose."],
        "Même est ici un adjectif qualifiant le nom féminin singulier chose → la même chose (accord au féminin singulier, sans -s).",
        "Ajouter un -s à même en le confondant avec un pluriel.",
        "premium",
      ),
      correction(
        "v3d-tout-c8",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Elles sont venues elles-même. »",
        ["Elles sont venues elles-mêmes."],
        "Même accolé à un pronom personnel (elles-mêmes) s'accorde avec ce pronom → féminin pluriel → elles-mêmes.",
        "Laisser même invariable après un pronom personnel, en le traitant comme un adverbe.",
        "premium",
      ),
      qcm(
        "v3d-tout-c9",
        "orthographe",
        "Avance",
        "Complétez : « Elle est ___ émue par le discours. »",
        [
          { id: "a", label: "tout" },
          { id: "b", label: "toute" },
        ],
        "a",
        "Tout est un adverbe devant l'adjectif féminin émue. Mais émue commence par une voyelle (é) → l'adverbe tout reste invariable devant un adjectif féminin commençant par une voyelle ou un h muet : tout émue.",
        "Écrire toute en appliquant mécaniquement la règle du féminin devant consonne, sans vérifier la première lettre de l'adjectif.",
        "premium",
      ),
      vraiFaux(
        "v3d-tout-c10",
        "orthographe",
        "Avance",
        "L'adverbe 'tout' est toujours invariable devant un adjectif féminin commençant par une consonne.",
        false,
        "Devant un adjectif féminin commençant par une consonne ou un h aspiré, l'adverbe tout prend les marques du féminin (et du pluriel) pour des raisons euphoniques : toute petite, toutes petites. Il reste invariable devant une voyelle ou un h muet.",
        "Croire que tout adverbe est toujours invariable quelle que soit la situation.",
        "premium",
      ),
    ],
  }),

  // ─── Série 58 : Pronoms relatifs ────────────────────────────────────────────
  buildSession({
    id: "fr-v3d-serie-rel",
    title: "Pronoms relatifs : correction d'erreurs",
    summary: "Identifier et corriger les erreurs d'emploi des pronoms relatifs simples et composés : qui, que, dont, où, lequel…",
    objective: "Choisir le pronom relatif approprié selon la fonction de l'antécédent dans la relative.",
    introduction: "Les pronoms relatifs introduisent des propositions subordonnées relatives. Leur choix dépend de la fonction du pronom dans la relative (sujet, COD, complément de nom, complément circonstanciel…). Ce point grammatical est au programme du CM1-CM2.",
    subdomain: "grammaire",
    topicKey: "pronoms_relatifs",
    topicLabel: "Pronoms relatifs",
    level: "Intermediaire",
    exerciseTypeLabel: "Correction d'erreurs, QCM, vrai/faux",
    estimatedMinutes: 14,
    access_tier: "premium",
    recommendedOrder: 58,
    completionSummary: {
      skill: "Sélectionner le pronom relatif correct selon la fonction dans la subordonnée",
      keyPoints: [
        "Qui : sujet de la relative (le livre qui traîne).",
        "Que : COD de la relative (le livre que je lis).",
        "Dont : complément introduit par 'de' (le livre dont je parle).",
        "Où : complément de lieu ou de temps (la ville où j'habite).",
        "Lequel/laquelle… : après préposition pour les non-animés (le stylo avec lequel j'écris).",
      ],
      retryAdvice: "Identifiez la fonction du pronom dans la subordonnée relative, puis choisissez le pronom correspondant.",
    },
    questions: [
      correction(
        "v3d-rel-1",
        "grammaire",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Le livre qui j'ai lu est passionnant. »",
        ["Le livre que j'ai lu est passionnant."],
        "Dans la relative, le pronom relatif reprend 'le livre' en fonction de COD (j'ai lu quoi ? le livre) → que.",
        "Employer qui (sujet) à la place de que (COD) par manque d'analyse de la fonction.",
        "premium",
      ),
      correction(
        "v3d-rel-2",
        "grammaire",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « L'homme que je t'ai parlé est arrivé. »",
        ["L'homme dont je t'ai parlé est arrivé."],
        "Le verbe parler se construit avec de (parler de quelqu'un). Le pronom relatif remplaçant un complément en 'de' → dont.",
        "Employer que (COD) au lieu de dont (complément de nom ou de verbe en 'de').",
        "premium",
      ),
      correction(
        "v3d-rel-3",
        "grammaire",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « La ville que j'habite est belle. »",
        ["La ville où j'habite est belle."],
        "Habiter introduit un complément de lieu. Le pronom relatif de lieu → où.",
        "Employer que (COD) au lieu de où (lieu ou temps) par méconnaissance des pronoms relatifs de lieu.",
        "premium",
      ),
      correction(
        "v3d-rel-4",
        "grammaire",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « C'est le professeur que m'a appris le plus. »",
        ["C'est le professeur qui m'a appris le plus."],
        "Dans la relative, le pronom est sujet (qui fait l'action d'apprendre) → qui.",
        "Employer que (COD) au lieu de qui (sujet) en confondant les fonctions sujet et COD.",
        "premium",
      ),
      correction(
        "v3d-rel-5",
        "grammaire",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Voici le stylo avec qui j'ai écrit. »",
        ["Voici le stylo avec lequel j'ai écrit."],
        "L'antécédent stylo est un nom de chose. Après une préposition, on utilise lequel/laquelle/lesquels pour les non-animés, pas qui (réservé aux personnes).",
        "Employer qui après une préposition même pour un antécédent non-animé (chose).",
        "premium",
      ),
      qcm(
        "v3d-rel-6",
        "grammaire",
        "Intermediaire",
        "Complétez : « La maison ___ j'ai grandi se trouve à Lyon. »",
        [
          { id: "a", label: "que" },
          { id: "b", label: "où" },
          { id: "c", label: "dont" },
          { id: "d", label: "qui" },
        ],
        "b",
        "La maison est un lieu. Dans la relative, le pronom exprime le lieu où l'action se déroule → où.",
        "Choisir que (COD) en confondant le complément de lieu avec un COD.",
        "premium",
      ),
      correction(
        "v3d-rel-7",
        "grammaire",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Je connais l'enfant que le père est médecin. »",
        ["Je connais l'enfant dont le père est médecin."],
        "Le père de l'enfant : la relation est exprimée par 'de'. Le pronom relatif remplaçant un complément du nom en 'de' → dont.",
        "Employer que (COD) au lieu de dont (complément du nom) par méconnaissance de la valeur possessive de dont.",
        "premium",
      ),
      correction(
        "v3d-rel-8",
        "grammaire",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « Voilà ce que tu as besoin. »",
        ["Voilà ce dont tu as besoin."],
        "Avoir besoin de quelque chose : le pronom relatif remplace un complément introduit par 'de' → dont.",
        "Employer ce que (COD) au lieu de ce dont (complément en 'de') pour le verbe avoir besoin.",
        "premium",
      ),
      vraiFaux(
        "v3d-rel-9",
        "grammaire",
        "Intermediaire",
        "Le pronom relatif 'dont' remplace un complément introduit par la préposition 'de'.",
        true,
        "Dont remplace un groupe nominal précédé de 'de' : parler de quelqu'un (→ dont je parle), le père de quelqu'un (→ dont le père), avoir besoin de quelque chose (→ ce dont j'ai besoin).",
        "Croire que dont ne s'utilise que dans les compléments de nom, sans l'appliquer aux compléments de verbe en 'de'.",
        "premium",
      ),
      correction(
        "v3d-rel-10",
        "grammaire",
        "Intermediaire",
        "Corrige l'erreur dans cette phrase : « La personne à que j'ai parlé est partie. »",
        ["La personne à qui j'ai parlé est partie."],
        "Parler à quelqu'un : après la préposition à, l'antécédent est une personne → à qui.",
        "Employer à que (agrammatical) au lieu de à qui après la préposition à avec un antécédent humain.",
        "premium",
      ),
    ],
  }),

  // ─── Série 59 : Accord sujet-verbe complexes ────────────────────────────────
  buildSession({
    id: "fr-v3d-serie-asvc",
    title: "Accord sujet-verbe : cas complexes",
    summary: "Corriger les erreurs d'accord verbal dans les constructions où le sujet est éloigné, collectif ou indéfini.",
    objective: "Accorder correctement le verbe avec son sujet dans des cas complexes : chacun, la plupart, beaucoup de, tout le monde, ni l'un ni l'autre…",
    introduction: "L'accord sujet-verbe pose des difficultés dès que le sujet est éloigné, collectif ou indéfini. Ces cas constituent des questions fréquentes au CRPE et sont aussi à enseigner à partir du CM1.",
    subdomain: "orthographe",
    topicKey: "accord_sujet_verbe_complexe",
    topicLabel: "Accord sujet-verbe complexes",
    level: "Avance",
    exerciseTypeLabel: "Correction d'erreurs, QCM, vrai/faux",
    estimatedMinutes: 14,
    access_tier: "free",
    recommendedOrder: 59,
    completionSummary: {
      skill: "Accorder le verbe avec un sujet complexe ou indéfini",
      keyPoints: [
        "Chacun, tout le monde, on → singulier.",
        "La plupart de, beaucoup de, plusieurs + nom pluriel → pluriel.",
        "C'est moi/toi/lui qui → accord à la personne du pronom.",
        "Ni l'un ni l'autre → singulier (ou pluriel si les deux sont impliqués simultanément).",
      ],
      retryAdvice: "Identifiez le vrai sujet grammatical (noyau) et non le nom le plus proche du verbe.",
    },
    questions: [
      correction(
        "v3d-asvc-1",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Chacun des élèves ont répondu correctement. »",
        ["Chacun des élèves a répondu correctement."],
        "Le sujet grammatical est chacun (pronom indéfini singulier), pas 'des élèves' (complément du nom) → accord au singulier : a répondu.",
        "Accorder avec le nom le plus proche 'élèves' (pluriel) au lieu du vrai sujet 'chacun' (singulier).",
        "free",
      ),
      correction(
        "v3d-asvc-2",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « La plupart des étudiants a réussi. »",
        ["La plupart des étudiants ont réussi."],
        "La plupart de + nom pluriel → verbe au pluriel : la plupart des étudiants ont réussi.",
        "Accorder avec 'la plupart' (singulier apparent) au lieu du nom pluriel qui suit.",
        "free",
      ),
      correction(
        "v3d-asvc-3",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « C'est moi qui est responsable. »",
        ["C'est moi qui suis responsable."],
        "Dans 'c'est + pronom + qui', le verbe de la relative s'accorde avec le pronom : moi = 1re pers. sing. → suis.",
        "Accorder le verbe à la 3e personne du singulier par attraction de 'c'est'.",
        "free",
      ),
      correction(
        "v3d-asvc-4",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Beaucoup d'élèves a refusé de partir. »",
        ["Beaucoup d'élèves ont refusé de partir."],
        "Beaucoup de + nom pluriel → verbe au pluriel : ont refusé.",
        "Accorder avec 'beaucoup' (singulier apparent) au lieu du nom pluriel 'élèves'.",
        "free",
      ),
      correction(
        "v3d-asvc-5",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « L'un et l'autre est arrivé en retard. »",
        ["L'un et l'autre sont arrivés en retard."],
        "L'un et l'autre exprime une coordination → les deux sujets sont impliqués → accord au pluriel : sont arrivés.",
        "Accorder au singulier en confondant 'l'un et l'autre' avec 'l'un ou l'autre' (qui admet le singulier).",
        "free",
      ),
      qcm(
        "v3d-asvc-6",
        "orthographe",
        "Avance",
        "Complétez : « Tout le monde ___ content. »",
        [
          { id: "a", label: "sont" },
          { id: "b", label: "est" },
        ],
        "b",
        "Tout le monde est un sujet collectif singulier → accord au singulier : est content.",
        "Accorder au pluriel en associant 'tout le monde' à une idée de pluralité.",
        "free",
      ),
      correction(
        "v3d-asvc-7",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « C'est eux qui ont décidé. »",
        ["Ce sont eux qui ont décidé."],
        "Le présentatif c'est se transforme en ce sont devant un pronom personnel de la 3e personne du pluriel (eux, elles).",
        "Utiliser c'est au lieu de ce sont devant un pronom pluriel.",
        "free",
      ),
      qcm(
        "v3d-asvc-8",
        "orthographe",
        "Avance",
        "Complétez : « La moitié des élèves ___ absent(s). »",
        [
          { id: "a", label: "sont" },
          { id: "b", label: "est" },
        ],
        "a",
        "La moitié de + nom pluriel → le pluriel est privilégié quand on met l'accent sur les individus : la moitié des élèves sont absents. L'accord au singulier est aussi toléré mais moins courant.",
        "Accorder systématiquement avec 'la moitié' (singulier) sans tenir compte du nom pluriel qui suit.",
        "free",
      ),
      qcm(
        "v3d-asvc-9",
        "orthographe",
        "Avance",
        "Complétez : « Ni l'un ni l'autre n'___ venu. »",
        [
          { id: "a", label: "est" },
          { id: "b", label: "sont" },
        ],
        "a",
        "Ni l'un ni l'autre présente les deux sujets comme exclusifs l'un de l'autre → accord au singulier avec le plus proche ou accord de sens : n'est venu. Les deux formes sont attestées, mais le singulier est plus fréquent en français soutenu.",
        "Accorder au pluriel en associant deux sujets coordonnés par ni à une idée de pluralité.",
        "free",
      ),
      correction(
        "v3d-asvc-10",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Plusieurs élèves a déjà terminé. »",
        ["Plusieurs élèves ont déjà terminé."],
        "Plusieurs est un déterminant indéfini pluriel → accord au pluriel : plusieurs élèves ont terminé.",
        "Accorder au singulier en confondant 'plusieurs' avec un collectif singulier.",
        "free",
      ),
    ],
  }),

  // ─── Série 60 : Homophones avancés ──────────────────────────────────────────
  buildSession({
    id: "fr-v3d-serie-hom2",
    title: "Homophones avancés : correction d'erreurs",
    summary: "Distinguer et corriger les confusions entre homophones grammaticaux complexes : quand/quant/qu'en, davantage/d'avantage, près/prêt, quelque/quel que.",
    objective: "Maîtriser les homophones avancés pour produire et corriger des écrits soutenus.",
    introduction: "Au-delà des homophones de base, le français recèle des confusions plus subtiles que le candidat au CRPE doit maîtriser pour produire des écrits de qualité et enseigner avec rigueur.",
    subdomain: "orthographe",
    topicKey: "homophones_avances",
    topicLabel: "Homophones avancés",
    level: "Avance",
    exerciseTypeLabel: "Correction d'erreurs, QCM, vrai/faux",
    estimatedMinutes: 14,
    access_tier: "premium",
    recommendedOrder: 60,
    completionSummary: {
      skill: "Distinguer les homophones avancés par leur nature grammaticale et leur contexte",
      keyPoints: [
        "Quand = conjonction de temps (remplaçable par 'lorsque') ; quant = dans 'quant à' (préposition) ; qu'en = que + en.",
        "Davantage = adverbe (plus) ; d'avantage = de + nom (un avantage précis).",
        "Prêt (adjectif, = disposé à) vs près (préposition/adverbe, = à proximité).",
        "Quelque(s) (déterminant, accord) vs quel(le)(s) que (locution concessive, verbe être).",
      ],
      retryAdvice: "Pour chaque homophone, appliquez le test grammatical : remplacement, analyse de la nature et de la fonction.",
    },
    questions: [
      correction(
        "v3d-hom2-1",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Il est près à partir. »",
        ["Il est prêt à partir."],
        "Prêt est un adjectif attribut (= disposé à, disponible pour). Près est un adverbe ou préposition de lieu (= à proximité). Test : 'il est disposé à partir' → prêt.",
        "Confondre prêt (adjectif d'état) et près (adverbe/préposition de lieu) car ils sont homophones.",
        "premium",
      ),
      correction(
        "v3d-hom2-2",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Quand à moi, je préfère rester. »",
        ["Quant à moi, je préfère rester."],
        "Quant à est une locution prépositionnelle (= en ce qui concerne). Quand est une conjonction de temps (remplaçable par 'lorsque'). Test : 'lorsque à moi' est impossible → quant à.",
        "Écrire quand au lieu de quant dans la locution 'quant à' par méconnaissance de la graphie.",
        "premium",
      ),
      correction(
        "v3d-hom2-3",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Travaille d'avantage si tu veux réussir. »",
        ["Travaille davantage si tu veux réussir."],
        "Davantage est un adverbe de quantité (= plus). D'avantage = préposition de + nom avantage (un avantage précis). On ne peut pas parler d'un avantage ici → davantage.",
        "Écrire d'avantage (deux mots) en confondant l'adverbe davantage avec le groupe nominal 'd'un avantage'.",
        "premium",
      ),
      correction(
        "v3d-hom2-4",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Quel que peu nerveux, il attendait. »",
        ["Quelque peu nerveux, il attendait."],
        "Quelque peu est une locution adverbiale figée (= un peu). Quel que (deux mots) est une locution concessive suivie du verbe être au subjonctif (quel que soit le résultat).",
        "Écrire quel que au lieu de quelque dans la locution adverbiale quelque peu.",
        "premium",
      ),
      correction(
        "v3d-hom2-5",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Quant il fait beau, nous sortons. »",
        ["Quand il fait beau, nous sortons."],
        "Quand est une conjonction de temps (remplaçable par 'lorsque'). Quant appartient uniquement à la locution 'quant à'. Test : 'lorsqu'il fait beau' → quand.",
        "Confondre quand (conjonction de temps) et quant (locution prépositionnelle 'quant à').",
        "premium",
      ),
      correction(
        "v3d-hom2-6",
        "orthographe",
        "Avance",
        "Corrige l'erreur dans cette phrase : « Il y a peut de chances. »",
        ["Il y a peu de chances."],
        "Peu est un adverbe de quantité. Peut est le verbe pouvoir conjugué (il peut). Test : 'il y a il peut de chances' est impossible → peu.",
        "Écrire peut (verbe) au lieu de peu (adverbe) par méconnaissance de la nature grammaticale.",
        "premium",
      ),
      qcm(
        "v3d-hom2-7",
        "orthographe",
        "Avance",
        "Quelle est la forme correcte pour l'inversion interrogative de 'je peux' ?",
        [
          { id: "a", label: "Puis-je" },
          { id: "b", label: "Peux-je" },
        ],
        "a",
        "Je peux → inversion interrogative : puis-je (forme spéciale issue du latin possum). Peux-je est agrammatical. On utilise 'puis-je' pour l'inversion sujet-verbe à la 1re personne du singulier.",
        "Former l'inversion de 'je peux' en peux-je par analogie avec les autres personnes.",
        "premium",
      ),
      qcm(
        "v3d-hom2-8",
        "orthographe",
        "Avance",
        "Complétez : « ___ la fin du mois, tout sera réglé. »",
        [
          { id: "a", label: "Quand" },
          { id: "b", label: "Quant" },
          { id: "c", label: "Qu'en" },
        ],
        "b",
        "Quant à la fin du mois est une locution prépositionnelle (= en ce qui concerne / d'ici). Test : 'lorsque la fin du mois' changerait le sens → quant à.",
        "Choisir quand (conjonction de temps) au lieu de quant (locution prépositionnelle) en confondant les deux homophones.",
        "premium",
      ),
      qcm(
        "v3d-hom2-9",
        "orthographe",
        "Avance",
        "Complétez : « Elle travaille ___ que lui. »",
        [
          { id: "a", label: "d'avantage" },
          { id: "b", label: "davantage" },
        ],
        "b",
        "Davantage est un adverbe de comparaison (= plus). D'avantage = préposition de + nom avantage. Ici, on compare des quantités de travail → adverbe → davantage.",
        "Écrire d'avantage (deux mots) en confondant l'adverbe de comparaison avec un groupe nominal.",
        "premium",
      ),
      vraiFaux(
        "v3d-hom2-10",
        "orthographe",
        "Avance",
        "Dans « Il est prêt », le mot 'prêt' est un adverbe de lieu.",
        false,
        "Prêt (avec accent circonflexe) est un adjectif qualificatif (attribut du sujet : il est prêt = disposé à agir). C'est près (sans accent) qui est un adverbe ou préposition de lieu (= à proximité). Les deux mots sont homophones mais n'ont pas la même nature ni le même sens.",
        "Confondre prêt (adjectif) et près (adverbe de lieu) ou attribuer la fonction d'adverbe à prêt.",
        "premium",
      ),
    ],
  }),
];
