import { ExerciseRecord, RevisionSession } from "@/types/domain";

const createdAt = "2026-03-20T08:00:00.000Z";

type QuestionInput = Omit<
  ExerciseRecord,
  "subject" | "validation_status" | "source" | "is_published" | "created_at" | "updated_at"
>;

type SessionInput = Omit<RevisionSession, "questionCount">;

function question(data: QuestionInput): ExerciseRecord {
  return {
    subject: "Francais",
    validation_status: "valide",
    source: "Serie CRPE Francais V3",
    is_published: true,
    created_at: createdAt,
    updated_at: createdAt,
    common_mistake: null,
    ...data,
  };
}

function buildSession(data: SessionInput): RevisionSession {
  return { ...data, questionCount: data.questions.length };
}

function qcm(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  choices: Array<{ id: string; label: string }>,
  value: string,
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
) {
  return question({
    id,
    subdomain,
    level,
    exercise_type: "qcm",
    instruction,
    support_text: null,
    choices,
    expected_answer: { mode: "single_choice", value },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
    topic_key: null,
    topic_label: null,
  });
}

function vraiFaux(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  value: boolean,
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
) {
  return question({
    id,
    subdomain,
    level,
    exercise_type: "vrai_faux",
    instruction,
    support_text: null,
    choices: [{ id: "true", label: "Vrai" }, { id: "false", label: "Faux" }],
    expected_answer: { mode: "boolean", value },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
    topic_key: null,
    topic_label: null,
  });
}

function reponseCourte(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  acceptableAnswers: string[],
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
  exercise_type: ExerciseRecord["exercise_type"] = "reponse_courte",
  support_text: string | null = null,
) {
  return question({
    id,
    subdomain,
    level,
    exercise_type,
    instruction,
    support_text,
    choices: null,
    expected_answer: { mode: "text", acceptableAnswers },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
    topic_key: null,
    topic_label: null,
  });
}

export const seriesV3BatchH: RevisionSession[] = [
  // ─── Serie 1 : Hyperonymie, hyponymie et relations semantiques ───
  buildSession({
    id: "fr-v3-serie-hyperonymie-hyponymie",
    title: "Hyperonymie, hyponymie et relations semantiques",
    summary: "Identifier les relations d'inclusion semantique entre mots generiques (hyperonymes) et mots specifiques (hyponymes).",
    objective: "Maitriser les notions d'hyperonymie et d'hyponymie pour enrichir le vocabulaire et faciliter la reformulation.",
    introduction:
      "En lexique, les mots s'organisent en reseaux hierarchiques : un hyperonyme est un mot de sens general qui englobe des mots plus precis, les hyponymes. Savoir reperer ces relations aide les eleves a reformuler, a classer et a mieux comprendre les textes.",
    subdomain: "lexique",
    topicKey: "hyperonymie_hyponymie",
    topicLabel: "Hyperonymie, hyponymie et relations semantiques",
    level: "Intermediaire",
    exerciseTypeLabel: "QCM, Vrai/Faux, Reponse courte",
    estimatedMinutes: 12,
    access_tier: "free",
    recommendedOrder: 37,
    completionSummary: {
      skill: "Identifier hyperonymes et hyponymes dans un ensemble lexical",
      keyPoints: [
        "L'hyperonyme est le mot generique qui englobe les autres (animal englobe chat, chien, oiseau).",
        "L'hyponyme est le mot specifique inclus dans le sens de l'hyperonyme (tulipe est hyponyme de fleur).",
        "Cette relation d'inclusion semantique est essentielle pour la reformulation et l'enrichissement du vocabulaire.",
      ],
      retryAdvice:
        "Posez-vous toujours la question : lequel des deux mots inclut l'autre ? Le mot qui inclut est l'hyperonyme.",
    },
    questions: [
      qcm(
        "v3h-hh-1",
        "lexique",
        "Intermediaire",
        "Quel terme designe un mot de sens general qui englobe d'autres mots de sens plus precis ?",
        [
          { id: "a", label: "Synonyme" },
          { id: "b", label: "Hyperonyme" },
          { id: "c", label: "Hyponyme" },
          { id: "d", label: "Antonyme" },
        ],
        "b",
        "L'hyperonyme est le mot generique qui inclut semantiquement d'autres mots plus specifiques. Par exemple, \"animal\" est l'hyperonyme de \"chat\", \"chien\" et \"oiseau\". Cette relation d'inclusion est au coeur de l'organisation hierarchique du lexique. Ne pas confondre avec le synonyme, qui designe un mot de sens proche et interchangeable dans certains contextes.",
        "Confondre hyperonyme et synonyme en pensant que le mot generique est simplement un equivalent du mot specifique.",
        "free",
      ),
      qcm(
        "v3h-hh-2",
        "lexique",
        "Intermediaire",
        "Dans la liste suivante, lequel est l'hyperonyme des autres : chaise, meuble, table, armoire ?",
        [
          { id: "a", label: "Chaise" },
          { id: "b", label: "Table" },
          { id: "c", label: "Meuble" },
          { id: "d", label: "Armoire" },
        ],
        "c",
        "\"Meuble\" est le terme generique qui englobe \"chaise\", \"table\" et \"armoire\". Chacun de ces trois mots est un hyponyme de \"meuble\" car il designe un type particulier de meuble. L'hyperonyme se reconnait au fait qu'il peut remplacer chacun des autres mots dans un contexte general sans perte de verite logique (une chaise est un meuble).",
        "Choisir le mot le plus courant plutot que le mot le plus englobant.",
        "free",
      ),
      vraiFaux(
        "v3h-hh-3",
        "lexique",
        "Intermediaire",
        "Vrai ou faux : \"rose\" est un hyperonyme de \"fleur\".",
        false,
        "C'est l'inverse : \"fleur\" est l'hyperonyme de \"rose\". La rose est un type particulier de fleur, donc \"rose\" est l'hyponyme de \"fleur\". L'hyperonyme est toujours le terme le plus general, celui qui englobe l'autre. On peut dire \"une rose est une fleur\" mais pas \"une fleur est une rose\".",
        "Inverser le sens de la relation d'inclusion en ne verifiant pas quel mot englobe l'autre.",
        "free",
      ),
      qcm(
        "v3h-hh-4",
        "lexique",
        "Intermediaire",
        "Parmi ces mots, lequel est un hyponyme de \"vehicule\" ?",
        [
          { id: "a", label: "Transport" },
          { id: "b", label: "Deplacement" },
          { id: "c", label: "Camionnette" },
          { id: "d", label: "Mobilite" },
        ],
        "c",
        "\"Camionnette\" est un hyponyme de \"vehicule\" car c'est un type specifique de vehicule. Les mots \"transport\", \"deplacement\" et \"mobilite\" appartiennent au meme champ lexical mais ne sont pas des hyponymes de \"vehicule\" : ce ne sont pas des types de vehicules. L'hyponyme doit pouvoir s'inscrire dans la phrase \"X est un type de Y\".",
        "Confondre champ lexical et relation d'hyponymie : tous les mots lies au theme ne sont pas forcement des hyponymes.",
        "free",
      ),
      reponseCourte(
        "v3h-hh-5",
        "lexique",
        "Intermediaire",
        "Quel est l'hyperonyme commun a \"pomme\", \"banane\" et \"cerise\" ?",
        ["fruit", "fruits", "un fruit"],
        "\"Fruit\" est l'hyperonyme qui englobe \"pomme\", \"banane\" et \"cerise\". Chacun de ces mots designe un type particulier de fruit. En classe, cette relation d'inclusion aide les eleves a organiser le vocabulaire en categories et a enrichir leurs productions ecrites par des reformulations plus generales ou plus precises.",
        "Repondre par un mot du meme niveau (par exemple \"orange\") au lieu de chercher le terme englobant.",
        "free",
      ),
      vraiFaux(
        "v3h-hh-6",
        "lexique",
        "Intermediaire",
        "Vrai ou faux : la relation hyperonyme/hyponyme est une relation d'inclusion semantique.",
        true,
        "L'hyperonymie et l'hyponymie reposent bien sur une relation d'inclusion semantique : le sens de l'hyponyme est inclus dans celui de l'hyperonyme. Dire que \"chat\" est hyponyme de \"animal\" revient a dire que le sens de \"chat\" inclut tous les traits semantiques de \"animal\" plus des traits specifiques. Cette relation structure l'organisation hierarchique du lexique.",
        "Confondre inclusion semantique et synonymie, qui est une relation d'equivalence et non d'inclusion.",
        "free",
      ),
      qcm(
        "v3h-hh-7",
        "lexique",
        "Intermediaire",
        "Comment appelle-t-on les mots \"guitare\", \"piano\" et \"violon\" par rapport au mot \"instrument de musique\" ?",
        [
          { id: "a", label: "Des synonymes" },
          { id: "b", label: "Des hyponymes" },
          { id: "c", label: "Des hyperonymes" },
          { id: "d", label: "Des antonymes" },
        ],
        "b",
        "\"Guitare\", \"piano\" et \"violon\" sont des hyponymes de \"instrument de musique\". Ils designent des types specifiques inclus dans la categorie plus generale. Ensemble, ils forment des co-hyponymes, c'est-a-dire des mots qui partagent le meme hyperonyme. Cette terminologie est celle preconisee par les programmes officiels (Eduscol 2021).",
        "Repondre synonymes en pensant que les mots designant des objets similaires sont des synonymes.",
        "free",
      ),
      reponseCourte(
        "v3h-hh-8",
        "lexique",
        "Intermediaire",
        "Donnez un hyponyme du mot \"arbre\".",
        ["chene", "sapin", "bouleau", "erable", "pin", "olivier", "platane", "peuplier", "hetre", "frene", "tilleul", "noyer", "pommier", "cerisier", "poirier", "prunier"],
        "Tout nom d'essence d'arbre est un hyponyme correct : chene, sapin, bouleau, erable, etc. L'hyponyme doit designer un type specifique d'arbre, c'est-a-dire un mot dont le sens est inclus dans celui de \"arbre\". Un mot comme \"foret\" ne conviendrait pas car une foret n'est pas un type d'arbre mais un ensemble d'arbres.",
        "Proposer un mot du champ lexical de l'arbre (branche, racine, foret) qui n'est pas un type d'arbre.",
        "free",
      ),
      vraiFaux(
        "v3h-hh-9",
        "lexique",
        "Intermediaire",
        "Vrai ou faux : \"mammifere\" est un hyponyme de \"chat\".",
        false,
        "C'est l'inverse : \"mammifere\" est un hyperonyme de \"chat\" car il designe une categorie plus large qui inclut le chat. Le chat est un type de mammifere, donc \"chat\" est l'hyponyme et \"mammifere\" l'hyperonyme. La relation d'inclusion va toujours du specifique (hyponyme) vers le general (hyperonyme).",
        "Inverser la hierarchie en confondant le mot englobant et le mot inclus.",
        "free",
      ),
      qcm(
        "v3h-hh-10",
        "lexique",
        "Intermediaire",
        "Quel interet pedagogique principal presente le travail sur l'hyperonymie et l'hyponymie en classe de francais ?",
        [
          { id: "a", label: "Ameliorer uniquement l'orthographe" },
          { id: "b", label: "Aider a la reformulation et a l'enrichissement du vocabulaire" },
          { id: "c", label: "Travailler exclusivement la conjugaison" },
          { id: "d", label: "Apprendre les regles de ponctuation" },
        ],
        "b",
        "Le travail sur l'hyperonymie et l'hyponymie aide directement les eleves a reformuler (remplacer un mot precis par un terme general ou inversement), a eviter les repetitions et a enrichir leur vocabulaire. En lecture, savoir identifier l'hyperonyme permet de comprendre des reprises anaphoriques (\"le felin\" pour reprendre \"le chat\"). C'est un levier majeur pour la comprehension et la production d'ecrits.",
        "Reduire l'interet de ces notions a un simple exercice de classement sans voir l'impact sur la comprehension et la production.",
        "free",
      ),
    ],
  }),

  // ─── Serie 2 : Familles de mots (base, radical, racine) ───
  buildSession({
    id: "fr-v3-serie-familles-de-mots",
    title: "Familles de mots (base, radical, racine)",
    summary: "Comprendre la formation des familles de mots en distinguant base, radical et racine selon la terminologie Eduscol.",
    objective: "Maitriser les notions de base, radical et racine pour analyser la formation des mots et identifier les familles lexicales.",
    introduction:
      "Une famille de mots regroupe les mots partageant un meme radical. Mais attention : les programmes officiels distinguent la base (mot de depart pour la derivation), le radical (forme prise par la base avec un affixe) et la racine (element etymologique, souvent latin ou grec). Ces distinctions sont essentielles au CRPE.",
    subdomain: "lexique",
    topicKey: "familles_de_mots",
    topicLabel: "Familles de mots (base, radical, racine)",
    level: "Intermediaire",
    exerciseTypeLabel: "QCM, Vrai/Faux, Reponse courte",
    estimatedMinutes: 12,
    access_tier: "free",
    recommendedOrder: 38,
    completionSummary: {
      skill: "Analyser la formation des mots et identifier les familles lexicales",
      keyPoints: [
        "La base est le mot servant de point de depart a la derivation (nation est la base de national).",
        "Le radical est la forme que prend la base en construction avec un affixe (chant- dans chanteur).",
        "La racine est l'element etymologique, souvent latin ou grec (cor, cordis pour coeur, cardiaque, cordial).",
      ],
      retryAdvice:
        "Pour chaque mot, demandez-vous : quel est le mot de depart (base) ? quelle forme prend-il avec les affixes (radical) ? et d'ou vient-il etymologiquement (racine) ?",
    },
    questions: [
      qcm(
        "v3h-fm-1",
        "lexique",
        "Intermediaire",
        "Selon la terminologie Eduscol, comment appelle-t-on le mot qui sert de point de depart a la derivation ?",
        [
          { id: "a", label: "Le radical" },
          { id: "b", label: "La racine" },
          { id: "c", label: "La base" },
          { id: "d", label: "Le prefixe" },
        ],
        "c",
        "La base est le mot qui sert de point de depart a la derivation. Par exemple, \"nation\" est la base de \"national\", \"nationaliser\", \"nationalite\". Il ne faut pas confondre la base avec le radical, qui est la forme que prend la base lorsqu'elle se combine avec un affixe, ni avec la racine, qui est l'element etymologique d'origine latine ou grecque.",
        "Confondre base et radical en utilisant les deux termes comme synonymes.",
        "free",
      ),
      vraiFaux(
        "v3h-fm-2",
        "lexique",
        "Intermediaire",
        "Vrai ou faux : les mots \"coeur\", \"cardiaque\", \"cordial\" et \"cordialite\" appartiennent a la meme famille de mots.",
        true,
        "Ces quatre mots partagent la meme racine latine cor, cordis (le coeur). Ils forment une famille de mots dite savante car ils sont relies par une racine etymologique greco-latine plutot que par un radical francais evident. \"Coeur\" est la forme populaire, tandis que \"cardiaque\" vient du grec kardia et \"cordial\" du latin cordialis. La famille de mots se definit comme l'ensemble des mots partageant un meme radical.",
        "Penser que des mots de forme tres differente ne peuvent pas appartenir a la meme famille.",
        "free",
      ),
      qcm(
        "v3h-fm-3",
        "lexique",
        "Intermediaire",
        "Dans le mot \"chanteur\", quelle est la forme du radical ?",
        [
          { id: "a", label: "Chant" },
          { id: "b", label: "Chante" },
          { id: "c", label: "Chanteur" },
          { id: "d", label: "-eur" },
        ],
        "a",
        "Le radical est la forme que prend la base en construction avec un affixe. Dans \"chanteur\", le radical est \"chant-\" auquel s'ajoute le suffixe \"-eur\". La base est le verbe \"chanter\", mais quand il entre en derivation, c'est la forme \"chant-\" qui apparait. Le suffixe \"-eur\" n'est pas le radical mais l'affixe qui s'y ajoute.",
        "Repondre \"chanteur\" en prenant le mot entier pour le radical au lieu d'isoler la partie commune.",
        "free",
      ),
      reponseCourte(
        "v3h-fm-4",
        "lexique",
        "Intermediaire",
        "Comment appelle-t-on l'element etymologique d'origine latine ou grecque a partir duquel se sont formes des mots en francais ?",
        ["racine", "la racine"],
        "La racine est l'element etymologique, souvent d'origine latine ou grecque, qui se retrouve dans plusieurs mots francais. Par exemple, la racine latine spir- (souffle) se retrouve dans \"respirer\", \"inspirer\", \"expirer\", \"aspirer\". Contrairement a la base (mot de depart en francais) et au radical (forme du mot avec un affixe), la racine renvoie a l'etymologie et permet d'expliquer les familles dites savantes.",
        "Repondre radical ou base sans faire la distinction avec l'element etymologique.",
        "free",
      ),
      qcm(
        "v3h-fm-5",
        "lexique",
        "Intermediaire",
        "Quelle est la base dans la serie \"terrasse, terrain, terrestre, enterrer\" ?",
        [
          { id: "a", label: "Terr-" },
          { id: "b", label: "Terre" },
          { id: "c", label: "Terra" },
          { id: "d", label: "Enterrer" },
        ],
        "b",
        "La base est le mot \"terre\", c'est-a-dire le mot existant en francais qui sert de point de depart a la derivation. \"Terr-\" est le radical, la forme que prend la base quand elle se combine avec des affixes. \"Terra\" est la racine latine. La distinction base/radical/racine est un point cle de la terminologie Eduscol 2021 pour le CRPE.",
        "Confondre la base (mot complet) avec le radical (forme tronquee servant a la derivation).",
        "free",
      ),
      vraiFaux(
        "v3h-fm-6",
        "lexique",
        "Intermediaire",
        "Vrai ou faux : une famille de mots savante est une famille dont les membres sont relies par une racine greco-latine.",
        true,
        "Les familles savantes sont effectivement reliees par une racine etymologique greco-latine. Par exemple, la racine grecque graph- (ecrire) relie \"graphie\", \"orthographe\", \"calligraphie\", \"biographie\". Ces mots ne partagent pas un radical francais evident mais un element etymologique commun. A l'inverse, une famille populaire repose sur un radical francais reconnaissable (chant-, dans chanter, chanteur, chanson).",
        "Penser que savant signifie simplement difficile ou rare, sans lien avec l'etymologie greco-latine.",
        "free",
      ),
      qcm(
        "v3h-fm-7",
        "lexique",
        "Intermediaire",
        "Dans la famille du mot \"voir\", quel mot releve d'une formation savante a partir de la racine latine vid- (voir) ?",
        [
          { id: "a", label: "Revoir" },
          { id: "b", label: "Visible" },
          { id: "c", label: "Voyant" },
          { id: "d", label: "Vue" },
        ],
        "b",
        "\"Visible\" est forme sur la racine latine vid- (videre = voir) avec le suffixe \"-ible\". C'est une formation savante. En revanche, \"revoir\", \"voyant\" et \"vue\" sont des formations populaires construites sur la base francaise \"voir\" avec des affixes courants. Reconnaitre cette double filiation (populaire et savante) est important pour comprendre les familles de mots au CRPE.",
        "Ne pas reperer la racine latine vid- dans \"visible\" et le classer comme un mot sans rapport avec \"voir\".",
        "free",
      ),
      reponseCourte(
        "v3h-fm-8",
        "lexique",
        "Intermediaire",
        "Quel est le radical commun aux mots \"fleuriste\", \"fleurir\" et \"defleurir\" ?",
        ["fleur", "fleur-"],
        "Le radical commun est \"fleur-\", la forme que prend la base \"fleur\" en construction avec les differents affixes : le suffixe \"-iste\" (fleuriste), le suffixe \"-ir\" (fleurir) et le prefixe \"de-\" (defleurir). On retrouve cette forme stable dans tous les mots derives, ce qui permet de les regrouper en une meme famille lexicale.",
        "Repondre \"fleurir\" (un mot derive) au lieu d'isoler le radical commun a tous les membres de la famille.",
        "free",
      ),
      vraiFaux(
        "v3h-fm-9",
        "lexique",
        "Intermediaire",
        "Vrai ou faux : \"aquatique\" et \"eau\" appartiennent a la meme famille de mots malgre des formes tres differentes.",
        true,
        "\"Eau\" et \"aquatique\" appartiennent bien a la meme famille de mots. \"Eau\" est issu de la forme populaire du latin aqua, tandis que \"aquatique\" conserve la racine latine aqua- sous sa forme savante. C'est un cas typique de doublet populaire/savant dans une meme famille. D'autres mots de cette famille savante incluent \"aquarium\", \"aquarelle\", \"aqueduc\".",
        "Exclure les mots de forme tres differente d'une meme famille en oubliant les racines etymologiques.",
        "free",
      ),
      qcm(
        "v3h-fm-10",
        "lexique",
        "Intermediaire",
        "Parmi ces ensembles, lequel constitue une veritable famille de mots (mots partageant un meme radical) ?",
        [
          { id: "a", label: "Mer, marin, maritime, amerrir" },
          { id: "b", label: "Mer, bleu, vague, sable" },
          { id: "c", label: "Mer, mere, maire, amer" },
          { id: "d", label: "Mer, eau, lac, riviere" },
        ],
        "a",
        "Seule la serie \"mer, marin, maritime, amerrir\" constitue une famille de mots : tous partagent le radical \"mer-/mar-\" issu du latin mare. La serie B (mer, bleu, vague, sable) forme un champ lexical (mots lies au theme de la mer dans un texte) mais pas une famille morphologique. La serie C regroupe des homophones sans lien de radical. La serie D rassemble des hyponymes de \"etendue d'eau\".",
        "Confondre famille de mots (lien morphologique par le radical) et champ lexical (lien thematique dans un texte).",
        "free",
      ),
    ],
  }),

  // ─── Serie 3 : Sens figure et evolution semantique ───
  buildSession({
    id: "fr-v3-serie-sens-figure-evolution",
    title: "Sens figure et evolution semantique",
    summary: "Comprendre les mecanismes du sens figure (metaphore, metonymie) et les processus d'evolution semantique (extension, restriction, polysemie).",
    objective: "Distinguer denotation et connotation, identifier les differents types de sens figure et analyser l'evolution du sens des mots.",
    introduction:
      "Les mots n'ont pas un sens fige : ils evoluent par metaphore, metonymie, extension ou restriction. Comprendre ces mecanismes est essentiel pour enseigner la comprehension en lecture et pour distinguer polysemie (un meme mot avec plusieurs sens lies) et homonymie (des mots differents de meme forme).",
    subdomain: "lexique",
    topicKey: "sens_figure_evolution",
    topicLabel: "Sens figure et evolution semantique",
    level: "Avance",
    exerciseTypeLabel: "QCM, Vrai/Faux, Reponse courte",
    estimatedMinutes: 14,
    access_tier: "premium",
    recommendedOrder: 39,
    completionSummary: {
      skill: "Analyser les mecanismes du sens figure et l'evolution semantique des mots",
      keyPoints: [
        "La denotation est le sens objectif et referentiel du mot ; la connotation porte les valeurs subjectives, affectives ou culturelles.",
        "La metaphore repose sur une ressemblance (pied de la montagne), la metonymie sur une contiguite (boire un verre).",
        "La polysemie (un meme mot avec plusieurs sens lies) se distingue de l'homonymie (mots differents de meme forme).",
      ],
      retryAdvice:
        "Pour chaque emploi figure, cherchez le lien avec le sens premier : ressemblance (metaphore) ou contiguite (metonymie).",
    },
    questions: [
      qcm(
        "v3h-sfe-1",
        "lexique",
        "Avance",
        "Comment appelle-t-on le sens objectif et referentiel d'un mot, par opposition a ses valeurs subjectives ou affectives ?",
        [
          { id: "a", label: "La connotation" },
          { id: "b", label: "La denotation" },
          { id: "c", label: "La polysemie" },
          { id: "d", label: "L'homonymie" },
        ],
        "b",
        "La denotation designe le sens objectif, referentiel d'un mot, celui qu'on trouve dans le dictionnaire. Par exemple, la denotation de \"rouge\" est la couleur situee entre l'orange et le violet dans le spectre lumineux. La connotation, en revanche, porte les valeurs subjectives, affectives ou culturelles associees au mot (\"rouge\" connote la passion, le danger, la revolution selon les contextes).",
        "Confondre denotation et connotation en pensant que la definition du dictionnaire inclut les valeurs affectives.",
        "premium",
      ),
      qcm(
        "v3h-sfe-2",
        "lexique",
        "Avance",
        "Dans l'expression \"le pied de la montagne\", quel mecanisme semantique est a l'oeuvre ?",
        [
          { id: "a", label: "Une metonymie" },
          { id: "b", label: "Une extension de sens" },
          { id: "c", label: "Une metaphore" },
          { id: "d", label: "Une restriction de sens" },
        ],
        "c",
        "\"Le pied de la montagne\" est une metaphore : le mot \"pied\" est employe par analogie de forme et de position avec le pied du corps humain (la partie la plus basse). La metaphore repose toujours sur une ressemblance entre le sens premier et le sens figure. Ce n'est pas une metonymie (qui reposerait sur un rapport de contiguite) ni une extension de sens (qui elargirait la categorie de referents).",
        "Repondre metonymie en confondant le rapport de ressemblance (metaphore) avec le rapport de contiguite (metonymie).",
        "premium",
      ),
      vraiFaux(
        "v3h-sfe-3",
        "lexique",
        "Avance",
        "Vrai ou faux : dans \"boire un verre\", le mot \"verre\" est employe par metonymie.",
        true,
        "C'est bien une metonymie : on designe le contenu (la boisson) par le contenant (le verre). La metonymie repose sur un rapport de contiguite — ici, le verre et la boisson sont physiquement lies (l'un contient l'autre). Ce n'est pas une metaphore car il n'y a pas de rapport de ressemblance entre le verre et la boisson, mais un rapport de proximite spatiale ou logique.",
        "Dire que c'est une metaphore en ne distinguant pas ressemblance (metaphore) et contiguite (metonymie).",
        "premium",
      ),
      qcm(
        "v3h-sfe-4",
        "lexique",
        "Avance",
        "Le mot \"viande\" designait autrefois toute nourriture, puis s'est restreint a la chair animale. Quel processus semantique est a l'oeuvre ?",
        [
          { id: "a", label: "Une extension de sens" },
          { id: "b", label: "Une metaphore" },
          { id: "c", label: "Une restriction de sens" },
          { id: "d", label: "Une metonymie" },
        ],
        "c",
        "Le mot \"viande\" illustre une restriction de sens : son sens s'est retreci au fil du temps, passant de \"toute nourriture\" (du latin vivenda, ce qui sert a vivre) au sens actuel de \"chair animale destinee a l'alimentation\". La restriction de sens reduit le nombre de referents possibles. C'est l'inverse de l'extension de sens, qui elargit la portee du mot.",
        "Confondre restriction et extension de sens en ne verifiant pas si le sens s'est elargi ou retreci.",
        "premium",
      ),
      reponseCourte(
        "v3h-sfe-5",
        "lexique",
        "Avance",
        "Comment appelle-t-on le fait qu'un meme mot possede plusieurs sens lies entre eux (par exemple \"souris\" designant le rongeur et le peripherique informatique) ?",
        ["polysemie", "la polysemie"],
        "La polysemie designe le fait qu'un meme mot possede plusieurs sens lies entre eux. \"Souris\" (rongeur) et \"souris\" (peripherique informatique) sont deux sens d'un meme mot, relies par une metaphore de forme. Il ne faut pas confondre avec l'homonymie, qui concerne des mots differents ayant la meme forme par hasard historique (\"mousse\" la plante et \"mousse\" le marin n'ont aucun lien semantique).",
        "Repondre homonymie en ne percevant pas le lien semantique entre les differents sens du mot.",
        "premium",
      ),
      qcm(
        "v3h-sfe-6",
        "lexique",
        "Avance",
        "Quelle est la difference fondamentale entre polysemie et homonymie ?",
        [
          { id: "a", label: "La polysemie concerne les mots rares, l'homonymie les mots courants" },
          { id: "b", label: "La polysemie releve d'un meme mot avec des sens lies, l'homonymie de mots differents de meme forme" },
          { id: "c", label: "La polysemie est orale, l'homonymie est ecrite" },
          { id: "d", label: "Il n'y a aucune difference, les deux termes sont synonymes" },
        ],
        "b",
        "La distinction est essentielle : la polysemie concerne un meme mot dont les differents sens sont relies par un lien semantique (metaphore, metonymie, extension). L'homonymie concerne des mots differents qui ont la meme forme (graphique ou phonique) par hasard historique, sans lien de sens. Par exemple, \"avocat\" (fruit) et \"avocat\" (juriste) sont des homonymes ; \"feuille\" (d'arbre) et \"feuille\" (de papier) relevent de la polysemie (lien metaphorique de forme).",
        "Traiter polysemie et homonymie comme synonymes ou croire que la distinction est arbitraire.",
        "premium",
      ),
      vraiFaux(
        "v3h-sfe-7",
        "lexique",
        "Avance",
        "Vrai ou faux : le mot \"panier\" a subi une extension de sens lorsqu'il est passe de l'objet en osier au \"panier\" de basket.",
        true,
        "Le mot \"panier\" a effectivement connu une extension de sens. A l'origine, il designait un objet en osier servant a transporter des marchandises. Par metaphore de forme (cercle ouvert dans lequel on depose quelque chose), il a designe l'anneau du terrain de basket. L'extension de sens elargit le nombre de referents possibles d'un mot, ici de l'objet artisanal au domaine sportif.",
        "Confondre extension de sens et creation d'un mot nouveau : c'est le meme mot dont le champ d'application s'elargit.",
        "premium",
      ),
      qcm(
        "v3h-sfe-8",
        "lexique",
        "Avance",
        "Dans \"Paris a vote pour le projet\", quel procede semantique permet d'utiliser le nom de la ville pour designer ses habitants ?",
        [
          { id: "a", label: "Une metaphore" },
          { id: "b", label: "Une metonymie" },
          { id: "c", label: "Une restriction de sens" },
          { id: "d", label: "Une polysemie" },
        ],
        "b",
        "C'est une metonymie : on designe les habitants par le lieu qu'ils occupent. Le rapport est un rapport de contiguite spatiale (la ville et ses habitants coexistent dans le meme espace). Ce n'est pas une metaphore car il n'y a pas de rapport de ressemblance entre la ville et les habitants, mais un rapport de proximite logique. Ce type de metonymie (lieu pour les gens) est tres courant dans la langue.",
        "Repondre metaphore en ne voyant pas que le rapport est de contiguite (lieu/habitants) et non de ressemblance.",
        "premium",
      ),
      reponseCourte(
        "v3h-sfe-9",
        "lexique",
        "Avance",
        "Comment appelle-t-on les valeurs subjectives, affectives ou culturelles associees a un mot, par opposition a son sens referentiel ?",
        ["connotation", "la connotation", "connotations", "les connotations"],
        "La connotation designe les valeurs subjectives, affectives ou culturelles qui s'ajoutent au sens referentiel (la denotation) d'un mot. Par exemple, \"demeure\" et \"baraque\" denotent toutes deux un lieu d'habitation, mais \"demeure\" connote le luxe et la noblesse tandis que \"baraque\" connote la precarite ou la familiarite. Les connotations varient selon les locuteurs, les epoques et les contextes culturels.",
        "Confondre connotation et registre de langue, qui est une notion liee mais distincte.",
        "premium",
      ),
      qcm(
        "v3h-sfe-10",
        "lexique",
        "Avance",
        "Pourquoi le travail sur le sens figure est-il essentiel pour la comprehension en lecture a l'ecole primaire ?",
        [
          { id: "a", label: "Parce qu'il permet de memoriser plus de definitions du dictionnaire" },
          { id: "b", label: "Parce que les textes litteraires et courants utilisent massivement des emplois figures que les eleves doivent apprendre a interpreter" },
          { id: "c", label: "Parce qu'il ameliore uniquement la production ecrite" },
          { id: "d", label: "Parce qu'il est necessaire uniquement pour l'analyse grammaticale" },
        ],
        "b",
        "Le sens figure est omnipresent dans les textes, tant litteraires que courants (expressions idiomatiques, metaphores lexicalisees, metonymies). Un eleve qui ne sait pas interpreter \"il pleut des cordes\" ou \"la tete du cortege\" risque un contresens. Enseigner les mecanismes du sens figure (metaphore par ressemblance, metonymie par contiguite) donne aux eleves des outils pour decrypter ces emplois et acceder a une comprehension fine des textes.",
        "Reduire le sens figure a un ornement litteraire sans voir son role fondamental dans la comprehension de tout type de texte.",
        "premium",
      ),
    ],
  }),
];
