import { ExerciseRecord, RevisionSession } from "@/types/domain";
import {
  frenchModuleSeriesIntegration,
  part4PremierLotSeriesCompletes,
} from "@/content/french-crpe-module";
import { seriesV3BatchA } from "@/content/french-crpe-series-v3-a";
import { seriesV3BatchB } from "@/content/french-crpe-series-v3-b";
import { seriesV3BatchC } from "@/content/french-crpe-series-v3-c";
import { seriesV3BatchD } from "@/content/french-crpe-series-v3-d";
import { seriesV3BatchE } from "@/content/french-crpe-series-v3-e";
import { seriesV3BatchF } from "@/content/french-crpe-series-v3-f";
import { seriesV3BatchG } from "@/content/french-crpe-series-v3-g";
import { seriesV3BatchH } from "@/content/french-crpe-series-v3-h";
import { seriesV3BatchI } from "@/content/french-crpe-series-v3-i";
import { seriesV3BatchJ } from "@/content/french-crpe-series-v3-j";
import { seriesV3BatchK } from "@/content/french-crpe-series-v3-k";
import { seriesTriNatureMots } from "@/content/french-crpe-series-tri-nature-mots";

const createdAt = "2026-03-12T08:00:00.000Z";

type QuestionInput = Omit<
  ExerciseRecord,
  "subject" | "validation_status" | "source" | "is_published" | "created_at" | "updated_at" | "level" | "access_tier"
>;

type SessionInput = Omit<RevisionSession, "questionCount" | "level" | "estimatedMinutes" | "access_tier">;

function question(data: QuestionInput): ExerciseRecord {
  return {
    subject: "Francais",
    validation_status: "valide",
    source: "Serie CRPE Francais V1",
    is_published: true,
    created_at: createdAt,
    updated_at: createdAt,
    common_mistake: null,
    ...data,
  };
}

function buildSession(data: SessionInput): RevisionSession {
  return {
    ...data,
    questionCount: data.questions.length,
  };
}

function textAnswer(...acceptableAnswers: string[]) {
  return {
    mode: "text" as const,
    acceptableAnswers,
  };
}

function qcm(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  instruction: string,
  choices: Array<{ id: string; label: string }>,
  value: string,
  explanation: string,
  commonMistake: string,
) {
  return question({
    id,
    subdomain,
    exercise_type: "qcm",
    instruction,
    support_text: null,
    choices,
    expected_answer: { mode: "single_choice", value },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
  });
}

function vraiFaux(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  instruction: string,
  value: boolean,
  explanation: string,
  commonMistake: string,
) {
  return question({
    id,
    subdomain,
    exercise_type: "vrai_faux",
    instruction,
    support_text: null,
    choices: [
      { id: "true", label: "Vrai" },
      { id: "false", label: "Faux" },
    ],
    expected_answer: { mode: "boolean", value },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
  });
}

function reponseCourte(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  instruction: string,
  acceptableAnswers: string[],
  explanation: string,
  commonMistake: string,
  exercise_type: ExerciseRecord["exercise_type"] = "reponse_courte",
  support_text: string | null = null,
) {
  return question({
    id,
    subdomain,
    exercise_type,
    instruction,
    support_text,
    choices: null,
    expected_answer: textAnswer(...acceptableAnswers),
    detailed_explanation: explanation,
    common_mistake: commonMistake,
  });
}

function correction(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  instruction: string,
  acceptableAnswers: string[],
  explanation: string,
  commonMistake: string,
) {
  return reponseCourte(
    id,
    subdomain,
    instruction,
    acceptableAnswers,
    explanation,
    commonMistake,
    "correction_orthographique",
  );
}

const legacyFrenchCrpeSeriesSeed: RevisionSession[] = [
  buildSession({
    id: "serie-accords-sujet-verbe",
    title: "Accords sujet-verbe dans des phrases simples et piegeuses",
    summary: "Une serie fondamentale pour fiabiliser l'accord du verbe, y compris quand le sujet est eloigne.",
    objective: "Identifier le vrai sujet avant de choisir la terminaison verbale.",
    introduction:
      "Cette serie travaille un automatisme central du CRPE : ne pas accorder avec le mot le plus proche, mais avec le noyau du sujet.",
    subdomain: "orthographe",
    topicKey: "accord_sujet_verbe",
    topicLabel: "Accord sujet-verbe",
    exerciseTypeLabel: "Correction orthographique, QCM, vrai/faux",
    recommendedOrder: 1,
    completionSummary: {
      skill: "Identifier le sujet reel avant d'accorder le verbe",
      keyPoints: [
        "Le verbe s'accorde avec le noyau du sujet.",
        "Un complement du nom ne commande pas l'accord.",
        "Les groupes collectifs demandent une verification du sens.",
      ],
      retryAdvice: "Soulignez le sujet, puis son noyau, avant de corriger la forme verbale.",
    },
    questions: [
      correction(
        "asv-1",
        "orthographe",
        'Corrigez si necessaire : "Les eleves de cette classe travaille serieusement."',
        ["Les eleves de cette classe travaillent serieusement."],
        'Le noyau du sujet est "eleves", au pluriel. Le verbe doit donc s\'accorder au pluriel.',
        "Accorder avec le mot le plus proche au lieu du noyau du sujet.",
      ),
      qcm(
        "asv-2",
        "orthographe",
        'Choisissez la forme correcte : "Le bruit des chaises ... la concentration."',
        [
          { id: "a", label: "perturbent" },
          { id: "b", label: "perturbes" },
          { id: "c", label: "perturbait" },
          { id: "d", label: "perturbe" },
        ],
        "d",
        'Le sujet est "Le bruit", singulier. "Des chaises" est un complement du nom.',
        'Accorder avec "chaises" parce que ce nom est plus proche du verbe.',
      ),
      vraiFaux(
        "asv-3",
        "orthographe",
        'Vrai ou faux : dans "Ni Paul ni ses camarades ne renoncent", le verbe au pluriel est correct.',
        true,
        'Deux sujets sont coordonnes par "ni ... ni" : le pluriel est ici attendu.',
        "N'accorder qu'avec le premier sujet.",
      ),
      correction(
        "asv-4",
        "orthographe",
        'Corrigez si necessaire : "La plupart des candidats reussit cette etape."',
        ["La plupart des candidats reussissent cette etape."],
        'Avec "la plupart des candidats", l\'accord suit ici l\'idee de pluralite.',
        'Accorder au singulier parce que "plupart" semble etre le noyau decisif.',
      ),
      reponseCourte(
        "asv-5",
        "orthographe",
        'Dans "Un grand nombre d\'exercices sont proposes", expliquez en un mot pourquoi le verbe est au pluriel.',
        ["sens", "pluralite", "pluriel logique"],
        "L'accord suit ici le sens pluriel de l'expression.",
        "Croire que le singulier est obligatoire des qu'un groupe commence par un nom singulier.",
      ),
      correction(
        "asv-6",
        "orthographe",
        'Corrigez si necessaire : "Toi qui relis ce chapitre, tu comprennent mieux la regle."',
        ["Toi qui relis ce chapitre, tu comprends mieux la regle."],
        'Le verbe principal s\'accorde avec "tu".',
        "Se laisser contaminer par une autre personne deja presente dans la phrase.",
      ),
      qcm(
        "asv-7",
        "orthographe",
        'Choisissez la forme correcte : "C\'est toi et moi qui ... cette affiche."',
        [
          { id: "a", label: "preparons" },
          { id: "b", label: "preparez" },
          { id: "c", label: "preparent" },
          { id: "d", label: "prepare" },
        ],
        "a",
        '"Toi et moi" equivaut a "nous". Le verbe s\'accorde donc a la 1re personne du pluriel.',
        "Accorder a la 3e personne du pluriel en traitant les sujets comme des tiers.",
      ),
      vraiFaux(
        "asv-8",
        "orthographe",
        'Vrai ou faux : dans "C\'est eux qui decide", le verbe est correctement accorde.',
        false,
        'Le pronom relatif "qui" reprend "eux" (3e personne du pluriel). Il faut ecrire "decident".',
        "Accorder avec le presentatif au lieu de l'antecedent du pronom relatif.",
      ),
      correction(
        "asv-9",
        "orthographe",
        'Corrigez si necessaire : "Le directeur ainsi que son adjoint participent a la reunion."',
        ["Le directeur ainsi que son adjoint participent a la reunion."],
        'Quand "ainsi que" a le sens de "et", le verbe s\'accorde au pluriel. La phrase est correcte.',
        'Corriger a tort en mettant le singulier parce que "directeur" est le premier sujet.',
      ),
      reponseCourte(
        "asv-10",
        "orthographe",
        'Dans "Aucun des eleves ne maitrise cette regle", pourquoi le verbe est-il au singulier ?',
        ["parce que le sujet est aucun", "aucun impose le singulier", "aucun est singulier"],
        'Le pronom indefini "aucun" impose le singulier, meme si le complement est au pluriel.',
        'Accorder avec "eleves" parce que ce nom est au pluriel.',
      ),
    ],
  }),
  buildSession({
    id: "serie-fonctions-essentielles",
    title: "Fonctions essentielles : sujet, verbe, COD, COI",
    summary: "Une serie de base pour distinguer les fonctions centrales de la phrase sans confondre nature et fonction.",
    objective: "Identifier sujet, COD, COI et attribut du sujet dans des phrases courtes.",
    introduction:
      "L'enjeu est simple : analyser ce que fait chaque groupe dans la phrase, et non seulement reconnaitre sa nature grammaticale.",
    subdomain: "grammaire",
    topicKey: "fonctions_essentielles",
    topicLabel: "Sujet, COD, COI et attribut",
    exerciseTypeLabel: "Identification grammaticale, QCM, vrai/faux",
    recommendedOrder: 2,
    completionSummary: {
      skill: "Analyser la structure minimale de la phrase",
      keyPoints: [
        "La nature d'un groupe n'est pas sa fonction.",
        "Le COD complete le verbe sans preposition.",
        "Le COI est souvent introduit par une preposition.",
      ],
      retryAdvice: "Quand vous hésitez, verifiez si le groupe est prepositionnel ou non.",
    },
    questions: [
      reponseCourte(
        "fct-1",
        "grammaire",
        'Dans "Les formateurs expliquent la consigne aux candidats", quelle est la fonction de "Les formateurs" ?',
        ["sujet", "Sujet", "le sujet", "Le sujet"],
        'Le groupe accomplit l\'action exprimee par le verbe : c\'est le sujet.',
        'Repondre "groupe nominal" au lieu de donner la fonction.',
        "identification_grammaticale",
      ),
      reponseCourte(
        "fct-2",
        "grammaire",
        'Dans la meme phrase, quelle est la fonction de "la consigne" ?',
        ["cod", "complement d'objet direct", "COD", "Complement d'objet direct", "Complément d'objet direct", "Le COD", "le cod"],
        'Le groupe complete directement le verbe, sans preposition : c\'est un COD.',
        "Confondre COD et COI.",
        "identification_grammaticale",
        'Phrase support : "Les formateurs expliquent la consigne aux candidats."',
      ),
      reponseCourte(
        "fct-3",
        "grammaire",
        'Dans la meme phrase, quelle est la fonction de "aux candidats" ?',
        ["coi", "complement d'objet indirect", "COI", "Complement d'objet indirect", "Complément d'objet indirect", "Le COI", "le coi"],
        'Le groupe est introduit par "a" : il s\'agit d\'un COI.',
        "Oublier que la preposition change la fonction.",
        "identification_grammaticale",
        'Phrase support : "Les formateurs expliquent la consigne aux candidats."',
      ),
      qcm(
        "fct-4",
        "grammaire",
        'Dans "Les eleves semblent fatigues", "fatigues" est :',
        [
          { id: "a", label: "COD" },
          { id: "b", label: "attribut du sujet" },
          { id: "c", label: "epithete" },
          { id: "d", label: "complement circonstanciel" },
        ],
        "b",
        'Le verbe "semblent" est un verbe attributif. "Fatigues" est attribut du sujet.',
        'Repondre "epithete" ou "adjectif" sans lire la consigne.',
      ),
      reponseCourte(
        "fct-5",
        "grammaire",
        'Dans "Le professeur parle a sa classe", pourquoi "a sa classe" n\'est-il pas COD ?',
        [
          "parce qu'il y a une preposition",
          "parce qu'il est introduit par une preposition",
          "parce qu'il y a a",
        ],
        'Le groupe est introduit par "a" : il ne complete pas directement le verbe.',
        "Chercher seulement a quelle question le groupe repond.",
      ),
      vraiFaux(
        "fct-6",
        "grammaire",
        'Vrai ou faux : dans "Les candidats relisent leur copie", "leur copie" est sujet.',
        false,
        'Le sujet est "Les candidats". "Leur copie" est COD.',
        "Prendre le groupe le plus proche du verbe pour le sujet.",
      ),
      qcm(
        "fct-7",
        "grammaire",
        'Dans "Marie donne un livre a son frere", quelle est la fonction de "un livre" ?',
        [
          { id: "a", label: "sujet" },
          { id: "b", label: "COD" },
          { id: "c", label: "COI" },
          { id: "d", label: "attribut du sujet" },
        ],
        "b",
        '"Un livre" complete directement le verbe "donne", sans preposition : c\'est un COD.',
        "Confondre COD et COI a cause de la presence d'un autre complement prepositionnel.",
      ),
      reponseCourte(
        "fct-8",
        "grammaire",
        'Dans "Cette lecon parait difficile", quelle est la fonction de "difficile" ?',
        ["attribut du sujet", "attribut"],
        'Le verbe "parait" est un verbe attributif. "Difficile" caracterise le sujet via ce verbe : c\'est un attribut du sujet.',
        'Repondre "epithete" en oubliant que le lien passe par un verbe attributif.',
      ),
      correction(
        "fct-9",
        "grammaire",
        'Identifiez la fonction erronee : on affirme que dans "Le chat dort sur le canape", "sur le canape" est COD. Corrigez.',
        ["complement circonstanciel de lieu", "complement circonstanciel", "CC de lieu", "CCL"],
        '"Sur le canape" indique le lieu : c\'est un complement circonstanciel de lieu, non un COD. Le COD complete directement le verbe sans preposition.',
        "Confondre complement circonstanciel et complement d'objet.",
      ),
      vraiFaux(
        "fct-10",
        "grammaire",
        'Vrai ou faux : dans "Elle pense a ses vacances", "a ses vacances" est un COD.',
        false,
        'Le groupe est introduit par la preposition "a" : il s\'agit d\'un COI, pas d\'un COD.',
        "Oublier que la preposition empeche de parler de COD.",
      ),
    ],
  }),
  buildSession({
    id: "serie-classes-grammaticales",
    title: "Classes grammaticales usuelles",
    summary: "Une serie de consolidation pour reconnaitre les classes grammaticales les plus frequentes.",
    objective: "Distinguer nom, verbe, adjectif, adverbe, determinant et pronom.",
    introduction:
      "La confusion entre classes grammaticales fragilise ensuite toute l'analyse. Cette serie travaille les reperages de base.",
    subdomain: "grammaire",
    topicKey: "classes_grammaticales",
    topicLabel: "Classes grammaticales",
    exerciseTypeLabel: "QCM, identification grammaticale",
    recommendedOrder: 3,
    completionSummary: {
      skill: "Identifier les classes grammaticales les plus frequentes",
      keyPoints: [
        "La classe depend de la nature du mot.",
        "L'adverbe modifie souvent un verbe, un adjectif ou un autre adverbe.",
        "Le determinant introduit le nom.",
      ],
      retryAdvice: "Demandez-vous a quel mot l'element se rattache et quelle nature il possede.",
    },
    questions: [
      qcm(
        "cgr-1",
        "grammaire",
        'Dans "Elle relit vite sa copie", "vite" est :',
        [
          { id: "a", label: "un adjectif" },
          { id: "b", label: "un nom" },
          { id: "c", label: "un pronom" },
          { id: "d", label: "un adverbe" },
        ],
        "d",
        '"Vite" modifie le verbe "relit" : c\'est un adverbe.',
        "Le confondre avec un adjectif parce qu'il exprime une qualite.",
      ),
      reponseCourte(
        "cgr-2",
        "grammaire",
        'Dans "Ce manuel utile reste sur la table", quelle est la classe grammaticale de "Ce" ?',
        ["determinant", "determinant demonstratif"],
        'Le mot introduit le nom "manuel" : c\'est un determinant demonstratif.',
        'Repondre "pronom" sans voir qu\'un nom suit immediatement.',
        "identification_grammaticale",
      ),
      qcm(
        "cgr-3",
        "grammaire",
        'Dans "Leur attention augmente", "attention" est :',
        [
          { id: "a", label: "un nom" },
          { id: "b", label: "un verbe" },
          { id: "c", label: "un adjectif" },
          { id: "d", label: "un adverbe" },
        ],
        "a",
        '"Attention" designe ici une realite : c\'est un nom.',
        "Le prendre pour un verbe a cause de la terminaison.",
      ),
      reponseCourte(
        "cgr-4",
        "grammaire",
        'Dans "Ces consignes sont utiles", quelle est la classe grammaticale de "utiles" ?',
        ["adjectif"],
        '"Utiles" qualifie le sujet "consignes" : sa classe grammaticale est adjectif (Éduscol 2021).',
        'Repondre "attribut" alors que la consigne demande la nature grammaticale.',
        "identification_grammaticale",
      ),
      qcm(
        "cgr-5",
        "grammaire",
        'Dans "Ils progressent parce qu\'ils s\'entrainent", "ils" est :',
        [
          { id: "a", label: "un determinant" },
          { id: "b", label: "un adverbe" },
          { id: "c", label: "un nom" },
          { id: "d", label: "un pronom" },
        ],
        "d",
        '"Ils" remplace un groupe nominal : c\'est un pronom personnel.',
        "Le classer comme determinant parce qu'il renvoie a des personnes.",
      ),
      vraiFaux(
        "cgr-6",
        "grammaire",
        'Vrai ou faux : dans "Marie court rapidement", "rapidement" est un adjectif.',
        false,
        '"Rapidement" modifie le verbe "court" : c\'est un adverbe, pas un adjectif.',
        "Confondre adverbe et adjectif parce qu'ils expriment tous deux une qualite.",
      ),
      reponseCourte(
        "cgr-7",
        "grammaire",
        'Dans "Nous preparons un exercice", quelle est la classe grammaticale de "un" ?',
        ["determinant", "determinant indefini", "article indefini"],
        '"Un" introduit le nom "exercice" : c\'est un determinant indefini (ou article indefini).',
        'Repondre "pronom" ou "adjectif numeral" sans analyser le contexte.',
        "identification_grammaticale",
      ),
      qcm(
        "cgr-8",
        "grammaire",
        'Dans "La consigne est claire et precise", "et" est :',
        [
          { id: "a", label: "une preposition" },
          { id: "b", label: "un adverbe" },
          { id: "c", label: "une conjonction de coordination" },
          { id: "d", label: "un pronom" },
        ],
        "c",
        '"Et" relie deux adjectifs coordonnes : c\'est une conjonction de coordination.',
        "Confondre conjonction de coordination et preposition.",
      ),
      reponseCourte(
        "cgr-9",
        "grammaire",
        'Dans "Le professeur parle a ses eleves", quelle est la classe grammaticale de "a" ?',
        ["preposition"],
        '"A" introduit un complement : c\'est une preposition.',
        'Confondre avec le verbe "a" (avoir) alors qu\'il n\'y a pas d\'accent.',
        "identification_grammaticale",
      ),
      qcm(
        "cgr-10",
        "grammaire",
        'Dans "Les enfants jouent dans la cour", "dans" est :',
        [
          { id: "a", label: "un adverbe" },
          { id: "b", label: "une conjonction" },
          { id: "c", label: "une preposition" },
          { id: "d", label: "un determinant" },
        ],
        "c",
        '"Dans" introduit le groupe nominal "la cour" : c\'est une preposition.',
        "Confondre preposition et adverbe parce que le mot est court.",
      ),
    ],
  }),
  buildSession({
    id: "serie-homophones-grammaticaux",
    title: "Homophones grammaticaux frequents",
    summary: "Une serie de discrimination grammaticale pour choisir la bonne graphie a partir d'un raisonnement.",
    objective: "Reconnaitre les principaux homophones grammaticaux a l'aide de tests simples.",
    introduction:
      "Les homophones sont tres rentables au CRPE. L'enjeu est de justifier chaque choix par une regle grammaticale claire.",
    subdomain: "orthographe",
    topicKey: "homophones_grammaticaux",
    topicLabel: "Homophones grammaticaux",
    exerciseTypeLabel: "QCM",
    recommendedOrder: 4,
    completionSummary: {
      skill: "Choisir une graphie en s'appuyant sur la grammaire",
      keyPoints: [
        'Remplacer "a" par "avait" permet souvent de trancher.',
        "Il faut distinguer coordination, verbe et preposition.",
        "La nature du determinant aide a choisir entre ses, ces, son.",
      ],
      retryAdvice: "Avant de repondre, formulez le test grammatical qui valide votre choix.",
    },
    questions: [
      qcm(
        "hg-1",
        "orthographe",
        'Completez : "Il ... relu sa fiche avant de partir."',
        [
          { id: "a", label: "a" },
          { id: "b", label: "à" },
        ],
        "a",
        'On peut remplacer par "avait relu" : il s\'agit du verbe avoir.',
        "Choisir selon la sonorite sans verifier la nature grammaticale.",
      ),
      qcm(
        "hg-2",
        "orthographe",
        'Completez : "Il pense ... ses resultats."',
        [
          { id: "a", label: "a" },
          { id: "b", label: "à" },
        ],
        "b",
        'Ici, le mot introduit un complement : c\'est une preposition.',
        "Ecrire le verbe avoir devant un groupe nominal.",
      ),
      qcm(
        "hg-3",
        "orthographe",
        'Completez : "Les consignes sont claires ... precises."',
        [
          { id: "a", label: "et" },
          { id: "b", label: "est" },
        ],
        "a",
        'Le mot relie ici deux adjectifs : c\'est une conjonction de coordination.',
        "Confondre conjonction et verbe etre.",
      ),
      qcm(
        "hg-4",
        "orthographe",
        'Completez : "Cette regle ... difficile au premier abord."',
        [
          { id: "a", label: "et" },
          { id: "b", label: "est" },
        ],
        "b",
        'Le mot est ici le verbe etre au present.',
        "Choisir la coordination sans identifier le verbe principal.",
      ),
      qcm(
        "hg-5",
        "orthographe",
        'Completez : "... cahier est range, mais ... stylos, la-bas sur la table, trainent encore."',
        [
          { id: "a", label: "Son / ses" },
          { id: "b", label: "Sont / ces" },
          { id: "c", label: "Son / ces" },
          { id: "d", label: "Ses / ces" },
        ],
        "c",
        '"Son" est possessif singulier ; "ces" est demonstratif pluriel. L\'adverbe "la-bas" renforce la deixis et confirme le demonstratif "ces".',
        'Ecrire "ses" uniquement parce que le nom qui suit est au pluriel, sans reperer l\'indice de deixis "la-bas".',
      ),
      qcm(
        "hg-6",
        "orthographe",
        'Completez : "... sont les eleves qui se preparent, pas ... voisins."',
        [
          { id: "a", label: "Ce / ses" },
          { id: "b", label: "Se / ces" },
          { id: "c", label: "Ses / ces" },
          { id: "d", label: "Ce / ces" },
        ],
        "d",
        'On ecrit "Ce sont" dans la tournure presentative. "Ces" designe ensuite les voisins.',
        'Confondre "ce" et "se" dans une tournure non pronominale.',
      ),
      qcm(
        "hg-7",
        "orthographe",
        'Completez : "Elle ... dit ... elle viendrait demain."',
        [
          { id: "a", label: "a / qu'" },
          { id: "b", label: "à / qu'" },
          { id: "c", label: "a / que" },
          { id: "d", label: "à / que" },
        ],
        "a",
        'On peut remplacer par "avait dit" : c\'est le verbe avoir. "Qu\'" est la conjonction "que" elide devant "elle".',
        'Ecrire "à" devant un complement sans verifier la nature grammaticale.',
      ),
      qcm(
        "hg-8",
        "orthographe",
        'Completez : "... regle ... simple a comprendre."',
        [
          { id: "a", label: "Cette / et" },
          { id: "b", label: "Cette / est" },
          { id: "c", label: "Sept / est" },
          { id: "d", label: "Cet / et" },
        ],
        "b",
        '"Cette" est un determinant demonstratif feminin singulier. "Est" est le verbe etre au present.',
        'Confondre "et" (coordination) et "est" (verbe etre) sans chercher le verbe principal.',
      ),
      vraiFaux(
        "hg-9",
        "orthographe",
        'Vrai ou faux : dans "Il se prepare a son examen", "se" est correctement ecrit.',
        true,
        '"Se" est ici le pronom reflexif du verbe pronominal "se preparer". C\'est correct.',
        'Confondre "se" (pronom reflexif) et "ce" (determinant demonstratif).',
      ),
      qcm(
        "hg-10",
        "orthographe",
        'Completez : "... eleves ont termine ... exercices ... ils etaient prepares."',
        [
          { id: "a", label: "Ces / leurs / et" },
          { id: "b", label: "Ses / leur / est" },
          { id: "c", label: "Ces / leurs / car" },
          { id: "d", label: "Ses / leurs / et" },
        ],
        "c",
        '"Ces" est demonstratif (on montre les eleves). "Leurs" est possessif pluriel. "Car" introduit une cause.',
        'Confondre "ces" et "ses" sans verifier si l\'on designe ou si l\'on marque la possession.',
      ),
    ],
  }),
  buildSession({
    id: "serie-accords-groupe-nominal",
    title: "Accords dans le groupe nominal",
    summary: "Une serie pour stabiliser les accords determinant, nom et adjectif.",
    objective: "Accorder correctement les elements du groupe nominal dans des cas courants.",
    introduction:
      "Le groupe nominal semble simple, mais les erreurs reviennent vite quand plusieurs expansions se cumulent.",
    subdomain: "orthographe",
    topicKey: "accords_groupe_nominal",
    topicLabel: "Accords dans le groupe nominal",
    exerciseTypeLabel: "Correction orthographique, QCM",
    recommendedOrder: 5,
    completionSummary: {
      skill: "Accorder correctement les constituants du groupe nominal",
      keyPoints: [
        "Le determinant, le nom et l'adjectif s'accordent entre eux.",
        "Le genre et le nombre se verifient sur le nom noyau.",
        "Un adjectif place apres plusieurs noms demande une lecture attentive.",
      ],
      retryAdvice: "Reperez d'abord le nom noyau, puis verifiez les accords autour de lui.",
    },
    questions: [
      correction(
        "agn-1",
        "orthographe",
        'Corrigez si necessaire : "Ces exercice difficiles demandent une lecture attentive."',
        ["Ces exercices difficiles demandent une lecture attentive."],
        '"Ces" est pluriel ; le nom doit donc s\'ecrire "exercices".',
        "N'accorder qu'un seul element du groupe nominal.",
      ),
      qcm(
        "agn-2",
        "orthographe",
        'Choisissez la bonne forme : "Une consigne et une demarche ...".',
        [
          { id: "a", label: "precise" },
          { id: "b", label: "precis" },
          { id: "c", label: "precises" },
          { id: "d", label: "precisee" },
        ],
        "c",
        'L\'adjectif se rapporte a deux noms feminins coordonnes : "precises".',
        "Accorder avec le nom le plus proche seulement.",
      ),
      correction(
        "agn-3",
        "orthographe",
        'Corrigez si necessaire : "Chaque candidate motivees relit ses notes."',
        ["Chaque candidate motivee relit ses notes."],
        'Le determinant "chaque" impose ici le singulier.',
        "Laisser l'adjectif au pluriel en se fiant a l'idee de groupe.",
      ),
      qcm(
        "agn-4",
        "orthographe",
        'Choisissez la forme correcte : "Des outils pedagogiques tres ..."',
        [
          { id: "a", label: "utile" },
          { id: "b", label: "utilisee" },
          { id: "c", label: "utilises" },
          { id: "d", label: "utiles" },
        ],
        "d",
        'Le nom "outils" est masculin pluriel ; l\'adjectif doit s\'accorder avec lui.',
        'Se laisser perturber par l\'adverbe "tres".',
      ),
      reponseCourte(
        "agn-5",
        "orthographe",
        'Dans "Les principales difficultes syntaxiques", quel mot commande l\'accord de "principales" ?',
        ["difficultes", "le nom difficultes"],
        'L\'adjectif "principales" s\'accorde avec le nom noyau "difficultes".',
        "Chercher un accord avec le mot le plus proche sans repérer le noyau nominal.",
      ),
      correction(
        "agn-6",
        "orthographe",
        'Corrigez si necessaire : "Les petit garcons jouent dans la cour."',
        ["Les petits garcons jouent dans la cour."],
        'L\'adjectif "petit" doit s\'accorder au pluriel avec le nom "garcons" : on ecrit "petits".',
        "Oublier l'accord de l'adjectif antepose.",
      ),
      vraiFaux(
        "agn-7",
        "orthographe",
        'Vrai ou faux : dans "une histoire passionnant", l\'adjectif est correctement accorde.',
        false,
        'Le nom "histoire" est feminin singulier. L\'adjectif doit s\'ecrire "passionnante".',
        "Ne pas verifier le genre du nom noyau avant d'accorder l'adjectif.",
      ),
      qcm(
        "agn-8",
        "orthographe",
        'Choisissez la forme correcte : "Un travail et une reflexion ..."',
        [
          { id: "a", label: "approfondi" },
          { id: "b", label: "approfondis" },
          { id: "c", label: "approfondies" },
          { id: "d", label: "approfondie" },
        ],
        "b",
        'L\'adjectif se rapporte a un nom masculin et un nom feminin coordonnes. Le masculin l\'emporte au pluriel : "approfondis".',
        "Accorder uniquement avec le nom le plus proche.",
      ),
      correction(
        "agn-9",
        "orthographe",
        'Corrigez si necessaire : "Plusieurs reponse exact figurent dans le corrige."',
        ["Plusieurs reponses exactes figurent dans le corrige."],
        '"Plusieurs" impose le pluriel : "reponses exactes".',
        "Laisser le singulier malgre un determinant qui indique le pluriel.",
      ),
      reponseCourte(
        "agn-10",
        "orthographe",
        'Dans "Toutes les consignes ecrites", pourquoi "ecrites" prend-il un -es ?',
        ["parce que consignes est feminin pluriel", "feminin pluriel", "accord avec consignes"],
        'L\'adjectif "ecrites" s\'accorde avec "consignes", feminin pluriel.',
        "Oublier la marque du feminin en plus de celle du pluriel.",
      ),
    ],
  }),
  buildSession({
    id: "serie-temps-de-base",
    title: "Present, imparfait et futur",
    summary: "Une serie de consolidation sur les temps de base et leurs formes les plus frequentes.",
    objective: "Reconnaître et produire les formes correctes au present, a l'imparfait et au futur simple.",
    introduction:
      "Avant les cas plus fins, il faut d'abord fiabiliser les temps de base. Cette serie melange reperage de forme et choix du temps.",
    subdomain: "conjugaison",
    topicKey: "temps_de_base",
    topicLabel: "Present, imparfait et futur",
    exerciseTypeLabel: "QCM, reponse courte",
    recommendedOrder: 6,
    completionSummary: {
      skill: "Choisir et former correctement les temps de base",
      keyPoints: [
        "Le present peut exprimer une habitude ou un constat.",
        "L'imparfait sert souvent au cadre ou a l'habitude dans le passe.",
        "Le futur simple exprime un fait a venir pose comme certain.",
      ],
      retryAdvice: "Reperez d'abord les indices temporels, puis verifiez la terminaison du verbe choisi.",
    },
    questions: [
      qcm(
        "tdb-1",
        "conjugaison",
        'Completez : "Chaque semaine, ils ... leurs erreurs."',
        [
          { id: "a", label: "analysent" },
          { id: "b", label: "analyseront" },
          { id: "c", label: "analysaient" },
          { id: "d", label: "analyseraient" },
        ],
        "a",
        'L\'expression "Chaque semaine" renvoie ici a une habitude actuelle : le present convient.',
        "Choisir le futur a cause de l'idee de repetition.",
      ),
      qcm(
        "tdb-2",
        "conjugaison",
        'Completez : "Quand elle etait etudiante, elle ... beaucoup."',
        [
          { id: "a", label: "lisait" },
          { id: "b", label: "lira" },
          { id: "c", label: "lit" },
          { id: "d", label: "lirait" },
        ],
        "a",
        "Le cadre passe et habituel appelle l'imparfait.",
        "Garder le present par automatisme de lecture.",
      ),
      reponseCourte(
        "tdb-3",
        "conjugaison",
        'Conjuguez au futur simple : "Nous (relire) la correction demain."',
        ["relirons"],
        'Le futur simple de "relire" a la 1re personne du pluriel est "relirons".',
        "Confondre le radical du futur avec celui du conditionnel.",
      ),
      qcm(
        "tdb-4",
        "conjugaison",
        'Choisissez la bonne forme : "Pendant le cours, les eleves ... en silence."',
        [
          { id: "a", label: "ecoutaient" },
          { id: "b", label: "ecoutent" },
          { id: "c", label: "ecouteront" },
          { id: "d", label: "ecouteraient" },
        ],
        "a",
        "Le groupe introducteur inscrit la scene dans un cadre descriptif passe : l'imparfait est attendu.",
        "Se fier a la vraisemblance de la phrase sans repérer le cadre temporel.",
      ),
      reponseCourte(
        "tdb-5",
        "conjugaison",
        'Donnez la forme au present : "Vous (finir) ce travail en groupe."',
        ["finissez"],
        '"Finir" au present, 2e personne du pluriel, se conjugue "vous finissez".',
        'Oublier le double "s" de la terminaison du 2e groupe.',
      ),
      reponseCourte(
        "tdb-6",
        "conjugaison",
        'Conjuguez a l\'imparfait : "Tu (prendre) toujours des notes en cours."',
        ["prenais"],
        '"Prendre" a l\'imparfait, 2e personne du singulier, se conjugue "tu prenais".',
        "Confondre le radical de l'imparfait avec celui du present.",
      ),
      qcm(
        "tdb-7",
        "conjugaison",
        'Completez : "L\'an prochain, elle ... dans une nouvelle ecole."',
        [
          { id: "a", label: "entrait" },
          { id: "b", label: "entre" },
          { id: "c", label: "entrera" },
          { id: "d", label: "entrerait" },
        ],
        "c",
        '"L\'an prochain" situe l\'action dans l\'avenir : le futur simple est attendu.',
        "Choisir le conditionnel a cause de la proximite des terminaisons avec le futur.",
      ),
      vraiFaux(
        "tdb-8",
        "conjugaison",
        'Vrai ou faux : dans "Nous mangions a la cantine", le verbe est au present.',
        false,
        'La terminaison "-ions" avec le radical "mange-" indique l\'imparfait, pas le present.',
        "Confondre la terminaison de l'imparfait avec celle du present pour la 1re personne du pluriel.",
      ),
      correction(
        "tdb-9",
        "conjugaison",
        'Corrigez si necessaire : "Demain, nous partiron tot."',
        ["Demain, nous partirons tot."],
        'Au futur simple, la 1re personne du pluriel se termine par "-ons" : "partirons".',
        "Oublier le -s final de la terminaison du futur a la 1re personne du pluriel.",
      ),
      qcm(
        "tdb-10",
        "conjugaison",
        'Quel temps est utilise dans "Les oiseaux chantaient chaque matin" ?',
        [
          { id: "a", label: "present" },
          { id: "b", label: "passe simple" },
          { id: "c", label: "imparfait" },
          { id: "d", label: "futur simple" },
        ],
        "c",
        'La terminaison "-aient" et l\'idee d\'habitude dans le passe indiquent l\'imparfait.',
        "Confondre imparfait et passe simple dans un contexte d'habitude passee.",
      ),
    ],
  }),
  buildSession({
    id: "serie-synonymes-antonymes",
    title: "Synonymes, antonymes et precision lexicale",
    summary: "Une serie pour travailler la justesse du mot choisi, pas seulement une proximite vague de sens.",
    objective: "Identifier un synonyme pertinent, un antonyme exact et quelques nuances lexicales.",
    introduction:
      "Le lexique utile au CRPE demande de la precision. Cette serie vous entraine a choisir le mot juste selon le contexte.",
    subdomain: "lexique",
    topicKey: "synonymes_antonymes",
    topicLabel: "Synonymie et antonymie",
    exerciseTypeLabel: "QCM, reponse courte",
    recommendedOrder: 7,
    completionSummary: {
      skill: "Choisir un mot proche ou oppose avec precision",
      keyPoints: [
        "Un synonyme n'est pas interchangeable dans tous les contextes.",
        "L'antonyme doit respecter le sens exact du mot de depart.",
        "Le contexte aide a valider une proposition.",
      ],
      retryAdvice: "Remplacez le mot cible dans la phrase : si le sens bouge trop, la reponse n'est pas bonne.",
    },
    questions: [
      qcm(
        "lex-1",
        "lexique",
        'Quel mot est le plus proche de "rigoureux" dans "un raisonnement rigoureux" ?',
        [
          { id: "a", label: "precis" },
          { id: "b", label: "bruyant" },
          { id: "c", label: "rapide" },
          { id: "d", label: "simple" },
        ],
        "a",
        '"Precis" est le mot le plus proche dans ce contexte.',
        "Choisir un mot positif mais non semantiquement proche.",
      ),
      qcm(
        "lex-2",
        "lexique",
        'Quel est l\'antonyme le plus exact de "implicite" ?',
        [
          { id: "a", label: "explicite" },
          { id: "b", label: "complexe" },
          { id: "c", label: "faible" },
          { id: "d", label: "vague" },
        ],
        "a",
        '"Explicite" est l\'oppose exact de "implicite".',
        "Confondre antonymie et simple changement de registre.",
      ),
      reponseCourte(
        "lex-3",
        "lexique",
        'Donnez un synonyme acceptable de "observer" dans "observer une erreur".',
        ["reperer", "constater"],
        'Dans ce contexte, "reperer" ou "constater" sont pertinents.',
        'Proposer un mot trop vague comme "voir".',
      ),
      qcm(
        "lex-4",
        "lexique",
        'Dans "une remarque nuancee", quel mot est le plus proche de "nuancee" ?',
        [
          { id: "a", label: "violente" },
          { id: "b", label: "banale" },
          { id: "c", label: "mesuree" },
          { id: "d", label: "breve" },
        ],
        "c",
        '"Mesuree" conserve l\'idee d\'une expression non brutale et precise.',
        "Choisir un mot seulement courant, sans proximite semantique claire.",
      ),
      reponseCourte(
        "lex-5",
        "lexique",
        'Donnez un antonyme acceptable de "frequent" dans "une erreur frequente".',
        ["rare", "occasionnel"],
        '"Rare" est l\'antonyme le plus direct ; "occasionnel" reste acceptable selon le contexte.',
        "Donner un mot negatif sans relation d'opposition nette.",
      ),
      qcm(
        "lex-6",
        "lexique",
        'Quel est le synonyme le plus pertinent de "elaborer" dans "elaborer une strategie" ?',
        [
          { id: "a", label: "concevoir" },
          { id: "b", label: "detruire" },
          { id: "c", label: "copier" },
          { id: "d", label: "oublier" },
        ],
        "a",
        '"Concevoir" partage l\'idee de construction methodique propre a "elaborer".',
        "Choisir un mot vaguement positif sans verifier la compatibilite avec le contexte.",
      ),
      reponseCourte(
        "lex-7",
        "lexique",
        'Donnez un antonyme acceptable de "accorder" dans "accorder une autorisation".',
        ["refuser", "retirer"],
        '"Refuser" est l\'antonyme le plus direct ; "retirer" fonctionne egalement en contexte.',
        "Proposer un mot sans lien d'opposition clair comme \"donner\".",
      ),
      vraiFaux(
        "lex-8",
        "lexique",
        'Vrai ou faux : "sobre" et "excessif" sont des antonymes.',
        true,
        '"Sobre" designe la retenue, "excessif" designe le trop-plein : ce sont bien des antonymes.',
        "Refuser l'antonymie parce que les mots n'ont pas le meme radical.",
      ),
      qcm(
        "lex-9",
        "lexique",
        'Dans "un discours limpide", quel synonyme convient le mieux a "limpide" ?',
        [
          { id: "a", label: "obscur" },
          { id: "b", label: "clair" },
          { id: "c", label: "long" },
          { id: "d", label: "ennuyeux" },
        ],
        "b",
        '"Clair" est le synonyme le plus pertinent de "limpide" dans ce contexte.',
        "Choisir un mot qui decrit une autre qualite du discours.",
      ),
      reponseCourte(
        "lex-10",
        "lexique",
        'Donnez un synonyme acceptable de "contraindre" dans "contraindre un eleve a refaire son travail".',
        ["obliger", "forcer"],
        '"Obliger" et "forcer" expriment la meme idee de pression exercee sur quelqu\'un.',
        'Proposer un mot trop faible comme "demander" qui n\'exprime pas la contrainte.',
      ),
    ],
  }),
  buildSession({
    id: "serie-nature-ou-fonction",
    title: "Nature ou fonction : ne plus melanger",
    summary: "Une serie pour distinguer la nature d'un mot ou groupe et sa fonction dans la phrase.",
    objective: "Repondre a une question d'analyse sans confondre classe grammaticale et role syntaxique.",
    introduction:
      "Beaucoup d'erreurs viennent d'une reponse juste... mais a une autre question. Cette serie cible la confusion classique entre nature et fonction.",
    subdomain: "analyse_langue",
    topicKey: "nature_ou_fonction",
    topicLabel: "Nature ou fonction",
    exerciseTypeLabel: "Identification grammaticale, vrai/faux",
    recommendedOrder: 8,
    completionSummary: {
      skill: "Distinguer ce qu'est un mot et le role qu'il joue",
      keyPoints: [
        "La nature renvoie a la classe grammaticale.",
        "La fonction renvoie au role dans la phrase.",
        "Un meme groupe peut garder sa nature et changer de fonction selon le contexte.",
      ],
      retryAdvice: "Relisez toujours la consigne : demande-t-on la nature ou la fonction ?",
    },
    questions: [
      vraiFaux(
        "nof-1",
        "analyse_langue",
        'Vrai ou faux : dans "Ces eleves progressent vite", dire que "vite" est adverbe repond a une question de nature.',
        true,
        'Dire que "vite" est un adverbe, c\'est indiquer sa nature grammaticale.',
        'Employer "fonction" pour toute analyse grammaticale.',
      ),
      reponseCourte(
        "nof-2",
        "analyse_langue",
        'Dans "Les candidats relisent leur copie", quelle est la fonction de "leur copie" ?',
        ["cod", "complement d'objet direct"],
        'Le groupe recoit directement l\'action du verbe : c\'est un COD.',
        'Repondre "groupe nominal", ce qui indique seulement la nature.',
        "identification_grammaticale",
      ),
      reponseCourte(
        "nof-3",
        "analyse_langue",
        'Dans "Un texte complexe", quelle est la nature de "complexe" ?',
        ["adjectif"],
        '"Complexe" qualifie le nom "texte" : sa nature est adjectif.',
        'Repondre "epithete" alors que la consigne demande la nature.',
        "identification_grammaticale",
      ),
      vraiFaux(
        "nof-4",
        "analyse_langue",
        'Vrai ou faux : dans "Le travail reste exigeant", "exigeant" est attribut du sujet.',
        true,
        'Le verbe "reste" est un verbe attributif. "Exigeant" est donc attribut du sujet.',
        'Se contenter de dire "adjectif" sans donner la fonction demandee.',
      ),
      reponseCourte(
        "nof-5",
        "analyse_langue",
        'Dans "Les outils numeriques", donnez la nature du groupe entier "Les outils numeriques".',
        ["groupe nominal", "gn"],
        'L\'ensemble forme un groupe nominal construit autour du nom noyau "outils".',
        "Donner une fonction alors que la consigne demande la nature du groupe.",
      ),
      qcm(
        "nof-6",
        "analyse_langue",
        'Dans "Elle marche rapidement", "rapidement" est :',
        [
          { id: "a", label: "une nature : adverbe" },
          { id: "b", label: "une fonction : complement circonstanciel de maniere" },
          { id: "c", label: "une nature : adjectif" },
          { id: "d", label: "une fonction : epithete" },
        ],
        "a",
        'Dire que "rapidement" est un adverbe revient a donner sa nature (classe grammaticale), pas sa fonction.',
        "Confondre la nature adverbe avec la fonction complement circonstanciel.",
      ),
      vraiFaux(
        "nof-7",
        "analyse_langue",
        'Vrai ou faux : dire que "dans la cour" est un groupe prepositionnel, c\'est donner sa nature.',
        true,
        '"Groupe prepositionnel" designe la nature du groupe (sa classe). Sa fonction pourrait etre complement circonstanciel de lieu.',
        "Croire que toute analyse grammaticale releve de la fonction.",
      ),
      reponseCourte(
        "nof-8",
        "analyse_langue",
        'Dans "Le petit chat dort paisiblement", quelle est la fonction de "petit" ?',
        ["epithete", "epithete du nom chat", "epithete liee"],
        '"Petit" qualifie directement le nom "chat" sans verbe intermediaire : c\'est une epithete.',
        'Repondre "adjectif" alors que la consigne demande la fonction.',
        "identification_grammaticale",
      ),
      qcm(
        "nof-9",
        "analyse_langue",
        'Parmi ces reponses, laquelle donne la fonction de "de la bibliotheque" dans "Le livre de la bibliotheque" ?',
        [
          { id: "a", label: "groupe prepositionnel" },
          { id: "b", label: "complement du nom" },
          { id: "c", label: "nom commun" },
          { id: "d", label: "determinant" },
        ],
        "b",
        '"Complement du nom" designe le role syntaxique du groupe dans le GN : c\'est bien une fonction.',
        'Repondre "groupe prepositionnel", qui est la nature du groupe, pas sa fonction.',
      ),
      correction(
        "nof-10",
        "analyse_langue",
        'Un eleve ecrit : "Dans la phrase, \'courageusement\' est complement circonstanciel de maniere ; sa nature est adverbe." Y a-t-il une erreur ?',
        ["non", "pas d'erreur", "correct", "c'est correct"],
        'L\'eleve distingue correctement nature (adverbe) et fonction (complement circonstanciel de maniere). Les deux reponses sont justes.',
        "Croire qu'on ne peut pas donner a la fois la nature et la fonction d'un meme mot.",
      ),
    ],
  }),
  buildSession({
    id: "serie-futur-conditionnel-subjonctif",
    title: "Futur, conditionnel et subjonctif : ne plus confondre",
    summary: "Une serie pour distinguer des formes proches et les employer selon le sens et la construction.",
    objective: "Differencier futur, conditionnel et subjonctif en liant les terminaisons aux valeurs d'emploi.",
    introduction:
      "Les erreurs de conjugaison viennent souvent d'une lecture trop rapide. Ici, vous travaillez a la fois la forme verbale et la valeur qu'elle exprime.",
    subdomain: "conjugaison",
    topicKey: "modes_temps_proches",
    topicLabel: "Futur, conditionnel et subjonctif",
    exerciseTypeLabel: "QCM, reponse courte, vrai/faux",
    recommendedOrder: 9,
    completionSummary: {
      skill: "Relier le mode et le temps au contexte de la phrase",
      keyPoints: [
        "Le futur renvoie a un fait a venir presente comme certain.",
        "Le conditionnel sert souvent l'hypothese ou l'attenuation.",
        'Le subjonctif depend de certaines constructions comme "il faut que" ou "bien que".',
      ],
      retryAdvice: "Reperez d'abord le declencheur : adverbe temporel, hypothese ou locution subordonnante.",
    },
    questions: [
      qcm(
        "fcs-1",
        "conjugaison",
        'Completez : "Demain, nous ... la correction complete."',
        [
          { id: "a", label: "verrions" },
          { id: "b", label: "verrons" },
          { id: "c", label: "voyons" },
          { id: "d", label: "verrez" },
        ],
        "b",
        'L\'adverbe "Demain" introduit ici un futur pose comme certain.',
        "Choisir le conditionnel parce que la terminaison semble plus soutenue.",
      ),
      qcm(
        "fcs-2",
        "conjugaison",
        'Completez : "Avec plus de temps, nous ... davantage d\'exercices."',
        [
          { id: "a", label: "ferons" },
          { id: "b", label: "ferions" },
          { id: "c", label: "faisons" },
          { id: "d", label: "fassions" },
        ],
        "b",
        "La phrase exprime une hypothese : le conditionnel est attendu.",
        "Ne regarder que la terminaison sans tenir compte de la valeur hypothetique.",
      ),
      reponseCourte(
        "fcs-3",
        "conjugaison",
        'Conjuguez : "Il faut que vous (prendre) le temps de relire."',
        ["preniez"],
        'Apres "il faut que", le verbe se met au subjonctif present.',
        "Donner l'infinitif ou employer l'indicatif.",
      ),
      vraiFaux(
        "fcs-4",
        "conjugaison",
        'Vrai ou faux : dans "Je voudrais que tu viennes", "viennes" est au subjonctif.',
        true,
        'Le verbe est bien au subjonctif present dans cette subordonnee introduite par "que".',
        'Repondre simplement "present" sans preciser le mode verbal.',
      ),
      qcm(
        "fcs-5",
        "conjugaison",
        'Dans "Si tu travaillais davantage, tu reussirais", "reussirais" est au :',
        [
          { id: "a", label: "futur" },
          { id: "b", label: "conditionnel" },
          { id: "c", label: "subjonctif" },
          { id: "d", label: "imparfait" },
        ],
        "b",
        'La structure "si + imparfait" appelle ici un conditionnel dans la proposition principale.',
        "Confondre futur et conditionnel a cause de la proximite des terminaisons.",
      ),
      reponseCourte(
        "fcs-6",
        "conjugaison",
        'Donnez l\'infinitif du verbe dans "nous tiendrons".',
        ["tenir"],
        'Malgre le radical irregulier "tiendr-", l\'infinitif reste "tenir".',
        "Reconstruire un infinitif fictif a partir du radical du futur.",
      ),
      qcm(
        "fcs-7",
        "conjugaison",
        'Completez : "Bien qu\'il ... fatigue, il continue."',
        [
          { id: "a", label: "est" },
          { id: "b", label: "sera" },
          { id: "c", label: "serait" },
          { id: "d", label: "soit" },
        ],
        "d",
        'La locution "bien que" demande le subjonctif.',
        'Garder l\'indicatif par automatisme apres "bien que".',
      ),
      vraiFaux(
        "fcs-8",
        "conjugaison",
        'Vrai ou faux : dans "Nous partirons des que tu seras pret", "seras" est au conditionnel.',
        false,
        '"Seras" est au futur simple de l\'indicatif. La structure "des que + futur" exprime une certitude temporelle, non une hypothese.',
        "Confondre futur et conditionnel a cause de la proximite des terminaisons en -r-.",
      ),
      reponseCourte(
        "fcs-9",
        "conjugaison",
        'Conjuguez : "Pourvu qu\'elle (reussir) son examen."',
        ["reussisse"],
        'La locution "pourvu que" exige le subjonctif present. La forme correcte est "reussisse".',
        'Employer le futur "reussira" alors que la locution commande le subjonctif.',
      ),
      qcm(
        "fcs-10",
        "conjugaison",
        'Completez : "S\'il pleuvait, nous ... a l\'interieur."',
        [
          { id: "a", label: "resterons" },
          { id: "b", label: "restions" },
          { id: "c", label: "resterions" },
          { id: "d", label: "restons" },
        ],
        "c",
        'La structure "si + imparfait" dans la subordonnee appelle le conditionnel present dans la principale.',
        "Utiliser le futur apres un si hypothetique a l'imparfait.",
      ),
    ],
  }),
  buildSession({
    id: "serie-analyse-groupe-nominal-relative",
    title: "Analyse de la langue : groupe nominal et subordination",
    summary: "Une serie exigeante pour relier groupe nominal, proposition relative et chaine d'accords.",
    objective: "Observer la structure d'une phrase complexe et justifier une analyse precise.",
    introduction:
      "Cette serie demande une lecture ordonnee de la phrase : reperer le noyau, identifier la relative, puis suivre les accords a distance.",
    subdomain: "analyse_langue",
    topicKey: "relative_et_chaine_accords",
    topicLabel: "Relative et chaine d'accords",
    exerciseTypeLabel: "Identification grammaticale, analyse, vrai/faux",
    recommendedOrder: 10,
    completionSummary: {
      skill: "Articuler syntaxe, groupe nominal et accords dans une phrase complexe",
      keyPoints: [
        "Le noyau d'un groupe nominal n'est pas tout le groupe.",
        "Une relative a une nature et une fonction distinctes.",
        "Le participe passe avec avoir peut s'accorder avec un COD antepose.",
      ],
      retryAdvice: "Reperez d'abord les noyaux nominaux, puis les verbes, puis les marqueurs de subordination.",
    },
    questions: [
      reponseCourte(
        "agl-1",
        "analyse_langue",
        "Quel est le noyau du groupe nominal sujet dans la phrase support ?",
        ["eleves"],
        'Le groupe sujet complet commence par "Les eleves qui relisent...", mais son noyau est "eleves".',
        "Recopier tout le groupe nominal au lieu d'identifier la tete du groupe.",
        "identification_grammaticale",
        'Phrase support : "Les eleves qui relisent attentivement leur brouillon reperent souvent des erreurs qu\'ils n\'avaient pas vues au debut."',
      ),
      reponseCourte(
        "agl-2",
        "analyse_langue",
        'Quelle est la nature de "qui relisent attentivement leur brouillon" ?',
        ["proposition subordonnee relative", "subordonnee relative"],
        'Le groupe est introduit par le pronom relatif "qui" : c\'est une proposition subordonnee relative.',
        'Repondre seulement "proposition" ou confondre avec une conjonction.',
        "identification_grammaticale",
        'Phrase support : "Les eleves qui relisent attentivement leur brouillon reperent souvent des erreurs qu\'ils n\'avaient pas vues au debut."',
      ),
      reponseCourte(
        "agl-3",
        "analyse_langue",
        "Quelle est la fonction de cette proposition relative ?",
        ["complement de l'antecedent", "expansion du nom", "complement de l'antecedent eleves"],
        "La relative precise quels eleves sont concernes : elle est complement de l'antecedent.",
        "Redonner la nature de la relative alors que la consigne demande sa fonction.",
        "reponse_courte",
        'Phrase support : "Les eleves qui relisent attentivement leur brouillon reperent souvent des erreurs qu\'ils n\'avaient pas vues au debut."',
      ),
      reponseCourte(
        "agl-4",
        "analyse_langue",
        'Dans "des erreurs qu\'ils n\'avaient pas vues", quelle est la nature de "qu\'" ?',
        ["pronom relatif"],
        '"Qu\'" introduit une relative et reprend le nom "erreurs" : c\'est un pronom relatif.',
        "Parler de conjonction de subordination.",
        "identification_grammaticale",
        'Phrase support : "Les eleves qui relisent attentivement leur brouillon reperent souvent des erreurs qu\'ils n\'avaient pas vues au debut."',
      ),
      reponseCourte(
        "agl-5",
        "analyse_langue",
        'Quel est l\'antecedent de "qu\'" ?',
        ["erreurs"],
        'Le pronom relatif "qu\'" reprend le nom "erreurs".',
        "Choisir un nom plus proche sans verifier le lien syntaxique.",
        "reponse_courte",
        'Phrase support : "Les eleves qui relisent attentivement leur brouillon reperent souvent des erreurs qu\'ils n\'avaient pas vues au debut."',
      ),
      qcm(
        "agl-6",
        "analyse_langue",
        'Pourquoi ecrit-on "les fleurs qu\'il avait vues" avec un accord ?',
        [
          { id: "a", label: "Le sujet \"il\" est masculin singulier" },
          { id: "b", label: "Le COD \"les fleurs\" (feminin pluriel) est place avant l'auxiliaire avoir" },
          { id: "c", label: "Le verbe \"voir\" est un verbe d'etat" },
          { id: "d", label: "Le participe passe s'accorde toujours avec l'auxiliaire avoir" },
        ],
        "b",
        'Avec l\'auxiliaire avoir, le participe passe s\'accorde avec le COD lorsqu\'il est place avant le verbe. Ici "qu\'" reprend "les fleurs" (feminin pluriel), d\'ou l\'accord "vues".',
        'Accorder le participe passe avec le sujet "il" au lieu du COD antepose.',
      ),
      vraiFaux(
        "agl-7",
        "analyse_langue",
        'Vrai ou faux : dans la phrase support, "attentivement" est une expansion du nom "brouillon".',
        false,
        '"Attentivement" modifie le verbe "relisent" : c\'est un adverbe de maniere.',
        "Rattacher automatiquement tout element voisin au nom le plus proche.",
      ),
      reponseCourte(
        "agl-8",
        "analyse_langue",
        'Dans "La regle que tu appliques est simple", quelle est la fonction du pronom relatif "que" ?',
        ["COD", "cod", "complement d'objet direct"],
        '"Que" reprend "regle" et fonctionne comme COD du verbe "appliques" dans la subordonnee relative.',
        "Confondre la fonction du pronom relatif avec celle de la proposition relative entiere.",
        "identification_grammaticale",
      ),
      qcm(
        "agl-9",
        "analyse_langue",
        'Dans "Les livres dont elle parle sont passionnants", "dont" est :',
        [
          { id: "a", label: "une conjonction de subordination" },
          { id: "b", label: "un pronom relatif representant un COI" },
          { id: "c", label: "un adverbe relatif" },
          { id: "d", label: "un pronom relatif representant un COD" },
        ],
        "b",
        '"Dont" est un pronom relatif qui reprend "livres" et fonctionne comme COI du verbe "parle" (parler de quelque chose).',
        "Confondre dont avec une conjonction ou lui attribuer la fonction COD.",
      ),
      vraiFaux(
        "agl-10",
        "analyse_langue",
        'Vrai ou faux : dans "Les resultats qu\'elle a obtenus sont excellents", le participe passe "obtenus" s\'accorde avec "elle".',
        false,
        'Avec l\'auxiliaire avoir, le participe passe s\'accorde avec le COD place avant : ici "qu\'" reprend "resultats" (masculin pluriel), d\'ou "obtenus".',
        "Accorder le participe passe avec le sujet alors que l'auxiliaire est avoir.",
      ),
    ],
  }),
  buildSession({
    id: "serie-gn-expansions",
    title: "Groupe nominal et expansions",
    summary: "Une serie d'approfondissement pour analyser le groupe nominal, son noyau et ses expansions.",
    objective: "Identifier le nom noyau et distinguer adjectif epithete, complement du nom et proposition relative.",
    introduction:
      "Cette serie travaille une competence tres rentable : savoir decrire precisement la composition d'un groupe nominal.",
    subdomain: "grammaire",
    topicKey: "groupe_nominal_expansions",
    topicLabel: "Groupe nominal et expansions",
    exerciseTypeLabel: "Identification grammaticale, analyse",
    recommendedOrder: 11,
    completionSummary: {
      skill: "Analyser un groupe nominal dans le detail",
      keyPoints: [
        "Le noyau est le nom principal du groupe.",
        "Une expansion peut etre un adjectif, un complement du nom ou une relative.",
        "Il faut distinguer nature de l'expansion et role dans le groupe.",
      ],
      retryAdvice: "Commencez toujours par isoler le noyau, puis nommez les expansions une a une.",
    },
    questions: [
      reponseCourte(
        "gne-1",
        "grammaire",
        'Dans "un manuel de grammaire tres utile", quel est le noyau du groupe nominal ?',
        ["manuel"],
        'Le nom principal du groupe est "manuel". Le reste vient le preciser.',
        "Prendre toute la suite du groupe comme noyau.",
        "identification_grammaticale",
      ),
      reponseCourte(
        "gne-2",
        "grammaire",
        'Dans le meme groupe, quelle est la fonction de "de grammaire" ?',
        ["complement du nom"],
        '"De grammaire" complete le nom "manuel" : c\'est un complement du nom.',
        'Repondre "groupe prepositionnel" alors qu\'on attend le role de l\'expansion.',
        "identification_grammaticale",
        'Support : "un manuel de grammaire tres utile"',
      ),
      reponseCourte(
        "gne-3",
        "grammaire",
        'Dans le meme groupe, quelle est la nature de "utile" ?',
        ["adjectif"],
        '"Utile" est un adjectif rattache au nom "manuel".',
        'Repondre "epithete" alors que la consigne demande la nature grammaticale.',
        "identification_grammaticale",
        'Support : "un manuel de grammaire tres utile"',
      ),
      qcm(
        "gne-4",
        "grammaire",
        'Dans "les eleves qui relisent leur brouillon", l\'expansion du nom est :',
        [
          { id: "a", label: "un adjectif epithete" },
          { id: "b", label: "une proposition relative" },
          { id: "c", label: "un adverbe" },
          { id: "d", label: "un complement du nom" },
        ],
        "b",
        'Le groupe introduit par "qui" est une proposition subordonnee relative.',
        "Ne pas reconnaitre le pronom relatif comme indice principal.",
      ),
      qcm(
        "gne-5",
        "grammaire",
        "Quelle est la difference principale entre une epithete et un complement du nom ?",
        [
          { id: "a", label: "L'epithete est un adjectif, le complement du nom est introduit par une preposition" },
          { id: "b", label: "L'epithete est toujours apres le nom, le complement du nom toujours avant" },
          { id: "c", label: "L'epithete est obligatoire, le complement du nom est facultatif" },
          { id: "d", label: "Il n'y a aucune difference, ce sont deux noms pour la meme fonction" },
        ],
        "a",
        "L'epithete est un adjectif qui qualifie directement le nom sans preposition, tandis que le complement du nom est un groupe introduit par une preposition (ex. : \"de cuir\", \"en bois\").",
        "Confondre la position dans la phrase avec la nature grammaticale de l'expansion.",
      ),
      reponseCourte(
        "gne-6",
        "grammaire",
        'Dans "une robe en soie naturelle", identifiez le complement du nom.',
        ["en soie naturelle", "en soie"],
        '"En soie naturelle" est un groupe prepositionnel qui complete le nom "robe" : c\'est un complement du nom.',
        'Repondre "naturelle" qui est une epithete de "soie", pas le complement du nom "robe".',
        "identification_grammaticale",
      ),
      vraiFaux(
        "gne-7",
        "grammaire",
        'Vrai ou faux : dans "le garcon joyeux qui chante", il y a deux expansions du nom "garcon".',
        true,
        '"Joyeux" est une epithete et "qui chante" est une proposition relative : le nom "garcon" a bien deux expansions.',
        "Ne compter que l'adjectif et oublier la relative.",
      ),
      qcm(
        "gne-8",
        "grammaire",
        'Dans "la maison de mes grands-parents", "de mes grands-parents" est :',
        [
          { id: "a", label: "une epithete" },
          { id: "b", label: "un complement du nom" },
          { id: "c", label: "un attribut du sujet" },
          { id: "d", label: "une apposition" },
        ],
        "b",
        'Le groupe prepositionnel "de mes grands-parents" precise le nom "maison" : c\'est un complement du nom.',
        "Confondre complement du nom et complement circonstanciel.",
      ),
      reponseCourte(
        "gne-9",
        "grammaire",
        'Dans "un exercice long et difficile", quelle est la fonction de "long" et "difficile" ?',
        ["epithete", "epithetes", "epithetes du nom exercice", "epithete liee"],
        '"Long" et "difficile" sont des adjectifs qualificatifs qui qualifient directement le nom "exercice" : ce sont des epithetes.',
        'Repondre "adjectif" au lieu de donner la fonction (epithete).',
        "identification_grammaticale",
      ),
      correction(
        "gne-10",
        "grammaire",
        'Un eleve ecrit : dans "le chapeau de paille", "de paille" est une epithete. Corrigez son erreur.',
        ["complement du nom", "c'est un complement du nom"],
        '"De paille" est un groupe prepositionnel, pas un adjectif. Sa fonction est complement du nom, non epithete.',
        'Confondre epithete et complement du nom lorsque l\'expansion precise la matiere.',
      ),
    ],
  }),
  buildSession({
    id: "serie-participe-passe-etre",
    title: "Participe passe avec etre",
    summary: "Une serie pour consolider la regle d'accord la plus stable avant les cas plus delicats avec avoir.",
    objective: "Accorder correctement le participe passe employe avec l'auxiliaire etre.",
    introduction:
      "L'accord du participe passe avec etre est plus regulier qu'avec avoir, mais les erreurs restent frequentes quand le sujet est eloigne.",
    subdomain: "orthographe",
    topicKey: "participe_passe_etre",
    topicLabel: "Participe passe avec etre",
    exerciseTypeLabel: "QCM, vrai/faux, correction orthographique",
    recommendedOrder: 12,
    completionSummary: {
      skill: "Accorder correctement le participe passe avec etre",
      keyPoints: [
        "Avec etre, le participe passe s'accorde avec le sujet.",
        "Il faut identifier le vrai sujet avant de choisir la marque finale.",
        "La distance entre sujet et verbe ne change pas la regle.",
      ],
      retryAdvice: "Soulignez le sujet, puis verifiez son genre et son nombre avant de corriger la forme.",
    },
    questions: [
      qcm(
        "ppe-1",
        "orthographe",
        'Choisissez la bonne forme : "Les copies sont ..."',
        [
          { id: "a", label: "corrige" },
          { id: "b", label: "corriges" },
          { id: "c", label: "corrigees" },
          { id: "d", label: "corrigeant" },
        ],
        "c",
        'Le sujet "copies" est feminin pluriel. Le participe passe avec etre s\'accorde donc en genre et en nombre.',
        "Laisser la forme invariable par automatisme.",
      ),
      correction(
        "ppe-2",
        "orthographe",
        'Corrigez si necessaire : "Les consignes sont reste clair."',
        ["Les consignes sont restees claires."],
        'Avec l\'auxiliaire etre, "restees" s\'accorde avec "consignes". L\'adjectif "claires" s\'accorde egalement.',
        "Corriger le participe passe mais oublier l'accord de l'adjectif qui suit.",
      ),
      vraiFaux(
        "ppe-3",
        "orthographe",
        'Vrai ou faux : dans "Les eleves sont arrives en avance", "arrives" est correctement accorde.',
        true,
        'Le sujet "eleves" est masculin pluriel. La forme "arrives" est correcte.',
        "Croire que le participe passe reste invariable quand il est employe avec etre.",
      ),
      qcm(
        "ppe-4",
        "orthographe",
        'Choisissez la forme correcte : "La candidate est ..."',
        [
          { id: "a", label: "preparee" },
          { id: "b", label: "prepare" },
          { id: "c", label: "prepares" },
          { id: "d", label: "preparees" },
        ],
        "a",
        'Le sujet est feminin singulier : on ecrit "preparee".',
        "Oublier la marque du feminin au singulier.",
      ),
      reponseCourte(
        "ppe-5",
        "orthographe",
        'Dans "Les erreurs sont reperees", avec quel element le participe passe s\'accorde-t-il ?',
        ["le sujet", "erreurs", "les erreurs"],
        'Avec etre, le participe passe s\'accorde avec le sujet : ici, "les erreurs".',
        "Chercher un COD alors que la regle demande de repérer le sujet.",
      ),
      correction(
        "ppe-6",
        "orthographe",
        'Corrigez si necessaire : "Les portes sont reste ouvert."',
        ["Les portes sont restees ouvertes."],
        'Le sujet "portes" est feminin pluriel. Le participe passe "restees" et l\'adjectif "ouvertes" s\'accordent en genre et en nombre avec le sujet.',
        "Corriger le participe passe mais oublier l'accord de l'adjectif attribut.",
      ),
      qcm(
        "ppe-7",
        "orthographe",
        'Choisissez la forme correcte : "Les athletes sont ..."',
        [
          { id: "a", label: "partie" },
          { id: "b", label: "partis" },
          { id: "c", label: "parti" },
          { id: "d", label: "partirent" },
        ],
        "b",
        'Le sujet "athletes" est masculin pluriel. Le participe passe avec etre s\'accorde donc au masculin pluriel : "partis".',
        "Laisser le participe passe au singulier par habitude.",
      ),
      vraiFaux(
        "ppe-8",
        "orthographe",
        'Vrai ou faux : dans "Ma soeur est tombee dans la cour", "tombee" est correctement accorde.',
        true,
        'Le sujet "Ma soeur" est feminin singulier. Le participe passe "tombee" porte bien la marque du feminin singulier.',
        "Douter de l'accord au feminin avec un verbe de mouvement.",
      ),
      reponseCourte(
        "ppe-9",
        "orthographe",
        'Accordez le participe passe : "Les feuilles sont (tomber) pendant la nuit."',
        ["tombees"],
        'Le sujet "feuilles" est feminin pluriel. Avec l\'auxiliaire etre, le participe passe s\'accorde : "tombees".',
        "Ecrire \"tombes\" en oubliant la marque du feminin.",
      ),
      qcm(
        "ppe-10",
        "orthographe",
        'Dans "Les lettres sont ecrites a la main", pourquoi ecrit-on "ecrites" ?',
        [
          { id: "a", label: "Le participe passe s'accorde avec le COD" },
          { id: "b", label: "Le participe passe s'accorde avec le sujet feminin pluriel car l'auxiliaire est etre" },
          { id: "c", label: "Le participe passe est toujours invariable" },
          { id: "d", label: "Le participe passe s'accorde avec le complement circonstanciel" },
        ],
        "b",
        'Avec l\'auxiliaire etre, le participe passe s\'accorde avec le sujet. "Lettres" est feminin pluriel, d\'ou "ecrites".',
        "Chercher un COD alors qu'avec etre l'accord se fait avec le sujet.",
      ),
    ],
  }),
];

const MODULE_EXERCISE_TYPE_LABELS: Record<ExerciseRecord["exercise_type"], string> = {
  qcm: "QCM",
  vrai_faux: "Vrai/faux",
  reponse_courte: "Reponse courte",
  identification_grammaticale: "Identification grammaticale",
  correction_orthographique: "Correction orthographique",
  analyse_texte: "Analyse de texte",
  tri_categories: "Tri par catégories",
  surlignage_propositions: "Délimitation de propositions",
};

function buildModuleSession(series: (typeof part4PremierLotSeriesCompletes)[number]): RevisionSession {
  const integration = frenchModuleSeriesIntegration[series.id];
  const questions = series.questions.map((item) =>
    question({
      id: item.id,
      subdomain: series.domain,
      topic_key: series.subdomain,
      topic_label: series.subdomainLabel,
      exercise_type: item.type,
      instruction: item.instruction,
      support_text: item.supportText,
      choices: item.choices,
      expected_answer: item.expectedAnswer,
      detailed_explanation: item.explanation,
      common_mistake: item.commonMistake,
    })
  );

  return buildSession({
    id: series.id,
    title: series.title,
    summary: series.objective,
    objective: series.objective,
    introduction: series.introduction,
    subdomain: series.domain,
    topicKey: series.subdomain,
    topicLabel: series.subdomainLabel,
    exerciseTypeLabel: Array.from(
      new Set(series.questions.map((item) => MODULE_EXERCISE_TYPE_LABELS[item.type])),
    ).join(", "),
    recommendedOrder: integration.recommendedOrder,
    completionSummary: {
      skill: series.bilan.competenceTravaillee,
      keyPoints: series.bilan.pointsARetenir,
      retryAdvice: series.bilan.conseilDeReprise,
    },
    questions,
  });
}

const moduleFrenchCrpeSeriesSeed = part4PremierLotSeriesCompletes.map(buildModuleSession);

export const frenchCrpeSeriesSeed: RevisionSession[] = [
  ...legacyFrenchCrpeSeriesSeed,
  ...moduleFrenchCrpeSeriesSeed,
  ...seriesV3BatchA,
  ...seriesV3BatchB,
  ...seriesV3BatchC,
  ...seriesV3BatchD,
  ...seriesV3BatchE,
  ...seriesV3BatchF,
  ...seriesV3BatchG,
  ...seriesV3BatchH,
  ...seriesV3BatchI,
  ...seriesV3BatchJ,
  ...seriesV3BatchK,
  ...seriesTriNatureMots,
];
