import { ExerciseRecord, RevisionSession } from "@/types/domain";

const createdAt = "2026-03-20T08:00:00.000Z";

type QuestionInput = Omit<
  ExerciseRecord,
  "subject" | "validation_status" | "source" | "is_published" | "created_at" | "updated_at"
>;

type SessionInput = Omit<RevisionSession, "questionCount">;

function question(data: QuestionInput): ExerciseRecord {
  return {
    subject: "Francais",
    validation_status: "valide",
    source: "Serie CRPE Francais V3",
    is_published: true,
    created_at: createdAt,
    updated_at: createdAt,
    common_mistake: null,
    ...data,
  };
}

function buildSession(data: SessionInput): RevisionSession {
  return { ...data, questionCount: data.questions.length };
}

function qcm(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  choices: Array<{ id: string; label: string }>,
  value: string,
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
) {
  return question({
    id,
    subdomain,
    level,
    exercise_type: "qcm",
    instruction,
    support_text: null,
    choices,
    expected_answer: { mode: "single_choice", value },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
    topic_key: null,
    topic_label: null,
  });
}

function vraiFaux(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  value: boolean,
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
) {
  return question({
    id,
    subdomain,
    level,
    exercise_type: "vrai_faux",
    instruction,
    support_text: null,
    choices: [{ id: "true", label: "Vrai" }, { id: "false", label: "Faux" }],
    expected_answer: { mode: "boolean", value },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
    topic_key: null,
    topic_label: null,
  });
}

function reponseCourte(
  id: string,
  subdomain: ExerciseRecord["subdomain"],
  level: string,
  instruction: string,
  acceptableAnswers: string[],
  explanation: string,
  commonMistake: string,
  access_tier: ExerciseRecord["access_tier"],
  exercise_type: ExerciseRecord["exercise_type"] = "reponse_courte",
  support_text: string | null = null,
) {
  return question({
    id,
    subdomain,
    level,
    exercise_type,
    instruction,
    support_text,
    choices: null,
    expected_answer: { mode: "text", acceptableAnswers },
    detailed_explanation: explanation,
    common_mistake: commonMistake,
    access_tier,
    topic_key: null,
    topic_label: null,
  });
}

export const seriesV3BatchF: RevisionSession[] = [
  // ──────────────────────────────────────────────
  // Serie 1 : Formes de phrases
  // ──────────────────────────────────────────────
  buildSession({
    id: "fr-v3-serie-formes-de-phrases",
    title: "Les formes de phrases",
    summary: "Identifier et distinguer les formes de phrases (negative, passive, exclamative, emphatique, impersonnelle) par rapport aux types de phrases.",
    objective: "Maitriser la distinction type / forme de phrase selon la terminologie Eduscol 2021.",
    introduction:
      "La terminologie officielle de 2021 distingue clairement trois types de phrases (declaratif, interrogatif, imperatif) et plusieurs formes (negative, passive, exclamative, emphatique, impersonnelle). Chaque phrase combine obligatoirement un type et une ou plusieurs formes. Cette serie vous entraine a ne plus confondre ces deux plans d'analyse.",
    subdomain: "grammaire",
    topicKey: "formes_de_phrases",
    topicLabel: "Formes de phrases",
    level: "Intermediaire",
    exerciseTypeLabel: "QCM, Vrai/Faux, Reponse courte",
    estimatedMinutes: 12,
    access_tier: "free",
    recommendedOrder: 30,
    completionSummary: {
      skill: "Distinguer types et formes de phrases selon Eduscol 2021",
      keyPoints: [
        "Il existe trois types de phrases : declaratif, interrogatif, imperatif.",
        "L'exclamation est une forme de phrase, pas un type.",
        "La phrase de base est positive, active et non exclamative.",
        "La forme emphatique se realise par clivage ou detachement.",
      ],
      retryAdvice:
        "Partez toujours de la phrase de base (positive, active, non exclamative) et identifiez les ecarts : c'est la forme qui change.",
    },
    questions: [
      qcm(
        "v3f-fdp-1",
        "grammaire",
        "Intermediaire",
        "Selon la terminologie officielle Eduscol 2021, combien de types de phrases existe-t-il ?",
        [
          { id: "a", label: "Trois : declaratif, interrogatif, imperatif" },
          { id: "b", label: "Quatre : declaratif, interrogatif, imperatif, exclamatif" },
          { id: "c", label: "Cinq : declaratif, interrogatif, imperatif, exclamatif, injonctif" },
        ],
        "a",
        "La terminologie officielle de 2021 retient exactement trois types de phrases : declaratif, interrogatif et imperatif. L'exclamation n'est plus consideree comme un type mais comme une forme de phrase. C'est un point capital au CRPE car l'ancienne classification a quatre types est encore tres repandue dans les manuels scolaires anterieurs.",
        "Repondre quatre en incluant l'exclamatif, par habitude de l'ancienne classification.",
        "free",
      ),
      vraiFaux(
        "v3f-fdp-2",
        "grammaire",
        "Intermediaire",
        'Vrai ou faux : selon la terminologie Eduscol 2021, la phrase "Quel beau spectacle !" est de type exclamatif.',
        false,
        "L'exclamation est une forme de phrase, pas un type. La phrase \"Quel beau spectacle !\" est de type declaratif et de forme exclamative. La terminologie officielle ne reconnait que trois types : declaratif, interrogatif et imperatif. Dire \"type exclamatif\" est donc une erreur terminologique.",
        "Confondre forme exclamative et type exclamatif, par reflexe de l'ancienne grammaire.",
        "free",
      ),
      qcm(
        "v3f-fdp-3",
        "grammaire",
        "Intermediaire",
        'A quelle forme de phrase correspond la transformation suivante : "Le chat mange la souris" → "La souris est mangee par le chat" ?',
        [
          { id: "a", label: "Forme negative" },
          { id: "b", label: "Forme passive" },
          { id: "c", label: "Forme emphatique" },
          { id: "d", label: "Forme impersonnelle" },
        ],
        "b",
        "Le sujet de la phrase active (\"le chat\") devient complement d'agent introduit par \"par\", et le COD (\"la souris\") devient sujet grammatical. C'est la forme passive. Le verbe passe a la voix passive avec l'auxiliaire etre + participe passe. La phrase de base est active : toute transformation vers la voix passive releve de la forme passive.",
        "Confondre forme passive et forme impersonnelle, qui sont deux transformations distinctes.",
        "free",
      ),
      reponseCourte(
        "v3f-fdp-4",
        "grammaire",
        "Intermediaire",
        'Quelle est la forme de phrase illustree par le procede de clivage dans : "C\'est Paul qui a gagne la course" ?',
        ["forme emphatique", "emphatique"],
        "Le clivage est un procede de mise en relief qui consiste a encadrer un element par \"c'est... qui\" ou \"c'est... que\". C'est l'un des deux moyens de realiser la forme emphatique (l'autre etant le detachement). La phrase de base serait \"Paul a gagne la course\" : le clivage met l'accent sur le sujet \"Paul\".",
        "Repondre forme exclamative en confondant emphase et exclamation.",
        "free",
      ),
      qcm(
        "v3f-fdp-5",
        "grammaire",
        "Intermediaire",
        'Comment appelle-t-on la forme de phrase illustree dans : "Paul, lui, a reussi l\'examen" ?',
        [
          { id: "a", label: "Forme passive" },
          { id: "b", label: "Forme exclamative" },
          { id: "c", label: "Forme emphatique par detachement" },
          { id: "d", label: "Forme impersonnelle" },
        ],
        "c",
        "Le detachement (ou dislocation) est un procede de mise en relief ou un element est separe du reste de la phrase et repris par un pronom. Ici, \"Paul\" est detache et repris par \"lui\". C'est le second procede de la forme emphatique, a cote du clivage (\"C'est Paul qui...\"). La phrase de base serait simplement \"Paul a reussi l'examen\".",
        "Ne pas distinguer detachement et clivage dans les deux formes de l'emphase.",
        "free",
      ),
      vraiFaux(
        "v3f-fdp-6",
        "grammaire",
        "Intermediaire",
        'Vrai ou faux : la phrase de base, selon la terminologie officielle, est definie comme positive, active et non exclamative.',
        true,
        "C'est exact. La phrase de base (ou phrase canonique) sert de reference : elle est positive (pas de negation), active (pas de transformation passive) et non exclamative. Attention : on ne dit pas « forme positive » ni « forme active » — ce sont simplement les caracteristiques de la phrase de base. Les formes de phrases (negative, passive, exclamative, emphatique, impersonnelle) s'analysent comme des ecarts par rapport a cette base.",
        "Oublier le critere \"non exclamative\" et ne retenir que positif et actif.",
        "free",
      ),
      qcm(
        "v3f-fdp-7",
        "grammaire",
        "Intermediaire",
        'A quelle forme de phrase correspond la transformation : "Un accident grave s\'est produit" → "Il s\'est produit un accident grave" ?',
        [
          { id: "a", label: "Forme passive" },
          { id: "b", label: "Forme negative" },
          { id: "c", label: "Forme impersonnelle" },
          { id: "d", label: "Forme emphatique" },
        ],
        "c",
        "Le pronom \"il\" est ici un sujet grammatical impersonnel (il ne designe rien). Le vrai sujet semantique, \"un accident grave\", est rejete apres le verbe. C'est la forme impersonnelle. Elle se reconnait a la presence d'un \"il\" vide de sens suivi d'un groupe verbal dont le sujet logique est deplace. On la distingue de la forme passive car il n'y a pas de complement d'agent.",
        "Confondre forme impersonnelle et forme passive parce que le sujet semble deplace.",
        "free",
      ),
      reponseCourte(
        "v3f-fdp-8",
        "grammaire",
        "Intermediaire",
        'Identifiez la forme de phrase (autre que declaratif) dans : "Les enfants ne jouent pas dans la cour."',
        ["forme negative", "negative"],
        "La phrase \"Les enfants ne jouent pas dans la cour\" est de type declaratif et de forme negative. La negation est marquee par l'encadrement du verbe avec \"ne... pas\". La phrase de base correspondante serait \"Les enfants jouent dans la cour\" (positive). Attention : le type reste declaratif car la phrase fait une declaration, un constat.",
        "Repondre phrase negative en confondant type et forme de phrase.",
        "free",
      ),
      vraiFaux(
        "v3f-fdp-9",
        "grammaire",
        "Intermediaire",
        'Vrai ou faux : la phrase "Ne partez pas !" combine le type imperatif, la forme negative et la forme exclamative.',
        true,
        "Cette phrase est bien de type imperatif (elle donne un ordre avec un verbe a l'imperatif). Elle est de forme negative (\"ne... pas\") et de forme exclamative (point d'exclamation, intonation forte). Une phrase peut tout a fait combiner un type et plusieurs formes simultanement. C'est meme tres frequent a l'oral.",
        "Croire qu'une phrase ne peut avoir qu'une seule forme a la fois.",
        "free",
      ),
      qcm(
        "v3f-fdp-10",
        "grammaire",
        "Intermediaire",
        'Parmi ces phrases, laquelle est une phrase atypique (averbale) ?',
        [
          { id: "a", label: "Bravo !" },
          { id: "b", label: "Le soleil brille." },
          { id: "c", label: "Viens ici." },
          { id: "d", label: "Est-ce que tu viens ?" },
        ],
        "a",
        "\"Bravo !\" est une phrase averbale : elle ne contient aucun verbe conjugue et ne peut pas etre ramenee a une phrase de base canonique (sujet + verbe). Les phrases atypiques incluent les phrases averbales (\"Quelle chance !\"), les mots-phrases (\"Oui.\", \"Helas !\") et les phrases elliptiques. Elles echappent a l'analyse en types et formes car elles ne reposent pas sur un verbe.",
        "Croire que toute phrase avec un point d'exclamation est simplement exclamative sans voir qu'elle est aussi averbale.",
        "free",
      ),
    ],
  }),

  // ──────────────────────────────────────────────
  // Serie 2 : Expansion du nom
  // ──────────────────────────────────────────────
  buildSession({
    id: "fr-v3-serie-expansion-du-nom",
    title: "Les expansions du nom",
    summary: "Identifier et distinguer les expansions du nom : epithete, complement du nom, apposition et proposition subordonnee relative.",
    objective: "Reconnaitre les differentes expansions du groupe nominal selon la terminologie Eduscol 2021.",
    introduction:
      "Le groupe nominal minimal se compose d'un determinant et d'un nom (Det + N). Les expansions du nom viennent enrichir ce noyau : epithete, complement du nom, apposition, relative. Savoir les identifier est essentiel pour l'analyse grammaticale au CRPE et pour enseigner la construction des phrases aux eleves.",
    subdomain: "grammaire",
    topicKey: "expansion_du_nom",
    topicLabel: "Expansions du nom",
    level: "Intermediaire",
    exerciseTypeLabel: "QCM, Vrai/Faux, Reponse courte",
    estimatedMinutes: 12,
    access_tier: "free",
    recommendedOrder: 31,
    completionSummary: {
      skill: "Identifier et nommer les expansions du groupe nominal",
      keyPoints: [
        "Le GN minimal = determinant + nom. Les expansions enrichissent ce noyau.",
        "L'epithete est un adjectif (ou une relative adjective) lie directement au nom, sans virgule.",
        "Le complement du nom est un groupe prepositionnel qui se rapporte au nom.",
        "L'apposition est un element detache du nom, separe par des virgules.",
      ],
      retryAdvice:
        "Pour chaque expansion, demandez-vous : est-elle directement accolee au nom (epithete), introduite par une preposition (complement du nom), ou separee par des virgules (apposition) ?",
    },
    questions: [
      qcm(
        "v3f-edn-1",
        "grammaire",
        "Intermediaire",
        'Dans "La pharmacienne de mon quartier est aimable", quelle est la fonction de "de mon quartier" ?',
        [
          { id: "a", label: "Epithete" },
          { id: "b", label: "Complement du nom" },
          { id: "c", label: "Apposition" },
          { id: "d", label: "COD" },
        ],
        "b",
        "\"De mon quartier\" est un groupe nominal prepositionnel (GNP) qui se rapporte au nom \"pharmacienne\". Il apporte une precision sur ce nom en indiquant de quelle pharmacienne on parle. C'est donc un complement du nom. Le complement du nom est toujours introduit par une preposition (de, a, en, pour, sans...) et fait partie du groupe nominal elargi.",
        "Confondre complement du nom et complement circonstanciel de lieu.",
        "free",
      ),
      vraiFaux(
        "v3f-edn-2",
        "grammaire",
        "Intermediaire",
        'Vrai ou faux : dans "un livre passionnant", "passionnant" est une epithete du nom "livre".',
        true,
        "\"Passionnant\" est un adjectif qualificatif place directement apres le nom \"livre\", sans virgule ni preposition. Il qualifie ce nom et fait partie du groupe nominal : c'est bien une epithete. L'epithete est l'expansion du nom la plus simple : un adjectif (ou un participe employe comme adjectif) accole au nom, en position antéposée ou postposée.",
        "Repondre attribut parce que l'adjectif qualifie le nom, sans verifier la presence d'un verbe attributif.",
        "free",
      ),
      qcm(
        "v3f-edn-3",
        "grammaire",
        "Intermediaire",
        'Dans "Marie, excellente pianiste, donnera un recital", quelle est la fonction de "excellente pianiste" ?',
        [
          { id: "a", label: "Epithete" },
          { id: "b", label: "Complement du nom" },
          { id: "c", label: "Apposition" },
          { id: "d", label: "Attribut du sujet" },
        ],
        "c",
        "\"Excellente pianiste\" est separe du nom \"Marie\" par des virgules : c'est un element detache. Cette position detachee est la marque de l'apposition. L'apposition apporte une information supplementaire sur le nom mais elle est syntaxiquement mobile et supprimable. Sans les virgules, on aurait une epithete ou un complement du nom, mais le detachement signale l'apposition.",
        "Confondre apposition et epithete en ne remarquant pas la virgule de detachement.",
        "free",
      ),
      reponseCourte(
        "v3f-edn-4",
        "grammaire",
        "Intermediaire",
        'Dans "Le gateau au chocolat est delicieux", quelle est la fonction du groupe "au chocolat" par rapport au nom "gateau" ?',
        ["complement du nom", "CDN"],
        "\"Au chocolat\" (= a + le chocolat) est un groupe prepositionnel qui precise le nom \"gateau\". Il indique de quel type de gateau il s'agit. C'est un complement du nom. Il ne faut pas le confondre avec un complement circonstanciel, car il ne modifie pas le verbe mais bien le nom. Le complement du nom est toujours un GNP rattache au noyau nominal.",
        "Analyser \"au chocolat\" comme un complement circonstanciel de moyen ou de matiere.",
        "free",
      ),
      qcm(
        "v3f-edn-5",
        "grammaire",
        "Intermediaire",
        'Dans "L\'eleve qui travaille bien reussira", quelle est la nature de "qui travaille bien" et quelle est sa fonction ?',
        [
          { id: "a", label: "Proposition subordonnee relative, epithete (relative determinative)" },
          { id: "b", label: "Proposition subordonnee conjonctive, complement du nom" },
          { id: "c", label: "Proposition subordonnee relative, apposition" },
          { id: "d", label: "Proposition subordonnee relative, complement du verbe" },
        ],
        "a",
        "\"Qui travaille bien\" est une proposition subordonnee relative introduite par le pronom relatif \"qui\". Elle se rapporte au nom \"eleve\" et le determine sans virgule : c'est une relative determinative (ou restrictive), qui fonctionne comme une epithete. Elle restreint le sens du nom : on ne parle pas de n'importe quel eleve, mais de celui qui travaille bien.",
        "Confondre relative determinative (sans virgule, fonction d'epithete) et relative apposee (avec virgules, fonction d'apposition).",
        "free",
      ),
      vraiFaux(
        "v3f-edn-6",
        "grammaire",
        "Intermediaire",
        'Vrai ou faux : dans "Les enfants, qui etaient fatigues, se sont endormis", la relative "qui etaient fatigues" est une relative determinative (epithete).',
        false,
        "La relative \"qui etaient fatigues\" est encadree par des virgules : elle est donc detachee du nom. C'est une relative apposee (ou non restrictive), et non une relative determinative. Sa fonction est l'apposition, pas l'epithete. Elle apporte une information supplementaire mais ne restreint pas le sens du nom : tous les enfants etaient fatigues et se sont endormis.",
        "Ne pas preter attention aux virgules, qui sont pourtant le critere decisif entre relative determinative et relative apposee.",
        "free",
      ),
      qcm(
        "v3f-edn-7",
        "grammaire",
        "Intermediaire",
        'Quelle expansion du nom est presente dans "une robe en soie" ?',
        [
          { id: "a", label: "Epithete" },
          { id: "b", label: "Complement du nom" },
          { id: "c", label: "Apposition" },
          { id: "d", label: "Attribut du COD" },
        ],
        "b",
        "\"En soie\" est un groupe prepositionnel introduit par la preposition \"en\" qui se rapporte au nom \"robe\". Il precise la matiere de la robe. C'est un complement du nom. On le distingue de l'epithete car il est introduit par une preposition, et de l'apposition car il n'est pas detache par des virgules.",
        "Analyser \"en soie\" comme un complement circonstanciel de matiere rattache au verbe.",
        "free",
      ),
      reponseCourte(
        "v3f-edn-8",
        "grammaire",
        "Intermediaire",
        'Dans "une petite maison blanche", quelle est la fonction de "petite" et de "blanche" par rapport au nom "maison" ?',
        ["epithete", "epithetes"],
        "\"Petite\" et \"blanche\" sont deux adjectifs qualificatifs directement accoles au nom \"maison\" (l'un antepose, l'autre postpose), sans preposition ni virgule de detachement. Ce sont deux epithetes. L'epithete peut etre placee avant ou apres le nom. La position n'affecte pas la fonction, meme si elle peut modifier la nuance de sens.",
        "Penser qu'un adjectif antepose a une fonction differente d'un adjectif postpose.",
        "free",
      ),
      vraiFaux(
        "v3f-edn-9",
        "grammaire",
        "Intermediaire",
        'Vrai ou faux : "expansion du nom" est le terme general qui regroupe l\'epithete et le complement du nom.',
        true,
        "Oui, selon la terminologie Eduscol 2021, \"expansion du nom\" est le terme generique qui designe tout element venant enrichir le groupe nominal minimal (Det + N). Il regroupe l'epithete, le complement du nom, l'apposition et la relative. C'est un concept-parapluie tres utile pour l'analyse grammaticale en classe.",
        "Croire que \"expansion du nom\" ne designe que l'epithete.",
        "free",
      ),
      qcm(
        "v3f-edn-10",
        "grammaire",
        "Intermediaire",
        'Dans "Victor Hugo, auteur des Miserables, est ne en 1802", quelle est la fonction de "auteur des Miserables" ?',
        [
          { id: "a", label: "Epithete" },
          { id: "b", label: "Complement du nom" },
          { id: "c", label: "Apposition" },
          { id: "d", label: "Attribut du sujet" },
        ],
        "c",
        "\"Auteur des Miserables\" est un groupe nominal detache, encadre par des virgules, qui apporte une information supplementaire sur \"Victor Hugo\". C'est une apposition. Elle est supprimable (la phrase reste grammaticale sans elle) et mobile. L'apposition se distingue de l'attribut du sujet car il n'y a pas de verbe attributif : le lien se fait directement, par juxtaposition detachee.",
        "Confondre apposition et attribut du sujet en pensant qu'il y a une equivalence Victor Hugo = auteur.",
        "free",
      ),
    ],
  }),

  // ──────────────────────────────────────────────
  // Serie 3 : Complement d'agent et attribut du COD
  // ──────────────────────────────────────────────
  buildSession({
    id: "fr-v3-serie-complement-agent-attribut-cod",
    title: "Complement d'agent et attribut du COD",
    summary: "Identifier le complement d'agent dans les phrases passives et l'attribut du COD avec les verbes de jugement, de denomination ou de transformation.",
    objective: "Maitriser deux fonctions avancees qui apparaissent regulierement dans les sujets de grammaire du CRPE.",
    introduction:
      "Le complement d'agent et l'attribut du COD sont deux fonctions qui destabilisent souvent les candidats au CRPE. Le premier est propre a la forme passive et correspond au sujet de la phrase active. Le second attribue une qualite ou un statut au COD, avec des verbes comme juger, estimer, elire, nommer, rendre ou trouver. Cette serie vous entraine a les reperer avec assurance.",
    subdomain: "grammaire",
    topicKey: "complement_agent_attribut_cod",
    topicLabel: "Complement d'agent et attribut du COD",
    level: "Avance",
    exerciseTypeLabel: "QCM, Vrai/Faux, Reponse courte",
    estimatedMinutes: 14,
    access_tier: "premium",
    recommendedOrder: 32,
    completionSummary: {
      skill: "Reconnaitre le complement d'agent et l'attribut du COD",
      keyPoints: [
        "Le complement d'agent est propre a la forme passive et correspond au sujet de la phrase active equivalente.",
        "Il est generalement introduit par \"par\", parfois par \"de\".",
        "L'attribut du COD attribue une qualite ou un statut au COD, avec des verbes comme juger, estimer, elire, nommer, rendre, trouver.",
        "La structure est : Sujet + Verbe + COD + Attribut du COD.",
      ],
      retryAdvice:
        "Pour le complement d'agent, retransformez la phrase passive en phrase active : l'agent devient le sujet. Pour l'attribut du COD, verifiez si un element qualifie ou renomme le COD.",
    },
    questions: [
      qcm(
        "v3f-caac-1",
        "grammaire",
        "Avance",
        'Dans "La scene a ete racontee par deux temoins", quelle est la fonction de "par deux temoins" ?',
        [
          { id: "a", label: "Complement circonstanciel de moyen" },
          { id: "b", label: "Complement d'agent" },
          { id: "c", label: "Complement du nom" },
          { id: "d", label: "COD" },
        ],
        "b",
        "\"Par deux temoins\" est le complement d'agent du verbe passif \"a ete racontee\". En retransformant en phrase active, on obtient : \"Deux temoins ont raconte la scene.\" L'agent (\"deux temoins\") devient le sujet de la phrase active. Le complement d'agent est propre a la forme passive et est generalement introduit par \"par\", parfois par \"de\".",
        "Confondre complement d'agent et complement circonstanciel de moyen a cause de la preposition \"par\".",
        "premium",
      ),
      vraiFaux(
        "v3f-caac-2",
        "grammaire",
        "Avance",
        'Vrai ou faux : dans "Ce professeur est estime de tous ses collegues", "de tous ses collegues" est un complement d\'agent.',
        true,
        "Oui, \"est estime\" est une forme passive (auxiliaire etre + participe passe). \"De tous ses collegues\" est le complement d'agent, introduit ici par la preposition \"de\" et non par \"par\". Certains verbes passifs, notamment ceux exprimant un sentiment (estimer, aimer, connaitre, respecter), admettent \"de\" comme introducteur du complement d'agent. La phrase active equivalente est : \"Tous ses collegues estiment ce professeur.\"",
        "Ne pas reconnaitre le complement d'agent quand il est introduit par \"de\" au lieu de \"par\".",
        "premium",
      ),
      qcm(
        "v3f-caac-3",
        "grammaire",
        "Avance",
        'Dans "On a elu Alice presidente", quelle est la fonction de "presidente" ?',
        [
          { id: "a", label: "Attribut du sujet" },
          { id: "b", label: "COD" },
          { id: "c", label: "Attribut du COD" },
          { id: "d", label: "Apposition" },
        ],
        "c",
        "\"Presidente\" qualifie le COD \"Alice\" par l'intermediaire du verbe \"elire\". La structure est : On (sujet) + a elu (verbe) + Alice (COD) + presidente (attribut du COD). L'attribut du COD attribue une propriete ou un statut au complement d'objet direct. Il ne faut pas le confondre avec l'attribut du sujet (qui passe par un verbe attributif comme etre ou paraitre) ni avec un second COD.",
        "Analyser \"presidente\" comme un second COD ou comme une apposition.",
        "premium",
      ),
      reponseCourte(
        "v3f-caac-4",
        "grammaire",
        "Avance",
        'Dans "Ses amis le trouvent courageux", quelle est la fonction de "courageux" ?',
        ["attribut du COD", "attribut du cod"],
        "\"Courageux\" est l'attribut du COD \"le\" (pronom representant une personne). Le verbe \"trouver\", employe au sens de \"juger\", \"considerer\", fait partie des verbes qui introduisent un attribut du COD. La structure est : Ses amis (sujet) + le trouvent (verbe + COD) + courageux (attribut du COD). Si l'on supprime \"courageux\", la phrase change radicalement de sens.",
        "Analyser \"courageux\" comme un epithete ou un attribut du sujet.",
        "premium",
      ),
      qcm(
        "v3f-caac-5",
        "grammaire",
        "Avance",
        'Quel est le test le plus fiable pour identifier un complement d\'agent ?',
        [
          { id: "a", label: "Verifier qu'il est introduit par \"par\"" },
          { id: "b", label: "Retransformer la phrase passive en phrase active : l'agent devient le sujet" },
          { id: "c", label: "Verifier qu'il repond a la question \"par qui ?\"" },
          { id: "d", label: "Verifier qu'il est supprimable" },
        ],
        "b",
        "Le test le plus fiable est la transformation active/passive. Si le groupe introduit par \"par\" (ou \"de\") devient le sujet de la phrase active equivalente, c'est bien un complement d'agent. Le simple critere de la preposition \"par\" est insuffisant (\"Il passe par Paris\" : \"par Paris\" n'est pas un agent). La suppression n'est pas fiable non plus car certains complements circonstanciels sont aussi supprimables.",
        "Se contenter du critere \"introduit par par\" sans verifier par la transformation passive/active.",
        "premium",
      ),
      vraiFaux(
        "v3f-caac-6",
        "grammaire",
        "Avance",
        'Vrai ou faux : dans "Cette nouvelle a rendu Marie furieuse", "furieuse" est un attribut du COD.',
        true,
        "\"Furieuse\" est bien l'attribut du COD \"Marie\". Le verbe \"rendre\" est l'un des verbes typiques qui introduisent un attribut du COD : il exprime une transformation de l'etat du COD. La structure est : Cette nouvelle (sujet) + a rendu (verbe) + Marie (COD) + furieuse (attribut du COD). \"Furieuse\" qualifie Marie par l'intermediaire du verbe, pas directement.",
        "Confondre avec un attribut du sujet en inversant sujet et COD dans l'analyse.",
        "premium",
      ),
      qcm(
        "v3f-caac-7",
        "grammaire",
        "Avance",
        'Dans "Le gateau a ete prepare par le patissier", si l\'on retransforme en phrase active, que devient "par le patissier" ?',
        [
          { id: "a", label: "COD de la phrase active" },
          { id: "b", label: "Complement circonstanciel de la phrase active" },
          { id: "c", label: "Sujet de la phrase active" },
          { id: "d", label: "COI de la phrase active" },
        ],
        "c",
        "En phrase active : \"Le patissier a prepare le gateau.\" Le complement d'agent de la phrase passive (\"par le patissier\") devient le sujet de la phrase active. C'est la definition meme du complement d'agent : il designe l'etre ou la chose qui accomplit l'action exprimee par le verbe passif. Cette correspondance agent → sujet est le critere le plus sur pour identifier la fonction.",
        "Penser que le complement d'agent devient un complement dans la phrase active.",
        "premium",
      ),
      reponseCourte(
        "v3f-caac-8",
        "grammaire",
        "Avance",
        'Citez un verbe (autre que "elire" et "trouver") qui peut introduire un attribut du COD.',
        ["nommer", "juger", "estimer", "rendre", "croire", "considerer", "declarer", "appeler", "proclamer", "sacrer"],
        "Parmi les verbes qui introduisent un attribut du COD, on trouve : nommer (\"On l'a nomme directeur\"), juger (\"Je le juge competent\"), estimer (\"Ils l'estiment capable\"), rendre (\"Cela le rend heureux\"), croire (\"Je le crois sincere\"), declarer (\"Le jury l'a declare coupable\"). Ces verbes ont en commun d'exprimer un jugement, une denomination ou une transformation qui porte sur le COD.",
        "Ne penser qu'aux verbes de denomination et oublier les verbes de jugement ou de transformation.",
        "premium",
      ),
      qcm(
        "v3f-caac-9",
        "grammaire",
        "Avance",
        'Dans "Les delegues ont ete recus par la directrice dans son bureau", quelle est la fonction de "par la directrice" et celle de "dans son bureau" ?',
        [
          { id: "a", label: "Complement d'agent ; complement circonstanciel de lieu" },
          { id: "b", label: "Complement circonstanciel de moyen ; complement circonstanciel de lieu" },
          { id: "c", label: "Complement d'agent ; complement d'agent" },
          { id: "d", label: "Complement du nom ; complement circonstanciel de lieu" },
        ],
        "a",
        "\"Par la directrice\" est le complement d'agent : en transformant en phrase active, on obtient \"La directrice a recu les delegues dans son bureau\" (l'agent devient sujet). \"Dans son bureau\" est un complement circonstanciel de lieu : il indique l'endroit de l'action et ne change pas de fonction entre la phrase passive et la phrase active. Attention a ne pas confondre deux groupes introduits par des prepositions differentes.",
        "Analyser les deux groupes prepositionnels comme des complements d'agent sous pretexte qu'ils sont tous deux dans une phrase passive.",
        "premium",
      ),
      vraiFaux(
        "v3f-caac-10",
        "grammaire",
        "Avance",
        'Vrai ou faux : dans "Ils considerent cette mesure comme indispensable", "indispensable" est un attribut du COD de "cette mesure".',
        true,
        "\"Indispensable\" est bien l'attribut du COD \"cette mesure\". Le verbe \"considerer\" fait partie des verbes de jugement qui introduisent un attribut du COD, souvent avec la preposition \"comme\" (considerer comme, regarder comme). La structure est : Ils (sujet) + considerent (verbe) + cette mesure (COD) + comme indispensable (attribut du COD). La presence de \"comme\" ne change pas la fonction : \"indispensable\" qualifie le COD via le verbe.",
        "Analyser \"comme indispensable\" comme un complement circonstanciel de comparaison.",
        "premium",
      ),
    ],
  }),
];
