-- Migration: 20260366_seed_grammaire_nouvelles.sql
-- Deux nouvelles séries — Grammaire
-- Série 1 : gram_attribut_du_sujet (QCM, 10 questions)
-- Série 2 : gram_expansions_nom (Vrai/Faux, 10 questions)

-- ============================================================
-- SÉRIE 1 : gram_attribut_du_sujet — L'attribut du sujet et les verbes attributifs
-- ============================================================

INSERT INTO public.exercises (
  id, subject, subdomain, topic_key, topic_label, level,
  exercise_type, instruction, support_text, choices, expected_answer,
  detailed_explanation, common_mistake, validation_status, source, access_tier, is_published
) VALUES
(
  'fa100000-0000-0000-0000-000000000001',
  'Francais',
  'grammaire',
  'gram_attribut_du_sujet',
  'L''attribut du sujet et les verbes attributifs',
  'Intermediaire',
  'qcm',
  'Dans la phrase « Ce gâteau semble délicieux », quel est l''attribut du sujet ?',
  NULL,
  '[{"id":"a","label":"Ce gâteau"},{"id":"b","label":"semble"},{"id":"c","label":"délicieux"},{"id":"d","label":"semble délicieux"}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  'L''attribut du sujet est « délicieux ». Il est introduit par le verbe attributif « semble » et qualifie le sujet « Ce gâteau ». L''attribut du sujet exprime une propriété du sujet par l''intermédiaire d''un verbe attributif.',
  'Confondre le verbe attributif avec l''attribut lui-même. Le verbe « semble » n''est pas l''attribut : il sert de lien entre le sujet et sa propriété.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa100000-0000-0000-0000-000000000002',
  'Francais',
  'grammaire',
  'gram_attribut_du_sujet',
  'L''attribut du sujet et les verbes attributifs',
  'Intermediaire',
  'qcm',
  'Parmi ces verbes, lequel n''est PAS un verbe attributif ?',
  NULL,
  '[{"id":"a","label":"paraître"},{"id":"b","label":"devenir"},{"id":"c","label":"appartenir"},{"id":"d","label":"demeurer"}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  '« Appartenir » n''est pas un verbe attributif. Les verbes attributifs (être, sembler, paraître, devenir, rester, demeurer) relient le sujet à un attribut qui exprime une propriété ou un état du sujet. « Appartenir » est un verbe transitif indirect qui introduit un complément d''objet indirect, non un attribut.',
  'Croire que tous les verbes qui expriment une idée d''état sont des verbes attributifs. Seuls les verbes qui admettent un attribut du sujet (et non un COD ou COI) sont attributifs.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa100000-0000-0000-0000-000000000003',
  'Francais',
  'grammaire',
  'gram_attribut_du_sujet',
  'L''attribut du sujet et les verbes attributifs',
  'Intermediaire',
  'qcm',
  'Dans la phrase « Les enfants restent calmes pendant l''orage », quelle est la nature de l''attribut du sujet ?',
  NULL,
  '[{"id":"a","label":"Un nom commun"},{"id":"b","label":"Un adjectif qualificatif"},{"id":"c","label":"Un groupe prépositionnel"},{"id":"d","label":"Un adverbe"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  '« Calmes » est un adjectif qualificatif, attribut du sujet « Les enfants ». Il est relié au sujet par le verbe attributif « restent ». L''adjectif s''accorde en genre et en nombre avec le sujet : ici, masculin pluriel.',
  'Confondre l''attribut du sujet avec un complément circonstanciel. « Calmes » ne peut être ni supprimé ni déplacé sans changer le sens fondamental de la phrase.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa100000-0000-0000-0000-000000000004',
  'Francais',
  'grammaire',
  'gram_attribut_du_sujet',
  'L''attribut du sujet et les verbes attributifs',
  'Intermediaire',
  'qcm',
  'Dans la phrase « Ma sœur est médecin », quelle est la nature de l''attribut du sujet « médecin » ?',
  NULL,
  '[{"id":"a","label":"Un adjectif qualificatif"},{"id":"b","label":"Un nom commun"},{"id":"c","label":"Un participe passé"},{"id":"d","label":"Un groupe nominal avec déterminant"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  '« Médecin » est un nom commun employé sans déterminant comme attribut du sujet « Ma sœur ». L''attribut du sujet peut être un adjectif, mais aussi un nom ou un groupe nominal. Ici, « médecin » exprime une propriété (la profession) du sujet par l''intermédiaire du verbe attributif « est ».',
  'Penser que l''attribut du sujet est toujours un adjectif. Le nom commun peut aussi occuper la fonction d''attribut du sujet, notamment avec les verbes « être », « devenir », « rester ».',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa100000-0000-0000-0000-000000000005',
  'Francais',
  'grammaire',
  'gram_attribut_du_sujet',
  'L''attribut du sujet et les verbes attributifs',
  'Intermediaire',
  'qcm',
  'Dans la phrase « Pierre paraît fatigué depuis ce matin », peut-on supprimer « fatigué » sans rendre la phrase agrammaticale ?',
  NULL,
  '[{"id":"a","label":"Oui, car c''est un complément facultatif"},{"id":"b","label":"Non, car c''est un attribut du sujet, élément essentiel"},{"id":"c","label":"Oui, car c''est une épithète détachée"},{"id":"d","label":"Non, car c''est un complément d''objet direct"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'L''attribut du sujet est un constituant essentiel de la phrase : il ne peut être ni supprimé ni déplacé. Si on retire « fatigué », la phrase *« Pierre paraît depuis ce matin » devient sémantiquement incomplète (le verbe attributif « paraître » exige un attribut). C''est ce caractère obligatoire qui distingue l''attribut du complément circonstanciel.',
  'Confondre l''attribut du sujet avec une épithète détachée ou un complément circonstanciel. Contrairement à ces éléments, l''attribut est indispensable à la construction du verbe attributif.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa100000-0000-0000-0000-000000000006',
  'Francais',
  'grammaire',
  'gram_attribut_du_sujet',
  'L''attribut du sujet et les verbes attributifs',
  'Intermediaire',
  'qcm',
  'Quelle est la différence fondamentale entre un attribut du sujet et une épithète ?',
  NULL,
  '[{"id":"a","label":"L''épithète est toujours un adjectif, l''attribut jamais"},{"id":"b","label":"L''attribut est relié au sujet par un verbe attributif, l''épithète est directement liée au nom"},{"id":"c","label":"L''épithète est obligatoire, l''attribut est facultatif"},{"id":"d","label":"Il n''y a pas de différence, ce sont des synonymes"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'L''attribut du sujet est relié au sujet par l''intermédiaire d''un verbe attributif (être, sembler, devenir…), tandis que l''épithète est une expansion du nom qui se rattache directement au nom qu''elle qualifie, sans verbe intermédiaire. Par exemple : « un chat noir » (épithète) vs « Le chat est noir » (attribut du sujet).',
  'Croire que l''épithète et l''attribut sont interchangeables. Ce sont deux fonctions distinctes de l''adjectif : l''une dépend du nom, l''autre du verbe attributif.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa100000-0000-0000-0000-000000000007',
  'Francais',
  'grammaire',
  'gram_attribut_du_sujet',
  'L''attribut du sujet et les verbes attributifs',
  'Intermediaire',
  'qcm',
  'Dans la phrase « Les routes deviennent glissantes en hiver », quel test permet de confirmer que « glissantes » est attribut du sujet ?',
  NULL,
  '[{"id":"a","label":"On peut le remplacer par un adverbe"},{"id":"b","label":"On peut le supprimer sans modifier le sens"},{"id":"c","label":"On peut le remplacer par le pronom « le » (invariable)"},{"id":"d","label":"On peut le déplacer en début de phrase"}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  'L''attribut du sujet peut être pronominalisé par « le » invariable : « Les routes le deviennent ». Ce test de pronominalisation est un critère fiable pour identifier l''attribut du sujet. Contrairement au COD, le pronom « le » remplaçant un attribut est toujours invariable, quel que soit le genre ou le nombre du sujet.',
  'Confondre le « le » pronom attribut (invariable) avec le « le/la/les » pronom COD (variable). L''invariabilité de « le » est le signe distinctif de l''attribut.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa100000-0000-0000-0000-000000000008',
  'Francais',
  'grammaire',
  'gram_attribut_du_sujet',
  'L''attribut du sujet et les verbes attributifs',
  'Intermediaire',
  'qcm',
  'Dans la phrase « Elle a l''air sérieuse », avec quel mot s''accorde l''attribut « sérieuse » ?',
  NULL,
  '[{"id":"a","label":"Avec « air » (masculin singulier)"},{"id":"b","label":"Avec « elle » (féminin singulier)"},{"id":"c","label":"Avec le verbe « a »"},{"id":"d","label":"L''accord est libre, les deux sont possibles"}]'::jsonb,
  '{"mode":"single_choice","value":"b"}'::jsonb,
  'Lorsque « avoir l''air » signifie « sembler », l''adjectif attribut s''accorde avec le sujet : « Elle a l''air sérieuse » (féminin singulier, accord avec « elle »). En revanche, si « air » désigne l''expression du visage (sens concret), l''accord avec « air » est possible : « Elle a l''air sérieux (= un air sérieux) ». Dans l''usage courant au CRPE, on privilégie l''accord avec le sujet quand « avoir l''air » = « sembler ».',
  'Accorder systématiquement avec « air » (masculin). Quand « avoir l''air » fonctionne comme un verbe attributif, l''accord se fait avec le sujet.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa100000-0000-0000-0000-000000000009',
  'Francais',
  'grammaire',
  'gram_attribut_du_sujet',
  'L''attribut du sujet et les verbes attributifs',
  'Intermediaire',
  'qcm',
  'Le verbe « passer » dans la phrase « Les feuilles passent du vert au jaune » fonctionne-t-il comme un verbe attributif ?',
  NULL,
  '[{"id":"a","label":"Oui, car il exprime un changement d''état comme « devenir »"},{"id":"b","label":"Non, car « du vert au jaune » est un complément circonstanciel"},{"id":"c","label":"Oui, car il est suivi d''un adjectif"},{"id":"d","label":"Non, car « passer » est toujours un verbe d''action"}]'::jsonb,
  '{"mode":"single_choice","value":"a"}'::jsonb,
  'Dans cet emploi, « passer » fonctionne comme un verbe attributif : il exprime un changement d''état du sujet, à l''image de « devenir ». Certains verbes peuvent avoir un emploi attributif dans des contextes spécifiques sans figurer dans la liste canonique (être, sembler, paraître, devenir, rester, demeurer). Selon les programmes Éduscol, il est important de reconnaître ces emplois attributifs contextuels.',
  'Croire que seuls les six verbes attributifs canoniques peuvent introduire un attribut du sujet. D''autres verbes (passer, tomber, vivre…) peuvent occasionnellement fonctionner comme verbes attributifs.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa100000-0000-0000-0000-000000000010',
  'Francais',
  'grammaire',
  'gram_attribut_du_sujet',
  'L''attribut du sujet et les verbes attributifs',
  'Intermediaire',
  'qcm',
  'Dans la phrase « Le problème est que nous manquons de temps », quelle est la nature de l''attribut du sujet ?',
  NULL,
  '[{"id":"a","label":"Un adjectif qualificatif"},{"id":"b","label":"Un groupe nominal"},{"id":"c","label":"Une proposition subordonnée complétive"},{"id":"d","label":"Un groupe prépositionnel"}]'::jsonb,
  '{"mode":"single_choice","value":"c"}'::jsonb,
  'L''attribut du sujet est la proposition subordonnée complétive « que nous manquons de temps ». Introduite par la conjonction « que », elle occupe la fonction d''attribut du sujet « Le problème » par l''intermédiaire du verbe attributif « est ». L''attribut du sujet peut donc être un adjectif, un nom, un groupe nominal, un infinitif ou même une proposition subordonnée.',
  'Ne pas reconnaître qu''une proposition subordonnée peut occuper la fonction d''attribut du sujet. On réduit souvent l''attribut à l''adjectif ou au nom, mais la proposition complétive est également possible.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
)
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- SÉRIE 2 : gram_expansions_nom — Les expansions du nom
-- ============================================================

INSERT INTO public.exercises (
  id, subject, subdomain, topic_key, topic_label, level,
  exercise_type, instruction, support_text, choices, expected_answer,
  detailed_explanation, common_mistake, validation_status, source, access_tier, is_published
) VALUES
(
  'fa110000-0000-0000-0000-000000000001',
  'Francais',
  'grammaire',
  'gram_expansions_nom',
  'Les expansions du nom',
  'Intermediaire',
  'vrai_faux',
  'Dans la phrase « Le chat noir dort sur le canapé », le mot « noir » est une épithète liée du nom « chat ».',
  NULL,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  '« Noir » est bien une épithète liée du nom « chat ». L''épithète liée est un adjectif qualificatif placé directement à côté du nom qu''il qualifie, sans en être séparé par une virgule ou un verbe. Elle fait partie du groupe nominal « Le chat noir » et apporte une précision sur le nom noyau.',
  'Confondre épithète liée et attribut du sujet. Ici, « noir » n''est pas relié au sujet par un verbe attributif : il est directement adjoint au nom.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa110000-0000-0000-0000-000000000002',
  'Francais',
  'grammaire',
  'gram_expansions_nom',
  'Les expansions du nom',
  'Intermediaire',
  'vrai_faux',
  'Dans la phrase « Épuisée, Marie s''est assise sur un banc », « Épuisée » est une épithète liée du nom « Marie ».',
  NULL,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  '« Épuisée » est une épithète détachée (et non liée) du nom « Marie ». Elle est séparée du nom par une virgule et placée en tête de phrase. L''épithète détachée (aussi appelée apposition adjectivale) se distingue de l''épithète liée par cette séparation graphique et prosodique. Elle apporte une information secondaire sur le nom.',
  'Confondre épithète liée et épithète détachée. La présence de la virgule et l''éloignement du nom sont les indices de l''épithète détachée.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa110000-0000-0000-0000-000000000003',
  'Francais',
  'grammaire',
  'gram_expansions_nom',
  'Les expansions du nom',
  'Intermediaire',
  'vrai_faux',
  'Dans la phrase « La maison de mes grands-parents est immense », « de mes grands-parents » est un complément du nom.',
  NULL,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  '« De mes grands-parents » est bien un complément du nom « maison ». Le complément du nom est un groupe prépositionnel (introduit par une préposition : de, à, en, pour…) qui apporte une précision sur le nom noyau. Ici, il indique l''appartenance. Le complément du nom est l''une des trois grandes expansions du nom, avec l''épithète et la proposition subordonnée relative.',
  NULL,
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa110000-0000-0000-0000-000000000004',
  'Francais',
  'grammaire',
  'gram_expansions_nom',
  'Les expansions du nom',
  'Intermediaire',
  'vrai_faux',
  'Une proposition subordonnée relative est une expansion du nom introduite par un pronom relatif (qui, que, dont, où…).',
  NULL,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'La proposition subordonnée relative est effectivement une expansion du nom. Elle est introduite par un pronom relatif (qui, que, dont, où, lequel…) et complète un nom appelé antécédent. Par exemple, dans « Le livre que j''ai lu est passionnant », la relative « que j''ai lu » est une expansion du nom « livre ». Selon la terminologie Éduscol, c''est l''une des trois principales expansions du nom.',
  'Confondre la proposition subordonnée relative (expansion du nom) avec la proposition subordonnée complétive (qui complète un verbe).',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa110000-0000-0000-0000-000000000005',
  'Francais',
  'grammaire',
  'gram_expansions_nom',
  'Les expansions du nom',
  'Intermediaire',
  'vrai_faux',
  'Dans la phrase « L''homme qui court dans le parc est mon voisin », « dans le parc » est une expansion du nom « homme ».',
  NULL,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  '« Dans le parc » n''est pas une expansion du nom « homme ». C''est un complément circonstanciel de lieu au sein de la proposition subordonnée relative « qui court dans le parc ». L''expansion du nom « homme » est la proposition relative tout entière (« qui court dans le parc »), pas le groupe prépositionnel seul. Il faut distinguer ce qui complète le nom de ce qui complète le verbe à l''intérieur de la relative.',
  'Isoler un constituant interne à la relative et le considérer comme une expansion directe du nom antécédent. C''est la relative entière qui est l''expansion.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa110000-0000-0000-0000-000000000006',
  'Francais',
  'grammaire',
  'gram_expansions_nom',
  'Les expansions du nom',
  'Intermediaire',
  'vrai_faux',
  'Les expansions du nom sont toutes supprimables sans rendre la phrase agrammaticale.',
  NULL,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Les expansions du nom (épithète, complément du nom, proposition subordonnée relative) sont en principe des constituants facultatifs du groupe nominal. On peut les supprimer sans rendre la phrase agrammaticale : « Le chat noir dort » → « Le chat dort ». C''est précisément ce caractère facultatif qui les distingue des compléments essentiels du verbe. Attention cependant : la suppression peut appauvrir le sens, mais la phrase reste grammaticalement correcte.',
  'Croire que certaines expansions sont obligatoires. Par définition, une expansion du nom enrichit le GN mais n''est jamais syntaxiquement indispensable.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa110000-0000-0000-0000-000000000007',
  'Francais',
  'grammaire',
  'gram_expansions_nom',
  'Les expansions du nom',
  'Intermediaire',
  'vrai_faux',
  'Dans la phrase « J''ai acheté une robe en soie très élégante », « en soie » et « très élégante » sont toutes deux des expansions du nom « robe ».',
  NULL,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":true}'::jsonb,
  'Les deux groupes sont bien des expansions du nom « robe ». « En soie » est un complément du nom (groupe prépositionnel introduit par « en ») et « très élégante » est une épithète liée (adjectif qualificatif avec son adverbe d''intensité). Un même nom peut recevoir plusieurs expansions de nature différente, qui s''accumulent pour enrichir le groupe nominal.',
  'Penser qu''un nom ne peut avoir qu''une seule expansion. Plusieurs expansions de nature différente peuvent se combiner autour d''un même nom noyau.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa110000-0000-0000-0000-000000000008',
  'Francais',
  'grammaire',
  'gram_expansions_nom',
  'Les expansions du nom',
  'Intermediaire',
  'vrai_faux',
  'Dans la phrase « Le voyage en Italie était merveilleux », « merveilleux » est une expansion du nom « voyage ».',
  NULL,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  '« Merveilleux » n''est pas une expansion du nom « voyage ». C''est un attribut du sujet « Le voyage en Italie », relié à ce sujet par le verbe attributif « était ». L''attribut du sujet est une fonction liée au verbe, pas au nom. En revanche, « en Italie » est bien une expansion du nom « voyage » (complément du nom).',
  'Confondre l''attribut du sujet avec une épithète ou une autre expansion du nom. L''attribut dépend du verbe attributif, l''expansion dépend directement du nom.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa110000-0000-0000-0000-000000000009',
  'Francais',
  'grammaire',
  'gram_expansions_nom',
  'Les expansions du nom',
  'Intermediaire',
  'vrai_faux',
  'Dans la phrase « Les élèves, attentifs, écoutaient le professeur », « attentifs » est un complément du nom « élèves ».',
  NULL,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  '« Attentifs » n''est pas un complément du nom. C''est une épithète détachée du nom « élèves ». Le complément du nom est un groupe prépositionnel (ex. : « de la classe »), tandis qu''ici « attentifs » est un adjectif qualificatif séparé du nom par des virgules. L''épithète détachée est une expansion du nom, mais elle se distingue du complément du nom par sa nature (adjectif, non groupe prépositionnel) et par sa mobilité dans la phrase.',
  'Confondre complément du nom et épithète détachée. Le complément du nom est toujours un groupe prépositionnel, jamais un adjectif seul.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
),
(
  'fa110000-0000-0000-0000-000000000010',
  'Francais',
  'grammaire',
  'gram_expansions_nom',
  'Les expansions du nom',
  'Intermediaire',
  'vrai_faux',
  'Dans la phrase « Le chien dont je t''ai parlé a été adopté », « dont je t''ai parlé » est un complément du nom « chien ».',
  NULL,
  '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
  '{"mode":"boolean","value":false}'::jsonb,
  '« Dont je t''ai parlé » n''est pas un complément du nom au sens strict. C''est une proposition subordonnée relative, expansion du nom « chien ». Le complément du nom désigne spécifiquement un groupe prépositionnel (« du voisin », « en bois »…). La proposition subordonnée relative est une autre catégorie d''expansion du nom, introduite par un pronom relatif. Il est essentiel de distinguer ces trois types d''expansion : épithète, complément du nom, proposition subordonnée relative.',
  'Utiliser « complément du nom » comme terme générique pour toutes les expansions. Chaque type d''expansion a un nom précis en grammaire scolaire Éduscol.',
  'valide',
  'CRPE Français V4 — Grammaire',
  'premium',
  true
)
ON CONFLICT (id) DO NOTHING;
