-- Migration: add 10 grammar series "Tri par categories" (100 questions)

insert into public.exercises (
  id,
  subject,
  subdomain,
  topic_key,
  topic_label,
  level,
  exercise_type,
  instruction,
  support_text,
  choices,
  expected_answer,
  detailed_explanation,
  common_mistake,
  validation_status,
  source,
  access_tier,
  is_published
)
values
  (
    'e5010000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par categories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "Le chat dort", dans quelle categorie faut-il classer "chat" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Chat" est le noyau du groupe nominal sujet "Le chat" : c''est un nom.',
    'Se laisser guider par le sens global de la phrase sans reperer le groupe nominal.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par categories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "Les eleves parlent", dans quelle categorie faut-il classer "parlent" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Parlent" est le verbe conjugue de la phrase : il exprime l''action et s''accorde avec "les eleves".',
    'Confondre le mot qui porte l''action avec un nom d''action.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par categories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "une candidate courageuse", dans quelle categorie faut-il classer "courageuse" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Courageuse" qualifie le nom "candidate" et s''accorde avec lui : c''est un adjectif.',
    'Repondre epithete ou attribut alors que l''on demande la nature grammaticale.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par categories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "un conseil utile", dans quelle categorie faut-il classer "utile" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Utile" apporte une qualite au nom "conseil" : c''est un adjectif.',
    'Confondre l''adjectif avec le nom qu''il accompagne.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par categories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "Ils corrigent leur copie", dans quelle categorie faut-il classer "corrigent" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Corrigent" est le verbe conjugue de la phrase. Il commande le groupe verbal.',
    'Chercher le mot le plus important du sens au lieu de reperer le verbe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par categories : nom, verbe, adjectif',
    'Facile',
    'vrai_faux',
    'Vrai ou faux : dans "la reponse juste", "juste" est un adjectif.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Juste" qualifie le nom "reponse" : c''est bien un adjectif.',
    'Confondre la valeur de qualite avec une fonction syntaxique.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par categories : nom, verbe, adjectif',
    'Facile',
    'reponse_courte',
    'Dans "les eleves attentifs", dans quelle categorie faut-il classer "eleves" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["nom"]}'::jsonb,
    '"Eleves" est le noyau du groupe nominal. C''est donc un nom.',
    'Repondre sujet alors que la consigne demande une categorie grammaticale.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par categories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "La fatigue revient vite", dans quelle categorie faut-il classer "fatigue" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    'Ici "fatigue" est precede de l''article "la" : le mot est employe comme nom.',
    'Se fier au fait que fatiguer existe comme verbe sans regarder le contexte.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par categories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "Il calme le groupe", dans quelle categorie faut-il classer "calme" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    'Dans cette phrase, "calme" est le verbe conjugue qui dit ce que fait le sujet "il".',
    'Classer automatiquement calme comme adjectif parce qu''il peut aussi l''etre dans d''autres phrases.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par categories : nom, verbe, adjectif',
    'Facile',
    'vrai_faux',
    'Vrai ou faux : dans "un texte clair", "clair" appartient a la categorie des verbes.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":false}'::jsonb,
    '"Clair" qualifie le nom "texte" : ce n''est pas un verbe, mais un adjectif.',
    'Confondre un mot qualificatif avec le noyau du groupe verbal.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par categories : determinant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "ce manuel", dans quelle categorie faut-il classer "ce" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Ce" introduit le nom "manuel" : c''est un determinant demonstratif.',
    'Repondre pronom sans voir qu''un nom suit immediatement.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par categories : determinant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "ceux qui reussissent", dans quelle categorie faut-il classer "ceux" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Ceux" remplace un groupe nominal entier : c''est un pronom demonstratif.',
    'Chercher un nom apres le mot alors qu''il fonctionne seul.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par categories : determinant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "elle relit tres vite", dans quelle categorie faut-il classer "tres" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Tres" modifie l''adverbe "vite" : c''est un adverbe.',
    'Le classer parmi les mots-outils sans regarder ce qu''il modifie.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par categories : determinant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "leur cahier est pret", dans quelle categorie faut-il classer "leur" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Leur" accompagne le nom "cahier" : ici, c''est un determinant possessif.',
    'Confondre avec le pronom "leur" de "je leur parle".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par categories : determinant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "Demain, nous reviserons", dans quelle categorie faut-il classer "demain" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Demain" precise le moment de l''action : c''est un adverbe.',
    'Le traiter comme un nom de temps sans regarder sa fonction dans la phrase.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par categories : determinant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "Personne n''a repondu", dans quelle categorie faut-il classer "personne" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Personne" remplace un groupe nominal et occupe la place du sujet : c''est un pronom indefini.',
    'Confondre le mot avec le nom "personne" dans "une personne".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par categories : determinant, pronom, adverbe',
    'Facile',
    'vrai_faux',
    'Vrai ou faux : dans "elles reussissent vite", "vite" est un adverbe.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Vite" modifie le verbe "reussissent" : c''est bien un adverbe.',
    'Le classer comme adjectif parce qu''il exprime une qualite.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par categories : determinant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "ces regles sont utiles", dans quelle categorie faut-il classer "ces" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Ces" introduit le nom "regles" : c''est un determinant demonstratif.',
    'Oublier de verifier si le mot est suivi d''un nom.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par categories : determinant, pronom, adverbe',
    'Facile',
    'reponse_courte',
    'Dans "Beaucoup travaillent en silence", dans quelle categorie faut-il classer "beaucoup" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["pronom"]}'::jsonb,
    'Dans cette phrase, "beaucoup" remplace un groupe de personnes : il est employe comme pronom indefini.',
    'Repondre adverbe par automatisme sans regarder qu''il est sujet du verbe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par categories : determinant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "Il travaille beaucoup", dans quelle categorie faut-il classer "beaucoup" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    'Ici, "beaucoup" modifie le verbe "travaille" : c''est un adverbe.',
    'Ne pas voir que le meme mot peut changer de categorie selon le contexte.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par categories : mots de liaison',
    'Intermediaire',
    'qcm',
    'Dans "Il part parce qu''il est fatigue", dans quelle categorie faut-il classer "parce que" ?',
    null,
    '[{"id":"a","label":"Preposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Parce que" introduit une proposition subordonnee de cause : c''est une conjonction de subordination.',
    'Confondre la relation logique de cause avec une coordination.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par categories : mots de liaison',
    'Intermediaire',
    'qcm',
    'Dans "Il voulait venir, mais il etait malade", dans quelle categorie faut-il classer "mais" ?',
    null,
    '[{"id":"a","label":"Preposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Mais" relie deux propositions de meme niveau : c''est une conjonction de coordination.',
    'Le traiter comme un simple mot logique sans nommer sa vraie nature.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par categories : mots de liaison',
    'Intermediaire',
    'qcm',
    'Dans "dans la classe", dans quelle categorie faut-il classer "dans" ?',
    null,
    '[{"id":"a","label":"Preposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Dans" introduit le groupe prepositionnel "dans la classe" : c''est une preposition.',
    'Confondre l''introduction d''un groupe avec l''introduction d''une proposition.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par categories : mots de liaison',
    'Intermediaire',
    'qcm',
    'Dans "quoique le cas soit rare", dans quelle categorie faut-il classer "quoique" ?',
    null,
    '[{"id":"a","label":"Preposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Quoique" introduit une proposition subordonnee de concession : c''est une conjonction de subordination.',
    'Le rapprocher a tort de ou ou de mais.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par categories : mots de liaison',
    'Intermediaire',
    'qcm',
    'Dans "avec soin", dans quelle categorie faut-il classer "avec" ?',
    null,
    '[{"id":"a","label":"Preposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Avec" introduit un groupe prepositionnel : c''est une preposition.',
    'Confondre la relation de moyen avec un lien entre deux propositions.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par categories : mots de liaison',
    'Intermediaire',
    'vrai_faux',
    'Vrai ou faux : dans "ni Paul ni Lea", "ni" est une conjonction de coordination.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Ni" appartient au groupe des conjonctions de coordination. Il relie ici deux elements de meme niveau dans un contexte negatif.',
    'Oublier que les coordinations ne sont pas limitees a et et mais.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par categories : mots de liaison',
    'Intermediaire',
    'qcm',
    'Dans "afin qu''il comprenne", dans quelle categorie faut-il classer "afin que" ?',
    null,
    '[{"id":"a","label":"Preposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Afin que" introduit une subordonnee de but : c''est une conjonction de subordination.',
    'Chercher un nom apres la locution alors qu''elle introduit un verbe conjugue.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par categories : mots de liaison',
    'Intermediaire',
    'qcm',
    'Dans "chez le voisin", dans quelle categorie faut-il classer "chez" ?',
    null,
    '[{"id":"a","label":"Preposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Chez" introduit un groupe nominal : c''est une preposition.',
    'Le confondre avec un adverbe de lieu.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par categories : mots de liaison',
    'Intermediaire',
    'reponse_courte',
    'Dans "car il avait revise", dans quelle categorie faut-il classer "car" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["conjonction de coordination","coordination"]}'::jsonb,
    '"Car" est une conjonction de coordination exprimant la cause.',
    'Le classer parmi les subordonnants parce qu''il donne une explication.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par categories : mots de liaison',
    'Intermediaire',
    'qcm',
    'Dans "Il est pret, or son binome ne l''est pas", dans quelle categorie faut-il classer "or" ?',
    null,
    '[{"id":"a","label":"Preposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Or" relie deux propositions de meme niveau en introduisant une nuance logique : c''est une conjonction de coordination.',
    'Ne pas connaitre cette conjonction plus rare et la ranger parmi les adverbes.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par categories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle categorie faut-il classer "rapidement" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Rapidement" est un adverbe : il ne varie pas.',
    'Penser que tous les mots longs ou derives sont necessairement variables.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par categories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle categorie faut-il classer "belles" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Belles" est un adjectif qualificatif : il varie selon le genre et le nombre.',
    'Confondre la forme observee avec la propriete generale du mot.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par categories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle categorie faut-il classer "leurs" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Leurs" est un determinant possessif : il varie au moins en nombre.',
    'Le confondre avec une forme figee a cause de sa terminaison deja marquee.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par categories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle categorie faut-il classer "tres" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Tres" est un adverbe : il est invariable.',
    'Chercher une variation de sens au lieu de regarder la forme.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par categories : variables ou invariables',
    'Facile',
    'vrai_faux',
    'Vrai ou faux : "parce que" appartient a la categorie des mots invariables.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'La locution conjonctive "parce que" ne varie pas : elle est invariable.',
    'Oublier que certaines locutions entieres fonctionnent comme des mots invariables.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par categories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle categorie faut-il classer "jamais" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Jamais" est un adverbe : sa forme ne varie pas.',
    'Le ranger parmi les pronoms ou les determinants parce qu''il est frequemment employe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par categories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle categorie faut-il classer "nous" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Nous" appartient au systeme des pronoms personnels, qui varie selon la personne et le nombre.',
    'Penser qu''un mot court est forcement invariable.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par categories : variables ou invariables',
    'Facile',
    'reponse_courte',
    'Dans "cet exercice", "cet" est-il variable ou invariable ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["variable"]}'::jsonb,
    '"Cet" est un determinant demonstratif. Il varie selon le genre et le nombre : ce, cet, cette, ces.',
    'Oublier les autres formes possibles du determinant demonstratif.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par categories : variables ou invariables',
    'Facile',
    'vrai_faux',
    'Vrai ou faux : le mot "et" peut prendre une marque de pluriel.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":false}'::jsonb,
    '"Et" est une conjonction de coordination invariable. Il ne prend jamais de marque de genre ou de nombre.',
    'Confondre la notion de coordination avec un accord syntaxique.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par categories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle categorie faut-il classer "hier" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Hier" est un adverbe de temps. Il est invariable.',
    'Le confondre avec un nom de date ou de moment.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par categories : familles de determinants',
    'Intermediaire',
    'qcm',
    'Dans "les eleves", dans quelle famille faut-il classer "les" ?',
    null,
    '[{"id":"a","label":"Article defini"},{"id":"b","label":"Article indefini"},{"id":"c","label":"Determinant possessif"},{"id":"d","label":"Determinant demonstratif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Les" est l''article defini pluriel.',
    'Le classer comme demonstratif parce qu''il montre un groupe deja connu.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par categories : familles de determinants',
    'Intermediaire',
    'qcm',
    'Dans "un exemple", dans quelle famille faut-il classer "un" ?',
    null,
    '[{"id":"a","label":"Article defini"},{"id":"b","label":"Article indefini"},{"id":"c","label":"Article partitif"},{"id":"d","label":"Determinant possessif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Un" introduit ici un nom non encore identifie : c''est un article indefini.',
    'Confondre article indefini et numeral.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par categories : familles de determinants',
    'Intermediaire',
    'qcm',
    'Dans "du courage", dans quelle famille faut-il classer "du" ?',
    null,
    '[{"id":"a","label":"Article defini contracte"},{"id":"b","label":"Article indefini"},{"id":"c","label":"Article partitif"},{"id":"d","label":"Determinant demonstratif"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Du" devant un nom massif comme "courage" est un article partitif.',
    'Le traiter comme la contraction de de le sans regarder le sens partitif.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par categories : familles de determinants',
    'Intermediaire',
    'qcm',
    'Dans "ces copies", dans quelle famille faut-il classer "ces" ?',
    null,
    '[{"id":"a","label":"Determinant demonstratif"},{"id":"b","label":"Determinant possessif"},{"id":"c","label":"Determinant indefini"},{"id":"d","label":"Article defini"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Ces" sert a designer : c''est un determinant demonstratif.',
    'Le confondre avec le possessif "ses".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par categories : familles de determinants',
    'Intermediaire',
    'qcm',
    'Dans "mon cahier", dans quelle famille faut-il classer "mon" ?',
    null,
    '[{"id":"a","label":"Determinant demonstratif"},{"id":"b","label":"Determinant possessif"},{"id":"c","label":"Determinant indefini"},{"id":"d","label":"Article indefini"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Mon" marque la possession : c''est un determinant possessif.',
    'Le traiter comme un simple article devant un nom singulier.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par categories : familles de determinants',
    'Intermediaire',
    'qcm',
    'Dans "plusieurs candidats", dans quelle famille faut-il classer "plusieurs" ?',
    null,
    '[{"id":"a","label":"Determinant demonstratif"},{"id":"b","label":"Determinant possessif"},{"id":"c","label":"Determinant indefini"},{"id":"d","label":"Article defini"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Plusieurs" donne une quantite non precisee exactement : c''est un determinant indefini.',
    'Le reduire a une simple indication numerique sans voir sa categorie.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par categories : familles de determinants',
    'Intermediaire',
    'vrai_faux',
    'Vrai ou faux : dans "Quel livre choisis-tu ?", "quel" est un determinant interrogatif.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Quel" introduit le nom "livre" dans une question : c''est un determinant interrogatif.',
    'Oublier qu''un meme mot peut etre interrogatif ou exclamatif selon le contexte.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par categories : familles de determinants',
    'Intermediaire',
    'reponse_courte',
    'Dans "Quelle belle idee !", dans quelle famille faut-il classer "Quelle" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["determinant exclamatif","exclamatif"]}'::jsonb,
    'Ici "Quelle" introduit le nom "idee" dans une exclamation : c''est un determinant exclamatif.',
    'Repondre interrogatif uniquement a cause de la forme du mot.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par categories : familles de determinants',
    'Intermediaire',
    'qcm',
    'Dans "aucun eleve", dans quelle famille faut-il classer "aucun" ?',
    null,
    '[{"id":"a","label":"Determinant indefini"},{"id":"b","label":"Determinant possessif"},{"id":"c","label":"Article defini"},{"id":"d","label":"Article partitif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Aucun" exprime une quantite nulle sans designer : c''est un determinant indefini.',
    'Le prendre pour un adverbe negatif.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par categories : familles de determinants',
    'Intermediaire',
    'qcm',
    'Dans "notre projet", dans quelle famille faut-il classer "notre" ?',
    null,
    '[{"id":"a","label":"Determinant demonstratif"},{"id":"b","label":"Determinant possessif"},{"id":"c","label":"Determinant indefini"},{"id":"d","label":"Article defini"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Notre" exprime la possession : c''est un determinant possessif.',
    'Confondre la possession avec une simple designation du nom.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par categories : familles de pronoms',
    'Intermediaire',
    'qcm',
    'Dans "il reussit", dans quelle famille faut-il classer "il" ?',
    null,
    '[{"id":"a","label":"Pronom personnel"},{"id":"b","label":"Pronom demonstratif"},{"id":"c","label":"Pronom relatif"},{"id":"d","label":"Pronom indefini"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Il" appartient a la serie des pronoms personnels.',
    'Le classer comme demonstratif parce qu''il renvoie a quelqu''un deja connu.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par categories : familles de pronoms',
    'Intermediaire',
    'qcm',
    'Dans "ceux-ci sont prets", dans quelle famille faut-il classer "ceux-ci" ?',
    null,
    '[{"id":"a","label":"Pronom personnel"},{"id":"b","label":"Pronom demonstratif"},{"id":"c","label":"Pronom possessif"},{"id":"d","label":"Pronom relatif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Ceux-ci" sert a designer un groupe : c''est un pronom demonstratif.',
    'Le confondre avec un determinant alors qu''il fonctionne seul.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par categories : familles de pronoms',
    'Intermediaire',
    'qcm',
    'Dans "Le mien est range", dans quelle famille faut-il classer "mien" ?',
    null,
    '[{"id":"a","label":"Pronom possessif"},{"id":"b","label":"Pronom demonstratif"},{"id":"c","label":"Pronom personnel"},{"id":"d","label":"Pronom relatif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Le mien" remplace un groupe nominal en marquant la possession : c''est un pronom possessif.',
    'Le prendre pour un adjectif possessif sans voir qu''aucun nom ne suit.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par categories : familles de pronoms',
    'Intermediaire',
    'qcm',
    'Dans "La fille qui lit", dans quelle famille faut-il classer "qui" ?',
    null,
    '[{"id":"a","label":"Pronom indefini"},{"id":"b","label":"Pronom demonstratif"},{"id":"c","label":"Pronom relatif"},{"id":"d","label":"Pronom personnel"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Qui" introduit une relative et reprend l''antecedent "fille" : c''est un pronom relatif.',
    'Le ranger parmi les interrogatifs uniquement a cause de sa forme.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par categories : familles de pronoms',
    'Intermediaire',
    'qcm',
    'Dans "Personne ne bouge", dans quelle famille faut-il classer "personne" ?',
    null,
    '[{"id":"a","label":"Pronom indefini"},{"id":"b","label":"Pronom personnel"},{"id":"c","label":"Pronom possessif"},{"id":"d","label":"Pronom demonstratif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Personne" designe un referent non specifie : c''est un pronom indefini.',
    'Le confondre avec le nom "personne".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par categories : familles de pronoms',
    'Intermediaire',
    'vrai_faux',
    'Vrai ou faux : dans "Qui vient ?", "Qui" est un pronom interrogatif.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'Dans une question directe, "qui" est bien un pronom interrogatif.',
    'Confondre forme interrogative et relative sans regarder l''absence d''antecedent.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par categories : familles de pronoms',
    'Intermediaire',
    'qcm',
    'Dans "Celui-la est plus clair", dans quelle famille faut-il classer "Celui-la" ?',
    null,
    '[{"id":"a","label":"Pronom possessif"},{"id":"b","label":"Pronom demonstratif"},{"id":"c","label":"Pronom personnel"},{"id":"d","label":"Pronom interrogatif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Celui-la" designe un element : c''est un pronom demonstratif.',
    'Chercher un nom absent au lieu de regarder la fonction autonome du mot.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par categories : familles de pronoms',
    'Intermediaire',
    'reponse_courte',
    'Dans "Les tiens arrivent", dans quelle famille faut-il classer "les tiens" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["pronom possessif","possessif"]}'::jsonb,
    '"Les tiens" remplace un groupe nominal tout en marquant la possession : c''est un pronom possessif.',
    'Le confondre avec un determinant possessif alors qu''il n''introduit aucun nom.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par categories : familles de pronoms',
    'Intermediaire',
    'qcm',
    'Dans "J''en veux encore", dans quelle famille faut-il classer "en" ?',
    null,
    '[{"id":"a","label":"Pronom personnel"},{"id":"b","label":"Pronom demonstratif"},{"id":"c","label":"Pronom relatif"},{"id":"d","label":"Pronom indefini"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"En" est ici un pronom personnel adverbial qui reprend un complement.',
    'Le ranger comme adverbe parce qu''il est court et place avant le verbe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par categories : familles de pronoms',
    'Intermediaire',
    'qcm',
    'Dans "Chacun avance a son rythme", dans quelle famille faut-il classer "chacun" ?',
    null,
    '[{"id":"a","label":"Pronom indefini"},{"id":"b","label":"Pronom personnel"},{"id":"c","label":"Pronom possessif"},{"id":"d","label":"Pronom interrogatif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Chacun" designe un element d''un ensemble sans le nommer : c''est un pronom indefini.',
    'Le confondre avec un determinant parce qu''il exprime une distribution.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par categories : formes verbales',
    'Intermediaire',
    'qcm',
    'Dans quelle categorie faut-il classer "manger" ?',
    null,
    '[{"id":"a","label":"Verbe conjugue"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passe"},{"id":"d","label":"Participe present"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Manger" est la forme de base du verbe : c''est un infinitif.',
    'Le confondre avec une forme conjuguee en -er par simple ressemblance visuelle.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par categories : formes verbales',
    'Intermediaire',
    'qcm',
    'Dans "Il mange vite", dans quelle categorie faut-il classer "mange" ?',
    null,
    '[{"id":"a","label":"Verbe conjugue"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passe"},{"id":"d","label":"Participe present"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Mange" est une forme personnelle, ici au present de l''indicatif : c''est un verbe conjugue.',
    'Ne pas tenir compte du sujet il et de la relation d''accord.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par categories : formes verbales',
    'Intermediaire',
    'qcm',
    'Dans "La porte fermee", dans quelle categorie faut-il classer "fermee" ?',
    null,
    '[{"id":"a","label":"Verbe conjugue"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passe"},{"id":"d","label":"Participe present"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Fermee" est une forme en -e issue du verbe "fermer" : c''est un participe passe.',
    'La classer comme adjectif sans voir sa nature verbale d''origine dans ce tri specifique.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par categories : formes verbales',
    'Intermediaire',
    'qcm',
    'Dans "Un eleve souriant", dans quelle categorie faut-il classer "souriant" ?',
    null,
    '[{"id":"a","label":"Verbe conjugue"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passe"},{"id":"d","label":"Participe present"}]'::jsonb,
    '{"mode":"single_choice","value":"d"}'::jsonb,
    '"Souriant" est ici un participe present.',
    'Confondre terminaison en -ant et gerondif sans verifier la presence de en.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par categories : formes verbales',
    'Intermediaire',
    'qcm',
    'Dans "Elle semble avoir compris", dans quelle categorie faut-il classer "avoir" ?',
    null,
    '[{"id":"a","label":"Verbe conjugue"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passe"},{"id":"d","label":"Participe present"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Avoir" est a l''infinitif apres le verbe "semble".',
    'Le confondre avec un auxiliaire conjugue parce qu''il appartient au systeme verbal.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par categories : formes verbales',
    'Intermediaire',
    'vrai_faux',
    'Vrai ou faux : dans "Ils avaient ferme la porte", "ferme" est un participe passe.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Ferme" est le participe passe employe avec l''auxiliaire "avaient".',
    'Le prendre pour un adjectif a cause de sa forme proche.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par categories : formes verbales',
    'Intermediaire',
    'reponse_courte',
    'Dans "Les volets ouverts laissaient entrer la lumiere", dans quelle categorie faut-il classer "ouverts" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["participe passe"]}'::jsonb,
    '"Ouverts" est un participe passe issu du verbe "ouvrir".',
    'Repondre adjectif sans respecter le tri demande sur les formes verbales.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par categories : formes verbales',
    'Intermediaire',
    'qcm',
    'Dans "Nous finissons a midi", dans quelle categorie faut-il classer "finissons" ?',
    null,
    '[{"id":"a","label":"Verbe conjugue"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passe"},{"id":"d","label":"Participe present"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Finissons" est une forme conjuguee a la 1re personne du pluriel.',
    'Oublier que les terminaisons personnelles marquent une conjugaison.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par categories : formes verbales',
    'Intermediaire',
    'vrai_faux',
    'Vrai ou faux : dans "Souriant, il entra", "souriant" est un participe present.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'Ici "souriant" est bien un participe present employe en construction detachee.',
    'Le confondre avec un adjectif pur sans tenir compte du tri verbal.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par categories : formes verbales',
    'Intermediaire',
    'qcm',
    'Dans "Il va venir", dans quelle categorie faut-il classer "venir" ?',
    null,
    '[{"id":"a","label":"Verbe conjugue"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passe"},{"id":"d","label":"Participe present"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Venir" est a l''infinitif apres le semi-auxiliaire "va".',
    'Le classer comme verbe conjugue a cause de la locution verbale globale.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par categories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Tout candidat doit relire", dans quelle categorie faut-il classer "Tout" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Tout" accompagne le nom "candidat" : c''est un determinant.',
    'Le confondre avec un pronom parce qu''il exprime la totalite.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par categories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Tous sont prets", dans quelle categorie faut-il classer "Tous" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Tous" remplace un groupe nominal entier : c''est un pronom.',
    'Chercher un nom absent apres le mot.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par categories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Elle est tout heureuse", dans quelle categorie faut-il classer "tout" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Tout" modifie l''adjectif "heureuse" : c''est un adverbe.',
    'Le classer comme adjectif a cause de l''accord possible dans d''autres contextes.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par categories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Le tout est de commencer", dans quelle categorie faut-il classer "tout" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"d"}'::jsonb,
    'Dans cette tournure lexicalisee, "tout" est employe comme nom.',
    'Vouloir forcer un classement en pronom parce qu''il renvoie a un ensemble.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par categories : le mot "tout"',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Il a lu tout le chapitre", "tout" est un determinant.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Tout" accompagne le nom "chapitre" : c''est un determinant.',
    'Le confondre avec un adverbe de quantite.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par categories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Elles sont toutes contentes", dans quelle categorie faut-il classer "toutes" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    'Ici "toutes" modifie l''adjectif "contentes". Malgre l''accord graphique, il s''agit d''un adverbe.',
    'Penser que toute marque d''accord exclut la categorie adverbe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par categories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Ils ont tout compris", dans quelle categorie faut-il classer "tout" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Tout" remplace ici l''ensemble des choses comprises : c''est un pronom.',
    'Le confondre avec un adverbe d''intensite.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par categories : le mot "tout"',
    'Difficile',
    'reponse_courte',
    'Dans "Toute la classe ecoute", dans quelle categorie faut-il classer "Toute" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["determinant"]}'::jsonb,
    '"Toute" introduit le nom "classe" : c''est un determinant.',
    'Repondre adjectif sans regarder la structure du groupe nominal.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par categories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Le bebe est tout petit", dans quelle categorie faut-il classer "tout" ?',
    null,
    '[{"id":"a","label":"Determinant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Tout" modifie l''adjectif "petit" : c''est un adverbe.',
    'Le prendre pour un determinant en raison du sens de totalite.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par categories : le mot "tout"',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Le tout forme un ensemble coherent", "tout" est un nom.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'Dans cette phrase, "tout" est bien employe comme nom.',
    'Confondre emploi nominal et reprise pronominale.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par categories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Le livre que tu lis est dense", dans quelle categorie faut-il classer "que" ?',
    null,
    '[{"id":"a","label":"Pronom relatif"},{"id":"b","label":"Conjonction de subordination"},{"id":"c","label":"Pronom interrogatif"},{"id":"d","label":"Adverbe restrictif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Que" reprend l''antecedent "livre" et introduit une relative : c''est un pronom relatif.',
    'Le classer comme conjonction en oubliant l''antecedent.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par categories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Je pense qu''il a raison", dans quelle categorie faut-il classer "que" ?',
    null,
    '[{"id":"a","label":"Pronom relatif"},{"id":"b","label":"Conjonction de subordination"},{"id":"c","label":"Pronom interrogatif"},{"id":"d","label":"Determinant exclamatif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    'Ici "que" introduit une subordonnee completive et ne reprend aucun antecedent : c''est une conjonction de subordination.',
    'Repondre pronom relatif a chaque fois que le mot introduit une proposition.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par categories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Il ne parle que de cela", dans quelle categorie faut-il classer "que" ?',
    null,
    '[{"id":"a","label":"Pronom relatif"},{"id":"b","label":"Conjonction de subordination"},{"id":"c","label":"Adverbe restrictif"},{"id":"d","label":"Pronom interrogatif"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    'Dans la tournure "ne... que", "que" marque la restriction : c''est un adverbe restrictif.',
    'Chercher une proposition subordonnee alors qu''il s''agit d''une tournure negative restrictive.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par categories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Que de questions !", dans quelle categorie faut-il classer "Que" ?',
    null,
    '[{"id":"a","label":"Pronom interrogatif"},{"id":"b","label":"Conjonction de subordination"},{"id":"c","label":"Adverbe restrictif"},{"id":"d","label":"Determinant exclamatif"}]'::jsonb,
    '{"mode":"single_choice","value":"d"}'::jsonb,
    '"Que" introduit ici le nom "questions" dans une exclamation : c''est un determinant exclamatif.',
    'Le classer comme pronom uniquement a cause de sa forme.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par categories : le mot "que"',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Que veux-tu ?", "que" est un pronom interrogatif.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'Dans cette question directe, "que" est bien un pronom interrogatif.',
    'Confondre toute interrogation avec une subordonnee.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par categories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Que cherches-tu exactement ?", dans quelle categorie faut-il classer "Que" ?',
    null,
    '[{"id":"a","label":"Pronom interrogatif"},{"id":"b","label":"Pronom relatif"},{"id":"c","label":"Conjonction de subordination"},{"id":"d","label":"Adverbe restrictif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    'Que sert ici a interroger sur l''objet cherche : c''est un pronom interrogatif.',
    'Chercher un antecedent qui n''existe pas.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par categories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "La reponse qu''il donne est precise", dans quelle categorie faut-il classer "qu''" ?',
    null,
    '[{"id":"a","label":"Pronom relatif"},{"id":"b","label":"Conjonction de subordination"},{"id":"c","label":"Pronom interrogatif"},{"id":"d","label":"Determinant exclamatif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    'Qu'' reprend l''antecedent "reponse" : c''est un pronom relatif.',
    'Confondre la presence du verbe avec une completive.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par categories : le mot "que"',
    'Difficile',
    'reponse_courte',
    'Dans "Il faut que tu viennes", dans quelle categorie faut-il classer "que" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["conjonction de subordination","subordination"]}'::jsonb,
    'Ici "que" introduit une subordonnee completive sans reprendre d''antecedent : c''est une conjonction de subordination.',
    'Repondre pronom relatif a cause de la forme inchangee du mot.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par categories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Que de patience il faut !", dans quelle categorie faut-il classer "Que" ?',
    null,
    '[{"id":"a","label":"Determinant exclamatif"},{"id":"b","label":"Pronom interrogatif"},{"id":"c","label":"Pronom relatif"},{"id":"d","label":"Adverbe restrictif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Que" introduit le nom "patience" dans une exclamation : c''est un determinant exclamatif.',
    'Le classer comme adverbe de quantite alors que le mot introduit un nom.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par categories : le mot "que"',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Il n''a que deux stylos", "que" appartient a une tournure restrictive.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'La tournure "ne... que" exprime la restriction. "Que" est alors un adverbe restrictif.',
    'Chercher un emploi de subordonnant des que le mot que apparait.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par categories : mots a double nature',
    'Difficile',
    'qcm',
    'Dans "leur cahier est ferme", dans quelle categorie faut-il classer "leur" ?',
    null,
    '[{"id":"a","label":"Determinant possessif"},{"id":"b","label":"Pronom personnel"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Leur" accompagne le nom "cahier" : c''est un determinant possessif.',
    'Le confondre avec le pronom de "je leur parle".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par categories : mots a double nature',
    'Difficile',
    'qcm',
    'Dans "Je leur parle souvent", dans quelle categorie faut-il classer "leur" ?',
    null,
    '[{"id":"a","label":"Determinant possessif"},{"id":"b","label":"Pronom personnel"},{"id":"c","label":"Pronom relatif"},{"id":"d","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Leur" reprend ici des personnes et complete le verbe "parle" : c''est un pronom personnel.',
    'Chercher un nom apres le mot alors qu''il est place devant le verbe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par categories : mots a double nature',
    'Difficile',
    'qcm',
    'Dans "Les eleves eux-memes ont verifie", dans quelle categorie faut-il classer "memes" ?',
    null,
    '[{"id":"a","label":"Adjectif"},{"id":"b","label":"Adverbe"},{"id":"c","label":"Pronom"},{"id":"d","label":"Preposition"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Memes" renforce le pronom "eux" : on l''analyse ici comme un adjectif de renforcement.',
    'Le rendre invariable par automatisme des que le mot meme apparait.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par categories : mots a double nature',
    'Difficile',
    'qcm',
    'Dans "Meme les experts hesitent", dans quelle categorie faut-il classer "Meme" ?',
    null,
    '[{"id":"a","label":"Adjectif"},{"id":"b","label":"Adverbe"},{"id":"c","label":"Pronom"},{"id":"d","label":"Determinant"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    'Meme signifie ici "jusqu''a / y compris" : c''est un adverbe.',
    'Le classer comme adjectif sans tenir compte du sens d''insistance.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par categories : mots a double nature',
    'Difficile',
    'qcm',
    'Dans "Plusieurs ont deja fini", dans quelle categorie faut-il classer "Plusieurs" ?',
    null,
    '[{"id":"a","label":"Determinant indefini"},{"id":"b","label":"Pronom indefini"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Plusieurs" fonctionne seul et remplace un groupe nominal : c''est un pronom indefini.',
    'Le classer comme determinant sans verifier s''il introduit un nom.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par categories : mots a double nature',
    'Difficile',
    'qcm',
    'Dans "Plusieurs copies manquent", dans quelle categorie faut-il classer "Plusieurs" ?',
    null,
    '[{"id":"a","label":"Determinant indefini"},{"id":"b","label":"Pronom indefini"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Plusieurs" introduit le nom "copies" : c''est un determinant indefini.',
    'Oublier que le meme mot peut etre pronom ou determinant selon le contexte.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par categories : mots a double nature',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Ce dossier a un vrai plus", "plus" est un nom.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'Dans cette phrase, "plus" designe un avantage distinctif : il est employe comme nom.',
    'Le traiter comme l''adverbe de comparaison par reflexe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par categories : mots a double nature',
    'Difficile',
    'qcm',
    'Dans "Il travaille plus vite", dans quelle categorie faut-il classer "plus" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Adverbe"},{"id":"c","label":"Pronom"},{"id":"d","label":"Determinant"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Plus" modifie l''adverbe "vite" dans un comparatif : c''est un adverbe.',
    'Le confondre avec un nom a cause de sa forme isolee.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par categories : mots a double nature',
    'Difficile',
    'reponse_courte',
    'Dans "Bien qu''il soit tard, nous continuons", dans quelle categorie faut-il classer "bien que" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["conjonction de subordination","subordination"]}'::jsonb,
    '"Bien que" est une locution qui introduit une subordonnee de concession : c''est une conjonction de subordination.',
    'Se focaliser sur le mot bien comme adverbe sans voir la locution complete.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par categories : mots a double nature',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Ce travail est bien organise", "bien" est un adverbe.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Bien" modifie l''adjectif "organise" : c''est un adverbe.',
    'Le classer comme nom abstrait par analogie avec "le bien".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  )
on conflict (id) do nothing;
