-- Migration: seed 6 "Tri par catégories" exercises — nature des mots
-- Session ID auto-generated: session-tri_nature_mots-Intermediaire-1
-- Requires: 20260326_add_tri_categories_type.sql to have run first.

insert into public.exercises (
  id,
  subject,
  subdomain,
  topic_key,
  topic_label,
  level,
  exercise_type,
  instruction,
  support_text,
  choices,
  expected_answer,
  detailed_explanation,
  common_mistake,
  validation_status,
  source,
  access_tier,
  is_published
)
values
  -- Q1 : Nom / Verbe / Adjectif
  (
    'ac110000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_nature_mots',
    'Tri par catégories : nature des mots',
    'Intermediaire',
    'tri_categories',
    'Classez ces six mots selon leur nature grammaticale.',
    null,
    '[{"id":"tc01q1w1","label":"soleil"},{"id":"tc01q1w2","label":"écrire"},{"id":"tc01q1w3","label":"belle"},{"id":"tc01q1w4","label":"maison"},{"id":"tc01q1w5","label":"courir"},{"id":"tc01q1w6","label":"sombre"}]'::jsonb,
    '{"mode":"categorization","categories":[{"id":"nom","label":"Nom"},{"id":"verbe","label":"Verbe"},{"id":"adjectif","label":"Adjectif"}],"mapping":{"tc01q1w1":"nom","tc01q1w2":"verbe","tc01q1w3":"adjectif","tc01q1w4":"nom","tc01q1w5":"verbe","tc01q1w6":"adjectif"}}'::jsonb,
    'Soleil et maison désignent des réalités concrètes : ce sont des noms. Écrire et courir sont des formes verbales à l''infinitif : ce sont des verbes. Belle et sombre expriment une qualité et s''accordent avec le nom qu''ils accompagnent : ce sont des adjectifs qualificatifs.',
    'Confondre la nature grammaticale (ce qu''est le mot) avec sa fonction syntaxique (son rôle dans la phrase). Un infinitif reste un verbe même s''il occupe la place d''un nom.',
    'valide',
    'Série CRPE Français — Tri par catégories',
    'free',
    true
  ),
  -- Q2 : Déterminant / Pronom / Adverbe
  (
    'ac110000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_nature_mots',
    'Tri par catégories : nature des mots',
    'Intermediaire',
    'tri_categories',
    'Classez ces six mots selon leur nature grammaticale. Le nom entre crochets indique le contexte quand il est nécessaire.',
    null,
    '[{"id":"tc01q2w1","label":"leurs [cahiers]"},{"id":"tc01q2w2","label":"elle"},{"id":"tc01q2w3","label":"vite"},{"id":"tc01q2w4","label":"aucun [élève]"},{"id":"tc01q2w5","label":"eux"},{"id":"tc01q2w6","label":"jamais"}]'::jsonb,
    '{"mode":"categorization","categories":[{"id":"determinant","label":"Déterminant"},{"id":"pronom","label":"Pronom"},{"id":"adverbe","label":"Adverbe"}],"mapping":{"tc01q2w1":"determinant","tc01q2w2":"pronom","tc01q2w3":"adverbe","tc01q2w4":"determinant","tc01q2w5":"pronom","tc01q2w6":"adverbe"}}'::jsonb,
    'Leurs [cahiers] et aucun [élève] introduisent chacun un nom : ce sont des déterminants (possessif et indéfini). Elle et eux fonctionnent seuls à la place d''un groupe nominal : ce sont des pronoms personnels. Vite et jamais modifient un verbe sans s''accorder : ce sont des adverbes.',
    'Confondre le pronom et le déterminant : le déterminant est toujours suivi d''un nom, le pronom le remplace et fonctionne seul. Leurs cahiers → déterminant ; eux → pronom.',
    'valide',
    'Série CRPE Français — Tri par catégories',
    'free',
    true
  ),
  -- Q3 : Préposition / Conjonction de coordination / Conjonction de subordination
  (
    'ac110000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_nature_mots',
    'Tri par catégories : nature des mots',
    'Intermediaire',
    'tri_categories',
    'Classez ces six mots de liaison selon leur nature grammaticale.',
    null,
    '[{"id":"tc01q3w1","label":"dans"},{"id":"tc01q3w2","label":"mais"},{"id":"tc01q3w3","label":"avec"},{"id":"tc01q3w4","label":"car"},{"id":"tc01q3w5","label":"parce que"},{"id":"tc01q3w6","label":"afin que"}]'::jsonb,
    '{"mode":"categorization","categories":[{"id":"prep","label":"Préposition"},{"id":"coord","label":"Conjonction de coordination"},{"id":"subord","label":"Conjonction de subordination"}],"mapping":{"tc01q3w1":"prep","tc01q3w2":"coord","tc01q3w3":"prep","tc01q3w4":"coord","tc01q3w5":"subord","tc01q3w6":"subord"}}'::jsonb,
    'Dans et avec introduisent un groupe nominal ou pronominal : ce sont des prépositions. Mais et car relient deux propositions de même niveau syntaxique : ce sont des conjonctions de coordination. Parce que et afin que introduisent une proposition subordonnée : ce sont des conjonctions de subordination.',
    'Confondre coordination et subordination. Test : la conjonction de subordination introduit une proposition qui dépend d''une principale ; la coordination relie des éléments de même rang.',
    'valide',
    'Série CRPE Français — Tri par catégories',
    'free',
    true
  ),
  -- Q4 : Variable / Invariable
  (
    'ac110000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_nature_mots',
    'Tri par catégories : nature des mots',
    'Intermediaire',
    'tri_categories',
    'Classez ces six mots : sont-ils variables (changent de forme selon le genre, le nombre ou la personne) ou invariables ?',
    null,
    '[{"id":"tc01q4w1","label":"belle"},{"id":"tc01q4w2","label":"rapidement"},{"id":"tc01q4w3","label":"leurs"},{"id":"tc01q4w4","label":"jamais"},{"id":"tc01q4w5","label":"parce que"},{"id":"tc01q4w6","label":"courageux"}]'::jsonb,
    '{"mode":"categorization","categories":[{"id":"variable","label":"Variable"},{"id":"invariable","label":"Invariable"}],"mapping":{"tc01q4w1":"variable","tc01q4w2":"invariable","tc01q4w3":"variable","tc01q4w4":"invariable","tc01q4w5":"invariable","tc01q4w6":"variable"}}'::jsonb,
    'Belle (beau/belle/beaux/belles) et courageux varient en genre et en nombre : ils sont variables. Leurs varie en nombre (leur/leurs) : il est variable. Rapidement, jamais et parce que ne changent jamais de forme : ils sont invariables.',
    'Oublier que leurs est variable (leur/leurs), ou croire que la terminaison -ment garantit l''invariabilité — elle s''applique aux adverbes, lesquels sont effectivement invariables, mais ce n''est pas la terminaison qui le prouve.',
    'valide',
    'Série CRPE Français — Tri par catégories',
    'free',
    true
  ),
  -- Q5 : Infinitif / Participe passé / Verbe conjugué
  (
    'ac110000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_nature_mots',
    'Tri par catégories : nature des mots',
    'Intermediaire',
    'tri_categories',
    'Classez ces six formes verbales selon leur statut morphologique.',
    null,
    '[{"id":"tc01q5w1","label":"manger"},{"id":"tc01q5w2","label":"mangé"},{"id":"tc01q5w3","label":"mangeons"},{"id":"tc01q5w4","label":"finir"},{"id":"tc01q5w5","label":"fini"},{"id":"tc01q5w6","label":"finissent"}]'::jsonb,
    '{"mode":"categorization","categories":[{"id":"infinitif","label":"Infinitif"},{"id":"pp","label":"Participe passé"},{"id":"conjugue","label":"Verbe conjugué"}],"mapping":{"tc01q5w1":"infinitif","tc01q5w2":"pp","tc01q5w3":"conjugue","tc01q5w4":"infinitif","tc01q5w5":"pp","tc01q5w6":"conjugue"}}'::jsonb,
    'Manger et finir sont les formes de base non personnelles : ce sont des infinitifs. Mangé et fini sont des formes susceptibles de s''accorder : ce sont des participes passés. Mangeons et finissent portent une marque de personne, de nombre et de temps : ce sont des verbes conjugués.',
    'Confondre l''infinitif -er et le participe passé -é pour les verbes du 1er groupe. Test : remplacer par un verbe du 3e groupe — si « vendre » convient, c''est un infinitif ; si « vendu » convient, c''est un participe passé.',
    'valide',
    'Série CRPE Français — Tri par catégories',
    'free',
    true
  ),
  -- Q6 : Les natures du mot « tout »
  (
    'ac110000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_nature_mots',
    'Tri par catégories : nature des mots',
    'Intermediaire',
    'tri_categories',
    'Le mot « tout » change de nature selon le contexte. Classez ces six occurrences. Le nom entre crochets indique ce qui suit immédiatement.',
    null,
    '[{"id":"tc01q6w1","label":"tout [le livre]"},{"id":"tc01q6w2","label":"Tous [ont réussi]"},{"id":"tc01q6w3","label":"tout [heureuse]"},{"id":"tc01q6w4","label":"toute [la classe]"},{"id":"tc01q6w5","label":"tout [compris]"},{"id":"tc01q6w6","label":"tout [petit]"}]'::jsonb,
    '{"mode":"categorization","categories":[{"id":"determinant","label":"Déterminant"},{"id":"pronom","label":"Pronom"},{"id":"adverbe","label":"Adverbe"}],"mapping":{"tc01q6w1":"determinant","tc01q6w2":"pronom","tc01q6w3":"adverbe","tc01q6w4":"determinant","tc01q6w5":"pronom","tc01q6w6":"adverbe"}}'::jsonb,
    'Tout [le livre] et toute [la classe] précèdent un nom : ce sont des déterminants. Tous [ont réussi] est sujet ; tout [compris] est COD — les deux fonctionnent seuls et remplacent un groupe nominal : ce sont des pronoms. Tout [heureuse] et tout [petit] modifient un adjectif : ce sont des adverbes.',
    'Croire que tout est toujours déterminant. Trois tests : un nom suit immédiatement → déterminant ; le mot fonctionne seul comme sujet ou complément → pronom ; le mot modifie un adjectif → adverbe.',
    'valide',
    'Série CRPE Français — Tri par catégories',
    'free',
    true
  );
