-- Migration: add free analyse_langue series "phrase_complexe_types" (10 questions)

insert into public.exercises (
  id,
  subject,
  subdomain,
  topic_key,
  topic_label,
  level,
  exercise_type,
  instruction,
  support_text,
  choices,
  expected_answer,
  detailed_explanation,
  common_mistake,
  validation_status,
  source,
  access_tier,
  is_published
)
values
  (
    'c30b0000-0000-0000-0000-000000000001',
    'Francais',
    'analyse_langue',
    'phrase_complexe_types',
    'Phrase complexe : types de propositions',
    'Intermediaire',
    'qcm',
    'Dans « Le maître explique la consigne et les élèves commencent l''exercice », les deux propositions sont :',
    null,
    '[{"id":"a","label":"deux propositions subordonnées"},{"id":"b","label":"deux propositions indépendantes coordonnées"},{"id":"c","label":"une principale et une subordonnée relative"},{"id":"d","label":"une seule proposition avec deux verbes"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    'Chaque segment possède son propre verbe conjugué et pourrait exister seul. Le lien est assuré par la conjonction de coordination « et » : il s''agit donc de deux propositions indépendantes coordonnées.',
    'Croire que toute phrase contenant un mot de liaison relève automatiquement de la subordination.',
    'valide',
    'CRPE Français V3',
    'free',
    true
  ),
  (
    'c30b0000-0000-0000-0000-000000000002',
    'Francais',
    'analyse_langue',
    'phrase_complexe_types',
    'Phrase complexe : types de propositions',
    'Intermediaire',
    'qcm',
    'Dans « Quand la cloche sonne, les élèves rangent leurs affaires », la proposition « Quand la cloche sonne » est :',
    null,
    '[{"id":"a","label":"une proposition indépendante"},{"id":"b","label":"une proposition subordonnée circonstancielle"},{"id":"c","label":"une proposition principale"},{"id":"d","label":"une proposition subordonnée relative"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    'Introduite par « quand », la proposition exprime ici le moment de l''action principale. Elle dépend syntaxiquement de la proposition « les élèves rangent leurs affaires » : c''est une subordonnée circonstancielle de temps.',
    'S''arrêter au sens temporel sans identifier le lien de dépendance qui fait d''elle une subordonnée.',
    'valide',
    'CRPE Français V3',
    'free',
    true
  ),
  (
    'c30b0000-0000-0000-0000-000000000003',
    'Francais',
    'analyse_langue',
    'phrase_complexe_types',
    'Phrase complexe : types de propositions',
    'Intermediaire',
    'vrai_faux',
    'Vrai ou faux : dans « Je pense qu''il réussira », « qu''il réussira » est une proposition subordonnée complétive.',
    null,
    null,
    '{"mode":"boolean","value":true}'::jsonb,
    'La proposition introduite par « que » complète le verbe « pense ». Elle ne peut pas fonctionner seule dans la phrase : c''est bien une subordonnée complétive.',
    'Confondre toute proposition introduite par « que » avec une relative, alors qu''ici « que » n''a pas d''antécédent.',
    'valide',
    'CRPE Français V3',
    'free',
    true
  ),
  (
    'c30b0000-0000-0000-0000-000000000004',
    'Francais',
    'analyse_langue',
    'phrase_complexe_types',
    'Phrase complexe : types de propositions',
    'Intermediaire',
    'reponse_courte',
    'Dans « Les élèves qui relisent leur copie progressent », quel type de proposition est « qui relisent leur copie » ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["proposition subordonnée relative","subordonnée relative","relative"]}'::jsonb,
    'Le groupe est introduit par le pronom relatif « qui » et complète l''antécédent « les élèves ». Il s''agit donc d''une proposition subordonnée relative.',
    'Répondre seulement « proposition » ou oublier que le pronom relatif renvoie à un antécédent.',
    'valide',
    'CRPE Français V3',
    'free',
    true
  ),
  (
    'c30b0000-0000-0000-0000-000000000005',
    'Francais',
    'analyse_langue',
    'phrase_complexe_types',
    'Phrase complexe : types de propositions',
    'Intermediaire',
    'qcm',
    'Laquelle de ces phrases contient une proposition subordonnée relative ?',
    null,
    '[{"id":"a","label":"Je viendrai si j''ai le temps."},{"id":"b","label":"Le livre que tu lis est passionnant."},{"id":"c","label":"Il a révisé, donc il est prêt."},{"id":"d","label":"Comme il pleuvait, nous sommes restés dedans."}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    'Dans « Le livre que tu lis est passionnant », « que tu lis » est introduit par le pronom relatif « que », lequel reprend l''antécédent « livre ». Les autres phrases contiennent une circonstancielle ou une coordination.',
    'Chercher uniquement un mot introducteur sans vérifier s''il reprend un antécédent.',
    'valide',
    'CRPE Français V3',
    'free',
    true
  ),
  (
    'c30b0000-0000-0000-0000-000000000006',
    'Francais',
    'analyse_langue',
    'phrase_complexe_types',
    'Phrase complexe : types de propositions',
    'Intermediaire',
    'vrai_faux',
    'Vrai ou faux : une proposition principale n''existe que s''il y a au moins une proposition subordonnée dans la phrase.',
    null,
    null,
    '{"mode":"boolean","value":true}'::jsonb,
    'On appelle « principale » la proposition dont dépend une ou plusieurs subordonnées. S''il n''y a aucune subordonnée, on parle plutôt de proposition indépendante, pas de principale.',
    'Employer « principale » comme synonyme systématique de « première proposition de la phrase ».',
    'valide',
    'CRPE Français V3',
    'free',
    true
  ),
  (
    'c30b0000-0000-0000-0000-000000000007',
    'Francais',
    'analyse_langue',
    'phrase_complexe_types',
    'Phrase complexe : types de propositions',
    'Intermediaire',
    'qcm',
    'Dans « Il pleuvait ; nous avons attendu sous le préau », le lien entre les deux propositions relève de :',
    null,
    '[{"id":"a","label":"la juxtaposition"},{"id":"b","label":"la subordination"},{"id":"c","label":"la relative"},{"id":"d","label":"la complétive"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    'Les deux propositions sont simplement séparées par un point-virgule, sans conjonction ni mot subordonnant. Elles sont donc juxtaposées.',
    'Imaginer une subordination implicite dès qu''un rapport logique de cause ou de conséquence peut être compris.',
    'valide',
    'CRPE Français V3',
    'free',
    true
  ),
  (
    'c30b0000-0000-0000-0000-000000000008',
    'Francais',
    'analyse_langue',
    'phrase_complexe_types',
    'Phrase complexe : types de propositions',
    'Intermediaire',
    'reponse_courte',
    'Dans « Bien qu''il soit tard, nous continuons », quel est le type de la proposition « Bien qu''il soit tard » ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["proposition subordonnée circonstancielle de concession","subordonnée circonstancielle de concession","circonstancielle de concession"]}'::jsonb,
    'La locution « bien que » introduit une subordonnée circonstancielle de concession. Elle exprime un fait admis qui n''empêche pas l''action principale.',
    'Nommer seulement le sens d''opposition sans préciser qu''il s''agit d''une subordonnée circonstancielle.',
    'valide',
    'CRPE Français V3',
    'free',
    true
  ),
  (
    'c30b0000-0000-0000-0000-000000000009',
    'Francais',
    'analyse_langue',
    'phrase_complexe_types',
    'Phrase complexe : types de propositions',
    'Intermediaire',
    'qcm',
    'Dans quelle phrase la proposition soulignée est-elle une principale ?',
    null,
    '[{"id":"a","label":"« Quand il arrive », tout le monde se tait."},{"id":"b","label":"Le candidat affirme « qu''il a compris »."},{"id":"c","label":"« Nous partirons » si le train est à l''heure."},{"id":"d","label":"Le manuel « que tu cherches » est ici."}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    'Dans « Nous partirons si le train est à l''heure », la proposition « Nous partirons » commande la subordonnée conditionnelle. Elle est donc principale. Dans les autres cas, les segments soulignés sont subordonnés.',
    'Choisir la proposition placée en premier sans vérifier si une autre dépend d''elle.',
    'valide',
    'CRPE Français V3',
    'free',
    true
  ),
  (
    'c30b0000-0000-0000-0000-00000000000a',
    'Francais',
    'analyse_langue',
    'phrase_complexe_types',
    'Phrase complexe : types de propositions',
    'Intermediaire',
    'vrai_faux',
    'Vrai ou faux : une phrase peut être complexe sans contenir de proposition subordonnée.',
    null,
    null,
    '{"mode":"boolean","value":true}'::jsonb,
    'Oui. Une phrase complexe peut être formée de plusieurs propositions indépendantes coordonnées ou juxtaposées, sans aucune subordination. Par exemple : « Il relit sa copie et il corrige ses erreurs. »',
    'Réduire la phrase complexe à la seule présence d''une subordonnée, alors qu''il suffit qu''il y ait plusieurs propositions.',
    'valide',
    'CRPE Français V3',
    'free',
    true
  )
on conflict (id) do nothing;
