-- Migration: add 10 grammar series "Tri par catégories" (100 questions)

insert into public.exercises (
  id,
  subject,
  subdomain,
  topic_key,
  topic_label,
  level,
  exercise_type,
  instruction,
  support_text,
  choices,
  expected_answer,
  detailed_explanation,
  common_mistake,
  validation_status,
  source,
  access_tier,
  is_published
)
values
  (
    'e5010000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par catégories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "Le chat dort", dans quelle catégorie faut-il classer "chat" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Chat" est le noyau du groupe nominal sujet "Le chat" : c''est un nom.',
    'Se laisser guider par le sens global de la phrase sans repérer le groupe nominal.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par catégories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "Les élèves parlent", dans quelle catégorie faut-il classer "parlent" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Parlent" est le verbe conjugué de la phrase : il exprime l''action et s''accorde avec "les élèves".',
    'Confondre le mot qui porte l''action avec un nom d''action.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par catégories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "une candidate courageuse", dans quelle catégorie faut-il classer "courageuse" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Courageuse" qualifie le nom "candidate" et s''accorde avec lui : c''est un adjectif.',
    'Répondre épithète ou attribut alors que l''on demande la nature grammaticale.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par catégories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "un conseil utile", dans quelle catégorie faut-il classer "utile" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Utile" apporte une qualité au nom "conseil" : c''est un adjectif.',
    'Confondre l''adjectif avec le nom qu''il accompagne.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par catégories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "Ils corrigent leur copie", dans quelle catégorie faut-il classer "corrigent" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Corrigent" est le verbe conjugué de la phrase. Il commande le groupe verbal.',
    'Chercher le mot le plus important du sens au lieu de repérer le verbe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par catégories : nom, verbe, adjectif',
    'Facile',
    'vrai_faux',
    'Vrai ou faux : dans "la réponse juste", "juste" est un adjectif.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Juste" qualifie le nom "réponse" : c''est bien un adjectif.',
    'Confondre la valeur de qualité avec une fonction syntaxique.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par catégories : nom, verbe, adjectif',
    'Facile',
    'reponse_courte',
    'Dans "les élèves attentifs", dans quelle catégorie faut-il classer "élèves" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["nom"]}'::jsonb,
    '"Élèves" est le noyau du groupe nominal. C''est donc un nom.',
    'Répondre sujet alors que la consigne demande une catégorie grammaticale.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par catégories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "La fatigue revient vite", dans quelle catégorie faut-il classer "fatigue" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    'Ici "fatigue" est précède de l''article "la" : le mot est employé comme nom.',
    'Se fier au fait que fatiguer existe comme verbe sans regarder le contexte.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par catégories : nom, verbe, adjectif',
    'Facile',
    'qcm',
    'Dans "Il calme le groupe", dans quelle catégorie faut-il classer "calme" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Verbe"},{"id":"c","label":"Adjectif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    'Dans cette phrase, "calme" est le verbe conjugué qui dit ce que fait le sujet "il".',
    'Classer automatiquement calme comme adjectif parce qu''il peut aussi l''être dans d''autres phrases.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5010000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_nom_verbe_adjectif',
    'Tri par catégories : nom, verbe, adjectif',
    'Facile',
    'vrai_faux',
    'Vrai ou faux : dans "un texte clair", "clair" appartient à la catégorie des verbes.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":false}'::jsonb,
    '"Clair" qualifie le nom "texte" : ce n''est pas un verbe, mais un adjectif.',
    'Confondre un mot qualificatif avec le noyau du groupe verbal.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par catégories : déterminant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "ce manuel", dans quelle catégorie faut-il classer "ce" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Ce" introduit le nom "manuel" : c''est un déterminant démonstratif.',
    'Répondre pronom sans voir qu''un nom suit immédiatement.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par catégories : déterminant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "ceux qui réussissent", dans quelle catégorie faut-il classer "ceux" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Ceux" remplace un groupe nominal entier : c''est un pronom démonstratif.',
    'Chercher un nom après le mot alors qu''il fonctionne seul.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par catégories : déterminant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "elle relit très vite", dans quelle catégorie faut-il classer "très" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Très" modifie l''adverbe "vite" : c''est un adverbe.',
    'Le classer parmi les mots-outils sans regarder ce qu''il modifie.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par catégories : déterminant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "leur cahier est prêt", dans quelle catégorie faut-il classer "leur" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Leur" accompagne le nom "cahier" : ici, c''est un déterminant possessif.',
    'Confondre avec le pronom "leur" de "je leur parle".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par catégories : déterminant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "Demain, nous réviserons", dans quelle catégorie faut-il classer "demain" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Demain" précise le moment de l''action : c''est un adverbe.',
    'Le traiter comme un nom de temps sans regarder sa fonction dans la phrase.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par catégories : déterminant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "Personne n''a repondu", dans quelle catégorie faut-il classer "personne" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Personne" remplace un groupe nominal et occupe la place du sujet : c''est un pronom indéfini.',
    'Confondre le mot avec le nom "personne" dans "une personne".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par catégories : déterminant, pronom, adverbe',
    'Facile',
    'vrai_faux',
    'Vrai ou faux : dans "elles réussissent vite", "vite" est un adverbe.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Vite" modifie le verbe "réussissent" : c''est bien un adverbe.',
    'Le classer comme adjectif parce qu''il exprime une qualité.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par catégories : déterminant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "ces règles sont utiles", dans quelle catégorie faut-il classer "ces" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Ces" introduit le nom "règles" : c''est un déterminant démonstratif.',
    'Oublier de vérifier si le mot est suivi d''un nom.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par catégories : déterminant, pronom, adverbe',
    'Facile',
    'reponse_courte',
    'Dans "Beaucoup travaillent en silence", dans quelle catégorie faut-il classer "beaucoup" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["pronom"]}'::jsonb,
    'Dans cette phrase, "beaucoup" remplace un groupe de personnes : il est employé comme pronom indéfini.',
    'Répondre adverbe par automatisme sans regarder qu''il est sujet du verbe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5020000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_determinant_pronom_adverbe',
    'Tri par catégories : déterminant, pronom, adverbe',
    'Facile',
    'qcm',
    'Dans "Il travaille beaucoup", dans quelle catégorie faut-il classer "beaucoup" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    'Ici, "beaucoup" modifie le verbe "travaille" : c''est un adverbe.',
    'Ne pas voir que le même mot peut changer de catégorie selon le contexte.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par catégories : mots de liaison',
    'Intermédiaire',
    'qcm',
    'Dans "Il part parce qu''il est fatigue", dans quelle catégorie faut-il classer "parce que" ?',
    null,
    '[{"id":"a","label":"Préposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Parce que" introduit une proposition subordonnée de cause : c''est une conjonction de subordination.',
    'Confondre la relation logique de cause avec une coordination.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par catégories : mots de liaison',
    'Intermédiaire',
    'qcm',
    'Dans "Il voulait venir, mais il était malade", dans quelle catégorie faut-il classer "mais" ?',
    null,
    '[{"id":"a","label":"Préposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Mais" relie deux propositions de même niveau : c''est une conjonction de coordination.',
    'Le traiter comme un simple mot logique sans nommer sa vraie nature.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par catégories : mots de liaison',
    'Intermédiaire',
    'qcm',
    'Dans "dans la classe", dans quelle catégorie faut-il classer "dans" ?',
    null,
    '[{"id":"a","label":"Préposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Dans" introduit le groupe prépositionnel "dans la classe" : c''est une préposition.',
    'Confondre l''introduction d''un groupe avec l''introduction d''une proposition.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par catégories : mots de liaison',
    'Intermédiaire',
    'qcm',
    'Dans "quoique le cas soit rare", dans quelle catégorie faut-il classer "quoique" ?',
    null,
    '[{"id":"a","label":"Préposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Quoique" introduit une proposition subordonnée de concession : c''est une conjonction de subordination.',
    'Le rapprocher à tort de ou ou de mais.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par catégories : mots de liaison',
    'Intermédiaire',
    'qcm',
    'Dans "avec soin", dans quelle catégorie faut-il classer "avec" ?',
    null,
    '[{"id":"a","label":"Préposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Avec" introduit un groupe prépositionnel : c''est une préposition.',
    'Confondre la relation de moyen avec un lien entre deux propositions.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par catégories : mots de liaison',
    'Intermédiaire',
    'vrai_faux',
    'Vrai ou faux : dans "ni Paul ni Léa", "ni" est une conjonction de coordination.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Ni" appartient au groupe des conjonctions de coordination. Il relie ici deux éléments de même niveau dans un contexte négatif.',
    'Oublier que les coordinations ne sont pas limitées à et et mais.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par catégories : mots de liaison',
    'Intermédiaire',
    'qcm',
    'Dans "afin qu''il comprenne", dans quelle catégorie faut-il classer "afin que" ?',
    null,
    '[{"id":"a","label":"Préposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Afin que" introduit une subordonnée de but : c''est une conjonction de subordination.',
    'Chercher un nom après la locution alors qu''elle introduit un verbe conjugué.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par catégories : mots de liaison',
    'Intermédiaire',
    'qcm',
    'Dans "chez le voisin", dans quelle catégorie faut-il classer "chez" ?',
    null,
    '[{"id":"a","label":"Préposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Chez" introduit un groupe nominal : c''est une préposition.',
    'Le confondre avec un adverbe de lieu.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par catégories : mots de liaison',
    'Intermédiaire',
    'reponse_courte',
    'Dans "car il avait révisé", dans quelle catégorie faut-il classer "car" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["conjonction de coordination","coordination"]}'::jsonb,
    '"Car" est une conjonction de coordination exprimant la cause.',
    'Le classer parmi les subordonnants parce qu''il donne une explication.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5030000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_mots_liaison',
    'Tri par catégories : mots de liaison',
    'Intermédiaire',
    'qcm',
    'Dans "Il est prêt, or son binome ne l''est pas", dans quelle catégorie faut-il classer "or" ?',
    null,
    '[{"id":"a","label":"Préposition"},{"id":"b","label":"Conjonction de coordination"},{"id":"c","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Or" relie deux propositions de même niveau en introduisant une nuance logique : c''est une conjonction de coordination.',
    'Ne pas connaître cette conjonction plus rare et la ranger parmi les adverbes.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par catégories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle catégorie faut-il classer "rapidement" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Rapidement" est un adverbe : il ne varie pas.',
    'Penser que tous les mots longs ou dérivés sont nécessairement variables.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par catégories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle catégorie faut-il classer "belles" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Belles" est un adjectif qualificatif : il varie selon le genre et le nombre.',
    'Confondre la forme observée avec la propriété générale du mot.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par catégories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle catégorie faut-il classer "leurs" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Leurs" est un déterminant possessif : il varie au moins en nombre.',
    'Le confondre avec une forme figée à cause de sa terminaison déjà marquée.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par catégories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle catégorie faut-il classer "très" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Très" est un adverbe : il est invariable.',
    'Chercher une variation de sens au lieu de regarder la forme.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par catégories : variables ou invariables',
    'Facile',
    'vrai_faux',
    'Vrai ou faux : "parce que" appartient à la catégorie des mots invariables.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'La locution conjonctive "parce que" ne varie pas : elle est invariable.',
    'Oublier que certaines locutions entières fonctionnent comme des mots invariables.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par catégories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle catégorie faut-il classer "jamais" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Jamais" est un adverbe : sa forme ne varie pas.',
    'Le ranger parmi les pronoms ou les déterminants parce qu''il est fréquemment employé.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par catégories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle catégorie faut-il classer "nous" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Nous" appartient au système des pronoms personnels, qui varie selon la personne et le nombre.',
    'Penser qu''un mot court est forcément invariable.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par catégories : variables ou invariables',
    'Facile',
    'reponse_courte',
    'Dans "cet exercice", "cet" est-il variable ou invariable ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["variable"]}'::jsonb,
    '"Cet" est un déterminant démonstratif. Il varie selon le genre et le nombre : ce, cet, cette, ces.',
    'Oublier les autres formes possibles du déterminant démonstratif.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par catégories : variables ou invariables',
    'Facile',
    'vrai_faux',
    'Vrai ou faux : le mot "et" peut prendre une marque de pluriel.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":false}'::jsonb,
    '"Et" est une conjonction de coordination invariable. Il ne prend jamais de marque de genre ou de nombre.',
    'Confondre la notion de coordination avec un accord syntaxique.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5040000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_variables_invariables',
    'Tri par catégories : variables ou invariables',
    'Facile',
    'qcm',
    'Dans quelle catégorie faut-il classer "hier" : mot variable ou mot invariable ?',
    null,
    '[{"id":"a","label":"Variable"},{"id":"b","label":"Invariable"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Hier" est un adverbe de temps. Il est invariable.',
    'Le confondre avec un nom de date ou de moment.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par catégories : familles de déterminants',
    'Intermédiaire',
    'qcm',
    'Dans "les élèves", dans quelle famille faut-il classer "les" ?',
    null,
    '[{"id":"a","label":"Article défini"},{"id":"b","label":"Article indéfini"},{"id":"c","label":"Déterminant possessif"},{"id":"d","label":"Déterminant démonstratif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Les" est l''article défini pluriel.',
    'Le classer comme démonstratif parce qu''il montre un groupe déjà connu.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par catégories : familles de déterminants',
    'Intermédiaire',
    'qcm',
    'Dans "un exemple", dans quelle famille faut-il classer "un" ?',
    null,
    '[{"id":"a","label":"Article défini"},{"id":"b","label":"Article indéfini"},{"id":"c","label":"Article partitif"},{"id":"d","label":"Déterminant possessif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Un" introduit ici un nom non encore identifié : c''est un article indéfini.',
    'Confondre article indéfini et numéral.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par catégories : familles de déterminants',
    'Intermédiaire',
    'qcm',
    'Dans "du courage", dans quelle famille faut-il classer "du" ?',
    null,
    '[{"id":"a","label":"Article défini contracté"},{"id":"b","label":"Article indéfini"},{"id":"c","label":"Article partitif"},{"id":"d","label":"Déterminant démonstratif"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Du" devant un nom massif comme "courage" est un article partitif.',
    'Le traiter comme la contraction de de le sans regarder le sens partitif.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par catégories : familles de déterminants',
    'Intermédiaire',
    'qcm',
    'Dans "ces copies", dans quelle famille faut-il classer "ces" ?',
    null,
    '[{"id":"a","label":"Déterminant démonstratif"},{"id":"b","label":"Déterminant possessif"},{"id":"c","label":"Déterminant indéfini"},{"id":"d","label":"Article défini"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Ces" sert à désigner : c''est un déterminant démonstratif.',
    'Le confondre avec le possessif "ses".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par catégories : familles de déterminants',
    'Intermédiaire',
    'qcm',
    'Dans "mon cahier", dans quelle famille faut-il classer "mon" ?',
    null,
    '[{"id":"a","label":"Déterminant démonstratif"},{"id":"b","label":"Déterminant possessif"},{"id":"c","label":"Déterminant indéfini"},{"id":"d","label":"Article indéfini"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Mon" marque la possession : c''est un déterminant possessif.',
    'Le traiter comme un simple article devant un nom singulier.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par catégories : familles de déterminants',
    'Intermédiaire',
    'qcm',
    'Dans "plusieurs candidats", dans quelle famille faut-il classer "plusieurs" ?',
    null,
    '[{"id":"a","label":"Déterminant démonstratif"},{"id":"b","label":"Déterminant possessif"},{"id":"c","label":"Déterminant indéfini"},{"id":"d","label":"Article défini"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Plusieurs" donne une quantité non précisée exactement : c''est un déterminant indéfini.',
    'Le réduire à une simple indication numérique sans voir sa catégorie.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par catégories : familles de déterminants',
    'Intermédiaire',
    'vrai_faux',
    'Vrai ou faux : dans "Quel livre choisis-tu ?", "quel" est un déterminant interrogatif.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Quel" introduit le nom "livre" dans une question : c''est un déterminant interrogatif.',
    'Oublier qu''un même mot peut être interrogatif ou exclamatif selon le contexte.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par catégories : familles de déterminants',
    'Intermédiaire',
    'reponse_courte',
    'Dans "Quelle belle idée !", dans quelle famille faut-il classer "Quelle" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["déterminant exclamatif","exclamatif"]}'::jsonb,
    'Ici "Quelle" introduit le nom "idée" dans une exclamation : c''est un déterminant exclamatif.',
    'Répondre interrogatif uniquement à cause de la forme du mot.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par catégories : familles de déterminants',
    'Intermédiaire',
    'qcm',
    'Dans "aucun élève", dans quelle famille faut-il classer "aucun" ?',
    null,
    '[{"id":"a","label":"Déterminant indéfini"},{"id":"b","label":"Déterminant possessif"},{"id":"c","label":"Article défini"},{"id":"d","label":"Article partitif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Aucun" exprime une quantité nulle sans désigner : c''est un déterminant indéfini.',
    'Le prendre pour un adverbe négatif.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5050000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_familles_determinants',
    'Tri par catégories : familles de déterminants',
    'Intermédiaire',
    'qcm',
    'Dans "notre projet", dans quelle famille faut-il classer "notre" ?',
    null,
    '[{"id":"a","label":"Déterminant démonstratif"},{"id":"b","label":"Déterminant possessif"},{"id":"c","label":"Déterminant indéfini"},{"id":"d","label":"Article défini"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Notre" exprime la possession : c''est un déterminant possessif.',
    'Confondre la possession avec une simple désignation du nom.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par catégories : familles de pronoms',
    'Intermédiaire',
    'qcm',
    'Dans "il reussit", dans quelle famille faut-il classer "il" ?',
    null,
    '[{"id":"a","label":"Pronom personnel"},{"id":"b","label":"Pronom démonstratif"},{"id":"c","label":"Pronom relatif"},{"id":"d","label":"Pronom indéfini"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Il" appartient à la série des pronoms personnels.',
    'Le classer comme démonstratif parce qu''il renvoie à quelqu''un déjà connu.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par catégories : familles de pronoms',
    'Intermédiaire',
    'qcm',
    'Dans "ceux-ci sont prêts", dans quelle famille faut-il classer "ceux-ci" ?',
    null,
    '[{"id":"a","label":"Pronom personnel"},{"id":"b","label":"Pronom démonstratif"},{"id":"c","label":"Pronom possessif"},{"id":"d","label":"Pronom relatif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Ceux-ci" sert à désigner un groupe : c''est un pronom démonstratif.',
    'Le confondre avec un déterminant alors qu''il fonctionne seul.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par catégories : familles de pronoms',
    'Intermédiaire',
    'qcm',
    'Dans "Le mien est rangé", dans quelle famille faut-il classer "mien" ?',
    null,
    '[{"id":"a","label":"Pronom possessif"},{"id":"b","label":"Pronom démonstratif"},{"id":"c","label":"Pronom personnel"},{"id":"d","label":"Pronom relatif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Le mien" remplace un groupe nominal en marquant la possession : c''est un pronom possessif.',
    'Le prendre pour un adjectif possessif sans voir qu''aucun nom ne suit.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par catégories : familles de pronoms',
    'Intermédiaire',
    'qcm',
    'Dans "La fille qui lit", dans quelle famille faut-il classer "qui" ?',
    null,
    '[{"id":"a","label":"Pronom indéfini"},{"id":"b","label":"Pronom démonstratif"},{"id":"c","label":"Pronom relatif"},{"id":"d","label":"Pronom personnel"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Qui" introduit une relative et reprend l''antécédent "fille" : c''est un pronom relatif.',
    'Le ranger parmi les interrogatifs uniquement à cause de sa forme.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par catégories : familles de pronoms',
    'Intermédiaire',
    'qcm',
    'Dans "Personne ne bouge", dans quelle famille faut-il classer "personne" ?',
    null,
    '[{"id":"a","label":"Pronom indéfini"},{"id":"b","label":"Pronom personnel"},{"id":"c","label":"Pronom possessif"},{"id":"d","label":"Pronom démonstratif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Personne" désigne un référent non spécifié : c''est un pronom indéfini.',
    'Le confondre avec le nom "personne".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par catégories : familles de pronoms',
    'Intermédiaire',
    'vrai_faux',
    'Vrai ou faux : dans "Qui vient ?", "Qui" est un pronom interrogatif.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'Dans une question directe, "qui" est bien un pronom interrogatif.',
    'Confondre forme interrogative et relative sans regarder l''absence d''antécédent.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par catégories : familles de pronoms',
    'Intermédiaire',
    'qcm',
    'Dans "Celui-là est plus clair", dans quelle famille faut-il classer "Celui-là" ?',
    null,
    '[{"id":"a","label":"Pronom possessif"},{"id":"b","label":"Pronom démonstratif"},{"id":"c","label":"Pronom personnel"},{"id":"d","label":"Pronom interrogatif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Celui-là" désigne un élément : c''est un pronom démonstratif.',
    'Chercher un nom absent au lieu de regarder la fonction autonome du mot.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par catégories : familles de pronoms',
    'Intermédiaire',
    'reponse_courte',
    'Dans "Les tiens arrivent", dans quelle famille faut-il classer "les tiens" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["pronom possessif","possessif"]}'::jsonb,
    '"Les tiens" remplace un groupe nominal tout en marquant la possession : c''est un pronom possessif.',
    'Le confondre avec un déterminant possessif alors qu''il n''introduit aucun nom.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par catégories : familles de pronoms',
    'Intermédiaire',
    'qcm',
    'Dans "J''en veux encore", dans quelle famille faut-il classer "en" ?',
    null,
    '[{"id":"a","label":"Pronom personnel"},{"id":"b","label":"Pronom démonstratif"},{"id":"c","label":"Pronom relatif"},{"id":"d","label":"Pronom indéfini"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"En" est ici un pronom personnel adverbial qui reprend un complément.',
    'Le ranger comme adverbe parce qu''il est court et placé avant le verbe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5060000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_familles_pronoms',
    'Tri par catégories : familles de pronoms',
    'Intermédiaire',
    'qcm',
    'Dans "Chacun avance à son rythme", dans quelle famille faut-il classer "chacun" ?',
    null,
    '[{"id":"a","label":"Pronom indéfini"},{"id":"b","label":"Pronom personnel"},{"id":"c","label":"Pronom possessif"},{"id":"d","label":"Pronom interrogatif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Chacun" désigne un élément d''un ensemble sans le nommer : c''est un pronom indéfini.',
    'Le confondre avec un déterminant parce qu''il exprime une distribution.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par catégories : formes verbales',
    'Intermédiaire',
    'qcm',
    'Dans quelle catégorie faut-il classer "manger" ?',
    null,
    '[{"id":"a","label":"Verbe conjugué"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passé"},{"id":"d","label":"Participe présent"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Manger" est la forme de base du verbe : c''est un infinitif.',
    'Le confondre avec une forme conjuguée en -er par simple ressemblance visuelle.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par catégories : formes verbales',
    'Intermédiaire',
    'qcm',
    'Dans "Il mange vite", dans quelle catégorie faut-il classer "mange" ?',
    null,
    '[{"id":"a","label":"Verbe conjugué"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passé"},{"id":"d","label":"Participe présent"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Mange" est une forme personnelle, ici au présent de l''indicatif : c''est un verbe conjugué.',
    'Ne pas tenir compte du sujet il et de la relation d''accord.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par catégories : formes verbales',
    'Intermédiaire',
    'qcm',
    'Dans "La porte fermée", dans quelle catégorie faut-il classer "fermée" ?',
    null,
    '[{"id":"a","label":"Verbe conjugué"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passé"},{"id":"d","label":"Participe présent"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Fermée" est une forme en -e issue du verbe "fermer" : c''est un participe passé.',
    'La classer comme adjectif sans voir sa nature verbale d''origine dans ce tri spécifique.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par catégories : formes verbales',
    'Intermédiaire',
    'qcm',
    'Dans "Un élève souriant", dans quelle catégorie faut-il classer "souriant" ?',
    null,
    '[{"id":"a","label":"Verbe conjugué"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passé"},{"id":"d","label":"Participe présent"}]'::jsonb,
    '{"mode":"single_choice","value":"d"}'::jsonb,
    '"Souriant" est ici un participe présent.',
    'Confondre terminaison en -ant et gérondif sans vérifier la présence de en.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par catégories : formes verbales',
    'Intermédiaire',
    'qcm',
    'Dans "Elle semble avoir compris", dans quelle catégorie faut-il classer "avoir" ?',
    null,
    '[{"id":"a","label":"Verbe conjugué"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passé"},{"id":"d","label":"Participe présent"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Avoir" est à l''infinitif après le verbe "semble".',
    'Le confondre avec un auxiliaire conjugué parce qu''il appartient au système verbal.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par catégories : formes verbales',
    'Intermédiaire',
    'vrai_faux',
    'Vrai ou faux : dans "Ils avaient fermé la porte", "fermé" est un participe passé.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Fermé" est le participe passé employé avec l''auxiliaire "avaient".',
    'Le prendre pour un adjectif à cause de sa forme proche.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par catégories : formes verbales',
    'Intermédiaire',
    'reponse_courte',
    'Dans "Les volets ouverts laissaient entrer la lumière", dans quelle catégorie faut-il classer "ouverts" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["participe passé"]}'::jsonb,
    '"Ouverts" est un participe passé issu du verbe "ouvrir".',
    'Répondre adjectif sans respecter le tri demande sur les formes verbales.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par catégories : formes verbales',
    'Intermédiaire',
    'qcm',
    'Dans "Nous finissons à midi", dans quelle catégorie faut-il classer "finissons" ?',
    null,
    '[{"id":"a","label":"Verbe conjugué"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passé"},{"id":"d","label":"Participe présent"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Finissons" est une forme conjuguée à la 1re personne du pluriel.',
    'Oublier que les terminaisons personnelles marquent une conjugaison.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par catégories : formes verbales',
    'Intermédiaire',
    'vrai_faux',
    'Vrai ou faux : dans "Souriant, il entra", "souriant" est un participe présent.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'Ici "souriant" est bien un participe présent employé en construction détachée.',
    'Le confondre avec un adjectif pur sans tenir compte du tri verbal.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5070000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_formes_verbales',
    'Tri par catégories : formes verbales',
    'Intermédiaire',
    'qcm',
    'Dans "Il va venir", dans quelle catégorie faut-il classer "venir" ?',
    null,
    '[{"id":"a","label":"Verbe conjugué"},{"id":"b","label":"Infinitif"},{"id":"c","label":"Participe passé"},{"id":"d","label":"Participe présent"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Venir" est à l''infinitif après le semi-auxiliaire "va".',
    'Le classer comme verbe conjugué à cause de la locution verbale globale.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par catégories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Tout candidat doit relire", dans quelle catégorie faut-il classer "Tout" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Tout" accompagne le nom "candidat" : c''est un déterminant.',
    'Le confondre avec un pronom parce qu''il exprime la totalite.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par catégories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Tous sont prêts", dans quelle catégorie faut-il classer "Tous" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Tous" remplace un groupe nominal entier : c''est un pronom.',
    'Chercher un nom absent après le mot.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par catégories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Elle est tout heureuse", dans quelle catégorie faut-il classer "tout" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Tout" modifie l''adjectif "heureuse" : c''est un adverbe.',
    'Le classer comme adjectif à cause de l''accord possible dans d''autres contextes.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par catégories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Le tout est de commencer", dans quelle catégorie faut-il classer "tout" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"d"}'::jsonb,
    'Dans cette tournure lexicalisée, "tout" est employé comme nom.',
    'Vouloir forcer un classement en pronom parce qu''il renvoie à un ensemble.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par catégories : le mot "tout"',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Il a lu tout le chapitre", "tout" est un déterminant.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Tout" accompagne le nom "chapitre" : c''est un déterminant.',
    'Le confondre avec un adverbe de quantité.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par catégories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Elles sont toutes contentes", dans quelle catégorie faut-il classer "toutes" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    'Ici "toutes" modifie l''adjectif "contentes". Malgré l''accord graphique, il s''agit d''un adverbe.',
    'Penser que toute marque d''accord exclut la catégorie adverbe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par catégories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Ils ont tout compris", dans quelle catégorie faut-il classer "tout" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Tout" remplace ici l''ensemble des choses comprises : c''est un pronom.',
    'Le confondre avec un adverbe d''intensité.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par catégories : le mot "tout"',
    'Difficile',
    'reponse_courte',
    'Dans "Toute la classe écoute", dans quelle catégorie faut-il classer "Toute" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["déterminant"]}'::jsonb,
    '"Toute" introduit le nom "classe" : c''est un déterminant.',
    'Répondre adjectif sans regarder la structure du groupe nominal.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par catégories : le mot "tout"',
    'Difficile',
    'qcm',
    'Dans "Le bébé est tout petit", dans quelle catégorie faut-il classer "tout" ?',
    null,
    '[{"id":"a","label":"Déterminant"},{"id":"b","label":"Pronom"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    '"Tout" modifie l''adjectif "petit" : c''est un adverbe.',
    'Le prendre pour un déterminant en raison du sens de totalite.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5080000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_mot_tout',
    'Tri par catégories : le mot "tout"',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Le tout forme un ensemble cohérent", "tout" est un nom.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'Dans cette phrase, "tout" est bien employé comme nom.',
    'Confondre emploi nominal et reprise pronominale.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par catégories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Le livre que tu lis est dense", dans quelle catégorie faut-il classer "que" ?',
    null,
    '[{"id":"a","label":"Pronom relatif"},{"id":"b","label":"Conjonction de subordination"},{"id":"c","label":"Pronom interrogatif"},{"id":"d","label":"Adverbe restrictif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Que" reprend l''antécédent "livre" et introduit une relative : c''est un pronom relatif.',
    'Le classer comme conjonction en oubliant l''antécédent.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par catégories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Je pense qu''il a raison", dans quelle catégorie faut-il classer "que" ?',
    null,
    '[{"id":"a","label":"Pronom relatif"},{"id":"b","label":"Conjonction de subordination"},{"id":"c","label":"Pronom interrogatif"},{"id":"d","label":"Déterminant exclamatif"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    'Ici "que" introduit une subordonnée complétive et ne reprend aucun antécédent : c''est une conjonction de subordination.',
    'Répondre pronom relatif à chaque fois que le mot introduit une proposition.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par catégories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Il ne parle que de cela", dans quelle catégorie faut-il classer "que" ?',
    null,
    '[{"id":"a","label":"Pronom relatif"},{"id":"b","label":"Conjonction de subordination"},{"id":"c","label":"Adverbe restrictif"},{"id":"d","label":"Pronom interrogatif"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    'Dans la tournure "ne... que", "que" marque la restriction : c''est un adverbe restrictif.',
    'Chercher une proposition subordonnée alors qu''il s''agit d''une tournure négative restrictive.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par catégories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Que de questions !", dans quelle catégorie faut-il classer "Que" ?',
    null,
    '[{"id":"a","label":"Pronom interrogatif"},{"id":"b","label":"Conjonction de subordination"},{"id":"c","label":"Adverbe exclamatif"},{"id":"d","label":"Déterminant exclamatif"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    'Dans « Que de questions ! », « que » est suivi de « de + nom » et exprime une grande quantité (équivalent de « combien »). C''est un adverbe exclamatif, pas un déterminant. Un déterminant exclamatif serait « Quelles questions ! » ou le précède directement le nom.',
    'Le classer comme pronom uniquement à cause de sa forme.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par catégories : le mot "que"',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Que veux-tu ?", "que" est un pronom interrogatif.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'Dans cette question directe, "que" est bien un pronom interrogatif.',
    'Confondre toute interrogation avec une subordonnée.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par catégories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Que cherches-tu exactement ?", dans quelle catégorie faut-il classer "Que" ?',
    null,
    '[{"id":"a","label":"Pronom interrogatif"},{"id":"b","label":"Pronom relatif"},{"id":"c","label":"Conjonction de subordination"},{"id":"d","label":"Adverbe restrictif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    'Que sert ici à interroger sur l''objet cherché : c''est un pronom interrogatif.',
    'Chercher un antécédent qui n''existe pas.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par catégories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "La réponse qu''il donne est précise", dans quelle catégorie faut-il classer "qu''" ?',
    null,
    '[{"id":"a","label":"Pronom relatif"},{"id":"b","label":"Conjonction de subordination"},{"id":"c","label":"Pronom interrogatif"},{"id":"d","label":"Déterminant exclamatif"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    'Qu'' reprend l''antécédent "réponse" : c''est un pronom relatif.',
    'Confondre la présence du verbe avec une complétive.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par catégories : le mot "que"',
    'Difficile',
    'reponse_courte',
    'Dans "Il faut que tu viennes", dans quelle catégorie faut-il classer "que" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["conjonction de subordination","subordination"]}'::jsonb,
    'Ici "que" introduit une subordonnée complétive sans reprendre d''antécédent : c''est une conjonction de subordination.',
    'Répondre pronom relatif à cause de la forme inchangée du mot.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par catégories : le mot "que"',
    'Difficile',
    'qcm',
    'Dans "Que de patience il faut !", dans quelle catégorie faut-il classer "Que" ?',
    null,
    '[{"id":"a","label":"Déterminant exclamatif"},{"id":"b","label":"Pronom interrogatif"},{"id":"c","label":"Adverbe exclamatif"},{"id":"d","label":"Adverbe restrictif"}]'::jsonb,
    '{"mode":"single_choice","value":"c"}'::jsonb,
    'Dans « Que de patience il faut ! », « que » est un adverbe exclamatif (équivalent de « combien »). La structure « que de + nom » montre que « que » n''est pas un déterminant (un déterminant précéderait directement le nom : « Quelle patience ! »). « Que » exprime ici la quantité/l''intensité.',
    'Confondre avec un déterminant exclamatif. Le déterminant exclamatif est « quel/quelle/quels/quelles » (qui précède directement le nom). « Que de + nom » est une construction adverbiale.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e5090000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_mot_que',
    'Tri par catégories : le mot "que"',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Il n''a que deux stylos", "que" appartient à une tournure restrictive.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'La tournure "ne... que" exprime la restriction. "Que" est alors un adverbe restrictif.',
    'Chercher un emploi de subordonnant dès que le mot que apparaît.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000001',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par catégories : mots à double nature',
    'Difficile',
    'qcm',
    'Dans "leur cahier est fermé", dans quelle catégorie faut-il classer "leur" ?',
    null,
    '[{"id":"a","label":"Déterminant possessif"},{"id":"b","label":"Pronom personnel"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Conjonction de subordination"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Leur" accompagne le nom "cahier" : c''est un déterminant possessif.',
    'Le confondre avec le pronom de "je leur parle".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000002',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par catégories : mots à double nature',
    'Difficile',
    'qcm',
    'Dans "Je leur parle souvent", dans quelle catégorie faut-il classer "leur" ?',
    null,
    '[{"id":"a","label":"Déterminant possessif"},{"id":"b","label":"Pronom personnel"},{"id":"c","label":"Pronom relatif"},{"id":"d","label":"Adverbe"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Leur" reprend ici des personnes et complète le verbe "parle" : c''est un pronom personnel.',
    'Chercher un nom après le mot alors qu''il est placé devant le verbe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000003',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par catégories : mots à double nature',
    'Difficile',
    'qcm',
    'Dans "Les élèves eux-mêmes ont vérifié", dans quelle catégorie faut-il classer "mêmes" ?',
    null,
    '[{"id":"a","label":"Adjectif"},{"id":"b","label":"Adverbe"},{"id":"c","label":"Pronom"},{"id":"d","label":"Préposition"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Mêmes" renforce le pronom "eux" : on l''analyse ici comme un adjectif de renforcement.',
    'Le rendre invariable par automatisme dès que le mot même apparaît.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000004',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par catégories : mots à double nature',
    'Difficile',
    'qcm',
    'Dans "Même les experts hésitent", dans quelle catégorie faut-il classer "Même" ?',
    null,
    '[{"id":"a","label":"Adjectif"},{"id":"b","label":"Adverbe"},{"id":"c","label":"Pronom"},{"id":"d","label":"Déterminant"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    'Même signifie ici "jusqu''à / y compris" : c''est un adverbe.',
    'Le classer comme adjectif sans tenir compte du sens d''insistance.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000005',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par catégories : mots à double nature',
    'Difficile',
    'qcm',
    'Dans "Plusieurs ont déjà fini", dans quelle catégorie faut-il classer "Plusieurs" ?',
    null,
    '[{"id":"a","label":"Déterminant indéfini"},{"id":"b","label":"Pronom indéfini"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Plusieurs" fonctionne seul et remplace un groupe nominal : c''est un pronom indéfini.',
    'Le classer comme déterminant sans vérifier s''il introduit un nom.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000006',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par catégories : mots à double nature',
    'Difficile',
    'qcm',
    'Dans "Plusieurs copies manquent", dans quelle catégorie faut-il classer "Plusieurs" ?',
    null,
    '[{"id":"a","label":"Déterminant indéfini"},{"id":"b","label":"Pronom indéfini"},{"id":"c","label":"Adverbe"},{"id":"d","label":"Nom"}]'::jsonb,
    '{"mode":"single_choice","value":"a"}'::jsonb,
    '"Plusieurs" introduit le nom "copies" : c''est un déterminant indéfini.',
    'Oublier que le même mot peut être pronom ou déterminant selon le contexte.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000007',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par catégories : mots à double nature',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Ce dossier a un vrai plus", "plus" est un nom.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    'Dans cette phrase, "plus" désigne un avantage distinctif : il est employé comme nom.',
    'Le traiter comme l''adverbe de comparaison par réflexe.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000008',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par catégories : mots à double nature',
    'Difficile',
    'qcm',
    'Dans "Il travaille plus vite", dans quelle catégorie faut-il classer "plus" ?',
    null,
    '[{"id":"a","label":"Nom"},{"id":"b","label":"Adverbe"},{"id":"c","label":"Pronom"},{"id":"d","label":"Déterminant"}]'::jsonb,
    '{"mode":"single_choice","value":"b"}'::jsonb,
    '"Plus" modifie l''adverbe "vite" dans un comparatif : c''est un adverbe.',
    'Le confondre avec un nom à cause de sa forme isolée.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000009',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par catégories : mots à double nature',
    'Difficile',
    'reponse_courte',
    'Dans "Bien qu''il soit tard, nous continuons", dans quelle catégorie faut-il classer "bien que" ?',
    null,
    null,
    '{"mode":"text","acceptableAnswers":["conjonction de subordination","subordination"]}'::jsonb,
    '"Bien que" est une locution qui introduit une subordonnée de concession : c''est une conjonction de subordination.',
    'Se focaliser sur le mot bien comme adverbe sans voir la locution complète.',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  ),
  (
    'e50a0000-0000-0000-0000-000000000010',
    'Francais',
    'grammaire',
    'tri_mots_double_nature',
    'Tri par catégories : mots à double nature',
    'Difficile',
    'vrai_faux',
    'Vrai ou faux : dans "Ce travail est bien organisé", "bien" est un adverbe.',
    null,
    '[{"id":"true","label":"Vrai"},{"id":"false","label":"Faux"}]'::jsonb,
    '{"mode":"boolean","value":true}'::jsonb,
    '"Bien" modifie l''adjectif "organisé" : c''est un adverbe.',
    'Le classer comme nom abstrait par analogie avec "le bien".',
    'valide',
    'CRPE Francais V3',
    'free',
    true
  )
on conflict (id) do nothing;
